Sawfly bugfixes
goonstation/goonstation pull request #10242
Opened 2022-08-13 19:22 UTC by NightmareChamillian

[input][bug]
## About the PR 
Makes Sawflies have more aggressive range checks on their attacks. Also fixes them having an injury slowdown. If the latter 

## Why's this needed? 
Bugs no good
Closes #10240
Closes #10105

## Changelog

```changelog
(u)CodeDude
(*)Added soft soft pizza to the game - a tasty drink found in soda machines!
(+)Made some small sprite changes to the base pizza sprite.
```

2022-08-13 19:23 UTC, NightmareChamillian commented
oh NO it's cursed

2022-08-13 19:52 UTC, ZeWaka requested changes
fix ur pr desc

2022-08-16 17:06 UTC, Tarmunora requested changes

2022-08-16 17:06 UTC, Tarmunora commented on code/mob/living.dm
> +	if(!istype(src, /mob/living/critter/robotic/sawfly)) //disables pain slowdown for sawflies- consider upgrading to all robots later
no. bad.
Just give sawflies a movement modifier with -INFINITY health_deficiency_adjustment or something

2022-08-16 17:06 UTC, Tarmunora commented on code/mob/living/critter/ai/sawflyai.dm
> +				if(GET_DIST(owncritter, holder.target) > target_range)
use `in_interact_range()` for this kind of melee range check

2022-08-17 01:31 UTC, ZeWaka requested changes

2022-08-17 01:31 UTC, ZeWaka commented on code/mob/living/critter/sawfly.dm
> +	health_deficiency_adjustment = -200000 //prevents them from having movespeed slowdown when injured
Please just use actual infinity

2022-08-19 16:25 UTC, merged