Meson cyber-eyes and blindness protect you from Singularity Mezzing
goonstation/goonstation pull request #10352
Opened 2022-08-19 22:13 UTC by pgmzeta

[BUG][GAME OBJECTS][MINOR]
## About the PR 
Being blinded or having Meson Cyber-eyes in whatever eyes you have protects you from the singularity's Mezzing event.

## Why's this needed? 
Meson eyes should work like meson goggles if all your eyes are mesons, and you can't look directly at something if you can't see.

2022-08-19 22:22 UTC, ZeWaka requested changes

2022-08-19 22:22 UTC, ZeWaka commented on code/obj/machinery/singularity.dm
> +			if (H.bioHolder?.HasEffect("blind") || H.blinded )
inconsistent spacing

2022-08-19 23:34 UTC, pgmzeta commented on code/obj/machinery/singularity.dm
> +			if (H.bioHolder?.HasEffect("blind") || H.blinded )
fixed (real)

2022-08-26 05:27 UTC, ZeWaka approved these changes

2022-08-29 22:34 UTC, merged