Fix Flockdrone AI shooting bugs
goonstation/goonstation pull request #10360
Opened 2022-08-20 03:29 UTC by FlameArrow57

[AI][GAMEMODES][BUG]

## About the PR 
This PR fixes bugs with AI controlled Flockdrones where they could shoot while stunned and while floorrunning

## Why's this needed? 
Bug fixes, fixes #9686

2022-08-20 03:43 UTC, TobleroneSwordfish approved these changes
something something one letter variable names

2022-08-20 23:26 UTC, amylizzle approved these changes
God I wish we could ditch the `walk()` and `walk_rand()` stuff.

2022-08-23 06:11 UTC, ZeWaka requested changes

2022-08-23 06:11 UTC, ZeWaka commented on code/mob/living/critter/ai/flock/flocktasks.dm
> +	var/mob/living/critter/flock/drone/F = holder.owner
something something 1 letter variable names

2022-08-24 17:55 UTC, merged