Epic barfight
goonstation/goonstation pull request #10568
Opened 2022-09-01 12:30 UTC by NightmareChamillian

## About the PR 
Makes it so that drinking glasses can shatter and spill their contents if a projectile ``Cross``es over them

## Why's this needed? 
Quality of life, allows for shooting range gimmicks

## Changelog

```changelog
(u)NightmarechaMillian
(+)Glasses now have a 33% chance to break when shot at- Get in a bar fight today!
```

2022-09-01 12:52 UTC, TobleroneSwordfish requested changes
Very cool little detail, could probably be a higher chance.

2022-09-01 12:52 UTC, TobleroneSwordfish commented on code/modules/chemistry/tools/food_and_drink.dm
> +	Cross(atom/movable/mover) //epic barfights
```suggestion
	Crossed(atom/movable/mover) //epic barfights
```
`Cross` is to check if something is allowed to cross, `Crossed` is to do something when it does.

2022-09-01 14:31 UTC, ThatFiveGuys commented
Should probably be kinetic projectiles only and agree with it should being a higher chance, maybe scaling with bullet damage?

2022-09-01 14:36 UTC, BatElite commented
30% seems pretty alright to me, in case you're aiming at someone behind the bar

2022-09-02 02:25 UTC, ZeWaka approved these changes

2022-09-02 02:25 UTC, ZeWaka commented on code/modules/chemistry/tools/food_and_drink.dm
> +		..()
```suggestion
		. = ..()
```

2022-09-02 07:57 UTC, Gannets commented
I love anything that makes the environment react better to combat.

2022-09-02 16:20 UTC, merged