Mining Encounter: Sea Trench Asteroid
goonstation/goonstation pull request #10805
Opened 2022-09-14 00:29 UTC by pgmzeta

## About the PR 
Adds a new very rare random magnet mining encounter themed around / re-using Abzu's trench. It can spawn one to three crates from a cut down list of trench crates, and algae appears on the rocks. 

Both the mechanical and technical implementations should be considered first draft, but it does work in game as written.

## Why's this needed? 
More variety in magnet pulls & mining.

## Changelog

```changelog
(u)glowbold
(+)The mining magnet can rarely pull in a chunk of rock from the depths of Abzu.
```

2022-09-14 00:30 UTC, NightmareChamillian commented
1) Adore the fact that mining magnets are getting more than 2 possible encounters
2) Would love to see a screenshot

2022-09-14 00:35 UTC, pgmzeta commented
screenshot added :)

2022-09-14 00:55 UTC, Zonespace27 commented on code/modules/mining/mining_encounters.dm
> +		var/list/crates = list(
this can be a static list on the datum itself

2022-09-14 00:56 UTC, Zonespace27 commented on code/modules/mining/mining_encounters.dm
> +		while (amount > 0)
this can just be a `for(var/i in 1 to rand(1, 3))` loop

2022-09-14 00:56 UTC, Zonespace27 commented on code/modules/mining/mining_encounters.dm
> +			if (floors.len) //ZeWaka: Fix for pick() from empty list
zewaka comment

2022-09-14 00:56 UTC, Zonespace27 commented on code/obj/mining.dm
> +			. = ..()
```suggestion
			return ..()
```

2022-09-14 00:56 UTC, Zonespace27 commented on code/obj/mining.dm
> +			if (length(space_overlays)) // Are we on the edge of a chunk wall
early return

2022-09-17 20:47 UTC, pgmzeta commented
updated to use some randomization in color for each tile. i think it's technically feasible to make these uniform per magnet pull, but i'm stumped on a good approach.

2022-09-22 19:45 UTC, Tarmunora requested changes
should also be able to pull in a couple of the trench mobcritters

2022-09-26 21:56 UTC, Tarmunora approved these changes
the having the number of enemies always be equal to the number of crates feels a little off, but otherwise lgtm

2022-10-01 23:53 UTC, frawhst commented on code/modules/mining/mining_encounters.dm
> +			if (floors.len)
```suggestion
			if (length(floors))
```
legally required to request this change

2022-10-01 23:53 UTC, merged