Allow DetGadget Hat and Lawbringer to work regardless of stammering and common mutantrace speeches
goonstation/goonstation pull request #10845
Opened 2022-09-17 02:02 UTC by FlameArrow57

[GAME OBJECTS][QoL]

## About the PR 
This PR allows the DetGadget Hat and Lawbringer to work even if you are stammering, and when playing with a lizard or cow mutantrace.

## Why's this needed? 
Would be cool to be able to any phrase when playing with a different mutantrace.

Also would be nice to use the Lawbringer when you are stammering

Fixes #7361

## Changelog
```changelog
(u)FlameArrow57
(+)The DetGadget Hat and Lawbringer are no longer affected by stammering or lizard and cow speech.
```

2022-09-17 02:36 UTC, ThatFiveGuys commented
The alternate phrases already exist to allow mutantrace support and also “poisoning” the hos with booze to reduce there lawbringer effectiveness is a very funny and good strategy that would be a shame to be gone. This pr has basically no benefit, and its detriment is getting rid of a very entertaining aspect of these items.

2022-09-17 03:45 UTC, FlameArrow57 commented
The PR doesn't change the effects of ethanol with the Lawbringer.

2022-09-17 12:58 UTC, ThatFiveGuys commented
> The PR doesn't change the effects of ethanol with the Lawbringer.

Still runs into same issue with stammering, also having it seemingly arbitrarily work for some voice changing things and not work for other voice changes seems really unintuitive

2022-09-20 16:30 UTC, ZeWaka requested changes
this is implemented in a completely wrong way, not mergeable whatsoever in its current approach

2022-09-20 16:30 UTC, ZeWaka commented on code/obj/item/gun/energy.dm
> +		return new_message
what are you even doing here

2022-09-20 16:30 UTC, ZeWaka commented on code/obj/item/gun/energy.dm
> -				if ("detain","execute","knockout","hotshot","incendiary","bigshot","highexplosive","he","clownshot","clown", "pulse", "punch")
?

2022-09-20 16:30 UTC, ZeWaka commented on code/obj/item/gun/energy.dm
> +				if ("knockout", "slepshot") // sleepshot -> slepshot
this isn't documented!

2022-09-20 16:30 UTC, ZeWaka commented on code/obj/item/clothing/hats.dm
> +
no, fix this another way

2022-09-20 16:30 UTC, ZeWaka commented on code/obj/item/clothing/hats.dm
> +									"glases" = list("glasses", /obj/item/clothing/glasses)) // glasses -> glases
no

2022-10-05 03:48 UTC, FlameArrow57 commented
Anything in mind for this? I wasn't sure if you were meaning some way to do it without allowing less letter than intended, or to just rework what was passed into speak_into()

2022-10-07 21:10 UTC, ZeWaka commented
> Anything in mind for this? I wasn't sure if you were meaning some way to do it without allowing less letter than intended, or to just rework what was passed into speak_into()

the speech pipeline should just be reworked entirely, so both the original and text-to-display pipeline can be modified/read by speech accents and such, this is a hacky bodge ontop of old smelly code

2022-11-17 05:32 UTC, closed without merging