New Command Traitor Items: AI Laser and Taser Upgrade Modules
goonstation/goonstation pull request #10922
Opened 2022-09-20 21:02 UTC by Wisemonster

[GAME OBJECTS] [FEATURE] [INPUT WANTED] [EXPERIMENTAL]

## About the PR 
This pr adds 2 new items for traitorous heads of staff, upgrade modules that let the AI use a taser and/or laser ability from their cameras. The laser module shoots a 20 damage phaser shot, with a 10 second cool down, that costs 7 tc. The taser module shoots a taser bolt that deals 75 stam damage, about 1 second of disorient, and has a separate 10 second cool down, that costs 6 tc.

## Why's this needed? 
AI ability upgrade modules have been in the code for a while now, and I figured these two abilities wouldn't really fit as anything other than traitor items. Plus gives traitor members of command more control of how a rogue AI can help them.

## Changelog

```changelog
(u)Wisemonster
(*)Adds two new command traitor items: An AI laser upgrade module and an AI taser upgrade module. Costs 7 tc and 6 tc respectively.

2022-09-21 05:35 UTC, Zonespace27 commented on code/datums/syndicate_buylist.dm
> +	vr_allowed = 0
true/false defines

2022-09-21 05:35 UTC, Zonespace27 commented on code/datums/syndicate_buylist.dm
> +	vr_allowed = 0
ditto

2022-09-22 04:06 UTC, Tarmunora requested changes
I'd drop the taser module and stick with just the laser module @6TC, and maybe take it out of spy/crate pools - not too set either way on that though

2022-09-22 23:15 UTC, Tarmunora approved these changes

2022-09-23 16:48 UTC, ZeWaka approved these changes
sure let's try it

2022-09-23 16:48 UTC, merged