Chef Objective Fix
goonstation/goonstation pull request #11050
Opened 2022-09-27 23:28 UTC by wolfolotl

[A-INTERNAL] [C-BUG]

## About the PR 
expands the blacklist for the chef crew objective to add stuff like spawners, inaccessible parent types, map- or traitor-specific items, and other various options that weren't excluded before. also makes the condiment, ingredient, and pie parents abstract types

my computer won't let me test this right now so if possible someone should give this a quick pass to make sure it doesn't Break Something Horribly

## Why's this needed? 
being able to do crew objectives good

2022-09-28 00:21 UTC, ZeWaka requested changes
these should all just be abstract types

2022-09-28 03:42 UTC, wolfolotl commented
> these should all just be abstract types

the majority of the blacklisted items I added are accessible in-game, just not in a way that someone can reasonably get every shift for one reason or another, I can definitely make the spawners abstract types though

2022-09-28 11:23 UTC, TobleroneSwordfish commented on code/datums/crew_objective.dm
> +		/obj/item/reagent_containers/food/snacks/greengoo,
```suggestion
#ifndef UNDERWATER_MAP
		/obj/item/reagent_containers/food/snacks/healgoo,
		/obj/item/reagent_containers/food/snacks/greengoo,
#endif
```

2022-10-01 23:20 UTC, ZeWaka approved these changes

2022-10-01 23:50 UTC, merged