Adds stinging nettles as a hydroponics plant
goonstation/goonstation pull request #11095
Opened 2022-10-01 02:02 UTC by colossusqw

## About the PR 
This PR adds stinging nettles to botany, they can be acquired by hacking into the seed vendor and will periodically inject any mob within a 1 tile radius with histamine or any other chems they might have, similar to rafflesia, however in a much smaller range and without creating smoke.

## Why's this needed? 
This is another fun way for botany to spread chems around, like rafflesia, however without spreading miasma smoke everywhere. It could be used as a weapon or used as a quick omnizine dispenser by medbay if you don't mind a little histamine, in general, another thing for plant enthusiasts to mess with.

```changelog
(u)Hans
(*)Added stinging nettle to the list of plants botany can make! (More info in minor changes)
(+)Stinging nettle will periodically inject anyone close with histamine and the chemicals spliced with it, similar to rafflesia but without the smoke.
(+)Stinging nettle can be circumvented by wearing chemical protection, and the frequency of injecting people depends on it's endurance, while the amount of chemicals varies upon potency.
```

2022-10-01 14:06 UTC, TobleroneSwordfish requested changes
Nettles :)

2022-10-01 14:06 UTC, TobleroneSwordfish commented on code/modules/hydroponics/plants_herb.dm
> +				..()
you've already called parent at the start of this proc, calling it twice may cause jank

2022-10-01 14:06 UTC, TobleroneSwordfish commented on code/obj/item/plants.dm
> +	crop_suffix	= " leaves"
```suggestion
	crop_suffix = " leaves"
```

2022-10-01 16:37 UTC, Tarmunora commented
Not really a fan but I suppose it can't be worse than rafflesia 😐

2022-10-01 18:26 UTC, ThatFiveGuys commented
Honestly i think this plant fills too similar of a niche to rafflesia with less of the flavor of rafflesia that this would fit best as a procgen plant for the terrainifys

2022-10-01 20:14 UTC, nefarious6th commented
find myself agreeing with ikea even though I liked this a lot initially. Would like to see it added at least for use in projects perhaps later. Would be a fun encounter on away zones, but my mind wraps back around to maybe having it generate in with histamine + random chem and then being able to uproot it and take with to re-plant.

Oh well. I think what I mean to say is I really like this and hope to see it in some aspect.

2022-10-01 20:37 UTC, Momoberry commented
> Honestly i think this plant fills too similar of a niche to rafflesia with less of the flavor of rafflesia that this would fit best as a procgen plant for the terrainifys

It's openly more usable than rafflesia. Rafflesia mass spams out a mix of miasma and whatever chem you put in. The issue is that makes a wide area unusable for people that don't want to breathe in 300u of miasma lol. This is a much more contained plant, and honestly a lot more usable by botany for positive things.

2022-10-01 20:51 UTC, ThatFiveGuys commented
> > Honestly i think this plant fills too similar of a niche to rafflesia with less of the flavor of rafflesia that this would fit best as a procgen plant for the terrainifys
> 
> It's openly more usable than rafflesia. Rafflesia mass spams out a mix of miasma and whatever chem you put in. The issue is that makes a wide area unusable for people that don't want to breathe in 300u of miasma lol. This is a much more contained plant, and honestly a lot more usable by botany for positive things.

The histamine makes it less usable for positive things (and also i have a pr in the works to address the miasma things for rafflesia)

2022-10-02 00:35 UTC, TobleroneSwordfish commented
Maybe give it a gene strain or mutation called "dead nettles" that removes the histamine?

2022-10-02 08:56 UTC, ZWRh3 commented
i support this but i agree with TobleroneSwordfish that there should be a histamineless mutation i also have one concern

"gib nettles": water and potassium splices are iirc non explosive until they get transfered into something else eg. a joint or in this case whatever poor sap is close to the plant i dont know if it would do the ok thing (explode once destroying itself in the process too like some botany proximity bomb) or the bad thing stunlock with explosions until they gib

2022-10-03 18:21 UTC, colossusqw commented on code/obj/item/plants.dm
> +	crop_suffix	= " leaves"
huh, it's correct on my end, weird.

2022-10-03 19:05 UTC, colossusqw commented on code/modules/hydroponics/plants_herb.dm
> +			H.reagents?.add_reagent(plantReagent, 5 * round(max(1,(1 + DNA.potency / (10 * (length(assoc_reagents) ** 0.5))))))
the formula is not the same, it's similar but one of them uses your current chem protection, i could try to make a sting thing with a check for that though

2022-10-03 19:09 UTC, colossusqw commented
Also, the histamine values have been changed for it to be a standard 5 units per time it injects you, making it be way less of a problem for non-evil injections

2022-10-29 21:48 UTC, pali6 approved these changes
Yeah sure, I've wanted something similar for a while.
Though my original idea was a grass mutation that injects you as you walk on the floor where the grass is growing.

2022-10-29 21:49 UTC, merged