Allow Flockmind to promote Flocktraces
goonstation/goonstation pull request #11185
Opened 2022-10-05 04:44 UTC by FlameArrow57

[QOL]

## About the PR 
This PR just allows Flockminds to promote Flocktraces

## Why's this needed? 
In case they have to quite the game, etc

2022-10-06 18:39 UTC, TobleroneSwordfish approved these changes
Should probably give the promoted trace a message or popup or something to tell them what happened.

2022-10-08 01:55 UTC, FlameArrow57 commented
promoteToFlockmind() already handles that if it looks good

2022-11-07 13:50 UTC, amylizzle requested changes

2022-11-07 13:50 UTC, amylizzle commented on code/datums/flock/flock.dm
> +					message += " This Flocktrace is afk."
```suggestion
					message += " This Flocktrace is unresponsive."
```

2022-11-07 13:50 UTC, amylizzle commented on code/datums/flock/flock.dm
> +					message += " This Flocktrace is afk."
```suggestion
					message += " This Flocktrace is unresponsive."
```

2022-11-07 13:50 UTC, amylizzle commented on code/datums/flock/flock.dm
> +			if (tgui_alert(usr, message, "Promote Flocktrace", list("Yes", "Cancel")) != "Cancel")
```suggestion
			if (tgui_alert(ui.user, message, "Promote Flocktrace", list("Yes", "Cancel")) != "Cancel")
```

2022-11-07 13:50 UTC, amylizzle commented on code/datums/flock/flock.dm
> +				var/choice = tgui_alert(usr, "Leave the Flock?", "Promote Flocktrace", list("No", "Yes", "Cancel"))
```suggestion
				var/choice = tgui_alert(ui.user, "Leave the Flock?", "Promote Flocktrace", list("No", "Yes", "Cancel"))
```

2022-11-08 20:48 UTC, pali6 requested changes
Are there any advantages to having multiple active flockminds in a flock?

2022-11-08 20:48 UTC, pali6 commented on code/datums/flock/flock.dm
> +			if (tgui_alert(user, message, "Promote Flocktrace", list("Yes", "Cancel")) != "Cancel")
I believe you generally want to check for alert result using `==`. Closing the alert or erroring out somehow will return `null` iirc and you don't want that to act as "Yes".

2022-11-08 20:48 UTC, pali6 commented on code/datums/flock/flock.dm
> +				if (choice != "Cancel")
Ditto.

2022-11-09 06:11 UTC, FlameArrow57 commented
For promoting Flocktraces, it just keeps one Flockmind always

2022-11-09 21:49 UTC, pali6 approved these changes

2022-11-09 21:49 UTC, merged