makes fire overlay onto walls like fluids
goonstation/goonstation pull request #11280
Opened 2022-10-10 04:06 UTC by Skeletonman0

[ATMOSPHERICS] [QOL]
## About the PR 
adds some code onto obj/hotspot borrowed from fluids to make fireflashes / plasmafires overlay onto walls
this does mean that it is visible from the other side of the wall however

i thought about applying this to atmos gases themselves, but that would probably be way too difficult
due to how they work in the first place.

## Why's this needed? 
looks nicer
![image](https://user-images.githubusercontent.com/64938519/194797739-272b0473-2716-470c-9f90-546c55eac0b1.png)

2022-10-10 04:57 UTC, virvatuli-gh commented
:eyes:

2022-10-10 07:11 UTC, ZeWaka commented on code/modules/atmospherics/FEA_fire.dm
> +		src.update_perspective_overlays()
you should surround this and check if the loc is null, no use doing this stuff if we're in nullspace - that should resolve the !t issue below

2022-10-10 22:57 UTC, Glamurio commented
I think it's a really slick effect, but I personally don't like that it's visible from the other side of the wall, though you win some and you lose some I guess

2022-10-10 23:35 UTC, TobleroneSwordfish commented
Might be worth profiling?

2022-10-11 04:12 UTC, ZeWaka commented
it doesn't need to be visible from the other side of the wall, offset overlays

2022-10-27 05:48 UTC, ZeWaka requested changes
no changes necessarily requested, but I'd like a performance evaluation of how expensive this is - via the disco inferno scenario()

2022-11-17 11:40 UTC, pali6 commented
> I think it's a really slick effect, but I personally don't like that it's visible from the other side of the wall, though you win some and you lose some I guess

That's actually a one line fix! :)

2022-11-17 11:48 UTC, pali6 commented on code/modules/atmospherics/FEA_fire.dm
> +						src.update_perspective_overlays()
What's the reasooning behind thse calls here?

2022-11-17 11:55 UTC, pali6 commented
![image](https://user-images.githubusercontent.com/358431/202439853-740ca6a3-9dc3-49e8-a42f-91e53fcc1987.png)
some corners have overlapping overlays which looks kinda bad

2022-11-17 11:57 UTC, pali6 commented
![image](https://user-images.githubusercontent.com/358431/202440148-1df54ef7-e584-4e75-826b-3d57b5d6f4e9.png)
Walls getting deleted doesn't quite update the overlays properly.

2022-11-17 11:58 UTC, pali6 commented
![image](https://user-images.githubusercontent.com/358431/202440325-865f1f85-c300-4a46-8be0-4b8db967f409.png)
Windows don't get any overlays when cardinally attached to a fire which looks kinda bad.

2022-11-17 12:02 UTC, pali6 requested changes
See my previous comments. Basically this will need to hook somewhere into the `tilenotify` proc on turfs most likely to keep the overlays up to date with wall changes. You will also need slightly different conditions for when to place overlays than fluids have (for example place these on windows). Also you will need to make it so if a has a fire both to the south and to east/west its bottom corners don't get covered by two overlays.

Also, for performance reasons, `blocked_perspective_objects` could be a flag bit field instead of an array. And `wall_overlay_images` could be a `static` where you give it a direction and icon state and it'll give you the right overlay image, no need to have it be on each hotspot.

2022-11-17 19:39 UTC, ZeWaka commented
zewaka idea: don't use overlays, just make the fire icon like 50x50 and use icon states for cheaper

2023-03-31 18:16 UTC, closed without merging