Make the Relay block teleports
goonstation/goonstation pull request #11379
Opened 2022-10-15 19:31 UTC by FlameArrow57

[GAME MODES][BALANCE][CLEANLINESS]

## About the PR 
This PR just makes the relay a teleportation jammer.

Reworks teleport jamming code to do this

## Why's this needed? 
Prevents late game bomb teleports, etc

Also in theme of Flock, Flock lore has the Flock hating teleportation. Also,

2022-10-15 19:32 UTC, FlameArrow57 commented
Saw that do_teleport() doesn't check if teleportation is blocked at the source of the teleport, relevant to hand teles. Could change that if wanted

Alternative could be making all Flock floortiles have a chance to or completely block teleports

2022-10-15 19:34 UTC, TobleroneSwordfish requested changes
Perfect candidate for just making into a component rather than sticking another var on atom

2022-10-15 21:28 UTC, TobleroneSwordfish approved these changes
that works 👍

2022-11-03 16:44 UTC, Tarmunora requested changes

2022-11-03 16:44 UTC, Tarmunora commented on _std/macros/atom_properties.dm
> +#define PROP_ATOM_TELEPORT_JAMMER(x) x("teleport_jammer", APPLY_ATOM_PROPERTY_SUM, REMOVE_ATOM_PROPERTY_SUM)
Property should automatically add/remove atoms from the teleblocker tracking cat when added/removed (see `PROP_UPDATE_INVISIBILITY` etc)

2022-11-04 04:36 UTC, Tarmunora commented on _std/macros/atom_properties.dm
> +	if (isnull(old_val) || !isnull(is_teleblocking)) { \
not `&&`?

2022-11-04 04:46 UTC, FlameArrow57 commented on _std/macros/atom_properties.dm
> +	if (isnull(old_val) || !isnull(is_teleblocking)) { \
Was fixed in recent commit

2022-11-04 07:37 UTC, Tarmunora approved these changes

2022-11-05 18:03 UTC, merged