FEA Spacewind (real delta P experience)
goonstation/goonstation pull request #11438
Opened 2022-10-18 21:05 UTC by Kapu1178

## About the PR 
Implements fairly robust spacewind to Goon's build of FEA.

The way it works is high pressure deltas enqueue movables to the spacewind controller. If they fail `PrepareAirflow()` they will not be queued.

The object is then pushed/pulled away/towards the source of the airflow on an interval set in the spacewind controller, currently 0.5 seconds. This repeats until the object's airflow speed drops to 0, at which point the object is removed from the process list.

## Why's this needed? 
It's fuggin' fun and cool.

## Changelog

```changelog
(u)Kapu1178
(*)Added high pressure airflow ("Spacewind"), that moves and tosses things around!
```

2022-10-18 21:16 UTC, frawhst commented
delta pee when

2022-10-21 06:41 UTC, ZeWaka requested changes
couldn't look at the west stuff

2022-10-21 06:41 UTC, ZeWaka commented on code/modules/atmospherics/FEA_spacewind.dm
> +	///A movement occurs here, but it doesn't mean the mob will be queued to the airflow loop.
```suggestion
	// A movement occurs here, but it doesn't mean the mob will be queued to the airflow loop.
```

2022-10-21 06:41 UTC, ZeWaka commented on code/modules/atmospherics/FEA_spacewind.dm
> +	///At this point, we're locked into an airflow movement.
```suggestion
	// At this point, we're locked into an airflow movement.
```

2022-10-21 06:41 UTC, ZeWaka commented on code/modules/atmospherics/FEA_spacewind.dm
> +			src:changeStatus("stunned", 3 SECONDS) // :)
type it

2022-10-21 06:41 UTC, ZeWaka commented on code/modules/atmospherics/FEA_spacewind.dm
> +			)
i don't hear anything.

2022-10-21 06:41 UTC, ZeWaka commented on code/modules/atmospherics/FEA_spacewind.dm
> +		)
ditto

2022-10-21 06:41 UTC, ZeWaka commented on code/modules/atmospherics/FEA_spacewind.dm
> +	return
you could decrease __health

2022-10-21 06:41 UTC, ZeWaka commented on code/modules/atmospherics/FEA_spacewind.dm
> +				sleep(1)
1 what

2023-06-17 17:16 UTC, Laboredih123 commented
how have i not seen this

2023-06-17 17:18 UTC, Laboredih123 commented
very cool

2023-08-08 02:38 UTC, deathrobotpunch commented
could you make it that if someone opens both airlocks at the same time everyone nearby gets sucked out into space?

2023-08-08 02:39 UTC, deathrobotpunch commented
it could lead to cool spacing chambers that sec could use for executions

2023-11-02 08:01 UTC, TheTyrant25 commented
is this still being worked on perchance

2023-11-03 02:39 UTC, closed without merging

2023-11-03 03:04 UTC, Laboredih123 commented
it was not :(

2023-11-03 08:54 UTC, TheTyrant25 commented
got permission to work on this, so i may pick it up