LSD rework
goonstation/goonstation pull request #11613
Opened 2022-10-26 18:00 UTC by TobleroneSwordfish

[FEATURE] [GAMEMODES] [CHEMISTRY]
## About the PR 
Makes LSD hallucinations a little more realistic:
- Hallucinations now pull from a much larger pool of beasties including changeling critters
- Hallucinations now move and attack more realistically
- Audio hallucinations now pull from a much larger pool, and can play multiple times depending on the sound (eg gunshots and attack sounds play multiple times with their respective attack delays)
- The colour shifting part is now slightly delayed so the first few hallucinations are much more likely to be mistaken for reality
- The chances of some effects have been adjusted slightly

Currently I can't figure out a way to make movement states work for hallucinations, so that will probably have to be a separate PR if I ever do.

## Why's this needed? 
LSD is currently just an annoyance, none of the hallucinations are at all realistic. This aims to make it actually useful for changelings and other antags to cause confusion and cover up their activities. For example some common vampire and arcfiend sound effects have been included.

## Changelog 

```changelog
(u)LeahTheTech
(+)LSD hallucinations are now a little more realistic.
```

2022-10-26 18:12 UTC, Laboredih123 commented
relative pathing wahh

2022-10-26 18:31 UTC, TobleroneSwordfish commented
> relative pathing wahh

I wanted it to be as low effort as possible to add more subtypes, but could switch to absolute pathing I spose.

2022-10-26 19:48 UTC, Tarmunora requested changes

2022-10-26 19:48 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Drugs.dm
> +								sleep(chosen.delay)
wouldn't it make more sense for this to be a proc on the `hallucinated_sound` datum?

2022-10-26 20:12 UTC, muzcl commented
a video to show the effects would be nice

2022-10-26 21:20 UTC, TobleroneSwordfish commented
Okay I got movement states working, but the implementation is reasonably cursed, see "Movement states hack" commit.

2022-10-26 21:27 UTC, TobleroneSwordfish commented
> a video to show the effects would be nice

The effects are so random it's very hard to show them off in a short clip, if you want to test it you can always checkout the PR.

2022-10-26 23:39 UTC, Tarmunora approved these changes

2022-10-28 03:09 UTC, Crackaduck commented
amazing, its going to be so fun having people actually believe in their trips

2022-10-28 08:53 UTC, merged