Removes owner names from organs/limbs
goonstation/goonstation pull request #11641
Opened 2022-10-28 01:23 UTC by frawhst

[FEEDBACK] [REMOVAL] [BALANCE] 
## About the PR 
Title.
Notably does NOT remove owner names from hair or skulls- hair because it's probably recognizable already, and skulls because of the in-hand interaction where you yell the owner's name. I could remove the latter though.

fixes #11639 incidentally.

## Why's this needed? 
Dumb that I can recognize a disembodied leg on the ground. Makes forensics less useful.

```changelog
(u)aloe
(+)Limbs and organs no longer bear the names of their owners.
```

2022-10-28 01:23 UTC, frawhst commented
bug???

2022-11-03 16:32 UTC, Tarmunora requested changes

2022-11-03 16:32 UTC, Tarmunora commented on code/obj/item/mob_parts/human_parts.dm
> +			// 		name = "[new_holder.real_name]'s [initial(name)]"
```suggestion
```

2022-11-16 20:45 UTC, MarkNais commented
I think it is funnier to have names on limbs / organs and should stay for that reason.

2022-12-09 00:58 UTC, closed without merging