Weldertank ruptured sprite
goonstation/goonstation pull request #11683
Opened 2022-10-29 17:07 UTC by NightmareChamillian

## About the PR 

Adds a sprite so it's more obvious when weldertanks are ruptured. Also sorry for bad master branch (I have since fixed it but not this branch)

![image](https://user-images.githubusercontent.com/96703882/198844198-a6691740-9192-4cfa-bb72-0a82b965d43b.png)

## Why's this needed? 

Too many times, I have been a lonely engineer in need of fuel and have walked up to what I thought was a perfectly functional fueltank to discover some trickster had exploded it.

2022-10-29 19:24 UTC, pali6 commented on code/modules/chemistry/tools/dispensers.dm
> +		icon_state = "weldtank1"
`smash` deletes the object anyway, is this necessary?

2022-10-29 19:24 UTC, pali6 commented on code/modules/chemistry/tools/dispensers.dm
> +		icon_state = "weldtank1" //to ensure that a weldertank's always going to be updated by their own explosion
I think naming the icon state something like `weldtank-broken` or `weldtank-exploded` would be more readable than `weldtank1`.

2022-10-30 17:39 UTC, BatElite commented
Is the tank still capable of holding reagents after it explodes?

(I'm not aware of a way to transfer to them but I wanna say there was something)

2022-10-30 22:28 UTC, NightmareChamillian commented
> Is the tank still capable of holding reagents after it explodes?

Beyond the sprites, nothing's been enabled or disabled about the exploded fueltank, which means it retains all functionality

2022-10-31 07:07 UTC, WALPVRGIS approved these changes
LGTM on the art side of things. 👍

2022-11-03 02:49 UTC, frawhst commented
Can exploding it make it an open container. fits the sprite

2022-11-05 18:09 UTC, ZeWaka requested changes
x

2022-11-07 14:57 UTC, NightmareChamillian commented
Some things:
a) had my plate quite full this past week, apologies for leaving this to dry for so long
b) They're now open containers, but have some weird interactions due to requiring a click-drag in order to pour reagents into them

2022-11-07 19:25 UTC, ZeWaka reviewed
i don't see any open container code

2022-11-07 19:25 UTC, ZeWaka commented on code/modules/chemistry/tools/dispensers.dm
> +
```suggestion
```

2022-11-08 15:23 UTC, NightmareChamillian commented on code/modules/chemistry/tools/dispensers.dm
> +		return isburst
I don't know much about open container code, but provided my understanding is correct, this should return 1 if it's burst, which lets whatever called the proc know that it's an open container

2022-11-10 23:18 UTC, ZeWaka approved these changes

2022-11-13 07:05 UTC, merged