CheMaster3000 rewrite with TGUI
goonstation/goonstation pull request #11826
Opened 2022-11-06 03:11 UTC by Saicchi

[CHEMISTRY][QOL][TGUI][ENHANCEMENT][SILICONS][CLEAN]

## About the PR 

Reworks the CheMaster300 giving it a (hopefully) nice UI, cleaner code and some new features.
- Choose bottle type:
	- Merges vials, small bottles, bottles and all can types into this option.
		- Default selection is the 50u biodegradeable bottle.
		- All bottle types can not be recycled.
- Choose multiple pill types:
	- Default selection is the vanilla pill which takes whichever color the chemical mixture is.
	- Variety of designs of floor pills for the clown!
- **Cyborgs can now use the ChemMaster3000**
- Quality of Life:
	- Put items and beakers in your hand or designated spot on the floor.
	- **Beaker automatically ejects when empty**.
	- Drag and Drop valid containers in the machine.
	- Quick switch beakers when inserting another one.
- **Minimum chemical amount for anything is 1 unit instead of 5 units (everything is rounded so no fractions).**
	- Might be a point of concern.
		- Item spam.
		- 100 1u pills from a beaker instead of 20u pills.

I'd appreciate if people tested the PR and gave me some feedback on stuff and things I missed.

This PR works only on ChemMaster 3000, meaning the other two devices ( mini chemaster3000 and prototype chemaster ) will not be affected.

![image](https://user-images.githubusercontent.com/47158232/200152121-9d0e53e0-42d0-470b-8741-934169e7bef4.png)
![image](https://user-images.githubusercontent.com/47158232/200152126-d41cdc63-7a12-4b12-8ce5-dde1cfe8a890.png)
![image](https://user-images.githubusercontent.com/47158232/200152133-d4c9080d-b5fc-4671-9ccb-1a9b40c0ff66.png)
![image](https://user-images.githubusercontent.com/47158232/200152135-18f9ab59-391d-474f-94ba-83c554633b4b.png)

The analyze button now shows the message on the chat.
![image](https://user-images.githubusercontent.com/47158232/200152151-d30add2e-d140-4290-99f8-698621d0c0d4.png)

## Why's this needed? 

ChemMaster 3000 is the only of the main 4 chemistry machines that doesn't have TGUI.

## Changelog

```changelog
(u)DrWolfy
(*)CheMaster3000 rework with TGUI.
```

2022-11-06 03:19 UTC, DisturbHerb commented
pretty sure that the biodegradable bottle was a balance change, currently (and rightly, i guess) you can only make glass bottles/vials in the recycler

2022-11-06 03:23 UTC, Saicchi commented
> EDIT - i'm not quite sure why the chemaster should be able to make a non-recyclable version of the glass bottles/vials

Vials have a unique injection method so I can understand that. The 30u glass bottle could easily be replaced with a 30u plastic bottle, provided someone makes a sprite for it.

I only added both to maintain the functionality.

2022-11-06 18:34 UTC, Azrun reviewed
Really wish the new features weren't part of this PR and the features were atomized for review a and comment.

2022-11-06 18:34 UTC, Azrun commented on tgui/packages/tgui/interfaces/ChemMaster.js
> +            title="Select patch icon">
Use something other than the term "icon", like style or type. That was it maintains emersion preferably.

2022-11-06 18:44 UTC, ZeWaka requested changes
'operations' window is way too large compared to the reagents preview area

you don't need all that explainer text in the operations window, we have tooltips and button styling for a reason

2022-11-06 20:22 UTC, Saicchi commented
![image](https://user-images.githubusercontent.com/47158232/200193186-56f7fef0-cfd5-4c46-a27c-ef3c9dda328c.png)
![image](https://user-images.githubusercontent.com/47158232/200193205-aa82196c-81ac-4dbc-b369-8d9895a5fcce.png)
![image](https://user-images.githubusercontent.com/47158232/200193210-ca80ce7f-69bb-48d9-a61e-6ba0f7c22d1b.png)

How about this? Increased the reagent list size, removed most of the tooltips and reduced width and height.

2022-11-17 05:31 UTC, ZeWaka commented
> How about this? Increased the reagent list size, removed most of the tooltips and reduced width and height. Also removed the icon terminology and went with type instead.

1. I'd make the container icons clearly look like buttons. Right now they look just like images with a tooltip.
2. probably less space between each row of options, it's still feeling super crammed - maybe make the reagent display smaller?

2022-11-17 16:05 UTC, Saicchi commented
> 1. I'd make the container icons clearly look like buttons. Right now they look just like images with a tooltip.
They had the background button on my first design I posted on discord, I made it transparent due to user feedback.

> 2. probably less space between each row of options, it's still feeling super crammed - maybe make the reagent display smaller?
Reverted the reagent display to the normal height ( used everywhere that ReagentList is used ).

I don't know how I could compress things any more since each row in the operations is already operating with no margin or padding.
![image](https://user-images.githubusercontent.com/47158232/202496725-2deee53e-bf1b-4198-8bfb-3fe1330b2f89.png)

The ChemMaster screen is already quite small, here is a full game image with the Reagent Extractor for comparision.

![image](https://user-images.githubusercontent.com/47158232/202495971-6cbc82a4-7445-408e-b189-6806fb5ed7a2.png)

2022-11-18 14:28 UTC, Saicchi commented
> Technically, there's this margin(?) here

All rows are the same width and column since they are using `<Stack>`. Removing it would make them uneven and rather ugly IMO.
I guess it could be slimmed down if the `Use bottle` and `Use patch box` text were moved to the side of the button instead of bottom.

>  it'd be best if you update the main pr body with the new images

Will do.

2022-11-18 16:51 UTC, Saicchi commented
Margin can go negative! This time it really can't reduce the height much further without affecting the selecting bottle window. 

![image](https://user-images.githubusercontent.com/47158232/202758117-685835e7-d237-4899-892c-1bbed9e85b19.png)
![image](https://user-images.githubusercontent.com/47158232/202758243-bb833e2e-993f-4349-a253-71e68c9f7bb1.png)

2022-11-19 14:02 UTC, pali6 commented
I don't see any DM-side TGUI code here, am I missing something?

2022-11-19 17:00 UTC, Saicchi commented
> I don't see any DM-side TGUI code here, am I missing something?

Github is having a hard time showing a good diff with its git diff algorithm.

https://github.com/goonstation/goonstation/blob/44703b28bb3583cd2cade90d29385b9da45bbc96/code/modules/chemistry/Chemistry-Machinery.dm#L457-L814

2022-11-24 00:13 UTC, vortex1942 commented
![image](https://user-images.githubusercontent.com/22815407/203666851-d58a3314-7461-47a2-987c-5a38a7e8beba.png)
Teeny tiny thing, but the padding between the flush/eject button is a lot smaller when compared to the other buttons on the menu.

2022-11-24 05:31 UTC, ZeWaka commented
btw the weird icon offsets have been fixed in master

2022-12-02 01:48 UTC, Saicchi commented
Indeed. They look much neater now.
![image](https://user-images.githubusercontent.com/47158232/205196267-c4542627-4756-4d1c-a43d-34257c730d2c.png)

2023-01-12 00:39 UTC, TobleroneSwordfish commented
Sorry this has been inactive for so long, but since I've recently gained the ability to hit the funny merge button I thought I'd look over it.
A few minor issues still:
- Clicking on the machine with your hand doesn't open the interface, you have to actually swap the beaker to access it.
- The pill and bottle icons are rendered at half in-game size making the pills almost impossible to see, have you tried seeing what they look like at normal in-game resolutions? (use the pixelated flag on `<Icon>` to prevent blurring)
- The reset button looks like it should reset the entire operations section and is also unnecessary since the input box has a reset button built in.
- The `Remove Amount` buttons seem largely pointless and are completely different to how any other chemistry machine works, consider just having `isolate` and `remove all` for parity with the reagent extractor.

2023-01-12 11:55 UTC, Cyle99 commented
Thanks for the feedback. I'll take a look into it.

2023-01-12 13:31 UTC, TobleroneSwordfish commented
- The icon issue isn't a big deal if it would be a pain to rework the UI to render them at full size.
- The reset button can just be removed imo since the textbox has one built in.
- There isn't a lot of reason for the chemmaster to need to be that precise at removing chems but if you want it to do that then at least copy/componentize the chem dispenser controls so you don't have two different looking UIs that do the same thing.

2023-01-12 14:44 UTC, pali6 commented
I'm not much of a fan of lowering the minimum amount to 1u. That will lead to even worse spam of pills etc.

2023-01-12 17:08 UTC, Saicchi commented
I've set the minimum amount for anything at 5 units.
Removed the reset button.

![image](https://user-images.githubusercontent.com/47158232/212128809-f20f7e5f-d908-4810-a59e-513393ea0c24.png)

> There isn't a lot of reason for the chemmaster to need to be that precise at removing chems but if you want it to do that then at least copy/componentize the chem dispenser controls so you don't have two different looking UIs that do the same thing.

They're already more of less the same. The ChemMaster is already using the same component for reagents from the Reagent Extractor.

ChemDispenser
![image](https://user-images.githubusercontent.com/47158232/212129055-212f9007-76cb-46d6-b2ae-12b1bdb24299.png)

ChemMaster
![image](https://user-images.githubusercontent.com/47158232/212128944-24933d2d-7416-459a-94fb-328226518bf3.png)
Reagent Extractor
![image](https://user-images.githubusercontent.com/47158232/212129311-e7b5c9f3-97b1-4b4a-84fd-e5aae00f4f2f.png)

2023-01-17 19:46 UTC, TobleroneSwordfish commented
!merge_upstream

2023-01-17 20:14 UTC, merged