New antagonist : Brain slugs
goonstation/goonstation pull request #11841
Opened 2022-11-06 22:33 UTC by Bartimeus973

[feature] [game-objects] [gamemodes] [input-wanted]
## About the PR 
Introduces a new antagonist to the classic and RP servers : Brain slugs.
The design document is here: https://docs.google.com/document/d/1XNOuS134lWLZojUUvmbZWNrCNR2SQaweFMcX2MZQdY8/edit#
I won't go too in details about the abilities since they are already detailed in the design doc.

This antagonist is centered around stealing organs, infesting corpses and offering a final evolution allowing it to live as a powerful alien monster.

Brain slugs spawn into the shift inside the body of the player's character. They may gain stronger abilities such as a way to turn turfs into deadly acid, or to create critters to fight for them by collecting organs off the crew.
Once sufficiently fed, they are allowed to become a terrifying monster allowed to roam through the disposal pipes, looking to feast on the crew. They may also revert from this form to the previous one after a while.
If they desire to, or die, the slug may exit the host's body and possess a dead human or a living small_animal. Doing so doesn't give any points to the slug.

Todo:
- [ ] Sprites!
- [ ] Sounds!

## Why's this needed? 
Keeps the game fresh by allowing a new alternative to the list of antagonists currently present in the game.
Offers a different dynamic to the antagonists currently present on the RP servers.

## Changelog 

```changelog
(u)Bartimeus973
(*)New antagonist on the RP and classic servers: Space slugs have invaded the station! These beings may try to possess the dead, or animals, and pass as crew waiting to harvest an innocent bystander's organs!
```

2022-11-06 23:02 UTC, Bartimeus973 commented
I probably messed up the implementation of the antagonist to rolls and roundstarts. I didn't fully grasp the system behind antag selection yet.

2022-11-13 02:08 UTC, nefarious6th commented
sprites look good, no errors.

some runtimes when using the restraining puddle ability both as an adult and baby slug:
![runtime1](https://user-images.githubusercontent.com/72267018/201501525-ae7bfcf0-1354-45b7-9fc0-be20b74533d9.png)
![runtime2](https://user-images.githubusercontent.com/72267018/201501527-dd8d96d9-7626-4d38-ab41-815926152d3e.png)

the broodling ability: when the broodlings burst out of the corpse, it creates an infinite loop of runtimes on blood.dm at line 133. i can't recover the runtime menu from the client to show more info, sorry.

all abilities seem to have good balance; devour and harvest might both be a touch slow imo

other thoughts about slugs:
- baby slugs can pilot vehicles -- is this intended given they already have space-proofing?
- adult slugs don't trigger beepsky like transformed werewolves and aboms do, which i expected them to. i assume intended?
- very very limited pool of NPC critters can be taken over; so far only capybara has worked for me and roaches, mice, walrus, ferrets have not

other thoughts not directly about slugs:
- you can weld out a pipe and weld it back in to patch it and bypass using the steel sheet patching, which maybe is more tedious? i think the patching with the sheet is way cooler though and wish there was a way for pipes to retain the hole even when welded out (unless they did and the sprite just ???)

probably another pipe-review on all the maps would be needed in conjunction with this just to be sure all the pipenets work.

2022-11-13 03:05 UTC, Bartimeus973 commented
Thank you very much for the runtimes and error reports! I'll get on them tomorrow.
A few things about some other points:

Yes baby slugs can pilot pods, but that isn't exactly intended. It is moreso to do with the fact that critters in general can control pods (see changeling limbs). That is more of a general thing that could be changed.
Adult slugs don't currently trigger beepsky, but being clear inhuman targets they probably should. I suppose i can change that!
The limited pool of npc is indeed a problem that is due to most mobs on station being obj/critters and not mob/critters. I'm working on turning the most common station mobs from obj to mobs on the side, but it's a fairly slow process.

I completely forgot that you can just unweld/reweld the pipe and it'll also fix the hole. I could make the pipe carry over the busted up status or find another way to go around it. Will see!

2022-11-20 19:33 UTC, Bartimeus973 commented
Pipes can still be welded on and off, but they now take a solid uninterupted five seconds of welding before they can be removed in order to not make it a pain to fix, while also leaving the steel sheet fixing as the prime way to fix it quickly.

Sec scanners now ring when slugs go through to alert security.

However, i dont think i will make securitrons and guardbuddies chase the slug, since those usually try to cuff the offender, and slugs cannot be cuffed as they dont have hands. It'd lead to messy behavior and a potential permastun.

2022-11-23 18:13 UTC, ThatGuyThe commented
awesome!!

2022-11-24 23:12 UTC, ThatGuyThe commented
i feel like you should be able to enter someone's head even if they are alive, just not being able to take control of them

2022-11-24 23:14 UTC, ThatGuyThe commented
just a suggestion though :)

2022-11-25 12:39 UTC, Bartimeus973 commented
I'm currently not really interested in letting them infest living people as it would either end up with the slug feeling like a glorified spectator or an eventual instant death for the host.
I do appreciatte the suggestion though! If you have more, please use the forum thread linked in the first few comments.

2022-11-25 23:08 UTC, Tarmunora requested changes

2022-11-25 23:08 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Medical.dm
> +										spawn(3 SECONDS)
again re spawn/SPAWN, nested spawn/sleep

2022-11-25 23:08 UTC, Tarmunora commented on code/modules/projectiles/special.dm
> +	ks_ratio = 1.0
define projectiles with `damage` and `stun`. `power` and `ks_ratio` are autogenerated from those values

2022-11-28 16:54 UTC, Bartimeus973 commented on code/WorkInProgress/recycling/disposal.dm
> +	var/holed_up = FALSE
Changed to "punctured"

2022-11-28 17:01 UTC, Bartimeus973 commented on code/mob/living/life/Life.dm
> +				else if (AH.points <= 0)
Changed the above if to be strictly superior to 0 to avoid this deadzone.

2022-11-28 17:03 UTC, Bartimeus973 commented on code/modules/antagonists/brain_slug/objs/acidic_goo_ball.dm
> +	desc = "A pile of sticky goo, restraining movement."
Seems i accidentally never saved the name/desc. Done now.

2022-11-28 18:14 UTC, Bartimeus973 commented on code/mob/living/life/Life.dm
> +						break
Indeed much more efficient.

2022-11-28 18:29 UTC, Bartimeus973 commented
It would appear that this antagonist has not managed to meet the expectations I and others had set for it, and as such i shall be closing this PR.
Thank you everyone who has been providing ideas, suggestions and feedback. It's still been fun and i feel like i've learned alot!

2022-11-28 18:29 UTC, closed without merging