Forbidden antagonist field for map settings datum
goonstation/goonstation pull request #11918
Opened 2022-11-10 15:39 UTC by Kubius

[BUG][CODE QUALITY]
## About the PR 

Creates a map settings datum variable containing a list of modes not permitted to appear on the map (currently, blob on Nadir) and makes both getSpecialModeCase and the late antagonist respawn check it for compatibility.

## Why's this needed? 

Fixes #11916 - hopefully for good.

2022-11-11 20:41 UTC, ZeWaka approved these changes

2022-11-11 20:41 UTC, ZeWaka commented on code/datums/configuration.dm
> +	if (map_settings && islist(map_settings.forbidden_antags) && length(map_settings.forbidden_antags))
```suggestion
	if (length(map_settings?.forbidden_antags))
```
it would never not be a list

2022-11-11 20:41 UTC, ZeWaka commented on code/map.dm
> +	var/list/forbidden_antags = list() //List of mode names to prevent from appearing in a map
doc comment

2022-11-11 20:41 UTC, ZeWaka commented on code/modules/events/antag_ghost_respawn.dm
> +			if (map_settings && islist(map_settings.forbidden_antags) && length(map_settings.forbidden_antags))
```suggestion
			if (length(map_settings?.forbidden_antags))
```
ditto

2022-11-11 20:41 UTC, ZeWaka commented on code/modules/events/antag_ghost_respawn.dm
> -					src.antagonist_type = pick(list())
lol pick from empty list is a runtime

2022-11-11 23:08 UTC, Kubius commented on code/modules/events/antag_ghost_respawn.dm
> -					src.antagonist_type = pick(list())
So I inadvertently fixed a thing?

2022-11-11 23:08 UTC, Kubius commented on code/map.dm
> +	var/list/forbidden_antags = list() //List of mode names to prevent from appearing in a map
Triple-slashed and slightly elaborated.

2022-11-12 06:10 UTC, ZeWaka commented on code/modules/events/antag_ghost_respawn.dm
> -					src.antagonist_type = pick(list())
yep

2022-11-12 06:10 UTC, ZeWaka approved these changes

2022-11-12 06:10 UTC, ZeWaka commented on code/map.dm
> +	var/list/forbidden_antags = list() /// List of mode names to prevent from appearing in a map (lowercase strings)
```suggestion

	/// List of mode names to prevent from appearing in a map (lowercase strings)
	var/list/forbidden_antags = list() 
```

2022-11-12 21:36 UTC, Tarmunora requested changes
Two thing:
1.) I think it's unwise to use a single var for both antagonist filtering and gamemode filtering like this, and would already cause issues if you wanted to block say, flock, where the gamemode name is `flock` and the antag respawn name is `Flockmind`
2.) this doesn't appear to affect mixed/etc?

2022-11-12 23:43 UTC, Kubius commented
Point 2, I think you're correct. (uh oh)

Point 1, I'm on the fence about. There are two ways I can think of to address this:

- Go around and standardize mode restrictions to operate on the ROLE_(whatever) defines mechanically, and use those in the forbidden antagonists field as well.
- Add a distinct class of forbid for each of latejoin antagonist filtering, mixed antagonist filtering, and gamemode filtering.

The latter just kinda strikes me as clunky?

2022-11-21 15:31 UTC, Kubius commented
To state it explicitly, I'd like input on which approach to take.

2022-12-29 00:56 UTC, closed without merging