Packet Controlled Manufacturers
goonstation/goonstation pull request #11923
Opened 2022-11-10 22:14 UTC by Conchuckter

## About the PR 
Adds the ability for 
Adds packet integration to manufacturers/fabrictors.

Also seems to fix a couple problems with pausing the queue.

## Why's this needed? 
Automation could be interesting, especially with mechcomp inserters etc.

## Changelog 

```changelog
(u)Conchuckter
(*)Manufacturers are now packet integrated, become a nerd today!
```

2022-11-11 12:16 UTC, zjdtmkhzt commented
The description says it fixes issues related to pausing, presumably that is the change that makes it so it uses the TIME macro instead of world.time?

2022-11-11 12:18 UTC, Conchuckter commented
Yup, I've had problems where after pausing the queue `time_left` would be set to something like 500 seconds. From my testing this has fixed it but I'm not entirely sure.

Not sure if its actually been reported.

2022-11-15 20:02 UTC, TobleroneSwordfish requested changes
one step closer to true factorio SS13

2022-11-15 20:02 UTC, TobleroneSwordfish commented on code/obj/machinery/manufacturer.dm
> +				if(world.time < last_queue_op + 5)
Consider using the `TIME` define here, to prevent issues with lag slowing things down.

2022-11-16 18:29 UTC, TobleroneSwordfish commented on code/obj/machinery/manufacturer.dm
> +#define MAX_SPEED_HACKED
should also `#undef` these at the bottom of the file

2022-11-19 12:44 UTC, pali6 approved these changes

2022-11-19 12:44 UTC, pali6 commented on code/obj/machinery/manufacturer.dm
> +				if(world.time < last_queue_op + 5)
```suggestion
				if(TIME < last_queue_op + 5)
```

2022-11-19 12:44 UTC, pali6 commented on code/obj/machinery/manufacturer.dm
> +					last_queue_op = world.time
```suggestion
					last_queue_op = TIME
```

2022-11-19 12:45 UTC, pali6 commented
Looks good to me, waiting for @MarkNais's review.

2022-11-24 06:07 UTC, MarkNais requested changes
One minor-issue: because the `help` command responds with `command=help` it causes a temporary feedback loop. See screenshot below. It thankfully stops (somehow) without being noticeable on local-testing, but still not something I want on production.
So I've suggested all of the responses being `command=term_message` .

![image](https://user-images.githubusercontent.com/9563541/203706612-b69a1a86-6132-4d6f-8fc2-c5b38fa96433.png)

2022-11-24 07:37 UTC, Conchuckter commented on code/obj/machinery/manufacturer.dm
> +				post_signal(list("address_1" = sender, "sender" = src.net_id, "command" = "queue", "data" = src.queue.Join(",")))
Just removed the command field from these packets entirely, as it is more consistent with other devices.

2022-11-24 07:48 UTC, merged