Pipe Spawners
goonstation/goonstation pull request #12032
Opened 2022-11-19 06:01 UTC by TheTyrant25

[OBJECTS] [INTERNAL] [MAPPING] [STATION SYSTEMS] [FEAT] [QOL]
## About the PR 
Hey, remember cable spawners? That, but it's pipes.
Disposal and Mail and Morgue and Cargo pipes, to be specific. Not atmospheric ones. We don't talk about those.
**BIG WARNING:** Pipes are inherently more complex and require manual placing of junctions. This is really just for drawing long stretches and 90 degree turns. DO NOT TRY TO MAKE 3 (or heaven forbid, 4) WAY JUNCTIONS WITH THESE.

## Why's this needed? 
It's handy

2022-11-19 08:02 UTC, frawhst commented
can't wait to make 3 (or heaven forbid, 4) way junctions with these

2022-11-19 08:02 UTC, frawhst commented
Also gonna draft this while the checks are screaming

2022-11-19 08:04 UTC, TheTyrant25 commented
yeah so the actual coding bit appears to be done, it's just uhhhh well bug fixing now

2022-11-19 08:37 UTC, TheTyrant25 commented
okay looks finished now

2022-11-19 13:02 UTC, pali6 commented on code/WorkInProgress/recycling/disposal.dm
> +			dpdir |= SOUTH
www.byond.com/docs/ref/info.html#/proc/get_dir

2022-11-19 13:02 UTC, pali6 commented on code/WorkInProgress/recycling/disposal.dm
> +				dpdir |= SOUTH
ditto

2022-11-19 13:03 UTC, pali6 commented on code/WorkInProgress/recycling/disposal.dm
> +		if (dpdir & (NORTH + SOUTH) || dpdir & (EAST + WEST))
```suggestion
		if ((dpdir & (NORTH | SOUTH)) || (dpdir & (EAST | WEST)))
```

2022-11-19 13:05 UTC, pali6 commented
Also, imo these should ignore pipespawners and pipes which are of the wrong type / color etc.
This should allow people to use these spawners next to each other when one is placing mail pipes and the other disposal pipes etc.

2022-11-20 03:25 UTC, TheTyrant25 commented
> Also, imo these should ignore pipespawners and pipes which are of the wrong type / color etc. This should allow people to use these spawners next to each other when one is placing mail pipes and the other disposal pipes etc.

Yeah that is a good point. They should be able to cross over too

2022-11-20 03:45 UTC, TheTyrant25 commented
redid the whole detection system so that it includes your three suggestions, @pali6

2022-11-20 07:52 UTC, TheTyrant25 commented
So the regular pipes work now, but the other kinds don't work at all, plus they break the regular pipes if they're nearby. I really don't know how to fix this

2022-11-20 13:22 UTC, TheTyrant25 commented
going to completely overhaul the system to use `.type` tomorrow

2022-11-22 13:11 UTC, TheTyrant25 commented
> I really don't know how to fix this
i found out how to fix it, by the way
just ignore the base type and establish a 'regular' subtype 👍 
and pray the users will use them

2022-11-24 18:57 UTC, pali6 requested changes
Looks good at a glance except for the __build.dm

2022-11-24 18:57 UTC, pali6 commented on _std/__build.dm
>  //#define I_AM_ABOVE_THE_LAW // Prevents all secbots and guardbuddies from spawning, useful for gun testing
don't commit __build.dm

2022-11-25 00:27 UTC, TheTyrant25 commented on _std/__build.dm
>  //#define I_AM_ABOVE_THE_LAW // Prevents all secbots and guardbuddies from spawning, useful for gun testing
oops thought i reverted that

2022-11-25 11:45 UTC, TheTyrant25 commented on code/modules/power/cable.dm
> +		CRASH("Lone cablespawner!\nCable location: [src.x] x, [src.y] y, [src.z] z.")
oh yeah forgot i did this lol. I think it should be fine, single pipe spawners have a similar crash behaviour, so i thought it should match

2022-12-01 02:45 UTC, TheTyrant25 commented
oops they do not connect to junctions

2022-12-01 03:41 UTC, TheTyrant25 commented
okay this is all complete now

2022-12-03 02:28 UTC, TheTyrant25 commented on code/modules/power/cable.dm
> +		CRASH("Lone cablespawner!\nCable location: [src.x] x, [src.y] y, [src.z] z.")
just going to remove that actually

2023-01-10 15:15 UTC, frawhst approved these changes
one small thing, otherwise lgtm

2023-01-10 15:15 UTC, frawhst commented on code/WorkInProgress/recycling/disposal.dm
> +	qdel(selftile)
```suggestion
	selftile.Cut()
```
bit cleaner (basically sets the list to 0-length)

2023-01-10 15:15 UTC, frawhst commented on code/WorkInProgress/recycling/disposal.dm
> +	qdel(selftile)
actually im just merging this

2023-01-10 17:43 UTC, merged