Handwashing clarifications
goonstation/goonstation pull request #12187
Opened 2022-11-27 08:01 UTC by MarkNais

## About the PR 
Notifies the player that they need to remove their gloves and have both hands free to improve their hygiene through hand-washing.

Fixes #12186 #12166
## Why's this needed? 
Players are unsure why handwashing isn't working.

Tested:
![image](https://user-images.githubusercontent.com/9563541/204125015-825a2080-aa27-4b18-bab0-5b33b12752d2.png)
![image](https://user-images.githubusercontent.com/9563541/204125018-b6b2cb2d-0592-47d1-b8b4-898ea5288b0f.png)
I also tested it with robot arms.

2022-11-27 08:02 UTC, MarkNais commented
I also tested hand-washing with one-arm: works.

2022-11-27 16:41 UTC, Kubius requested changes
Barring a typo, LGTM.

2022-11-27 16:41 UTC, Kubius commented on code/obj/submachine/cooking.dm
> +					user.show_text("If you want to improve your hygine, you need to remove your gloves first.")
```suggestion
					user.show_text("If you want to improve your hygiene, you need to remove your gloves first.")
```

2022-11-28 06:43 UTC, ZeWaka approved these changes

2022-11-28 07:15 UTC, merged