Cable spawners fix
goonstation/goonstation pull request #12232
Opened 2022-11-30 11:31 UTC by TheTyrant25

[BUG] [MAPPING] [INTERNAL]
## About the PR 
Fixes the node subtypes of cable spawners to actually connect to things. Also adds two new global dir lists and a proc, `alldirs_unique`, `ordinal_unique` and `proc/invert_dir()`. Also shortens the cable spawner check detection by like, a lot. A horrific amount. Thanks to pali for teaching me about `get_step()` in the pipe spawner PR! Life is about growth and change.

## Why's this needed? 
The cable spawner `/node` subtypes were completely broken and never worked in the first place. This fixes that.

2022-11-30 11:33 UTC, TheTyrant25 commented
luckily nobody has had any reason to use them yet, so it's led to no errors 👍

2022-11-30 12:57 UTC, TheTyrant25 commented
DISASTER
I COMMITTED BUILD AND ATLAS

2022-11-30 13:24 UTC, TobleroneSwordfish requested changes
cod review 🐟

2022-11-30 13:24 UTC, TobleroneSwordfish commented on code/modules/power/cable.dm
> +			cable_laying(0, directions[i]) */
just remove it instead of commenting, git history will preserve the old version anyway

2022-11-30 13:24 UTC, TobleroneSwordfish commented on code/modules/power/cable.dm
> +			if (normal_cable.type == src.cable_type)
should probably use `istype`

2022-11-30 13:24 UTC, TobleroneSwordfish commented on code/modules/power/cable.dm
> +	anchored = 1
```suggestion
	anchored = TRUE
```

2022-11-30 13:24 UTC, TobleroneSwordfish commented on code/modules/power/cable.dm
> +	// as it needs to store up to 8 at once
make these doc comment with triple slashes

2022-11-30 13:24 UTC, TobleroneSwordfish commented on _std/macros/dir.dm
> +proc/invert_dir(dir)
https://secure.byond.com/docs/ref/#/proc/turn

2022-12-01 02:29 UTC, TheTyrant25 commented on _std/macros/dir.dm
> +proc/invert_dir(dir)
i
i am a silly sausage

2022-12-01 03:41 UTC, TheTyrant25 commented
it's all done now

2023-01-02 03:57 UTC, merged