Fix getting radiation messages on radiation healing
goonstation/goonstation pull request #12268
Opened 2022-12-02 16:50 UTC by amylizzle

## About the PR 
If you're in the cryotube you get messages for being exposed to radiation. You shouldn't, because it's negative radiation, ie, healing.

2022-12-02 16:54 UTC, frawhst commented
that explains why I would get a 'you feel warm' etc whenever I admin healed myself!!

2022-12-02 16:54 UTC, frawhst approved these changes

2022-12-02 16:57 UTC, amylizzle commented
Yeah, it annoyed me every time I got in a cryotube, I just kept forgetting to fix it

2022-12-02 18:46 UTC, Tarmunora requested changes

2022-12-02 18:46 UTC, Tarmunora commented on code/mob/living.dm
> +	else if((actual_dose > 0) && (src.radiation_dose || prob(10)) && !ON_COOLDOWN(src,"radiation_feel_message",10 SECONDS))
```suggestion
	else if((actual_dose > 0) && (!src.radiation_dose || prob(10)) && !ON_COOLDOWN(src,"radiation_feel_message",10 SECONDS))
```

2022-12-03 13:22 UTC, amylizzle commented on code/mob/living.dm
> +	else if((actual_dose > 0) && (src.radiation_dose || prob(10)) && !ON_COOLDOWN(src,"radiation_feel_message",10 SECONDS))
ooh good catch

2022-12-03 18:25 UTC, Tarmunora approved these changes

2022-12-04 09:43 UTC, merged