adds a confirmation prompt for blob deployment
goonstation/goonstation pull request #12360
Opened 2022-12-09 18:05 UTC by nefarious6th

[gamemodes][qol]

## About the PR 
adds a confirmation prompt to blobs deploying their first nucleus. at least i hope that's how this works.

## Why's this needed? 
Verification
preventing blobs from misclicking and deploying

2022-12-09 19:20 UTC, TobleroneSwordfish commented
Oh and if you're adding it for blob you may as well add it for flock too for consistency

2022-12-09 23:16 UTC, nefarious6th commented on code/modules/antagonists/blob/blob_abilities.dm
>  		if (..())
just remove the `TRUE`?

2022-12-09 23:21 UTC, nefarious6th commented on code/modules/antagonists/blob/blob_abilities.dm
>  		if (..())
oh, whoops, i get it now, i moved the section under all the stuff you can't deploy into

2022-12-10 08:33 UTC, TobleroneSwordfish requested changes

2022-12-10 08:33 UTC, TobleroneSwordfish commented on code/datums/abilities/flock/flockmind.dm
> +
I'd move this below the area checks so you can use it to see if the area you've selected is valid without actually deploying.

2022-12-10 08:33 UTC, TobleroneSwordfish commented on code/modules/antagonists/blob/blob_abilities.dm
> +
Again, put it below the tutorial check so you don't get a confirmation prompt if you can't use the ability

2022-12-11 09:57 UTC, merged