Destructible stones
goonstation/goonstation pull request #12479
Opened 2022-12-22 03:31 UTC by TobleroneSwordfish

[FEATURE] [GAME OBJECTS]
## About the PR 
Lets mining tools break stones on non-restricted z levels.

## Why's this needed? 
Annoying invincible stones from terrainify.

## Changelog 

```changelog
(u)LeahTheTech
(+)More types of stones can now be broken with mining tools.
```

2022-12-22 06:53 UTC, Tarmunora commented
> cant concussive glove a rock
😭

2022-12-30 05:25 UTC, ZeWaka requested changes

2022-12-30 05:25 UTC, ZeWaka commented on code/obj/decorations.dm
> +					rock.pixel_y = rand(-16,16)
use `rand_pos`

2022-12-30 05:25 UTC, ZeWaka commented on code/obj/decorations.dm
> +					rock.pixel_y = rand(-16,16)
{} instance initalization var like said on the discord

2023-01-08 20:26 UTC, merged