Credit transfer device rework
goonstation/goonstation pull request #12619
Opened 2023-01-03 16:37 UTC by DisturbHerb

[OBJECTS][TGUI][CLEANLINESS][QOL][REWORK][WIKI]

## About the PR 
This PR reworks the credit transfer device from its current state. While it still facilitates direct credit transfers between accounts, a lot of the back-end code has been rewritten for cleanliness and to implement new features.

To start, it now has a TGUI interface. Players can register their card with the machine and they'll own it unless the machine is reset by themselves or by a Head of Staff.
![qsRkvSMzNo](https://user-images.githubusercontent.com/66253095/210399607-8e78c9ba-d780-4fa9-a68c-e99e8ec8d5cd.png)

The owner of the machine can set a price on the machine for a payer to transfer, who can then optionally add a percentage tip on top.
![z3TC9xQAo9](https://user-images.githubusercontent.com/66253095/210399776-3bfad249-0569-454c-bf12-88a8211b6287.png)

Once a transaction is complete, the machine will print out a receipt detailing the transaction, and the customer may elect to print themselves a copy as well.
![TqxxuklJ8J](https://user-images.githubusercontent.com/66253095/210399865-9b96fb43-5012-4537-b4b6-7b60e3200a0d.png)

On the back-end, there's also a bunch of safety stuff to ensure nothing is accidentally or intentionally altered during the payment process.

## To Do
- Replace the tip rounding code with `ceil()` once 515 is out, the tip amount currently rounds down, I'd like it to round up to the nearest integer.
- Get someone else who's far more handsome than I to look at the DM code because for all I know it's fugly as shit. But it works!

## Why's this needed? 
Improving the ease of use of the device with an interface and clear instructions on use, in addition to the added features, should encourage its greater use. Unfortunately, the credit transfer device is neglected by most to the point where it's just table clutter. This also enables some fun forensic accounting stuff if you're into that.

## Changelog 

```changelog
(u)DisturbHerb
(+)Credit transfer devices have been reworked and TGUI-ified.
```

2023-01-03 16:45 UTC, ZeWaka requested changes

2023-01-03 16:45 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/Cashreg.tsx
> +            {owner ? 'Owner: ' + owner : 'Swip ID to own'}
```suggestion
            {owner ? 'Owner: ' + owner : 'Swipe ID to own'}
```

2023-01-03 16:45 UTC, ZeWaka commented on code/obj/machinery/cashreg.dm
> +					src.print_receipt(payee, O.registered, transaction_price, transaction_tip, transaction_total, customer_copy = true)
merge skew

2023-01-03 16:45 UTC, ZeWaka commented on code/obj/machinery/cashreg.dm
> +	proc/print_receipt(payee, payer, price, tip, total, customer_copy = false)
merge skew

2023-01-03 16:45 UTC, ZeWaka commented on code/obj/machinery/cashreg.dm
> +		var/transaction_total = src.amount + round(src.amount * src.tip) // when we get to 515 please replace this with ceil()
you do know we have ceil right now, right?

2023-01-03 16:45 UTC, ZeWaka commented on code/obj/machinery/cashreg.dm
> +	var/transaction_limit = 999999
```suggestion
	var/const/transaction_limit = 999999
```

2023-01-03 16:45 UTC, ZeWaka commented on code/obj/machinery/cashreg.dm
> +	var/obj/item/card/id/owner_card = null
disposing

2023-01-03 16:55 UTC, DisturbHerb commented
Fingerprints aren't being left on the machine despite `src.add_fingerprints(user)` going off properly on `attack_hand(mob/user)` while I was stepping through the code. Will have to take a look at it later.

2023-01-03 16:57 UTC, BatElite commented
> Fingerprints aren't being left on the machine despite `src.add_fingerprints(user)` going off properly on `attack_hand(mob/user)` while I was stepping through the code. Will have to take a look at it later.

You need FPRINT in the flags I believe

2023-01-12 19:29 UTC, pali6 commented
!merge_upstream

2023-01-12 19:36 UTC, pali6 commented
!merge_upstream

2023-01-12 20:35 UTC, pali6 commented
!merge_upstream

2023-01-12 20:56 UTC, pali6 commented
!merge_upstream

2023-01-12 21:14 UTC, pali6 commented
!merge_upstream

2023-01-12 21:33 UTC, pali6 commented
!merge_upstream

2023-01-12 21:49 UTC, pali6 commented
!merge_upstream

2023-01-16 18:30 UTC, TobleroneSwordfish requested changes
Stuff found while testing:
- The "click to edit price" tooltip comes up even when the reader is not owned. Also just having an arbitrary space you have to click on to edit the price isn't great.
- The "swipe ID to own" button has a tooltip that says "click to register ownership" but that only works while you're directly holding the ID.
- The "click to set tip percentage" tooltip comes up when there is no price set.
- There's no margin between the two bottom buttons, they're just smooshed together.
- Might be nice if it saved prices between each sale, since a lot of uses of it are going to be selling similarly priced items.
Otherwise this looks really cool, great for RP shops!

2023-01-19 03:03 UTC, TobleroneSwordfish commented
As I said in discord, having the entire middle area light up and give you a tooltip even if you can't interact with it is kinda jarring, would make much more sense if it just didn't do that for non-owners.

2023-01-21 11:52 UTC, TobleroneSwordfish approved these changes

2023-01-21 13:37 UTC, merged