Vampires and thralls only get a blood penalty for draining rotten corpses
goonstation/goonstation pull request #12717
Opened 2023-01-12 10:46 UTC by CheffieGithub

## About the PR 
Changes the vampire bite isDead check to a decomp stage check, does penalties if its started decomposing at all.

## Why's this needed? 
The recent change to thralls made them very good at killing things but killing things makes them get a trickle of blood. 
Makes it less punishing for killing prey as a vampire/thrall.
gives more incentive for proper corpse disposal.

## Changelog 

```changelog
(u)Cheffie
(+)Vampires only get a penalty for draining rotting corpses
```

2023-01-12 23:36 UTC, Tarmunora requested changes
Fine for thralls, but not for full vampires I think.

2023-01-12 23:50 UTC, CheffieGithub commented
Im just curious, why not for full vampires? I feel like them being different will just encourage thralls to go off on their own since their masters won't really benefit from their kills. And it adds more use to diseased touch other than just killing high value targets for immediate thralling.

2023-01-13 01:28 UTC, Tarmunora commented
> Im just curious, why not for full vampires?

Because the current system allows for the draining of dead bodies at half-value as a crutch/fallback but encourages going for live prey. This change (along with a syringe of formaldehyde) would more-or-less completely negate that aspect of vampires.

2023-01-13 09:21 UTC, CheffieGithub commented
I could add a check for embalming fluid as well, I was going to do that anyway

2023-01-13 21:24 UTC, Tarmunora approved these changes

2023-01-17 20:02 UTC, merged