Pod Wars Team Planning Maps
goonstation/goonstation pull request #12733
Opened 2023-01-13 17:22 UTC by Mister-Moriarty

[Feature] [Gamemodes] [Add To Wiki]

## About the PR:
Expands the physical station minimaps feature implemented in #12463 and previous PRs to work with maps of any size, and adds map computers and controller computers to the Bridge of both the NSV Pytheas and Lodbrok.

Each debris map computer will display the location of both pod carriers, the three control points, all minor areas, asteroids, and warp beacons, and the location of every living member of the respective team. Should one of the teams capture a control point, the colour of the control point on the minimap will change to the primary colour of the capturing team. Their controllers operate in the same way as the handheld controller on the Cairngorm.

To this end, a minimap renderer datum has been created, which will handle all operations related to drawing the minimaps, and allow for specific areas to be drawn separately on an `atom/movable` for easy recolouring across various minimap instances. Each pod pilot will also receive a special tracking implant, and the Bridges of the two pod carriers have been redesigned.

## Why's this needed?
While static debris field maps already exist, an additional live, high visibility minimap will help aid coordination within teams, especially in matters of determining where to stage an assualt, where all players on a team are currently at, and in navigating the field.

## Changelog:
```changelog
(u)Mr. Moriarty
(*)The NSV Pytheas and Lodbrok have now both been installed with debris field map displays and map controllers, similar to the ones that may be found on the Cairngorm, situated in their Bridges.
```

2023-02-09 21:43 UTC, TobleroneSwordfish requested changes
Extremely cool, I wasn't aware this had actual pilot tracking too. The code overall looks good, I'm a little concerned about the memory impacts of shoving every solid turf in a 500x500 z level in a list, but it seems to load fine and is only a roundstart issue anyway.

The minimap markers on the map controllers are ludicrously small currently, to the point of being 1-2 pixels (probably caused by the larger map size)
![image](https://user-images.githubusercontent.com/20713227/217944614-099ba0f3-3fb8-4a0d-973c-0fe6d28bf65c.png)

2023-02-09 21:43 UTC, TobleroneSwordfish commented on code/modules/minimap/minimap_renderer.dm
> +	proc/recolour_area(var/area_group, var/colour)
as much as it pains me as a fellow brit, we should probably stick to `color` for proc names at least (don't worry about comments tho)

2023-02-09 22:02 UTC, Mister-Moriarty commented
> ...I'm a little concerned about the memory impacts of shoving every solid turf in a 500x500 z level in a list, but it seems to load fine and is only a roundstart issue anyway.

A turf will only be placed into that list should the area containing it have a non-null `minimaps_to_render_on` var, so only a small fraction of the (likely more than) 500^2 turfs will be placed into that list.
​

> The minimap markers on the map controllers are ludicrously small currently, to the point of being 1-2 pixels (probably caused by the larger map size)

Regarding the miniscule pilot markers, that will likely require a resizing system for minimap markers, which I will hopefully begin work on soon.

Thank you for the review!

2023-02-17 07:20 UTC, ZeWaka commented on code/modules/minimap/minimap_object.dm
> +/obj/machinery/computer/pod_wars_minimap_controller
this should be an abstract type right?

2023-02-17 07:20 UTC, ZeWaka commented on code/modules/minimap/minimap_renderer.dm
> +			if (2**i & bitflag)
parentheses pls

2023-03-04 01:17 UTC, ZeWaka commented
fuu

2023-03-15 07:04 UTC, ZeWaka approved these changes

2023-03-22 05:40 UTC, Kyle2143 commented
Yes, this is amazing. This is something I had "planned" to add to each ship shortly after releasing pod wars. This has literally all the features I had considered for this, so I wonder if I actually wrotw it down or this is just such a logical feature that anyone would arrive at it.

 I remember Sov pitched a good way to implement this, but I never got around to it cause I was already starting to wind down for a while and have been not here.

2023-04-03 00:18 UTC, merged