mobifies scorpions
goonstation/goonstation pull request #12777
Opened 2023-01-16 00:53 UTC by colossusqw

[LABEL][AI][Rework]
## About the PR 
This PR:
This PR replaces the critter scorpions with a mob version. They will wander around and attack players and other mobs alike, and like their critter counterpart, can be tamed with food.

## Why's this needed? 
Mob > critter

## Changelog 

```changelog
(u)Hans
(+)Mobifies scorpions!
```

2023-01-16 20:39 UTC, amylizzle requested changes
Code looks good. Only suggestion I have is to replace the `qdel()` call on the food with the standard mob eating behaviour.

2023-01-16 20:39 UTC, amylizzle commented on code/mob/living/critter/small_animal.dm
> +			qdel(I)
Maybe replace this with `I.Eat()`

2023-01-16 21:48 UTC, amylizzle commented
Oh I meant in general, not specifically `I.Eat()`. You might wanna cast it to a snack and use the eat proc from that, with the appropriate arguments.

2023-01-16 22:22 UTC, amylizzle approved these changes

2023-01-22 09:25 UTC, pali6 commented
Does this need a changelog entry?

2023-01-22 09:26 UTC, pali6 approved these changes

2023-01-22 09:27 UTC, pali6 commented
Eh, I'm gonna with "doesn't".

2023-01-22 09:27 UTC, merged