Genebooth info PDA App for Geneticists
goonstation/goonstation pull request #12855
Opened 2023-01-23 22:41 UTC by Saicchi

[FEATURE]

## About the PR 
PDA program for Geneticists only which shows what is in the genebooths.
Only present in Geneticists PDA, AI nor Medical Director have it.
May be harder to make hidden gene booths if someone steals a Geneticists PDA to check the booths.

![image](https://user-images.githubusercontent.com/47158232/214164860-2d58cd5e-81b2-4540-b3b4-dd2bd8254ada.png)

## Why's this needed? 
So Geneticists can more easily keep track of whats is in the Genebooth and how much there is left.

## Changelog 

```changelog
(u)DrWolfy
(+)Genebooth Info program for Geneticists!
```

2023-01-23 23:25 UTC, Wisemonster commented
Considering the Mdir is in charge of the geneticist, has the ability to lock genes in the gene booth, and the ce and rd have apps of the departments under them, it seems a bit weird that the mdir doesn't have this app on their pda.

2023-01-24 21:48 UTC, Saicchi commented
Added the tracker to the MDir and AI.

2023-02-02 19:57 UTC, TobleroneSwordfish commented
![image](https://user-images.githubusercontent.com/20713227/216436360-74e316e4-3e1b-43c5-a470-44d29b437dc8.png)
?

2023-02-02 20:54 UTC, Saicchi commented
> ![image](https://user-images.githubusercontent.com/20713227/216436360-74e316e4-3e1b-43c5-a470-44d29b437dc8.png) ?

That was the test description I gave to to the Alcohol Resitance gene. As it says I only locked it the 3rd booth.

2023-02-04 15:58 UTC, TobleroneSwordfish requested changes

2023-02-04 15:58 UTC, TobleroneSwordfish commented on code/obj/item/device/pda2/smallprogs.dm
> +		for_by_tcl(GB, /obj/machinery/genetics_booth)
```suggestion
		for_by_tcl(booth, /obj/machinery/genetics_booth)
```
try not to use non-standard 1 or 2 letter variable names (ie `turf/T` is okay, but `genetics_booth/GB` is not)

2023-02-04 15:58 UTC, TobleroneSwordfish commented on code/obj/item/device/pda2/smallprogs.dm
> +			for (var/datum/geneboothproduct/P as anything in GB.offered_genes)
```suggestion
			for (var/datum/geneboothproduct/product as anything in GB.offered_genes)
```

2023-02-07 12:40 UTC, Saicchi commented
![image](https://user-images.githubusercontent.com/47158232/217247220-e3ff1ca1-2ed9-4675-9472-7b66dda99e1e.png)
No changes in the layout, only displaying how a more proper use of it would look like.

2023-02-08 02:53 UTC, TobleroneSwordfish approved these changes

2023-02-08 06:48 UTC, merged