Vending machine slogans now have maptext
goonstation/goonstation pull request #12913
Opened 2023-01-28 14:57 UTC by DisturbHerb

[FEATURE][OBJECTS]

## About the PR 
Vending machines, when outputting the slogans loaded onto them, now have associated maptext.
![image](https://user-images.githubusercontent.com/66253095/215273321-807da507-81ff-4c7d-b3a3-30fcc23b50e5.png)

## Why's this needed? 
Slogans are presently quite easy to miss when they're outputted. This should hopefully add more flavour.

2023-01-29 20:06 UTC, ZeWaka requested changes

2023-01-29 20:06 UTC, ZeWaka commented on code/modules/vending/vending.dm
> +		src.audible_message("<span class='subtle'><span class='game say'><span class='name'>[src]</span> beeps, \"[message]\"</span></span>", 2, assoc_maptext = slogan_text)
why aren't you reusing text_out

2023-01-30 03:33 UTC, DisturbHerb commented on code/modules/vending/vending.dm
> +		src.audible_message("<span class='subtle'><span class='game say'><span class='name'>[src]</span> beeps, \"[message]\"</span></span>", 2, assoc_maptext = slogan_text)
that is a good question

2023-01-30 06:41 UTC, ZeWaka requested changes

2023-01-30 06:41 UTC, ZeWaka commented on code/modules/vending/vending.dm
> +		src.audible_message("<span class='game say'><span class='name'>[src]</span> beeps,</span> \"[voidSpeak(text_out)]\"", 2, assoc_maptext = slogan_text)
double voidspeak?

2023-02-02 22:06 UTC, ZeWaka approved these changes

2023-02-04 19:00 UTC, merged