Reworks and adds a few flags (the fabric kind)
goonstation/goonstation pull request #12926
Opened 2023-01-29 17:04 UTC by DisturbHerb

[MAPPING][OBJECTS][FEATURE][REWORK]

## About the PR 
This PR re-organises `obj/decal/wallsign/flag` into its own type, `obj/decal/poster/flag`, and introduces a new `obj/item/flag` that can be placed on walls much like fabric banners (#5036). Flags can also now be taken down from walls by attacking them with a free hand. All instances of flags in the public repository have been updated with the new file path. I hope.

Also, more flags. Thanks to Geonightman#2706 on Discord for making the icons for these.*
![flegs](https://user-images.githubusercontent.com/66253095/215811614-4cc553e8-b88f-4694-878b-1788fd65ad9c.png)

*this has been updated like numerous times sorry (accurate as of 1 feb 2023)

I drew the folded flag states and the blank flag stuff and I don't love them, feedback will be appreciated.

All of the flags, save for the lesbian pride ones, are currently player-unobtainable. I'm working on that.

## Why's this needed? 
Flags are nice and I wanted them for a thing.

```changelog
(u)DisturbHerb + Geonightman
(+)Flags can now be hung up and removed from walls.
(+)Adds a bunch of pride flags.
```

2023-01-30 04:57 UTC, ZeWaka commented
Why not just have a generic flag that can be painted like a canvas?

2023-01-30 05:07 UTC, DisturbHerb commented
> Why not just have a generic flag that can be painted like a canvas?

we've already got banners tho

2023-09-09 10:29 UTC, DisturbHerb commented
Opening this PR as-is for review (since this was never actually opened).

2023-09-22 11:08 UTC, TobleroneSwordfish requested changes
seems cool

2023-09-22 11:08 UTC, TobleroneSwordfish commented on code/obj/decal/poster.dm
> +	var/obj/item/flag/starting_flag = /obj/item/flag
this var shouldn't be typed since it's not an instance, also should have a doc comment indicating it's a type var

2023-09-22 11:08 UTC, TobleroneSwordfish commented on code/obj/item/flag.dm
> +	var/obj/decal/poster/flag/associated_flag = /obj/decal/poster/flag
same here

2023-09-22 11:08 UTC, TobleroneSwordfish commented on code/obj/item/flag.dm
> +		if (locate(/obj/decal/poster/flag, T))
```suggestion
		if (locate(/obj/decal/poster/flag) in T)
```
also may as well put it inside the type check

2023-09-22 11:08 UTC, TobleroneSwordfish commented on code/obj/item/flag.dm
> +		if (istype(T, /turf/simulated/wall/))
might want to include unsimmed too?

2023-09-22 11:08 UTC, TobleroneSwordfish commented on code/obj/item/flag.dm
> +			src.loc = new_flag
```suggestion
			src.set_loc(new_flag)
```
`src.loc =` is crime

2023-10-07 08:09 UTC, flappybatpal approved these changes

2023-10-22 04:12 UTC, TealSeer approved these changes

2023-12-19 04:31 UTC, merged