Datumises Wrestlers
goonstation/goonstation pull request #13155
Opened 2023-02-21 20:38 UTC by Mister-Moriarty

[Gamemodes] [Internal] [Code Quality]

## About the PR:
Wrestlers have been fully migrated onto the new datum system, including roundstart, random event, wrestlerdoodle, VR, and admin-spawned wrestlers.

## Why's this needed?
Same rationale as #9366.

2023-02-23 16:18 UTC, flappybatpal requested changes

2023-02-23 17:24 UTC, Mister-Moriarty commented on code/modules/antagonists/__antagonist.dm
> +	proc/remove_self(take_gear = TRUE)
Ah, my apologies, I forgot to remove the silent argument from those calls.

2023-02-23 20:53 UTC, flappybatpal commented
![image](https://user-images.githubusercontent.com/70909958/221027006-0484af27-1d83-4ecf-ab17-1afe57ba3c96.png)
If a regular wrestler gets a wrestling belt they get twice the wrestle abilities. This doesn't happen on live.

2023-02-24 10:25 UTC, flappybatpal commented
There are a further two things that might be out of scope but do need to be addressed.
1. The wrestling belt and wrestle contract both display an antagonist role on the Player Options panel:
![image](https://user-images.githubusercontent.com/70909958/221150613-b3069a7a-45bc-405a-95f5-15f1ccbf0b6a.png)
While this does not show up anywhere else such as the antag list or logs it is a concern for administrators being misled if they open a Player Options panel. I imagine this is the same issue that occurs with VR antagonists, where the "false" antag role is. This might be out of scope as the lack of issue with this elsewhere points to the logic used on Player Options
2. The Antagonists panel (in Game Options) lists a Ghost Respawn wrestler twice:
![image](https://user-images.githubusercontent.com/70909958/221153749-6d685a99-4be0-4d58-8e07-4c4ac59bf24f.png)

2023-02-24 10:26 UTC, flappybatpal approved these changes

2023-02-24 14:42 UTC, TobleroneSwordfish commented
I've fixed the player panel on master, still a little jank with interactions between the belt and the true antag, but it's probably fine.

2023-02-24 14:44 UTC, merged