Stops you from cutting a piece off of cable coils from a distance
goonstation/goonstation pull request #13331
Opened 2023-03-09 09:59 UTC by goonstation-enjoyer

[GAME OBJECTS] [BUG]
## About the PR 
Title. I tested this.

## Why's this needed? 
You shouldn't be able to cut a piece off of cables that are far away from you.

I don't think this needs a changelog.

2023-03-09 18:40 UTC, TobleroneSwordfish commented
How is `attackby` getting called at a distance anyway?

2023-03-09 19:17 UTC, ZeWaka requested changes

2023-03-09 19:17 UTC, ZeWaka commented on code/obj/item/cable_coil.dm
> +			if (GET_DIST(user, src) > 1)
no. in interact range

2023-03-09 21:37 UTC, goonstation-enjoyer commented
> How is `attackby` getting called at a distance anyway?

It isn't
1. Click cable with wirecutters
2. Drop cable and walk away
3. Put a number into the input box it opens
4. The cable teleports to you

2023-03-09 22:33 UTC, ZeWaka commented on code/obj/item/cable_coil.dm
>  			A.set_loc(user.loc) //Hey, split_stack, Why is the default location for the new item src.loc which is *very likely* to be a damn mob?
would be cleaner to just split stack after the check

2023-03-10 03:18 UTC, ZeWaka commented on code/obj/item/cable_coil.dm
>  			A.set_loc(user.loc) //Hey, split_stack, Why is the default location for the new item src.loc which is *very likely* to be a damn mob?
No, I meant modify the input() line so you don't split it until you actually do

2023-03-18 06:50 UTC, ZeWaka approved these changes

2023-03-20 05:10 UTC, merged