Assorted satchel and ore-scoop bugfixes and QOL changes
goonstation/goonstation pull request #13617
Opened 2023-04-08 20:44 UTC by M-Earthfire

[QOL][Game-Objects]

## About the PR 

This PR introduces various changes to the behaviour of produce/mining satchels and connected interactions, with a focus on the mining satchel and issues connected to it.

- Satchels can now be assigned exceptions within `var/list/exceptions` for what items within `var/list/allowed` they should not use. Also, satchels can now be modified with `var/maximal_w_class` to constrain which is the biggest weight class a possible item should have.
- When trying to put an item with multiple stacks in a satchel (e.g. stacked ores) the stack gets split up automatically and single ores inserted into the satchel. A safety limit of 20 splits per interaction is added so a single interaction should rather not be able to create 100 items. `proc/split_stack_into_satchel` was added to quickly split the stack into a satchel. This fixes #7614
- This behaviour was added to ore scoops and pod ore scoops as well
- `proc/check_valid_content` was added to quickly check if a satchel can contain a certain item that is passed as argument.
- When harvesting items from plants with a satchel, only items are added into the satchel that can actually be added into the satchel
- Most interactions i found that dump items from satchels both set `tooltip_rebuild` to 1 and call `UpdateIcon()` on the satchel. This fixes #12900
- Ore scoops now don't need two hands to be able to switch satchels. Clicking with an ore scoop on a mining satchel now switches the ore scoops and places the old satchel in the container the former was. If it wasn't in a container, it tries to place the ejected satchel in a free hand, if able. This mimics the behaviour of using kinetic guns on ammo to quick reload them.

## Why's this needed? 

Firstly, this PR prevents stacking ores in a bunch so you cannot place 1000+ ores in a satchel anymore. 

Beyond that, by changing how ore scoop works, it enables much more intuitive handling or ore scoops for miners without accidently dropping of satchels... to be honest, that was grinding my gears to a degree it made me make this PR

Lastly, this standartises behaviour of satchels accross the board and makes them more versatile and easy to work with.

## Changelog 

```changelog
(u)Lord_Earthfire
(+)Satchels (e.g. mining, produce satchels) cannot hold stacks of items anymore. Stuffing a stack of items splits part of it up into singular items.
(+)The ore scoop doesn't need two hands to be reloaded anymore. Enjoy quick reloading of your scoop without annoying dropping of mining satchels!
```

2023-04-08 21:22 UTC, CheffieGithub commented
big balance change with the stacking limits, probably mention that in the title

2023-04-09 05:05 UTC, M-Earthfire commented
> big balance change with the stacking limits, probably mention that in the title

That's why i put it explicitely in the changelog. It should be known about,  although it mostly affects people trying to powergame satchels, so i don't really think it's a big balance change.

2023-04-09 11:16 UTC, CheffieGithub commented
Its been around for so long it may as well be a balance change but its a good change

2023-04-09 14:31 UTC, virvatuli-gh approved these changes
I can't comment on the code of this but I like the proposed changes quite a bit. The ore scoop QoL in particular is something that's been needed for a long time (it's bugged me forever when playing miner) and the super-stacking of items in bags is a nonsensical bug that should have been fixed ages ago before it became considered a "feature". :thumbsup:

2023-04-13 02:13 UTC, ZeWaka requested changes

2023-04-13 02:13 UTC, ZeWaka commented on code/modules/chemistry/Chemistry-Machinery.dm
> +			S:tooltip_rebuild = 1
does this need to be a `:`?

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +			if (manipulated_satchel.contents.len < manipulated_satchel.maxitems)
length()

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +				if (manipulated_satchel.contents.len == manipulated_satchel.maxitems)
ditto

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +				if (!max_stack_reached && (manipulated_satchel.contents.len < manipulated_satchel.maxitems)) // if we split up the item and it was more than the satchel can find we should not add the rest
ditto

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +				if (manipulated_satchel.contents.len == manipulated_satchel.maxitems)
ditto

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +					var/amount_of_stack_splits = min(S.satchel.maxitems - S.satchel.contents.len, src.amount - 1, S.satchel.max_stack_scoop)
ditto

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +				if (!max_stack_reached && (S.satchel.contents.len < S.satchel.maxitems))
ditto

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +				if (!max_stack_reached && (SCOOP.contents.len < SCOOP.capacity)) // if we split up the item and it was more than the satchel can find we should not add the rest
ditto

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/material.dm
> +					var/amount_of_stack_splits = min(SCOOP.capacity - SCOOP.contents.len, src.amount - 1, SCOOP.max_stack_scoop)
ditto

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/satchel.dm
> +	var/list/exceptions = list() //! this list are for items that are in the allowed-list for other reasons, but should not be able to be put in satchels
please initialize these in new()
https://hackmd.io/@goonstation/code#StartupRuntime-trade-offs-with-lists-and-the-%E2%80%9Chidden%E2%80%9D-init-proc

2023-04-13 02:13 UTC, ZeWaka commented on code/obj/item/satchel.dm
> +		var/amount_of_stack_splits = min(src.maxitems - src.contents.len, item_to_split.amount - 1, src.max_stack_scoop)
length()

2023-04-13 11:38 UTC, M-Earthfire commented on code/datums/components/transfers.dm
> +				incoming:tooltip_rebuild = 1
You mean typing the tooltip of the satchel?

2023-05-23 16:44 UTC, ZeWaka approved these changes

2023-05-23 16:44 UTC, ZeWaka commented on code/obj/item/satchel.dm
> +	var/list/exceptions  //! this list are for items that are in the allowed-list for other reasons, but should not be able to be put in satchels
```suggestion
	var/list/allowed = null
	var/list/exceptions = null //! this list are for items that are in the allowed-list for other reasons, but should not be able to be put in satchels
```

2023-05-23 21:40 UTC, merged