Research module sprite
goonstation/goonstation pull request #13623
Opened 2023-04-09 16:20 UTC by Wisemonster

[QOL] [UI] [SILICONS]

## About the PR 
Renames the research module to science, and updates the module's UI sprite.
![goonstation  icons_mob_hud_robot dmi  - Dream Maker 4_9_2023 10_20_35 AM](https://user-images.githubusercontent.com/87689371/230784186-a6f7e306-ef4d-43f9-9cfb-793d1d76cb8e.png)

## Why's this needed? 
Makes it make more sense, considering the research module is more of a science module. Mostly cause research wouldn't fit on the sprite, though.

## Changelog 

```changelog
(u)Wisemonster
(+)Renames research module to science module.
```

2023-04-11 16:37 UTC, nefarious6th commented
Cute sprite. Ty to you and soleilan for giving love to this module!

2023-04-13 01:58 UTC, ZeWaka requested changes

2023-04-13 01:58 UTC, ZeWaka commented on code/modules/robotics/robot/module/chemistry.dm
>  	mod_hudicon = "chemistry"
please change this as well

2023-04-13 03:13 UTC, Wisemonster commented on code/modules/robotics/robot/module/chemistry.dm
>  	mod_hudicon = "chemistry"
Done

2023-04-14 16:04 UTC, merged