Makes catwalks constructable by players.
goonstation/goonstation pull request #13643
Opened 2023-04-11 04:34 UTC by CaioFrancisco

[FEATURE] [GAME OBJECTS] [ADD TO WIKI]
## About the PR 

This PR allows players to make catwalks (and catwalk support beams) from metal rods. Catwalks and support beams can also be cut away by snipping tools. To build a catwalk (and the support beams automatically), you just have to click on a lattice with a single metal rod (making each catwalk cost roughly a metal sheet). This also changes all grilles to return only 1 steel rod when cutting, because code. (If a dev thinks this is too unreasonable, I can try to counter it with even more weird jank.)

## Why's this needed? 

The game needs it's environment to be more constructable, and because some miners or engineers may think this is a great opportunity to make stylish off-station places.

## Changelog 

```changelog
(u)Caio029
(*)Catwalks are now constructable. Click on a lattice with a steel rod and you'll starting building a catwalk on it. Check minor updates for more details.
(+)While normal roles have to wait an actionbar to build the catwalk, players with engineering training don't have to wait for such actionbar.
(+)To destroy the catwalks and the support beams, click on it with wirecutters or scissors.
```

2023-04-11 04:58 UTC, Laboredih123 commented
damn there goes my infinitely stacked lattice barricades smh

2023-04-11 05:09 UTC, CaioFrancisco commented
someone used lattice barricades??!??!??!???!!!!?!??!!??!

2023-04-12 17:16 UTC, TobleroneSwordfish commented on code/turf/floors_airless.dm
> +		var/obj/grille/catwalk/catwalk = new
materials!

2023-04-13 15:25 UTC, TobleroneSwordfish requested changes

2023-04-13 17:10 UTC, CaioFrancisco commented on code/obj/grille.dm
> +				drop_rods(1)
well, it currently doesn't really work like that, currently. a grille, when it reaches 0 health after some kind of damage, sets itself to ruined and drops a rod. if it gets cut again while ruined, it drops a final rod and `qdel`s itself. it doesn't drop all rods at once. it's kinda scope creep-ey, but i'll change how it drops rods once i actually get home.

2023-04-14 00:43 UTC, CaioFrancisco commented
Should be good to go now. It looks less janky, although the variable name could be shorter. Eh, suggest+commit in any new variable names if you want to.

2023-04-14 15:57 UTC, TobleroneSwordfish commented
Seems like it always places the support turf facing north, leading to ugly looking patterns under the catwalk:
(top is map placed catwalk, bottom is constructed catwalk)
![image](https://user-images.githubusercontent.com/20713227/232094711-767add8e-9aff-4250-839a-391e2617220f.png)
Would it be feasible to have the support turfs auto-connect alongside the catwalks?

2023-04-14 16:17 UTC, CaioFrancisco commented
Oh, I didn't notice that. Right, I'm gonna check how auto-turfs are currently implemented (if at all) and make a separate PR for it. I'll set the PR to draft again, until I get home. If making the turfs auto-connect is not already there, then I'll close this PR and PR up auto-turfs before re-opening this PR.

2023-04-17 14:30 UTC, TobleroneSwordfish approved these changes

2023-04-17 15:57 UTC, CaioFrancisco commented
Tested with the new auto catwalk supports, seems to work fine.

2023-04-18 12:49 UTC, merged