refactored some mob part and limb code
goonstation/goonstation pull request #13670
Opened 2023-04-14 04:22 UTC by TheTyrant25

[CODE QUALITY] [INTERNAL]
## About the PR
Cleans up some doc comments, and changes some binary vars to use `TRUE` and `FALSE` defines properly.
## Why's this needed?
Cleaner code is a cleaner mental state. I was reading through the vars and i couldn't tell if it was an int or bool, which is bad if there's tons to read through. Thought this should have been atomized out, so i did.

2023-04-14 16:08 UTC, TobleroneSwordfish requested changes

2023-04-15 04:33 UTC, TheTyrant25 commented on code/obj/item/mob_parts/human_parts.dm
>  	override_attack_hand = 1
huh seems like some parts vanished

2023-04-15 08:23 UTC, TheTyrant25 commented on code/obj/item/mob_parts/human_parts.dm
>  	override_attack_hand = 1
oh wait i removed it because the doc comment is already in the parent part. sorry for the confusion

2023-04-15 08:24 UTC, TheTyrant25 commented on code/obj/item/mob_parts.dm
> +	/// Used by getHandIconState to determine the attached-to-mob-sprite hand sprite, but for foot sprites, presumably
replaced it with getPartIconState 👍

2023-04-20 17:08 UTC, merged