Mobifies transposed scientist and shades
goonstation/goonstation pull request #13703
Opened 2023-04-16 00:31 UTC by CheffieGithub

## About the PR 
changes obj critter crunched and shade into mob critters. draft until I sort out some generic aiholders.

## Why's this needed? 
obj critters bad

2023-04-27 19:07 UTC, Tarmunora approved these changes
will require some changes to secrets when merged

2023-04-29 18:27 UTC, TobleroneSwordfish requested changes

2023-04-29 18:27 UTC, TobleroneSwordfish commented on code/mob/living/critter/adventure.dm
> +	src.say(pick("Cut the power! It's about to go critical, cut the power!","I warned them. I warned them the system wasn't ready.","Shut it down!","It hurts, oh God, oh God."))
could put these behind a chance in `Life`?

2023-04-29 18:27 UTC, TobleroneSwordfish commented on code/mob/living/critter/adventure.dm
> +		src.hand_attack(target)
This should be `critter_basic_attack` now I think

2023-04-29 18:27 UTC, TobleroneSwordfish commented on code/mob/living/critter/adventure.dm
> +	// architect of the ancient throne, god of the inner sanctuary, jubilation, praise! // watchfire reveals night, the darkened monstrosity
same here

2023-04-29 18:57 UTC, CheffieGithub commented
life is a good call

2023-05-03 17:47 UTC, merged