Stackable, Placeable Construction Cones
goonstation/goonstation pull request #13820
Opened 2023-04-23 22:15 UTC by pgmzeta

## About the PR 
* Enables stacking of construction cones, up to five in a stack.
* You can now place cones down on the floor directly by clicking (along with audio feedback!)
* Increases the number of cones in the Engineering Apparel vendor from 12 to 16
* Moves the icons for cones from `decoration.dmi` into `construction.dmi`
* Adds icon states for 1-5 cones in a stack

## Why's this needed? 
Cones are stackable in real life, so it felt appropriate to add it in-game. Allows engineers to save a few slots when getting cones to mark their construction/repair/deathtrap projects.

## Demo
https://user-images.githubusercontent.com/91498627/233868914-248a478d-ebe6-431e-952a-64a52def992f.mp4

## Changelog 

```changelog
(u)glowbold
(+)Construction cones stack up to five at a time and can be placed on the ground by clicking.
```

2023-04-24 02:02 UTC, ZeWaka commented
why can't i wear them on my head

2023-04-24 18:25 UTC, pgmzeta commented
> why can't i wear them on my head

good point

2023-04-25 15:28 UTC, TobleroneSwordfish requested changes

2023-04-25 15:28 UTC, TobleroneSwordfish commented on code/WorkInProgress/mantaObjects.dm
> +		return 1
this should be unnecessary since it's roughly what the default implementation does?

2023-04-25 15:28 UTC, TobleroneSwordfish commented on code/WorkInProgress/mantaObjects.dm
> +			wear_state = "cone_hat_5"
```suggestion
	_update_stack_appearance()
		src.amount = clamp(src.amount, 1, src.max_stack)
		icon_state = "cone_[src.amount]"
		item_state = "cone_[src.amount]"
		wear_state = "cone_hat_[src.amount]"
```

2023-04-27 19:16 UTC, TobleroneSwordfish approved these changes
Code looks good, will let people with artstyle opinions comment on the sprites.

2023-04-27 20:21 UTC, Exester509 commented
At last can we have coneheads in the game

2023-05-17 06:08 UTC, ZeWaka reviewed
possible secret care

2023-05-17 06:08 UTC, ZeWaka approved these changes

2023-05-26 12:43 UTC, flappybatpal commented
No usage of `/obj/item/constructioncone` in secret maps, similarly nothing found in secret code or use of "cone" icon_state.

2023-05-26 13:22 UTC, merged