adds Promethazine, a chemical that stops vomiting
goonstation/goonstation pull request #13946
Opened 2023-05-03 01:22 UTC by colossusqw

[LABEL][chemistry][feature]

## About the PR 
This PR adds Promethazine, a anti-emetic chemical that can be used to prevent many instances of vomiting. It has some slight OD effects such as a small chance of slowing you down slightly on severe ODs, but besides that it's mainly just a chemical to stop you from puking. Made by combining, oil, ammonia, sulfur and space cleaner.

## Why's this needed? 
Too many things make you puke out your guts and make the station filthy, so i tried to get something to help out the poor janitors :).

```changelog
(u)Colossusqw
(*)Added Promethazine, a anti-emetic agent that stops vomiting.
(+)Slightly refactored many instances of vomiting messages, please do point out any weirdness that occurs.
```

2023-05-03 01:26 UTC, CaioFrancisco commented
My only two balancing concerns is how there's barely any punishment for smoking this chem into the halls (including overdosing someone with it.) There's also the small fact that it completely nullifies drinking too much Bo Jack, which is weird.

2023-05-03 01:30 UTC, colossusqw commented
> My only two balancing concerns is how there's barely any punishment for smoking this chem into the halls (including overdosing someone with it,) and also the small fact that it completely nullifies drinking too much Bo Jack, which is weird.

I'm not sure it being easy to give out to people is exactly a balancing concern, considering all this does is reduce the amount of puke around. I could change the bojack part easily, maybe just changing it to only stop you puking? Hmm, would feel weird for it to remove some bojack without you puking though...

2023-05-03 06:24 UTC, M-Earthfire commented
> My only two balancing concerns is how there's barely any punishment for smoking this chem into the halls (including overdosing someone with it,) and also the small fact that it completely nullifies drinking too much Bo Jack, which is weird.

Tbh, it's good to not have a punishment for smoking it. Smoke can and should have good effects if applied with certain chems. 

Personally, i think the recipe is too complex for what a mediocre effect the chem has. Personally, i would throw out sulfur and ammonia and add something like sugar. Or is the recipe there to emulate a certain reaction?

2023-05-03 14:47 UTC, Tarmunora requested changes

2023-05-03 14:47 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Medical.dm
> +			penetrates_skin = TRUE
```suggestion
			depletion_rate = 0.4
```

2023-05-08 01:09 UTC, TDHooligan commented
going to add a suggestion specifically to keep skinpen, following its' initial discussion:
1 - balance wise, the chem benefits only janitors, who are also the only ones who care about vomiting. janitors lack penetrative means to transfer reagents, but could totally splash a bucketful of this stuff onto irritating nerds with drug problems.
2 - its' use as a poison is limited to foods (where it could already be added to the food itself)
3 - it's technically a topical treatment

the standard depletion rate should see to it that smoking it isn't too effective, without skinpen we'll probably see very little usage of it.

2023-05-28 14:30 UTC, pali6 commented
@Tarmunora

2023-05-29 18:55 UTC, merged