Mobifies rockworms
goonstation/goonstation pull request #14055
Opened 2023-05-11 22:03 UTC by CheffieGithub

## About the PR 
Mobifies rockworms, lets them throw up ores without being dead so miners have incentive to not kill them all.

TODO
basic taming so they don't seek ores?
turn throwing up ore into ability so players can do it.

## Why's this needed? 
Object bad. pet worm cute??

2023-05-12 01:11 UTC, Vaskritaya commented on code/mob/living/critter/mining_critter.dm
> +	health_brute_vuln = 0.1
I think you meant for this to be burn vuln instead

2023-05-18 20:43 UTC, CheffieGithub commented on code/mob/living/critter/ai/rockworm.dm
> +			qdel(T) // Eat code is AAAAAAAAAAAAAAA make it actually eat later
I dunno how to make it just eat the ores

2023-05-21 20:00 UTC, TobleroneSwordfish requested changes
Okay I tested this a bit and noticed the following:
- Since they're now living critters they can and will immediately wander off into space and drift off into the void, probably best to either make them not path onto space tiles or give them space traversal.
- You can only tame them with rocks, they will accept any other ore but instead of being tamed they will get angry, this seems backwards. Probably just let them be tamed with ore too.
- Tameable rockworms are very cute.

2023-05-22 16:16 UTC, TobleroneSwordfish requested changes
![image](https://github.com/goonstation/goonstation/assets/20713227/29c26a4c-51ff-45f1-8df7-9e78ed384106)

2023-05-22 16:16 UTC, TobleroneSwordfish commented on code/mob/living/critter/mining_critter.dm
> +			if (src.ai_type == /datum/aiHolder/rockworm)
```suggestion
			if (src.seek_ore)
```

2023-05-22 16:32 UTC, CheffieGithub commented on code/mob/living/critter/mining_critter.dm
> +			if (src.ai_type == /datum/aiHolder/rockworm)
oh yeah I forgor that

2023-05-22 16:41 UTC, merged