(Draft) HoP Pocketwatch
goonstation/goonstation pull request #14063
Opened 2023-05-12 17:32 UTC by Flaborized

[FEAT]

## About the PR 

This PR adds a pocketwatch (currently called the Monitor Watch but I probably want a better name) for the HoP, which can measure time and various financial stuff currently including:

- Current Overall Station Budget
- QM, Research, Payroll Budgets
- Total PTL earnings this round

This is displayed using maptext over the item when held in-hand, and the watch even flicks open when you put it in your hand (and flicks shut when you drop it or put it in your pocket or w/e). The timekeeping uses the in-game timezone (same one clockwork oranges use). The display looks like an analog watch when it's measuring time, and a digital display when measuring other things (it's not a real analog watch, just a cool screen). Pictures:

![](https://cdn.discordapp.com/attachments/1041726307584704532/1106631706733191330/image.png)

![](https://cdn.discordapp.com/attachments/1041726307584704532/1106624800769712258/image.png)

![](https://cdn.discordapp.com/attachments/1041726307584704532/1106624875105357854/image.png)

![](https://cdn.discordapp.com/attachments/1041726307584704532/1106632015027126272/hop_watch_animate.gif)

![](https://cdn.discordapp.com/attachments/1041726307584704532/1106632068508680222/hop_watch_idle.gif)

## Why's this needed? 

I thought of the idea and thought it was cute and cool! The HoP could use a fun little item, and I think this one is in line with the design of the job, focused on money and probably the type to carry a fancy pocket watch. I also personally like being able to monitor how different departments are doing in a round, and this lets you do that in style while on the go. 

## TO-DO
This is a draft so here's a list of things I plan on implementing

- Actually give it to the HoP, in their pocket roundstart likely
- Needs an in-hand sprite, I'll draw this
- Could probably use some more modes to display, can't think of any atm. Open to suggestions
- Could use a better name, also open to suggestions!
- Maybe a pickup sound that makes the opening animation more satisfying? if I can get one
- Some sorta very silly mode that's added when emagged
- A silly interaction when you smack people with it; you wave it around like you're trying to hypnotize them (to no effect)
- Other uses?? Hit ID cards with it to measure... something? idk

## Changelog 

```changelog
(u)Flaborized
(+)The HoP now carries a pocketwatch on their person: it can measure time, or various financial things. 
```

2023-05-12 18:28 UTC, Piesuu commented
It could take the amount of manifest entries (amount of security records) and display the amount of crew on the station from that!

2023-05-13 11:40 UTC, Gannets commented
Yeah, this feels on-brand for the HoP.

2023-05-13 20:24 UTC, Flaborized commented
some more work:

- added a step counter! it counts your steps (tiles moved by any means) while in your hand or pocket. made possible with good coding advice from pali and gerhazo
- named it the "T-MO Watch" based on a pun by grifflez. Time is money!!
- Added a 'timer' function where it counts up seconds.
- added a little light on the watch that blinks whenever someone rings the HoP service bell (no noise or chat output)
- generally rewrote some code that I hastily made to comply with the guidelines a bit more (though it's probably not perfect by any means)

2023-05-14 17:01 UTC, Flaborized commented
Undrafting this because I think I'm done adding stuff to it. Didn't make a stopwatch function since I didn't wanna do that Work, but may do it later or smile as someone else does it later. Same with crew headcount, good idea for future mayb

2023-05-14 17:33 UTC, TobleroneSwordfish requested changes
I love this thing, the little animations are great.

2023-05-14 17:33 UTC, TobleroneSwordfish commented on code/obj/item/device/pocketwatch.dm
> +	var/hour_minute_divider = ":" //used to make the colon in the time blink like a clock display
these should be doc comments like
```
/// Comment
var/foo
```
or
```
var/foo //! Comment
```

2023-05-14 17:33 UTC, TobleroneSwordfish commented on code/obj/item/device/pocketwatch.dm
> +		src.UpdateOverlays(src.alert_overlay, "alert")
```suggestion
		src.UpdateOverlays(src.alert_overlay, "alert")
		if(current_clock_mode == "Service Bell Ring Counter")
			update_clock()
```

2023-05-14 17:33 UTC, TobleroneSwordfish commented on code/obj/item/bell.dm
> +		for(var/obj/item/pocketwatch/watch in world)
iterating world is Bad, use `for_by_tcl` instead (you'll need to add `START_TRACKING` to the watch's `New` and `STOP_TRACKING` to its `disposing`)

2023-05-14 17:33 UTC, TobleroneSwordfish commented on code/obj/item/device/pocketwatch.dm
> +		return "[minutes]:[seconds]"
since this is stolen from game clocks it should probably just go in `helpers.dm`

2023-05-14 17:33 UTC, TobleroneSwordfish commented on code/obj/item/device/pocketwatch.dm
> +				for(var/mob/living/critter/small_animal/cat/jones/jones in world)
same here, `in world` is bad

2023-05-14 20:21 UTC, Flaborized commented
> These are good sensible changes, though one issue I found testing them is that the time keeping function shows the wrong time entirely :sheltersweat: which I didn't notice cuz I originally implemented it with world.timeofday and broke it when switching to TIME so I gotta fix that

Ok fixed this, I hadn't realized that world.timeofday was what I needed for getting real time, and the guidelines made me think I should replace those uses with TIME. Thanks to pali and zewaka for helping figure this out!

2023-05-14 20:26 UTC, TobleroneSwordfish approved these changes

2023-05-17 12:49 UTC, merged