TGUI ID Computer
goonstation/goonstation pull request #14766
Opened 2023-06-29 05:57 UTC by Garash2k

## About the PR 
Rising  #11970 from it's grave from when I worked on it 6 months ago. Adressed the "loading from game data point," made it compatible with dept. ID computers, and added a few goodies such as a selection on the card look button, faster updating card name, and some put_in_hand_or_eject.
I know that compactness is a concern when going from raw html to tgui, but I think this result is ok, with every job being visible, and the area accesses peeking out of the fold with this new default window size.

![image](https://github.com/goonstation/goonstation/assets/6396368/59c800b6-2c40-4592-a1a8-02ea2287256b)
![image](https://github.com/goonstation/goonstation/assets/6396368/4bc452d8-ba37-4576-8efe-47c5f9c2d202)
![image](https://github.com/goonstation/goonstation/assets/6396368/5449aba9-86fe-4a06-8ad7-f6e774be6b37)
![image](https://github.com/goonstation/goonstation/assets/6396368/af5df8ab-0571-4066-b2b1-0ec1be1d93d1)

## Why's this needed? 

Color coding and groupings should make it easier to use. Also a useless Login feature has been removed, making it faster to use. Plus, TGUI looks more modern than raw html

## Changelog 

```changelog
(u)Garash
(+)New snappier UI for the Identification Computers, go commit ID fraud today!
```

[UI][Feature]

2023-06-29 07:31 UTC, Luxizzle commented
A little nitpick, but the background colors make the interface look extremely busy and the options hard to read.

2023-06-29 09:32 UTC, Glamurio commented
Love this, great job, fantastic work, this makes me excited to work on my HoP rework again.

> A little nitpick, but the background colors make the interface look extremely busy and the options hard to read.

Suggestion: Only have the headers colored, but the main content be black. Here's a mockup:

![image](https://github.com/goonstation/goonstation/assets/51779813/db91d4d3-a559-47c3-95b0-8d998bf02739)

2023-06-29 16:27 UTC, Luxizzle commented
> Love this, great job, fantastic work, this makes me excited to work on my HoP rework again.
> 
> > A little nitpick, but the background colors make the interface look extremely busy and the options hard to read.
> 
> Suggestion: Only have the headers colored, but the main content be black. Here's a mockup:
> 
> ![image](https://user-images.githubusercontent.com/51779813/249732791-db91d4d3-a559-47c3-95b0-8d998bf02739.png)

Yeah, something like that, I'd suggest making them collapsible, see the WeaponVendor as an example. And don't darken the colors by 20% as they ruin the contrast and makes the colors hideous in my opinion

2023-06-29 22:09 UTC, Garash2k commented
> Yeah, something like that, I'd suggest making them collapsible, see the WeaponVendor as an example. And don't darken the colors by 20% as they ruin the contrast and makes the colors hideous in my opinion

The reason the colors are darkened is for accessibility concerns. Because the text is white, it has poor readability unless the background color is darkened
![image](https://github.com/goonstation/goonstation/assets/6396368/c7bddb25-7a9d-4fc0-9b01-844d94df237a)
![image](https://github.com/goonstation/goonstation/assets/6396368/eee6dfc9-ff37-49fa-998f-8e85ce578451)

As for collapsible, I'm not seeing the use for it, each section would only collapse 1 to 3 lines of buttons, and it's not like a seed vendor where you can be interested in a specific category that would otherwise be a few pages down.

2023-06-30 23:23 UTC, Glamurio commented
> The reason the colors are darkened is for accessibility concerns. Because the text is white, it has poor readability unless the background color is darkened.

Totally valid, however they have a point about the colors. Whenever it comes to accessibility, I like to do a luminance comparison of the colors and decide if using black font color might be better. I'm not sure however, how good it would look to have one or two departments with black headers.

Perhaps we could achieve a happy medium? How does 10% look, does that still pass or at least barely fail?

Additionally, since we are using HTML and presumably CSS, you could try the text-shadow property:
`text-shadow: 0 0 1px black, 0 0 1px black, 0 0 1px black, 0 0 1px black; `
With this, white text could be outlined black. That way, the text will stand out no matter the background.

2023-07-06 08:52 UTC, Glamurio commented
![image](https://github.com/goonstation/goonstation/assets/51779813/2330fe06-0672-416e-948c-98b28d183334)

Small typo, you misspelled "maintenance"

2023-07-22 05:42 UTC, Garash2k commented
!merge_upstream

2023-07-22 21:08 UTC, ZeWaka requested changes

2023-07-22 21:08 UTC, ZeWaka commented on tgui/packages/tgui/styles/interfaces/IDComputer.scss
> + * @copyright 2022
```suggestion
 * @copyright 2023
```

2023-07-22 21:08 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/IDComputer.js
> + * @copyright 2022
```suggestion
 * @copyright 2023
```

2023-07-22 21:08 UTC, ZeWaka approved these changes

2023-07-23 00:02 UTC, ZeWaka requested changes
actually one small change i see that can help with the verticality
do this with the top - probably a 2/3 1/3 split because long names
![image](https://github.com/goonstation/goonstation/assets/4741640/ad45c4ab-8136-4c8f-a29d-efab211443a3)

2023-07-23 03:43 UTC, Garash2k commented
Horizontal!
![image](https://github.com/goonstation/goonstation/assets/6396368/eb7dd041-bd73-42d3-97e0-92ea581ca032)

Also while testing it, I noticed that very long buttons would grow out of the window/their parent. With a whitespace property we can make them wrap, which is better than then ending up on top of the Pronouns/PIN section.
![image](https://github.com/goonstation/goonstation/assets/6396368/212f7c37-31fe-4e1b-b905-5fdec32257de)

2023-07-23 04:14 UTC, ZeWaka approved these changes

2023-07-23 04:14 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/IDComputer.js
> +                      )}
```suggestion
                        && (
                          <Button onClick={() => act("pronouns", { pronouns: "remove" })}
                            icon="trash" tooltip="Remove" />
                        )}
```

2023-07-23 05:25 UTC, Garash2k commented
!merge_upstream

2023-08-04 01:35 UTC, merged