Fixes for mob spawners
goonstation/goonstation pull request #14777
Opened 2023-06-29 21:22 UTC by CheffieGithub

## About the PR 
Fixes death alert spam and laysound sounds. Adds puritan to stop revival.

## Why's this needed? 
10x owlery death alerts not good

2023-06-30 19:11 UTC, TobleroneSwordfish requested changes

2023-06-30 19:11 UTC, TobleroneSwordfish commented on code/obj/mob_spawn.dm
> +				qdel(implant)
```suggestion
				qdel(implant)
			H.implant = list()
```
best not to leave references to qdel'd things lying around

2023-06-30 19:26 UTC, Tarmunora commented
I think the corpses' PDAs might be showing up when scanning for PDAs - probably want to fix that one way or another

2023-07-02 11:07 UTC, CheffieGithub commented
I have an idea for how to fix the scanning which could also be extended to salvagers and the ops pda, probably

2023-07-02 12:21 UTC, CheffieGithub commented
Added a variable for PDAs to indicate scannablity if this is a good solution it should be added to pda2/salvager and pda2/syndicate I think

2023-07-02 13:31 UTC, merged