Add flower random spawner & random room showcase
goonstation/goonstation pull request #14795
Opened 2023-07-01 00:54 UTC by Glamurio

[Feature]
## About the PR 
This PR adds a new random spawner `/obj/random_item_spawner/flowers`.

It also adds a new random room to showcase it.

![image](https://github.com/goonstation/goonstation/assets/51779813/2b617945-28f4-4b86-a5d8-453456dea9e6)

## Why's this needed? 
Having access to more random spawners allows for more varied, dynamic content.

2023-07-01 11:57 UTC, Glamurio commented
I do not know how to fix that Beepsky bug, it's very confusing

2023-07-25 09:32 UTC, Glamurio commented
I've spoken to several people and this is supposedly a Linter problem, not a problem in the actual code.

2023-08-07 16:10 UTC, Azrun requested changes
Now compiler angry.

2023-08-09 09:20 UTC, Glamurio commented on code/obj/random_spawners.dm
> +		- list(/obj/item/plant/flower/rose/holorose)
Okay, I see what you're saying, I'll just make it several statements

2023-08-18 18:11 UTC, merged