Standardize coffee recipes
goonstation/goonstation pull request #14800
Opened 2023-07-01 12:35 UTC by Glamurio

[QoL]
## About the PR 
This adds a /fresh variant to any recipes that require coffee, essentially allowing both freshly brewed coffee and regular coffee to be mixed to get the resulting drink.

## Why's this needed? 
The fact that "freshly brewed coffee" and "coffee" are two different chemicals is very confusing, especially to newer players playing bartender. It was also needlessly restrictive. This should allow for more freedom when creating drinks that contain coffee, without homogenizing the chemicals. (Though that may be a future step)

This is part of an ongoing series of changes I am planning to standardize coffee makers and espresso machines.

## Changelog 

```changelog
(u)Glamurio (Ryou)
(+)Standardized all coffee recipes to work with either regular coffee, or its freshly brewed variant.
```

2023-07-01 12:44 UTC, DisturbHerb commented
this is probably more an indictment on recipe code itself than anything else :))

2023-07-02 01:25 UTC, ZeWaka commented
please label your PRs, ty

2023-07-02 20:56 UTC, Glamurio commented
> please label your PRs, ty

Sorry, pretty much always do, just forgot about Catering

2023-07-03 23:56 UTC, Tarmunora approved these changes

2023-07-25 02:04 UTC, Tarmunora commented
merge conflicts

2023-07-25 17:11 UTC, Tarmunora commented
why is this showing like 1500 lines added. I think you messed up resolving the merge conflict and now there are 2 of each recipe in the file

2023-07-27 08:57 UTC, Glamurio commented
> why is this showing like 1500 lines added. I think you messed up resolving the merge conflict and now there are 2 of each recipe in the file

You're very right, god this indentation thing mid-PR really tripped me up, it should be fixed now

2023-07-27 16:05 UTC, Tarmunora requested changes
branch is still kinda fucked up

2023-07-29 10:55 UTC, Glamurio commented
This was the stupidest PR ever, next time this happens I'll just scrap it and do it over
It should HOPEFULLY be fixed now

2023-08-04 23:34 UTC, Azrun commented
I think the coffee things are gone now? 😕

2023-08-05 00:37 UTC, Tarmunora commented
Yeah the only change in the branch rn is deleting a single line of whitespace

2023-08-06 10:19 UTC, Glamurio commented
So good at fixing I undid the whole PR. Officially worst contributor of all time. I'll fix it when I have some time, sorry to have wasted your time, I feel really bad about this

2023-08-07 16:22 UTC, Azrun requested changes

2023-08-07 16:22 UTC, Azrun commented on code/modules/chemistry/Chemistry-Recipes.dm
> +		drinkrecipe = 1
`TRUE`

2023-08-09 17:43 UTC, merged