access
goonstation/goonstation pull request #14992
Opened 2023-07-18 05:01 UTC by cheekybrdy

[BALANCE] [INPUT WANTED] [FEATURE]

## About the PR 
Gives sleepers a implant with listening post access on sleeper roll.

## Why's this needed? 
Adds Listening Post Access to sleepers. This gives them the ability to get access to some traitor items, without adding the antag power of a full uplink to them.

## Changelog 

```changelog
(u)Cheekybrdy
(*)Added listening post access to sleeper agents, this is done through a implant.
```

2023-07-18 16:42 UTC, Mister-Moriarty requested changes

2023-07-18 16:42 UTC, Mister-Moriarty commented on code/modules/antagonists/traitor/sleeper_agent.dm
> +	boutput(owner.current, "<h3><span class='alert'>You have been granted access to the local listening post due to a new implant, don't lose it!</span></h3>")
```suggestion
	var/mob/living/carbon/human/H = src.owner.current
	boutput(H, "<h3><span class='alert'>You have awakened as a Syndicate [display_name]!</span></h3>")
	new /obj/item/implant/access/infinite/sleeper(H)
	boutput(H, "<h3><span class='alert'>You have been granted access to the local listening post due to a new implant, don't lose it!</span></h3>")
```
Minor style critique.

2023-07-18 19:38 UTC, BatElite commented on code/modules/antagonists/traitor/sleeper_agent.dm
> +	boutput(owner.current, "<h3><span class='alert'>You have been granted access to the local listening post due to a new implant, don't lose it!</span></h3>")
Agreeing with this. My personal suggestion would be "An implant within you pings awake,[...]" so as to not imply that the syndicate is actively monitoring folks' implants, but that's a minor thing.

2023-07-19 17:24 UTC, Mister-Moriarty commented on code/modules/antagonists/traitor/sleeper_agent.dm
> +	boutput(owner.current, "You feel something activate within you, and a vision of a place hidden in the asteroids near the station.")
```suggestion
	boutput(H, "You feel something activate within you, and a vision of a place hidden in the asteroids near the station.")
```
`owner.current` got reverted in what I assume was a merge conflict between your origin and local branches. Ensure to pull changes from your origin prior to making changes on your local.

I also feel that the text is now too ambiguous.

2023-08-01 03:59 UTC, cheekybrdy commented
As of this, it adds the fingerpad discussed in the forums into the code but not on any map. It also currently has the implant still in it for as the fingerpads get added to maps, should I take it out entirely?

2023-08-02 08:36 UTC, TheColorCyan commented
Its probably better if you put fingerpads on all listening posts and remove implants entirely 
Also this is a buff to traitors and spiefs as well since they dont have to get an agent card

2023-08-02 09:04 UTC, cheekybrdy commented
> Its probably better if you put fingerpads on all listening posts and remove implants entirely Also this is a buff to traitors and spiefs as well since they dont have to get an agent card

I agree completely, I'm just not sure if I should have implants in to start and have map PRs for the handpads for merge conflict purposes. Then remove implants once those are in or just remove them from this first PR entirely.

2023-08-02 09:12 UTC, TheColorCyan commented
> I agree completely, I'm just not sure if I should have implants in to start and have map PRs for the handpads for merge conflict purposes. Then remove implants once those are in or just remove them from this first PR entirely.

You can just add them all in this PR and fully remove implants from it, i dont see the issues
At least i dont understand the merge conflict purposes? Its just doesn't need to conflict with goons master branch

2023-08-03 00:56 UTC, cheekybrdy commented
Please disregard that, review request was due to a accidental close and reopen

2023-08-03 01:06 UTC, cheekybrdy commented
I've messed up this branch bigtime, I'll redo the PR

2023-08-03 01:06 UTC, closed without merging