Chef can now name meals
goonstation/goonstation pull request #15048
Opened 2023-07-22 16:26 UTC by Valtsu0

## About the PR 
Allows chefs to name meals by using a plate in hand. People without chef training will still have the old in hand use effect of dumping a random piece of food.
![image](https://github.com/goonstation/goonstation/assets/30974789/d0380c04-92c2-4ffa-95f9-d62e1e527f18)
![image](https://github.com/goonstation/goonstation/assets/30974789/dd349eb2-04d0-4cc7-961c-d49a70f9a7bc)
![image](https://github.com/goonstation/goonstation/assets/30974789/97fa1fb2-b4ef-4882-b1ed-9409fbf4bd42)

## Why's this needed? 
Implements [this thread](https://forum.ss13.co/showthread.php?tid=21540)

## Changelog 

```changelog
(u)Valtsu0
(+)Chef can now name meals by using a plate in hand
```

2023-07-24 01:52 UTC, TobleroneSwordfish requested changes

2023-07-24 01:52 UTC, TobleroneSwordfish commented on code/obj/item/kitchen.dm
> +			if (length(str) > 64)
you're cutting the string to length 32, then checking if it's longer than 64?

2023-07-24 01:52 UTC, TobleroneSwordfish commented on code/obj/item/kitchen.dm
> +			if(str)
better to just return if `!length(str)`

2023-07-24 01:52 UTC, TobleroneSwordfish commented on code/obj/item/kitchen.dm
> +			var/str = copytext(html_encode(tgui_input_text(user, "Dish name?", "Set name")), 1, 32)
`tgui_input_text` takes a `max_length` argument for preventing the user from entering text past a certain length (you should still check again on the server though)

2023-07-25 03:09 UTC, frawhst commented on code/obj/item/kitchen.dm
> +	// used in attackby procs ofgent_coners/food/snacks and /obj/item/kitchen/food_box
I dunno what happened here but it probably shouldn't have

2023-07-25 03:09 UTC, frawhst commented on code/obj/item/kitchen.dm
> +			tooltip_rebuild = 1
```suggestion
			tooltip_rebuild = TRUE
```
tiny change, `TRUE/FALSE` are preferred for boolean values

2023-07-28 18:10 UTC, Tarmunora approved these changes

2023-07-28 18:11 UTC, merged