Resprites Robuddies
goonstation/goonstation pull request #15188
Opened 2023-07-30 22:55 UTC by Mister-Moriarty

[Game Objects] [Sprites]

## About The PR:
PR-1, 3, 4, 6, and 7 robuddies, the robuddy types currently ingame, have been resprited to match modern spriting standards. Additionally resprites robuddy frames and robuddy charging docks.
Most sprites are based upon Erin's robuddy sprites, published in #723 and later reverted in #753.
Regarding the aforementioned reversion, Flourish has given assent for a second resprite.

Mailbuddies, goldenbuddies, xmasbuddies, Hemera's secbuddies, and Evengy now use "skin" overlays to recolour their frames, as opposed to an entirely separate icon file.

Robuddy lights have refactored into overlays.
Robuddy hats now make use of the existing human sprites for worn hats, offset to fit the robuddy sprites.
Deprecates the `icon_needs_update` variable.
Temporarily removes the mostly unused costumes, pending a refactor.

*Does not* resprite Super Protector Friend IIIs - I have however reorganised their sprites to be compatible with the new backend code for robuddy faces and lights.

*Does not* resprite Gerhazo's mob robuddies, as they use their own specific set of sprites for conveying emotes.

Please notify me if I have missed a guardbot subtype or object using robuddy sprites. This project has spanned almost two months, and despite my best efforts, I have most definitely missed something somewhere.

## Why Is This needed?
Pairity with modern spriting standards.

## Changelog:
```changelog
(u)Mr. Moriarty & Erinexx
(+)Resprited robuddies.
```

2023-07-31 07:39 UTC, TheTyrant25 approved these changes
a little confused on why you made skin_icon_state instead of just using the normal icon state, but i'm sure there's a good reason for it. lgtm

2023-07-31 17:33 UTC, Mister-Moriarty commented
> a little confused on why you made skin_icon_state instead of just using the normal icon state, but i'm sure there's a good reason for it. lgtm

Skin overlays are separate to the robuddy bodies so that they may be reused for robuddy frames. See the goldenbuddy's frame.

2023-08-03 20:01 UTC, ZeWaka requested changes

2023-08-03 20:01 UTC, ZeWaka commented on code/modules/robotics/bot/guardbot.dm
> +	var/lights_icon_state = "on"
doc comments please

2023-08-03 22:36 UTC, ZeWaka approved these changes

2023-08-05 18:48 UTC, merged