Adds cinnamon, both as plant and associated chem
goonstation/goonstation pull request #15192
Opened 2023-07-31 12:07 UTC by Glamurio

[Feature] [Hydroponics]

## About the PR 
This PR adds cinnamon sticks as a vegetable (because technically it is). It grows on cinnamon trees, whose bark is harvested for the delicious treat.

![image](https://github.com/goonstation/goonstation/assets/51779813/bc2d26c2-ff6f-4226-89c3-aed34017c3a1)

Cinnamon is also a chemical that enhances flavor, but has a side effect that when consuming too much of it, it will restrain you in place and make you cough up a bunch of cinnamon dust, rapidly depleting the chem. As this used some of the `/datum/particleSystem/blow_cig_smoke`, I reworked that, as it was always hard-coded to be white smoke, but it now allows for people to pass a desired color for the smoke.

Additionally it adds cinnamon to cinnamon donuts, which had no cinnamon.

## Why's this needed? 
This was a requested feature. Also, cinnamon is delicious.

Relevant thread on the forum:
https://forum.ss13.co/showthread.php?tid=21599

I'm likely going to add cinnamon in powdered form, akin to curry powder, to the chef locker, and allow people to produce it as well. But that will be in a follow-up PR.

## Changelog 

```changelog
(u)Ryou (Glamurio) & Zac 
(*)Added cinnamon to the game. Ask your local botanist to grow you some! Careful not too eat too much of it.
```

2023-07-31 15:49 UTC, MintyPhresh commented
thank you so much for not making this a tree mutation

2023-08-13 22:28 UTC, TobleroneSwordfish requested changes

2023-08-13 22:28 UTC, TobleroneSwordfish commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +						if (human_target && rand(1,5) == 1)
```suggestion
						if (target)
```
the cast wasn't doing anything and you may as well make them cough 100%

2023-08-13 22:28 UTC, TobleroneSwordfish commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +						M.visible_message("<span class='alert'><B>[M]</B> blows smoke right into <B>[target]</B>'s face![message_append]</span>", group = "[M]_blow_smoke_at_[target]")
```suggestion
						M.visible_message("<span class='alert'><B>[M]</B> blows cinnamon right into <B>[target]</B>'s face![message_append]</span>", group = "[M]_blow_smoke_at_[target]")
```

2023-08-13 22:28 UTC, TobleroneSwordfish commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +					M.losebreath += (1 * mult)
```suggestion
				if (prob(80))
					M.losebreath += (2 * mult)
```
challenging

2023-08-13 22:28 UTC, TobleroneSwordfish commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +					M.restrain_time = TIME + 30
```suggestion
					M.changeStatus("stunned", 3 SECONDS)
```

2023-08-13 23:06 UTC, merged