gives bartender sci cartridge with reagent scanner built in
goonstation/goonstation pull request #15202
Opened 2023-08-01 02:21 UTC by deathrobotpunch

## About the PR 
this PR gives bartenders the reagent scanner built in to their PDA device

## Why's this needed? 
This is needed because the bartender deals a lot in reagents and should have a reagent scanner built in to their PDA

## Changelog 

```changelog
(u)deathrobotpunch1
(*)Bartender now has a reagent scanner built in to their PDA!
```

2023-08-03 00:22 UTC, deathrobotpunch commented
why no merge?

2023-08-04 01:34 UTC, ZeWaka commented
> why no merge?

saying this will just make people wait longer to review it

2023-08-04 03:16 UTC, MintyPhresh commented
I personally like the idea, but not the execution; Tenders should ideally get a cartridge with medical records (for slow metabolism/underage tracking) and reagent scanning. They don't really need the signaler program...

2023-08-04 04:53 UTC, ZeWaka requested changes

2023-08-04 04:53 UTC, ZeWaka commented on code/obj/item/device/pda2/pda2.dm
> +		setup_default_cartridge = /obj/item/disk/data/cartridge/toxins
Yeah make a new cartridge

2023-08-04 06:06 UTC, deathrobotpunch commented on code/obj/item/device/pda2/pda2.dm
> +		setup_default_cartridge = /obj/item/disk/data/cartridge/toxins
ok thank you

2023-08-04 07:57 UTC, deathrobotpunch commented
i’m new to coding and I nearly melted my brain trying to figure out how to commit changes in a new file

2023-08-06 23:39 UTC, deathrobotpunch commented
zewaka can you review this already?

2023-08-07 23:41 UTC, deathrobotpunch commented on code/obj/item/device/pda2/pda2.dm
> +		setup_default_cartridge = /obj/item/disk/data/cartridge/toxins
i made the changes

2023-08-11 00:28 UTC, Tarmunora requested changes

2023-08-11 00:28 UTC, Tarmunora commented on code/obj/item/device/pda2/cartridges.dm
> +		desc = "your friend for making the perfect drink"
Grammar (punctuation, capitalization, etc.)

2023-08-11 06:06 UTC, deathrobotpunch commented on code/obj/item/device/pda2/cartridges.dm
> +		desc = "your friend for making the perfect drink"
added!

2023-08-13 03:38 UTC, merged