Adds listening post access to sleeper agents
goonstation/goonstation pull request #15222
Opened 2023-08-03 03:54 UTC by cheekybrdy

[BALANCE] [FEATURE]
## About the PR 
This PR is a remake of #14992. It adds handscanners which a sleeper can use to enter listening post to every map.

## Why's this needed? 
It gives sleepers more options to work with without the full power of a uplink. This makes them more then a late hard mode traitor

## Changelog 

```changelog
(u)Cheekybrdy
(*)Sleeper agents can now use a scanner at the listening post to get into it.
```

2023-08-03 03:54 UTC, cheekybrdy commented
Discussion thread from the original PR: https://forum.ss13.co/showthread.php?tid=21546

2023-08-03 04:49 UTC, deathrobotpunch commented
AAAAAAAAAAAA RUNTIMEEEEESSSSSSS

2023-08-03 18:20 UTC, Mister-Moriarty requested changes

2023-08-03 18:20 UTC, Mister-Moriarty commented on code/obj/machinery/sleeperscanner.dm
> +		for (var/obj/machinery/door/airlock/pyro/reinforced/syndicate/M in by_type[/obj/machinery/door])
The type `/obj/machinery/door/airlock/pyro/reinforced/syndicate` is used in several prefabs and in Z2; listening post doors will require to be their own subtype if this is to work.
I would personally recommend refactoring sleeper hand scanners into a subtype of `/obj/machinery/door_control`, and utilising `id` to open the listening post doors.

2023-08-04 03:16 UTC, cheekybrdy commented
!merge_upstream

2023-08-04 03:38 UTC, closed without merging

2023-08-04 04:15 UTC, TheTyrant25 commented
might want to start over on a fresh branch at this point