BRINGS THE GREAT DEVTEST
goonstation/goonstation pull request #15227
Opened 2023-08-04 01:25 UTC by Laboredih123

[MAPPING][QOL]

## About the PR 
Adds a new map for developers to test their features and all sorts of things.

## Why's this needed? 
Atlas has grown too large and has lessened its usefulness for development. A new map is needed to let developers test.

2023-08-04 01:33 UTC, ZeWaka commented
need pictures and better description

2023-08-04 01:47 UTC, Laboredih123 commented
> need pictures and better description

Image added. Unsure of how to better description, tried anyway.

2023-08-04 04:11 UTC, TheTyrant25 commented
presumably mention all features that are in the devtest map so that people viewing this pr in the future can see what was originally added vs what got changed (if any) later down the line

2023-08-04 04:12 UTC, TheTyrant25 requested changes
![image](https://github.com/goonstation/goonstation/assets/51260013/7e0bc583-a227-47ed-92ff-2a6667caa31e)
you seem to have duplicated the file into unused and the main map folder btw

2023-08-04 04:57 UTC, Laboredih123 commented
shite

2023-08-04 05:06 UTC, TheTyrant25 approved these changes

2023-08-04 05:09 UTC, Laboredih123 commented
> presumably mention all features that are in the devtest map so that people viewing this pr in the future can see what was originally added vs what got changed (if any) later down the line

ok i listed all the things

2023-08-04 17:10 UTC, Laboredih123 commented
!merge upstream

2023-08-04 18:02 UTC, Laboredih123 commented
is that meant to do something

2023-08-04 21:48 UTC, Laboredih123 commented
oh i stupif

2023-08-04 21:48 UTC, Laboredih123 commented
!merge_upstream

2023-08-05 00:45 UTC, Tarmunora requested changes
Security area can be dropped - there's really nothing I can see needing to test wrt sec stuff that isn't really trivially spawned anyways - at most, the sec vendor an a table of requisition tokens
Clown hole, gnome chompsky, station pets. and other jokes/eastereggs/"fun things" can be dropped - kinda just bloat

2023-08-05 03:40 UTC, Laboredih123 commented
time to kill stuff

2023-08-06 05:57 UTC, Laboredih123 commented
looks like i forgot to update the image

2023-08-07 17:35 UTC, Tarmunora approved these changes

2023-08-07 23:54 UTC, Laboredih123 commented on _std/__build.dm
> +//#define MAP_OVERRIDE_DEVTEST			// Developer Testing map by cringe
ight then i suppose

2023-08-10 23:46 UTC, Azrun approved these changes

2023-08-10 23:46 UTC, merged