Add listening post access to sleepers
goonstation/goonstation pull request #15231
Opened 2023-08-04 05:04 UTC by cheekybrdy

## About the PR 
This is a rework of https://github.com/goonstation/goonstation/pull/15222 which is a rework of https://github.com/goonstation/goonstation/pull/14992 because I messed something up again. This PR adds handscanners to the listening post which allow sleeper agents to leave and enter it.

## Why's this needed? 
This gives sleepers access to items in the listening post giving them traitor items without the full power of the traitor uplink. This makes them feel like more then a late HMT.

## Changelog 

```changelog
(u)Cheekybrdy
(*)Sleeper agents can now access the listening post through scanners at the entrance.
```

2023-08-04 05:06 UTC, cheekybrdy commented
Discussion thread: https://forum.ss13.co/showthread.php?tid=21546

2023-08-04 20:17 UTC, Mister-Moriarty requested changes
I would again recommend refactoring `/obj/machinery/sleeperscanner` into `/obj/machinery/door_control/sleeperscanner`, and matching the `id` var on both the sleeper scanner and on the `/obj/machinery/door/airlock/pyro/reinforced/syndicate/listening_post` type to a unique string, alongside the rather minor required code changes.

This refactor would avoid the duplication of code, as your sleeper hand scanners operate in a similar manner to door controls.

2023-08-04 20:17 UTC, Mister-Moriarty commented on code/obj/machinery/sleeperscanner.dm
> +	if (user.mind?.get_antagonist(ROLE_SLEEPER_AGENT) && user.mind?.get_antagonist(ROLE_SLEEPER_AGENT))
```suggestion
	if (ishuman(user) && user.mind?.get_antagonist(ROLE_SLEEPER_AGENT))
```

2023-08-11 17:01 UTC, Mister-Moriarty requested changes
You appear to have removed several files from `goonstation.dme`, which is likely causing the runtimes.

If you have not already, I would also recommend installing the `.dmm` and `.dmi` merge drivers, as you appear to be having issues with merging upstream map changes.

2023-08-12 05:25 UTC, cheekybrdy commented
This lgtm

2023-08-13 12:29 UTC, TobleroneSwordfish requested changes

2023-08-13 12:29 UTC, TobleroneSwordfish commented on code/obj/machinery/door/door_control.dm
> +	if (ishuman(user) && user.mind?.get_antagonist(ROLE_SLEEPER_AGENT))
```suggestion
	if (user.mind?.get_antagonist(ROLE_SLEEPER_AGENT))
```
no particular reason to have this, may as well allow goose sleeper agents

2023-08-13 12:29 UTC, TobleroneSwordfish commented on code/obj/machinery/door/door_control.dm
> +	var/image/chat_maptext/welcome_text
why is this defined on the type and as a local?

2023-08-13 12:29 UTC, TobleroneSwordfish commented on code/obj/machinery/door/door_control.dm
> +	var/entrance_scanner = 0 // Do we want a welcome message or similar for the area upon activation?
for reference, doc comments look like this
```
///This is a doc comment
var/foo = 3
```

2023-08-16 16:29 UTC, TobleroneSwordfish requested changes
- You've accidentally deleted some walls on atlas and cog 1, see the mapdiffbot renders in `Checks` for details.
- The scanner seems to only speak the first time it's used, and says "" every time afterwards
- It can be spammed a bit, it's good practice to put an `ON_COOLDOWN` check on anything that generates a chat message so it doesn't flood the chat box

2023-08-18 21:26 UTC, TobleroneSwordfish requested changes

2023-08-18 21:26 UTC, TobleroneSwordfish commented on code/obj/machinery/door/door_control.dm
> +	return
```suggestion
```

2023-08-18 21:26 UTC, TobleroneSwordfish commented on code/obj/machinery/door/door_control.dm
> +			ON_COOLDOWN(src, "scanner_speak", 2)
```suggestion
```

2023-08-18 21:26 UTC, TobleroneSwordfish commented on code/obj/machinery/door/door_control.dm
> +	ON_COOLDOWN(src, "scanner_speak", 2)
```suggestion
```

2023-08-18 21:26 UTC, TobleroneSwordfish commented on code/obj/machinery/door/door_control.dm
> +	playsound(src.loc, 'sound/effects/handscan.ogg', 50, 1)
```suggestion
	if (ON_COOLDOWN(src, "scan", 2 SECONDS))
		return
	playsound(src.loc, 'sound/effects/handscan.ogg', 50, 1)
```
not sure what the other `ON_COOLDOWN` calls are trying to do, but this is how you'd add a cooldown to the scanner

2023-08-20 02:04 UTC, cheekybrdy commented
!merge_upstream

2023-08-20 04:29 UTC, cheekybrdy commented
Alarming amount of changes, but no differences on mapdiff, weird

2023-08-21 17:13 UTC, merged