crepes that can have food items folded in them
goonstation/goonstation pull request #15386
Opened 2023-08-15 00:25 UTC by klushy225

[Catering]
[Feature]
[Game object]

## About the PR 
Adds crepes that can have other food items folded into them. Crepe batter is made by combining two milk bottles, one egg, and one sweet dough in the mixer. The batter is then cooked on low for 5 seconds in the oven. Other ingredients can be added in the oven with the batter or folded into the crepe after it is cooked by clicking on it with the ingredient.

SPRITES: https://imgur.com/a/0io2HRL

it marked my crepes as erotic lmfao

## Why's this needed? 

Someone ordered crepes while I was chef the other day, and there were no crepes. and I like crepes.

## Changelog 

```changelog
(u)Klushy225
(*)Added crepes to the game, which can have other ingredients folded into them
```

2023-08-15 01:49 UTC, deathrobotpunch commented
can I put a crepe in a crepe and create crepeseption?

2023-08-15 02:23 UTC, klushy225 commented
> 

of course!

2023-08-15 02:36 UTC, ZeWaka commented on code/datums/cookingrecipes.dm
> +		//I.Blend(custom_crepe_food.get_food_color(), ICON_ADD)
commented out code?

2023-08-15 02:44 UTC, klushy225 commented on code/datums/cookingrecipes.dm
> +		//I.Blend(custom_crepe_food.get_food_color(), ICON_ADD)
forgot about that, fixing it now

2023-08-15 04:37 UTC, deathrobotpunch commented
best PR yet

2023-08-15 21:35 UTC, wolfolotl commented
1. can we see a screenshot of how they look
2. this might be out of scope but what are your thoughts on using an icing bag on a crepe to let you drizzle it with whatever's inside

2023-08-16 01:10 UTC, klushy225 commented
> 1. can we see a screenshot of how they look
> 2. this might be out of scope but what are your thoughts on using an icing bag on a crepe to let you drizzle it with whatever's inside

1. sure I'll post the sprites now

2. I can try, but this is only my second PR so we'll see

2023-08-16 03:20 UTC, deathrobotpunch commented
the crepes are too erotic for my eyes you should have added an NSFW warning to protect the younger ones

2023-08-17 07:36 UTC, wolfolotl commented
could probably make the finished crepes a bit bigger, item sprite scale's pretty loose but they seem to be about the size of tortilla chips currently

2023-09-05 19:30 UTC, TobleroneSwordfish requested changes
Sorry for the late review, I think this one slipped through the cracks!

2023-09-05 19:30 UTC, TobleroneSwordfish commented on code/datums/cookingrecipes.dm
> +		var/obj/item/reagent_containers/food/snacks/custom_crepe = new
this should be a crepe and not an abstract snack object

2023-09-20 12:45 UTC, klushy225 commented
sorry for kinda forgetting about this- I took a break from SS13 and life got in the way. I'm working on fixing it up now

2023-09-20 16:47 UTC, jan-antilles commented
I'm not really a fan of the sprites, they look kinda mushy and indistinct. And personally I would rather have crepes be a nice dish made with Botany fruit, instead of "heehoo food crimes," but that's mostly just me.

2023-09-20 16:55 UTC, klushy225 commented
> I'm not really a fan of the sprites, they look kinda mushy and indistinct. And personally I would rather have crepes be a nice dish made with Botany fruit, instead of "heehoo food crimes," but that's mostly just me.

I could add some special recipes with cream and fruits on top and such. The sprite work is very temporary

2023-12-31 00:53 UTC, closed without merging