Make click dragging an item onto a stored HUD equip it
goonstation/goonstation pull request #15381
Opened 2023-08-14 20:33 UTC by FlameArrow57

[GAME OBJECTS][QoL]

## About the PR 
This PR makes it so that click dragging an item stored in a storage HUD onto the HUD location where it's stored will equip it

## Why's this needed? 
When you are trying really fast to equip an item, it's common that instead of just clicking the item, you will click the item, hold left mouse button, and release when it's on the HUD where it's stored, making you think you never clicked it or some bug happened (order of milliseconds). This makes it so that doing so will actually equip it instead of doing nothing.

## Changelog 
```changelog
(u)FlameArrow57
(+)Improved item equip consistency when equipping an item from your inventory with mouse flicks.
```

2023-08-15 09:26 UTC, TobleroneSwordfish requested changes
may as well make it work for unequipping too for consistency

2023-08-15 09:26 UTC, TobleroneSwordfish commented on code/datums/hud/storage.dm
> +	proc/get_clicked_position(mob/user, list/params)
doc comment pls

2023-08-15 14:07 UTC, FlameArrow57 commented
Can you clarify? Unequipping is done with hotkey, or just click drag to a single inventory spot?

2023-08-16 16:10 UTC, TobleroneSwordfish commented
Click dragging to hand didn't seem to work for unequipping? I know it's specifically coded for backpacks but it makes sense to be general if we're doing this.

2023-08-16 22:55 UTC, FlameArrow57 commented
I see what you're saying, but point of the PR was to just fix the one issue that's in the description, that's a different thing

2023-08-18 21:28 UTC, merged