Organise robotic critters into their own DMI files
goonstation/goonstation pull request #15430
Opened 2023-08-17 15:02 UTC by CheffieGithub

## About the PR 
Moves robotic critters out of mixed places in `icons/misc` and `icons/obj` into `icons/mob/critter/robotic`
Updates some icon_state names to be more clear, especially the drones.

## Why's this needed? 
Large DMIs are bad, smaller ones are easier to find and should be in one place ideally.

2023-09-21 11:50 UTC, TobleroneSwordfish requested changes
better late than never :)))

2023-09-21 11:50 UTC, TobleroneSwordfish commented on code/obj/critter/automaton.dm
> -
?

2023-09-21 11:50 UTC, TobleroneSwordfish commented on code/obj/critter/drone.dm
> +		icon = 'icons/mob/critter/robotic/drone/disruptor.dmi'
This seems excessive, some of these files have a single icon state in them.

2023-09-22 13:45 UTC, CheffieGithub commented on code/obj/critter/automaton.dm
> -
it was duplicated

2023-09-29 23:33 UTC, merged