Adds the ability to repair damaged windows with sheets of the same material.
goonstation/goonstation pull request #15493
Opened 2023-08-23 01:27 UTC by unfunnyperson

[GAME OBJECTS] [PLAYER ACTIONS]

## About the PR 
Adds the ability to repair damaged windows by clicking on them with a stack of sheets of the same material.
This takes 2 second to do and consumes 1 sheet.

## Why's this needed? 
The current ways to repair a damaged window are either silicate(which ruins the color of the window) or tearing down and replacing the window(griefs the atmosphere).

Adding a non-intrusive way to repair station windows would make repairs a lot less tedious to do.

## Changelog

```changelog
(u)UnfunnyPerson
(+)Clicking a window with a sheet of the same material will repair the window.
```

2023-08-23 18:42 UTC, Tarmunora approved these changes
ah yes let me just glue another pane of glass on the window. That ought to fix it

2023-08-23 19:20 UTC, TobleroneSwordfish requested changes

2023-08-23 19:20 UTC, TobleroneSwordfish commented on code/obj/window.dm
> +		else if (src.health < src.health_max && istype(W, /obj/item/sheet) && W.material == src.material)
this should use `isSameMaterial` instead of direct reference equality

2023-08-25 04:11 UTC, Azrun commented
I think this really interferes with the function of `silicate` for something that seems be described as a vanity QoL.  I'd prefer the actionbar duration was longer but also factors in `hasTrait("carpenter")` and `hasTrait("training_engineer")`.

2023-08-25 15:59 UTC, MeggalBozale commented
I spun up a bit of discussion in imcoder, perhaps a weldingtool would make more sense for this situation.
[Link](https://discord.com/channels/182249960895545344/890226559691157524/1144659754547937291) to the discussion so you can take a look

2023-08-25 18:25 UTC, Azrun commented
I think I prefer the idea of the small silicate dispenser that can be refilled and improve connection to chemistry.  Use of welder to reduce or minimize visual effect of silicate might be cool as well.

2023-08-25 23:58 UTC, NightmareChamillian commented
Big disagree on @Azrun 's silicate idea. Engineers already have far, far too many things they have to carry, and adding another is just going to result in it going unused.

A welding tool or, by going the C:DDA route, soldering iron could work, but I also think the use of glass sheets is fine. It fits in with some of the more cartoony things that can happen, and makes sense, given the fact that engineers are likely to already be carrying them in the event that windows are broken/damaged.

2023-08-26 03:03 UTC, Azrun commented
I meant that I preferred the idea discussed in imcoder, wasn't my idea.  I don't think engineers *have* to carry around everything.  They could be a tool that is available. That is what makes those carts handy.

I like the idea of slapping the glass on top better than this, I feel like glass is a more limited resource.  My understanding is that's isn't even a very feasible thing to do and could damage the glass further.

2023-08-28 02:35 UTC, Azrun approved these changes

2023-08-28 02:37 UTC, merged