Add TGUI color picker to character creation
goonstation/goonstation pull request #15506
Opened 2023-08-23 22:23 UTC by Glamurio

[QoL] [UI] [Rework]
## About the PR 
Converts the color picker in character creation to TGUI, using a heavily modified version of 

https://github.com/omgovich/react-colorful/ (MIT License, copyright and liability statements included in code)

This was made largely made possible by utilizing a lot of existing color picker code from this PR: 

https://github.com/BeeStation/BeeStation-Hornet/pull/9417

## Why's this needed? 
The current color picker is, in my knowledge, the default Windows color picker. This works most of the time, but is clunky, and prone to errors for some people. The new one is not only sleek and easy to use, but also modifiable and much more versatile, and will allow us to limit color selections by palettes or other restrictions in the future.

## Changelog 

```changelog
(u)Glamurio (Ryou)
(*)Added TGUI to the character creation color pickers.
```

2023-08-24 07:06 UTC, Azrun commented
Was permission granted to re-license the non-MIT aspects?

2023-08-24 08:31 UTC, Glamurio commented
> Was permission granted to re-license the non-MIT aspects?

According to @ZeWaka we have permission.

2023-08-24 15:37 UTC, ZeWaka commented
> > Was permission granted to re-license the non-MIT aspects?
> 
> According to @ZeWaka we have permission.

To clarify:
They were not granted a relicense under our license, but under MIT. So, license headers will need to be added.

2023-08-25 03:24 UTC, Azrun requested changes

2023-08-25 03:24 UTC, Azrun commented on code/modules/tgui/tgui_color_picker.dm
> +/**
Please add MIT header with appropriate attribution.

https://github.com/itsmeowForks/BeeStation-Hornet/blame/cb28c720d98d18dde0fc55c0ad0cb425680c5961/code/modules/tgui_input/color.dm

2023-08-25 03:24 UTC, Azrun commented on tgui/packages/tgui/styles/themes/generic.scss
> +$generic: #484455;
Please add MIT header with appropriate attribution.

https://github.com/itsmeowForks/BeeStation-Hornet/commits/cb28c720d98d18dde0fc55c0ad0cb425680c5961/tgui/packages/tgui/styles/themes/generic.scss

2023-08-28 02:38 UTC, Azrun approved these changes

2023-08-29 17:08 UTC, merged

2023-08-29 23:27 UTC, Sovexe commented
Seeing a few bugs since the merging of PR

* there is now a color.js and color.ts, and both export a Color class 
* some uses of colors such as the interaction eye and font using style such as `good` `bad` `average` are no longer working on local servers
* interface not found errors occurring on live when trying to use the color selector modal