Donut2 AIsat tweaks
goonstation/goonstation pull request #15549
Opened 2023-08-28 06:57 UTC by TheTyrant25

[MAPPING]
## About the PR
- adds a secoff spawn point in the little checkpoint in the ai satellite. For fun. (they're able to use the teleporter to get back)
- Changes the interior ai satellite power grid to blue cabling to distinguish it from the out solar connections (red and yellow). The blue network is controlled by the SMES.

## Why's this needed?
Sec spawn? It's funny. And there's actually equipment there that they can use to suit up with first anyway.
Blue cables? It visually distinguishes the inner and outer grids. And looks nice.

2023-08-29 15:39 UTC, Sord213 requested changes
The sec spawn is funny but if a newer player spawns there that doesn't know how to use teleporters it could cause some confusion.

2023-08-29 21:51 UTC, Glamurio commented
> The sec spawn is funny but if a newer player spawns there that doesn't know how to use teleporters it could cause some confusion.

Don't Security Officers have like a minimum of 30 or 50 rounds played before you can pick them? If it's SecOff only and not SecAss, it should be okay.

2023-08-29 23:53 UTC, TheTyrant25 commented
I thought new players had to have a certain amount of hours before they could play secoff?

2023-08-29 23:54 UTC, TheTyrant25 commented
that was my thought too

2023-08-30 09:57 UTC, TheTyrant25 commented
i've ditched the spawn anyway

2023-08-30 21:32 UTC, merged