Makes beakers seperate visually based on states of matter
goonstation/goonstation pull request #15675
Opened 2023-09-04 03:12 UTC by ThatFiveGuys

## About the PR 
Chemicals with different states of matter will now seperate into different layers. Solids will go on the bottom, liquids will overlay ontop of solids, and gases will overlay behind everything. 
![image](https://github.com/goonstation/goonstation/assets/73148980/c9673239-9728-47c1-97a2-9cedda10ed51)
![image](https://github.com/goonstation/goonstation/assets/73148980/b4793cbe-4ade-48c2-9c98-7796c501bcb2)

## Why's this needed? 
Looks neat + could potientally be useful for some future gameplay stuff.

## Changelog 

```changelog
(u)Ikea
(*)Different states of matter will now visually seperate in beakers.
```

2023-09-04 04:35 UTC, Laboredih123 commented
what about my frobscottle

2023-09-04 04:41 UTC, Laboredih123 commented
:wahhh:

2023-09-05 21:57 UTC, Tarmunora requested changes

2023-09-05 21:57 UTC, Tarmunora commented on code/modules/chemistry/tools/beakers.dm
> +	var/image/gas_fluid_image
why are these vars here and not local to the `update_icon()`, since they appear to always be getting nulled

2023-09-27 00:47 UTC, closed without merging