Remove 'murder' from the list of possible eldritch artifact faults
goonstation/goonstation pull request #15762
Opened 2023-09-08 23:15 UTC by 444Portal

[BALANCE] [REMOVAL] [SCIENCE]
## About the PR 
Comments out /datum/artifact_fault/murder = 2, from the list of faults the Eldritch Artifacts can roll. That's it. That's the PR.

## Why's this needed? 
Instantly gibbing with no real warning, even if they are funny on paper, aren't fun to have happen to you.

2023-09-08 23:16 UTC, 444Portal commented
I forgot to merge master so it has the commits from my old PR, sorry, I'm pretty dense. shouldn't change anything but artifact_controls.dm however.

2023-09-08 23:24 UTC, Laboredih123 commented
counterpoint: funny when i die. i meddled with eldritch forces beyond my understanding, funny eldritch force says no

2023-09-08 23:41 UTC, Glamurio commented
> counterpoint: funny when i die. i meddled with eldritch forces beyond my understanding, funny eldritch force says no. could lower the chance of no being said.

Counter counterpoint: Funnier if it's not instant. Injects you with a bomb that will gib you. Rush to doctor to be saved or die.

2023-09-09 21:29 UTC, MeggalBozale commented
Should definitely go two ways, if artlab can get instant kill weapons they should get weapons that instantly kill themselves and vice versa. I think a cap should be put on both ways for artifacts to keep instant death out of the equation.

2023-09-12 06:48 UTC, frawhst reviewed
I'm fine with this as long as you increase the weight of one of the other murdery faults to compensate- add a few points to `poison` or `explode` or something.

2023-09-12 06:48 UTC, frawhst commented on code/datums/controllers/artifact_controls.dm
> +//		/datum/artifact_fault/murder = 2,
```suggestion
```
Just delete, no need to have outdated stuff lying around in comments

2023-09-14 20:18 UTC, Tarmunora requested changes
Id rather just change the fault to kill in a way that is borg and/or cloneable, rather than just delete outright

2023-09-15 13:21 UTC, MeggalBozale commented
I don't see why making a clone scanner a necessity for artifact lab without being disintegrated should be considered a good idea, let alone any department.

2023-09-15 18:53 UTC, 444Portal commented
Going to close this and make a new PR at some point - a bit too tired/busy/whatever and it'll probably go stale. Until then I guess.

2023-09-15 18:53 UTC, closed without merging