Adds sounds to the Jester's Hat and Jester's Mask
goonstation/goonstation pull request #15839
Opened 2023-09-14 18:13 UTC by CrystalClover

[CLOTHING] [FEATURE] [SOUND]
## About the PR 
Adds a jingling bell to the Jester's Hat as the players walks
Adds a laughing effect to the Jester's Mask when interacted with (similar to the clown mask)
also changes jester_laugh.ogg to laugh_evil.ogg to seperate it from the new jester_laugh_1.ogg &jester_laugh_2.ogg

https://github.com/goonstation/goonstation/assets/94804240/e134218e-3b99-4559-bc1a-38c937cef971

## Why's this needed? 
Makes the Jester outfit have more similarities with the base clown, giving it more flavour.

```changelog
(u)CrystalClover
(+)Added jingling bell sounds to the Jester's Hat
(+)Added laughing sounds to the Jester's Mask when used
(+)Updates jester_laugh.ogg to laguh_evil.ogg and replaces all instances of it
```

2023-09-14 20:21 UTC, Tarmunora requested changes

2023-09-14 20:21 UTC, Tarmunora commented on code/obj/item/clothing/masks.dm
> +	var/list/sounds_instrument = list('sound/misc/jester_laugh_1.ogg', 'sound/misc/jester_laugh_2.ogg')
```suggestion
	var/list/sounds_instrument = list('sound/misc/jester_laugh_1.ogg', 'sound/misc/jester_laugh_2.ogg')
```
...instrument?

2023-09-14 20:21 UTC, Tarmunora commented on code/obj/item/clothing/masks.dm
> +	var/randomized_pitch = 1
do these need to be vars?

2023-09-14 20:21 UTC, Tarmunora commented on code/obj/item/clothing/masks.dm
> +			spam_flag = 1
use the `ON_COOLDOWN` macro instead

2023-09-14 21:11 UTC, CrystalClover commented on code/obj/item/clothing/masks.dm
> +			spam_flag = 1
added all the changes you suggested

2023-09-30 03:19 UTC, TobleroneSwordfish requested changes
The jingling is cool, but I'm not a fan of the laugh sound, it's pretty weird and in general we don't have voice acting in this game aside from some very cursed cluwne laughter.

2023-09-30 21:57 UTC, CrystalClover commented
> The jingling is cool, but I'm not a fan of the laugh sound, it's pretty weird and in general we don't have voice acting in this game aside from some very cursed cluwne laughter.

Do you have any suggestions of a replacement for the laugh as the use noise for the mask?

2023-10-07 09:17 UTC, flappybatpal commented
Unless anyone can think of anything the answer is probably nothing. It doesn't need to try and replicate the clown mask.

2023-10-13 03:52 UTC, closed without merging