'diving' on grenades reduces their overall impact but gibs you
goonstation/goonstation pull request #15855
Opened 2023-09-16 01:44 UTC by pgmzeta

## About the PR 

Allows players to 'dive' on some explosives, reducing their world impact at the cost of gibbing themselves.

Changes for each supported bomb type are separated into commits for easier review or splitting out into separate PRs.

## Why's this needed? 
* rule of cool
* existing discussion: https://forum.ss13.co/showthread.php?tid=21772

## TODOs
- [ ] find a better way to convey 'diving' onto an explosive
- [ ] implement on more explosives because it *really* sucks to try and fail

## Changelog 

```changelog
(u)glowbold
(+)You can 'dive' onto explosive grenades and pipe bombs by laying down on the same tile and pulling it at detonation. NanoTrasen appreciates your sacrifice.
```

2023-09-16 01:52 UTC, Sbmhawk commented
I would say not gibbing outright, but ruining organs in the chest area, and a lot of damage.

(At the very least, for stinger nades)

2023-09-16 01:55 UTC, Sbmhawk commented
Also, I haven't looked at the code, but I would make sure that throwing a nade on a stunned person (or vice versa) does NOT trigger this

2023-09-16 01:56 UTC, pgmzeta commented
> Also, I haven't looked at the code, but I would make sure that throwing a nade on a stunned person (or vice versa) does NOT trigger this

yep, considered this - you have to be pulling the active grenade and be lying down on the same tile.

2023-09-16 02:32 UTC, Absolute-Baller commented
I'm sorta just spitballing and imnotcoder so this might be completely off-base or unfeasible, but I imagine a more robust system would be a general explosion-power reduction feature. It could be something like: when laying down on top of a tile where an explosion is occurring, you eat up to [x] explosion power, and it gets applied to you in the form of brute damage or whatever. Some damage still always occurs, but just enough to show that an explosion happened. Then, if the power of the explosion exceeds [x], you eat [x] explosion power, gib, and the rest of the explosion power gets applied to the explosion.

2023-09-16 12:40 UTC, Glamurio commented
Didn't check all of the code, but how does this interact with gimmick grenades? I don't want people gibbed for banana or owlbombs. Perhaps in the case of owlbombs they can turn into an actual owl critter (concentrated effect).

2023-09-16 13:01 UTC, pgmzeta commented
> Didn't check all of the code, but how does this interact with gimmick grenades? I don't want people gibbed for banana or owlbombs. Perhaps in the case of owlbombs they can turn into an actual owl critter (concentrated effect).

owlbomb/hotdogbomb only force-clothe the 'sacrifice', and my plan for the future is to make the clothing completely irremovable if you dive on those two grenades specifically.

the other gimmick grenades do not call this and have no effect.

2023-09-17 01:42 UTC, TDHooligan commented
could also have slide (resist + throw) be a shorthand for this that doesnt require the aiming of grab + move + lie.

2023-09-17 17:21 UTC, pgmzeta commented
> for an action that's not likely to be done except explicitly to suicide.
in retrospect making these custom suicides feels like an obvious solution

2023-09-19 06:51 UTC, pgmzeta commented
Rather major change in approach; please see the updated PR description.

2023-09-24 04:08 UTC, Tarmunora requested changes
Interesting idea but I'm feeling like it (further) complicates explosion code while also not affecting the majority of actual grenades (stinger/frag grenade projectiles come to mind).

2023-09-24 04:08 UTC, Tarmunora commented on code/mob/living/carbon/human/procs/damage.dm
> +/mob/living/carbon/human/proc/cover_explosion_with_body(power, brisance=1)
a decent amount of this proc appears to be copy-paste from `ex_act()` - any reason not to just call that to handle non-organ stuff?

2023-09-24 04:08 UTC, Tarmunora commented on code/datums/controllers/explosion_controls.dm
> +					power *= ITEM_EXPLOSION_COVERED_REDUCTION_MULT
would make more sense for `cover_explosion_with_body()` to return a modified `power` imo, and/or have a maximum amount that power can be lowered by - e.g.: a maxcap TTV should probably be relatively unaffected

2023-09-25 01:18 UTC, pgmzeta commented
> Interesting idea but I'm feeling like it (further) complicates explosion code while also not affecting the majority of actual grenades (stinger/frag grenade projectiles come to mind).

Thank you for the feedback - I'll work on integrating this and the previous eat-shrapnel implementation. Agreed on adding explosion complexity, but I am worried that it will be frustrating to dive on an explosive and have nothing come of it just depending on the bomb type. Don't mind cutting it if others don't think that's a valid concern.

2023-09-25 03:41 UTC, Tarmunora commented
> ... I am worried that it will be frustrating to dive on an explosive and have nothing come of it just depending on the bomb type...

I think having a system that explicitly covers only pipebombs and some grenades would cover most people's expectations fairly well, for what it's worth

2023-10-11 17:44 UTC, Tarmunora requested changes
oops i forgot about this PR

2023-10-17 17:12 UTC, pgmzeta commented on code/obj/item/grenades.dm
> +				src.strength = max((src.strength * 0.75), (src.strength - 3))
Switched to applying the explosion act using its power, but doing that will result in them getting double-exploded once the bomb itself detonates. Could convert this to crush damage with a suitable strength multiplier instead, or another route if you think there's a better way.

2023-10-17 21:32 UTC, Tarmunora approved these changes

2023-10-17 23:02 UTC, merged