Remove ability for AI Eye to swap borg cells
goonstation/goonstation pull request #15866
Opened 2023-09-16 19:24 UTC by MeggalBozale

## About the PR 
Intangible AI eyes can no longer swap cells for cyborgs in docking stations.

## Why's this needed? 
Fixes #15851 by ensuring cells swappers are not intangble.

2023-09-16 21:00 UTC, pgmzeta requested changes
please do the same check for `cell-remove` or AIs can brick cyborgs and not be able to fix them

2023-09-16 22:05 UTC, MeggalBozale commented on code/modules/robotics/robot/robot_docking_station.dm
> +			if (isintangible(user))
Might catch other intangible, devious spirits, but I have no issue with it being isAIeye

2023-09-17 00:54 UTC, pgmzeta approved these changes

2023-09-18 12:16 UTC, 444Portal commented
Not entirely sure why this is a bug that needs fixed - If the issue is the AI Eye ghost is swapping it, and less about the AI doing it, then, it's fine, right? As Docking Stations seem to be somewhat automated? I mean, how does a Roboticist Swap Cells when the sprite shoes an active Docking Station as shut? Dunno.

2023-09-18 12:25 UTC, MeggalBozale commented
I always imagine there's some physical part to cell swapping in the station that doesn't show visually.

2023-09-18 18:42 UTC, Tarmunora commented
🤷 if the idea is to make cell swapping an action for humans to perform instead of the AI/etc. wouldn't checking for silicon be better? Its not like the AI can't just deploy an eyebot to get around this if they want to

2023-09-18 18:54 UTC, MeggalBozale commented
Fair idea, I personally would be for that behavior. Though if this is controversial / there will be some discussion needed on this it may be a good idea to open a forums thread, or discussion in imcoder

2023-09-18 21:40 UTC, 444Portal commented
Recently been discussing Silicon balance with a few people, both devs and players. I think my stance has shifted to a 'I want this to stay but if it gets merged I wouldn't really care'.

2023-09-19 21:17 UTC, Sord213 commented
It's definitely a bug, and likely only one that was introduced when the AI eye was turned into an intangible mob and never noticed, considering silicons are not intended to be able to change their own power cells without human intervention.

2023-09-21 11:19 UTC, MeggalBozale commented
Thread has been open for 3 days, and reactions seem to be more positive than negative. This is ready to merge unless there's any final objections

2023-09-26 15:14 UTC, merged