Update shuttles and shuttle floors for in rotation maps
goonstation/goonstation pull request #15890
Opened 2023-09-18 18:22 UTC by CheffieGithub

## About the PR 
Replace icon varedits with the typed colours for shuttle floors.
Removes turf shuttle corners from all arrival shuttles.
Changes dir of shuttle floors to match arrival shuttle direction where it doesn't.
Puts plating under all windows in arrival shuttles.
Replace transparent broken walls with windows in shuttle cockpits.
Update wrestlemap arrival shutttle with compact sleepers.
Removed shuttle corners from the horizon ranch shuttle on donut 2.

Update the old heater in the cog 1 wreck to the newer ones:
![image](https://github.com/goonstation/goonstation/assets/113442598/e6bc1149-07d6-4037-9b7c-087f8e151ba0)

Slight moving around of the donut 3 arrival shuttle:
![image](https://github.com/goonstation/goonstation/assets/113442598/25d719fa-4596-4f90-a244-5f0e03988720)
(lights and cyro moved)

Removed the extra windows from the back of donut 2 arrival shuttle:
![image](https://github.com/goonstation/goonstation/assets/113442598/b0071eab-861a-4f0c-b6d1-f56515ce4fa0)

## Why's this needed? 
Fixes and updates for shuttles. Good for consistency. Typed floors will be better if anyone changes the icon_state.

2023-09-18 20:37 UTC, ZeWaka commented
> donut 2 arrival shuttle:

i feel like cyro should be moved up one tile...

2023-09-18 23:12 UTC, CheffieGithub commented
Not really possible due to heater and wingrilles. Getting the layering to look right will probably cause issues.
![image](https://github.com/goonstation/goonstation/assets/113442598/9555589b-f649-4498-8a9a-e80ed7831c58)

Instead I extended arrivals by one tile as a whole so the shuttle can have some space for cyro without seats in the way.

2023-09-19 09:53 UTC, flappybatpal commented
This is getting out of scope but there are a number of things about shuttles I'd question

1. I never really understood the design decision to put the heaters over wingrilles.

![image](https://github.com/goonstation/goonstation/assets/70909958/7c907551-14c2-4f78-8a01-ca93d6e9b732)

I have put the left side over shuttle walls, the right side are over windows. I think it might be a carry over from the old heater sprites that do not cover nearly the entire tile.
The heaters can be exploded but the propulsion units are invincible so you can't move past them even if the window and heater is gone.
2. Not sure why the shuttle walls are simulated rather than unsimulated, although it is very rare that they take damage outside of meteors. The windows can interactive for the rare case where it might be unsafe to leave such as blob or flood.
3. We should delete and replace the old propulsion and heater sprites. The fact these are varedited on every map is silly and we shouldn't be using perspective incorrect icons elsewhere.

2023-09-19 12:54 UTC, CheffieGithub commented
I think the point of wingrilles is to allow you to see through the back, lots of walls on shuttles are varedited to be transparent like the cockpit walls and the old shuttle windows (which are just transparent old flat walls).
I don't know why they are simulated either since they have return cases for almost all types of damage its been that way for a while. I can replace them in this PR or a different one if you like.

2023-09-19 21:15 UTC, Sord213 commented
I'm guessing the shuttle walls are just super duper old, probably before we had unsimulated walls maybe? It confused me as well but effectively doesn't make much of a difference. Either way changing all the janky old shuttle stuff is probably out of scope for this PR, but it's something we could (and probably should) change....at some point....later....

2023-09-22 08:41 UTC, flappybatpal commented
> I think the point of wingrilles is to allow you to see through the back, lots of walls on shuttles are varedited to be transparent like the cockpit walls and the old shuttle windows (which are just transparent old flat walls). I don't know why they are simulated either since they have return cases for almost all types of damage its been that way for a while. I can replace them in this PR or a different one if you like.

![image](https://github.com/goonstation/goonstation/assets/70909958/08f53ae9-d8eb-4896-a5a9-8a112b138529)

That does rely on the propulsion not being opaque and they have a default opacity of 1.

2023-09-22 10:51 UTC, flappybatpal commented
![image](https://github.com/goonstation/goonstation/assets/70909958/fe5179d2-6275-4937-b29c-fb894c46ee40)

You can get under these on Cogmap2, Donut2 and Donut 3 (including asylum shuttle) and Wrestlemap.

2023-09-22 10:51 UTC, flappybatpal requested changes

2023-09-22 13:39 UTC, CheffieGithub commented on maps/kondaru.dmm
> +	icon_state = "wall3_trans";
Because all the shuttle corners are varedits, I plan to change that but not in this PR

2023-09-23 13:24 UTC, flappybatpal commented
Considering another PR is planned I will merge as-is.

2023-09-23 13:24 UTC, merged