fix emergency shuttle takeoff sounds
goonstation/goonstation pull request #15903
Opened 2023-09-20 02:19 UTC by pgmzeta

## About the PR 
Replace area-based sound with landmarks, and updates/adds landmark to all in-rotation maps.

## Why's this needed? 
Better cues for emergency shuttle takeoff

2023-09-22 16:15 UTC, CheffieGithub commented
Maybe it would be better if it just picked the closest door / engine instead. Just so you don't need a landmark on every map

2023-09-25 01:07 UTC, pgmzeta commented
> Maybe it would be better if it just picked the closest door / engine instead. Just so you don't need a landmark on every map

Some of the shuttles use real engines, and some use decals - and I imagine admins will end up editing shuttles in-situ as well that might throw a wrench in that. Is there a different way you had in mind?

2023-09-25 17:48 UTC, Tarmunora approved these changes

2023-09-26 16:52 UTC, ZeWaka requested changes

2023-09-26 16:52 UTC, ZeWaka commented on code/modules/transport/shuttle/shuttle_controller.dm
>  						playsound(sound_location, 'sound/effects/flameswoosh.ogg', 75)
should have a fallback and log if there's no landmark, also repeated code

2023-09-27 19:01 UTC, merged