Switch all instances of /obj/item/plank to /obj/item/sheet/wood
goonstation/goonstation pull request #15921
Opened 2023-09-21 14:06 UTC by MeggalBozale

[QoL] [Game-Objects]
## About the PR 
Title, the functionality of the planks is now in wood sheets, and all instances of planks in game are changed. The specific changes are listed below. (I'm pretty sure it would goof something up if I _deleted_ the type since they're probably still around in secret content / maps, but I'd like to follow up on that in a future PR.)

Ultimate goal is that plank.dm can be deeleted, once all the functionality and uses of /obj/item/plank are gone.

Updates the random spawner to spawn wood sheets instead of planks.
Updates zombie code to use /obj/item/sheet/wood/zwood for constructing barricades. Probably the larger share of changes is for this behavior.
Allows wood sheets to be used to furnish reinforced tables in place of planks. Gives botany trees a nice use that should exist.
Replaces planks from digging on unsimmed dirt with wood sheets: It works, I tried it, shouldn't affect gameplay much.

## Why's this needed? 
Primarily intended to fix #15845, but I also believe that bringing the two intuitively 'same-y' types together should help overall for gameplay. Lets tree wood be used for more things, all that.

## Changelog
```changelog
(u)MeggalBozale
(+)Wooden planks are mostly replaced with instances of wood sheets, meaning spare planks can be used to furnish tables now.
```

2023-09-21 14:37 UTC, MeggalBozale commented
Not sure if I should find+replace all of the stuff in maps in this PR though id like to

2023-09-21 21:34 UTC, Glamurio commented
> Not sure if I should find+replace all of the stuff in maps in this PR though id like to

I think if you're doing a "switch all instances" PR, you should switch ALL instances, and not only most of them. So yeah, go ahead. Don't worry about secret stuff, feel free to delete the obsolete stuff, some dev can handle those replacements.

2023-09-21 22:24 UTC, MeggalBozale commented
Gocha. Worst case I'll revert the commit find+replaces all.

2023-09-25 12:58 UTC, TobleroneSwordfish requested changes
Thanks for doing this, good cleanup 👍 
Would be good to retain the left click on turf to build barrier behaviour from planks.
Will need (very minor) secret changes.

2023-09-25 15:16 UTC, MeggalBozale commented on code/datums/manufacturing.dm
> +	item_paths = list("MET-2")
Seems "WOOD" is wood, I'll change it to that

2023-09-25 15:18 UTC, MeggalBozale commented on code/datums/manufacturing.dm
> +	time = 1 SECOND
You can make barricades with the zwood, point is to remove _all_ of the planks even if they're a part of that zombie gamemode

2023-09-25 15:21 UTC, MeggalBozale commented on code/obj/table.dm
> +				return
Hm ok

2023-09-27 16:24 UTC, merged