Goonhub API: Ban Endpoints
goonstation/goonstation pull request #15923
Opened 2023-09-21 14:49 UTC by TheTyrant25

[TOOLING] [INTERNAL]
## About the PR
Adds api support for the ban endpoints. Adds three new request bodies to match.

Adds a template for people in the future trying to set up routes. Also for my own reference.

## why tho
Goonhub API is good.

2023-09-21 16:44 UTC, ZeWaka requested changes
we'll need a way to differentiate between query and path parameters, right now you're missing all the query ones

2023-09-21 16:44 UTC, ZeWaka commented on code/modules/goonhub/api/routes/bans/AddBans.dm
> +	method = RUSTG_HTTP_METHOD_GET
```suggestion
/// POST /bans
/// Add a ban for given player data
/datum/apiRoute/bans/add
	method = RUSTG_HTTP_METHOD_POST
```

2023-09-21 16:44 UTC, ZeWaka commented on code/modules/goonhub/api/routes/bans/AddBanDetails.dm
> +/// Add Details
need to use the descriptions.
```suggestion
/// Add new player details to an existing ban. This should be used when an evasion attempt is detected.
```

2023-09-22 03:39 UTC, TheTyrant25 commented
okay so now everything should be fixed. Except for uh. Path for the bans. Which i don't know what to do with.

2023-09-26 02:52 UTC, ZeWaka approved these changes

2023-09-26 02:52 UTC, ZeWaka commented on code/modules/goonhub/api/requests/bans/CheckBansBody.dm
> +	var/ip					= "string"
```suggestion
	var/server_id	= "string"
	var/ckey		= "string"
	var/comp_id		= "string"
	var/ip			= "string"
```

2023-09-26 02:52 UTC, ZeWaka commented on code/modules/goonhub/api/requests/bans/CheckBansBody.dm
> +		"ip"				= src.ip
```suggestion
		"server_id"	= src.server_id,
		"ckey"		= src.ckey,
		"comp_id"	= src.comp_id,
		"ip"		= src.ip
```

2023-09-26 02:52 UTC, ZeWaka commented on code/modules/goonhub/api/requests/bans/AddBansDetailBody.dm
> +		"ip"				= src.ip
```suggestion
		"ckey"		= src.ckey,
		"comp_id"	= src.comp_id,
		"ip"		= src.ip
```

2023-09-26 02:52 UTC, ZeWaka commented on code/modules/goonhub/api/requests/bans/AddBansDetailBody.dm
> +	var/ip					= "string"
```suggestion
	var/ckey	= "string"
	var/comp_id	= "string"
	var/ip		= "string"
```

2023-09-26 02:52 UTC, ZeWaka commented on code/modules/goonhub/api/requests/bans/AddBansBody.dm
> +	var/duration			= 0
```suggestion
	var/round_id	= 0
	var/server_id	= "string"
	var/ckey		= "string"
	var/comp_id		= "string"
	var/ip			= "string"
	var/reason		= "string"
	var/duration	= 0
```

2023-09-26 05:50 UTC, merged