Revolutionary sign damage scales with number of nearby revs
goonstation/goonstation pull request #15962
Opened 2023-09-23 03:54 UTC by unfunnyperson

[BALANCE] [GAME OBJECTS]
## About the PR 

Revsign damage also scales with nearby revs in a 6 tile radius, Each rev is 5 extra damage up to a max of 25 damage(The user will count toward this)
Lowers base damage of the sign to 3
Non-revs do not gain the damage buff if they attack using the sign

## Why's this needed? 
The revolutionary sign isn't a very good item in its current state. Its extremely loud, deals little damage, and the buff it gives isnt very good. Compared to the syndie dagger which has a very powerful stun ability and a cheaper cost, the revsign is a poor choice. This change is intended to make the revsign worth the 4 tc.

## Changelog

```changelog
(u)UnfunnyPerson
(+)The revolutionary sign will deal increased damage depending on the amount of nearby revs
```

2023-09-23 23:34 UTC, MeggalBozale requested changes

2023-09-23 23:34 UTC, MeggalBozale commented on code/datums/syndicate_buylist.dm
Looks good but maybe a rewording on 'increased damage' to be more IC

2023-09-23 23:34 UTC, MeggalBozale commented on code/obj/item/misc_weapons.dm
You should probably just tally up the amount of revolutionaries in range, and then do the damage math at the end of it

2023-09-24 04:15 UTC, Tarmunora approved these changes

2023-09-24 11:50 UTC, MeggalBozale approved these changes
Good work

2023-09-25 11:03 UTC, merged