Introduces the COMSIG_MOB_EX_ACT signal and makes syringe implants remove on explosion of the mob
goonstation/goonstation pull request #16019
Opened 2023-09-25 21:32 UTC by M-Earthfire

[Internal][Balance][Game Objects]

## About the PR 

Introduces the `COMSIG_MOB_EX_ACT` signal. It is send on `ex_act` on a mob.

Also, this PR uses this signal to make syringe implants caused by the syringe gun to be removed when the mob carrying them suffers from an explosion.

## Why's this needed? 

Pottassium+Ice in syringe guns proven to be far too effective for how little effort they need to set up. While it is nice to explode people with this combination, a single syringe could cause 4-5 explosions with this method.

By changing syringes to be removed on explosion of the mob, a single syringe can only explode the person at two times at maximum (due to delays) until the syringe+the chemicals are removed. 

In general, this makes getting hit with a PotIce syringe gun much more surviveable and severly diminishes their utility for crowd control while still keeping this mixture viable for the syringe gun. Get some better chem mixes, nerds.

## Changelog 

```changelog
(u)Lord_Earthfire
(+)Syringes, fired from the syringe gun, stuck in a human desintegrate when that human is affected by an explosion.
```

2023-09-25 21:38 UTC, Tarmunora requested changes
should call it `...EX_ACT` imo for clarity

2023-09-25 21:38 UTC, Tarmunora commented on _std/defines/component_defines/component_defines_atom.dm
> +	#define COMSIG_MOB_EXPLODES "mob_explosion"
```suggestion
	/// Sent when the mob is affected by an explosion
	#define COMSIG_MOB_EX_ACT "mob_explosion_act"
```
and rename throughout

2023-09-25 21:38 UTC, Tarmunora commented on code/obj/item/implant.dm
> +				UnregisterSignal(loosing_mob, COMSIG_MOB_EXPLODES)
```suggestion
			on_remove(var/mob/losing_mob)
				..()
				UnregisterSignal(losing_mob, COMSIG_MOB_EXPLODES)
```

2023-09-26 14:49 UTC, TobleroneSwordfish commented
Good solution 👍

2023-09-27 18:59 UTC, merged