Eject Occupants action ejects corpses from cargo hold contents
goonstation/goonstation pull request #16051
Opened 2023-09-27 05:35 UTC by pgmzeta

## About the PR 

when completing the eject occupants action bar, in addition to the driver/passenger ejection, check if the secondary system of the pod is storage, and if so unload any mobs in the direct load list.

## Why's this needed? 
Fix #7425
it's a pretty long action bar for it to do nothing if the intent is to empty people

2023-09-27 09:37 UTC, Glamurio approved these changes

2023-09-29 22:26 UTC, TobleroneSwordfish approved these changes
I guess?

2023-09-30 00:29 UTC, UrsulaMejor reviewed
I don't think this is needed. You load corpses in by click dragging them to the pod, and you unload them by clickdragging the pod to the floor. There's really no need for this.

Instead, ejecting occupants should just not start the bar if there's nobody in it to eject. People getting forgotten in the trunk of the pod is a feature, not a bug.

2023-09-30 08:17 UTC, UrsulaMejor requested changes

2023-09-30 08:17 UTC, UrsulaMejor commented on code/modules/transport/pods/vehicle.dm
> +		return
Should instead use locate(Type) in Container 
e.g.,
```

if(locate(/mob) in src.contents)
    actions.start(new/datum/action/bar/icon/eject_pod(src,usr), usr)
    return
```

2023-10-01 03:54 UTC, merged

2023-10-01 03:54 UTC, UrsulaMejor reviewed
ye