Fixes ai being able to unglue things from people
goonstation/goonstation pull request #16125
Opened 2023-09-30 04:11 UTC by unfunnyperson

## About the PR 
Stops the ai from being able to unglue items from things

## Why's this needed? 
Fixes #16011

2023-09-30 06:26 UTC, ZeWaka requested changes

2023-09-30 06:26 UTC, ZeWaka commented on code/datums/components/glued.dm
> +	if(user?.a_intent == INTENT_HELP && !isintangible(user))
This should be can_act / the other physical interaction check

2023-09-30 17:04 UTC, ZeWaka approved these changes

2023-09-30 17:46 UTC, ZeWaka commented
> can_act and can_reach are unnecessary here, attackhand should not happen in the first place if that is the case

why are intangibles even getting through then

2023-09-30 18:18 UTC, pali6 commented
Because some stuff implements `ai_attack` as just a call to `AttackHand` (when the correct thing would be for both to call a third, new proc instead).

2023-10-05 17:50 UTC, ZeWaka approved these changes

2023-10-05 17:50 UTC, ZeWaka commented on code/datums/components/glued.dm
> +	if(user?.a_intent == INTENT_HELP && !isintangible(user) && can_act(user) && can_reach(user, parent))
```suggestion
	if(user?.a_intent == INTENT_HELP && !isintangible(user))
```
okay for now

2023-10-08 02:22 UTC, ZeWaka commented
so what would you recommend here @pali6

2023-10-08 09:33 UTC, pali6 commented
I don't really care either way. It's not like more checks hurt anything (most likely), they're just redundant

2023-10-25 02:57 UTC, merged