Crew Credits Antagonists Tab
goonstation/goonstation pull request #16185
Opened 2023-10-01 18:59 UTC by Mister-Moriarty

[UI] [QoL]

## About The PR:
Implements an antagonists tab to the end of round crew credits, displaying details regarding each major antagonist of the round, including their antagonist roles; job; status; objectives; general statistics, such as purchased equipment or blood drank; and their subordinate antagonists.

Antagonists not considered major, such as subordinate antagonists, generic antagonists, or revolutionaries will be displayed under the "Other Antagonists" section. If a subordinate antagonist has a master, they will instead be listed under their master's data entry.

Additionally to better facilitate a tab oriented structure, the crew credits datum has been refactored.

## Why Is This Needed?
Deprecates the old text window readout of antagonist statistics, and therefore fixes #15870.

## Changelog:
```changelog
(u)Mr. Moriarty
(*)Added an antagonists tab to the end of round crew credits.
```

2023-10-01 19:04 UTC, 444Portal commented
Hell yeah! Looks great.

2023-10-01 21:08 UTC, mordent-goonstation requested changes

2023-10-01 21:08 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/CrewCredits/AntagonistsTab.tsx
> +        </Stack>
Slice this out into its own component, there's a lot of presentation information here that adds unnecessary complexity to reading the parent component to show what's actually just `<GameModeDisplay>{data.game_mode}</GameModeDisplay>`

2023-10-01 21:08 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/CrewCredits/AntagonistsTab.tsx
> +        />)
Not confirmed the data types match entirely, but you can probably just do:
```suggestion
        (<Antagonist
          key={index}
          {...antagonist}
        />)
```

2023-10-01 21:08 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/CrewCredits/CrewTab.tsx
> +*/
```suggestion
 */
```

2023-10-01 22:43 UTC, Mister-Moriarty commented on tgui/packages/tgui/components/goonstation/ItemList.tsx
> +    </Flex>
I'm using `Flex` so to avoid spacing other than where explicitly stated.

2023-10-01 22:48 UTC, Mister-Moriarty commented on tgui/packages/tgui/components/goonstation/ItemList.tsx
> +export const ItemList = (props: ItemListProps) => {
I would rather have `ItemList` be located in the common components list; in order to pull it out of the crew credits folder, and individual first has to know it is located there, whereas when in the common list, it is more visible to UI coders, and as a result is more likely to be used.

2023-10-01 22:51 UTC, Mister-Moriarty commented
Thank you kindly for the UI review!

2023-10-02 13:22 UTC, TobleroneSwordfish requested changes
Overall looks great! Thanks for doing this, have some nitpicks:

2023-10-02 21:04 UTC, Mister-Moriarty commented on code/datums/mind.dm
> +	var/list/datum/antagonist/subordinate/subordinate_antagonists = list()
Subordinate antagonists track their master's mind directly.

2023-10-05 01:48 UTC, TobleroneSwordfish commented
Some things are definitely not rendering right in the stolen items section:
![image](https://github.com/goonstation/goonstation/assets/20713227/68a11ef5-b2c7-42e8-abd5-3897249bedae)

2023-10-05 11:56 UTC, flappybatpal commented
Could be nice if you could click the antag in General and it would take you over to them in Antagonists.

2023-10-05 13:26 UTC, mordent-goonstation commented
> Some things are definitely not rendering right in the stolen items section: ![image](https://user-images.githubusercontent.com/20713227/272756418-68a11ef5-b2c7-42e8-abd5-3897249bedae.png)

Looks like it's sending up all four directions (or the entire spritesheet?) of it or something?

2023-10-05 13:35 UTC, TobleroneSwordfish commented on code/modules/antagonists/spy_thief/spy_thief.dm
> +					"iconBase64" = "[icon2base64(icon(initial(stolen_item.icon), initial(stolen_item.icon_state), frame = 1))]",
```suggestion
					"iconBase64" = "[icon2base64(icon(initial(stolen_item.icon), initial(stolen_item.icon_state), frame = 1, dir = initial(stolen_item.dir)))]",
```
I think this is it, might do strange things with items but probably not?

2023-10-05 17:08 UTC, Mister-Moriarty commented
> Once the server starts restarting, can you still switch tabs and expand/collapse sections?

You may, yes, from what I have tested on the live servers.

2023-10-05 17:48 UTC, TobleroneSwordfish commented
Testmerge updated 👍

2023-10-05 19:30 UTC, amylizzle commented
This seems to be already reported, but still 
![image](https://github.com/goonstation/goonstation/assets/3855802/528755de-1a54-48bd-bb41-aa3c0a881fa9)

2023-10-08 19:59 UTC, merged