ABCU: auto pressurize newly built tiles
goonstation/goonstation pull request #16256
Opened 2023-10-04 06:05 UTC by kbsmilk

## About the PR 
* Adds an option (defaulting to enabled) for the ABCU to pressurize its build area to standard station air.
* It has no material cost or downside.
* Moves APC building into the same code block for a minor benefit.

## Why's this needed? 
Pressurizing newly built stuff isn't very fun. This saves time, skipping to the fun part: using newly built stuff!

## Changelog 

```changelog
(u)Smilg
(+)ABCU can now automagically pressurize anything it builds.
```

2023-10-06 19:45 UTC, MeggalBozale commented
Come on this should at least cost molitz for how much of a convenience it is

2023-10-15 22:22 UTC, TobleroneSwordfish requested changes
should probably either cost molitz or (cooler) require a connected canister that it uses to pressurize

2023-10-15 22:22 UTC, TobleroneSwordfish commented on code/WorkInProgress/blueprints.dm
> +					var/turf/simulated/T = src.turfs_to_pressurize[I]
```suggestion
				for (var/turf/simulated/T as anything in src.turfs_to_pressurize)
```

2023-10-15 22:22 UTC, TobleroneSwordfish commented on code/WorkInProgress/blueprints.dm
> +			src.turfs_to_pressurize = new/list
```suggestion
			src.turfs_to_pressurize = list()
```

2023-10-15 22:22 UTC, TobleroneSwordfish commented on code/WorkInProgress/blueprints.dm
> +						T.assume_air(gas_add)
`assume_air` handles group processing internally, you don't need to do this

2023-11-01 09:07 UTC, kbsmilk commented
This is going to take a Lot more code for material consumption

2023-11-01 09:07 UTC, closed without merging