Cream & Yoghurt additions/reworks
goonstation/goonstation pull request #16288
Opened 2023-10-05 23:54 UTC by CrystalClover

## About the PR 
### Additions:
Cream reagent: Taken from cream (condiment), breaks down into milk and cholesterol
Yoghurt reagent: Made from combining Milk and ????, heals damage to the intestine

### Reworks: 
Food Processor:
Now converts every 10 units of milk or yoghurt in a drinks container into cream and yoghurt (food) respectively, and dispenses the remaining container with any milk/yoghurt that wasn't used.

Frozen Yoghurt & Yoghurt: 
Both contain 10 units of Yoghurt, and give you a Disease Resist buff, Frozen Yoghurt also gives you the Cold Food buff

Condiments:
You cannot apply a condiment to a food if the condiment contains no reagents 
(does not affect things such as adding maple syrup to pancakes)
You cannot add a condiment to another condiment

The following foods have had their reagents changed:
Icecream - Starts with 10 units of Cream
Cream Pie - Starts with 10 units of Cream
Creamy Sponge Cake - Starts with 20 units of Sugar & 10 units of Cream
All Cookies - Now contain chems that come from the constituant parts
All Moon Pies - Inherit the chems from the cookies used and also start with 10 units of Cream
Rancid Milk - Now contains 25 units of yoghurt and 25 units of ????

## Why's this needed? 
Makes cream and yoghurt much easier to obtain and gives them more uses, the items with changed reagents now make more sense than having none at all

## Changelog 

```changelog
(u)CrystalClover
(*)Added Cream reagent to the game, which comes from dollops of cream. Can be used for filling donuts or icing cakes!
(*)Added Yoghurt reagent to the game, which is made from mixing Milk and ????. Improves gut health! (Heals intestinal damage)
(*)Food processors no longer destroy the bottle they use to make Cream or Yoghurt! They also accept any drink container, and convert every 10 units of Milk/Yoghurt into dollops of Cream or Yoghurt pots respectively.
(+)Almost all foods made with Cream now have 10 units of the Cream reagent in them by default. (This also includes icecreams)
(+)Cookies  and Moon Pies have had their reagents changed to better reflect what they are made of.
(+)Condiments can no longer be applied to eachother, and cannot be applied to a food if they do not contain anything.
```

2023-10-06 15:51 UTC, MylieDaniels requested changes
Looks really good, though a bit broad!  I've made suggestions, mostly about keeping some empty space in the food proportional to it's reagent volume - this helps people make more customized food as well as allowing poisonings to occur.

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/ice_cream.dm
> +	initial_reagents = list("yoghurt"=10)
```suggestion
	initial_volume = 30
	initial_reagents = list("yoghurt"=15)
```
Food with spare reagent space, beloved by traitors and chefs alike!

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 20
```suggestion
		initial_volume = 40
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 20
```suggestion
		initial_volume = 40
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 20
```suggestion
		initial_volume = 50
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 20
```suggestion
		initial_volume = 40
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 20
```suggestion
		initial_volume = 40
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 20
```suggestion
		initial_volume = 40
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +	initial_volume = 40
```suggestion
	initial_volume = 75
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 50
```suggestion
		initial_volume = 100
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 50
```suggestion
		initial_volume = 100
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
>  		initial_volume = 50
```suggestion
		initial_volume = 100
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 60
```suggestion
		initial_volume = 100
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 50
```suggestion
		initial_volume = 100
```

2023-10-06 15:51 UTC, MylieDaniels commented on code/modules/food_and_drink/snacks.dm
> +		initial_volume = 50
```suggestion
		initial_volume = 100
```

2023-10-06 16:33 UTC, CrystalClover commented on code/modules/chemistry/Chemistry-Recipes.dm
> +		result_amount = 1
changed resulting amount to 2

2023-10-06 18:33 UTC, MylieDaniels approved these changes
Looks solid to me!

2023-10-26 06:39 UTC, kbsmilk approved these changes
Looks fine code-wise. In the future I'd suggest atomizing some more. The cream obj and its addition to existing foods, changing a bunch of cookie reagents, and making condiments unusable on other condiments: all three of these could be separated by scope, into 3 different PRs.

2023-10-26 19:28 UTC, kbsmilk commented
I forgot to mention, the changelog is way too big IMO. At most, I'd suggest 1 major and 1 minor, or just 2 minor, explaining cream and yoghurt's additions and a brief line about their recipe.

2023-12-21 20:13 UTC, merged