PlayerSaves api routes definitions
goonstation/goonstation pull request #16397
Opened 2023-10-11 07:28 UTC by TheTyrant25

[INTERNAL] [ADMIN]
## About the PR
Adds definitions for routes of the Player Saves endpoint.
Includes `List data and saves`, `add data`, `add save`, `add data in bulk`, `delete data`, `delete save`
The `Get` route's correct_response is a bit weird because it's getting two resources at once but hopefully it works fine.

2023-10-11 16:21 UTC, Wirewraith approved these changes

2023-10-11 17:41 UTC, ZeWaka requested changes

2023-10-11 17:44 UTC, TheTyrant25 commented on code/modules/goonhub/api/models/players/weird/GetPlayerSaves.dm
> +	src.saves =	response["saves"]
im... not sure how to approach that honestly
seeing as the two return args seem to both be existing models

2023-10-13 00:16 UTC, ZeWaka commented on code/modules/goonhub/api/models/players/weird/GetPlayerSaves.dm
> +	src.saves =	response["saves"]
x

2023-10-13 08:28 UTC, TheTyrant25 commented on code/modules/goonhub/api/models/players/weird/GetPlayerSaves.dm
> +	src.saves =	response["saves"]
ah it may be fixed now

2023-10-15 16:31 UTC, merged