Bugifx - Lizard tails should drop again
goonstation/goonstation pull request #16783
Opened 2023-11-04 18:29 UTC by gear-space

[Bug][Critters]
## About the PR 
Providing a "fix" for lizard tails not dropping that’ll either be accepted or gets attention from someone who can figure out what’s going on with mob ai :D 

What I think is happening: When counting steps to determine when the tail should die, /mob/living/critter/small_animal/livingtail/death more often than not gets called twice by the AI mob controller. This causes the tail to get deleted the first time, then https://github.com/goonstation/goonstation/blob/b47b5ab317ec8dcfa5299720defab0668135abac/code/del.dm#L144 gets run since we’re trying to delete a null atom and the dropped tail gets yeeted to the abyss. Stackraces available in linked bug ticket.

**Solution:** Move the step count to the life process. This way the tail can still use the wander mob AI, but if it ends up not moving, it’ll still die at some point and not call die twice. 

## Why's this needed? 
Fixes https://github.com/goonstation/goonstation/issues/16374 
- During testing I found that tails dropped in space aren't able to move. They get stuck in a loop, never stop living, and splatter blood spots on the tile forever! Proposed PR fixes this as well.

2023-11-04 19:32 UTC, CheffieGithub commented
But its not a step counter then, its a timer. The issue is probably it moving while doing the death, instead just add a check to the counter statement.

2023-11-06 01:01 UTC, TobleroneSwordfish requested changes
This makes more sense than a step count anyway

2023-11-06 03:21 UTC, gear-space commented on code/mob/living/critter/small_animal.dm
> +	if (src.currentsteps++ >= src.maxsteps)
Thanks for the feedback and keeping the code clean! I'll make a proper coder out of me one of these days 🤪😸

2023-11-06 20:35 UTC, CheffieGithub commented
Life will probably be faster than movement, so maybe boost the numbers a bit so that its close to what it was before?

2023-11-06 21:27 UTC, TobleroneSwordfish commented
I'll up a little bit

2023-11-06 21:27 UTC, merged