prevent catwalks connecting to grilles
goonstation/goonstation pull request #17081
Opened 2023-11-25 15:21 UTC by TheTyrant25

[GAME OBJECT]
## About the PR 
Prevents grilles and catwalks auto connecting to each other. Even though catwalks are under `obj/grille/catwalk`, they visually looks strange when connecting in this way.

This PR also moves the catwalk code to the bottom of the file for code quality. All the procs for grilles are at the top now, and all the info procs for catwalks are below it, rather than being in the middle like it was before.

## Why's this needed?
Fixes #10733

2023-11-25 15:33 UTC, TheTyrant25 commented
!merge upstream

2023-11-25 23:21 UTC, Tarmunora commented
Hm. Kinda feel like this would be best handled by refactoring out an abstract parent, so that catwalks aren't a child of grilles and `connect_to` can be used as expected without having to is istype for carveouts

2023-11-26 05:09 UTC, TheTyrant25 commented
fair enough. I'll do that instead then

2023-11-26 08:36 UTC, TheTyrant25 commented
massive find replace moment
also, i do not know how to use updatepaths, so any advice in setting that up for this pr would be appreciated

2023-11-26 20:51 UTC, Tarmunora requested changes
`obj/mesh/update_icon()` implementation should either be written in a general way that works for both grilles and catwalks, or the current implementation should be pulled down to `obj/mesh/grille/update_icon()`

Catwalks do not work, probably due to marked problems

May be more issue yet to reveal themselves

also maps in secrets will need path updates

2023-11-26 20:51 UTC, Tarmunora commented on code/obj/grille.dm
>  			G.UpdateIcon()
```suggestion
		for (var/obj/mesh/O in orange(1,src))
			O.UpdateIcon()
```

2023-11-26 20:51 UTC, Tarmunora commented on code/obj/grille.dm
> +	var/connects_to = list(/obj/mesh/catwalk, /obj/machinery/door) // We're working differently from grilles. We don't check a list and then another, we check all possible atoms to connect to.
Unused var

2023-12-05 17:10 UTC, Tarmunora commented
Catwalks still do not work

2023-12-05 18:02 UTC, TheTyrant25 commented
damn

2023-12-18 13:35 UTC, TheTyrant25 commented
this has gotten really bad really fast. I can't be bothered to fix this merge conflict. I'll revisit it later

2023-12-18 13:35 UTC, closed without merging