Change the emag text for the PTL and adds a sound
goonstation/goonstation pull request #17249
Opened 2023-12-08 01:33 UTC by NibChocolateeny

[Rework][Player Actions]

## About the PR 
If you emag the PTL, a small sound will play, and the player who emags it will get a more clear message hitning at what they just did (make it steal money!)

Also, for admins, theres a "demag" proc for the ptl now. :>

## Why's this needed? 
the money is being stolen! Now maybe someone can notice, maybe. (probably not!)
also, "messed with the polairty?" What does it mean? this is clearer, I think

## Changelog 
```changelog
(u)NibChocolateeny
(+)Emagging the PTL makes a quiet sound and has a more self-explanatory message for the emagger
```

2023-12-08 05:41 UTC, TealSeer commented on code/modules/power/pt_laser.dm
> +		playsound(src.loc, 'sound/machines/bweep.ogg', 10, 1)
```suggestion
		playsound(src.loc, 'sound/machines/bweep.ogg', 10, TRUE)
```

2023-12-08 05:41 UTC, TealSeer commented on code/modules/power/pt_laser.dm
> +	return 1
```suggestion
	return TRUE
```

2023-12-08 05:41 UTC, TealSeer commented on code/modules/power/pt_laser.dm
> +		return 0
```suggestion
		return FALSE
```

2023-12-08 05:41 UTC, TealSeer commented on code/modules/power/pt_laser.dm
>  	return 1
```suggestion
	return TRUE
```

2023-12-08 17:45 UTC, Sbmhawk commented
Doesn't this also put power back into the grid?

Swapping the polarity, or some mention of being able to buy power should be included imo.
Instead of just "fund transfer protocol"

2023-12-08 22:13 UTC, NibChocolateeny commented
@Sbmhawk i dont think it can GIVE power to station, maybe jsut to itself? But it is more complicated than just money steal, yes. i changed the messages to hint at having negative outpit control when EMAGd

2023-12-16 23:49 UTC, Tarmunora requested changes

2023-12-16 23:49 UTC, Tarmunora commented on code/modules/power/pt_laser.dm
> +		src.visible_message(SPAN_ALERT("The [src.name] chirps 'OUTPUT CONTROLS UNLOCKED: INVERSE POLARITY ENABLED' \
```suggestion
		src.audible_message(SPAN_ALERT("The [src.name] chirps 'OUTPUT CONTROLS UNLOCKED: INVERSE POLARITY ENABLED' \
```

2023-12-17 20:35 UTC, Tarmunora approved these changes

2023-12-19 07:50 UTC, merged