Re-implements invisible catwalk lube fix.
goonstation/goonstation pull request #17252
Opened 2023-12-08 18:13 UTC by CalliopeSoups

## About the PR 
I forgot to handle catwalks in #17155 so this PR re-implements Leahthetech's fix. 

## Why's this needed? 
Lube needs to be visible so you can dodge it.

## Changelog 

```changelog
(u)CalliopeSoups
(+)Lube is visible on catwalks again.
```

2023-12-08 23:51 UTC, TobleroneSwordfish requested changes
You also need to add the second `UpdateOverlays` call in the spawn to remove the overlay again

2023-12-08 23:51 UTC, TobleroneSwordfish commented on code/turf/floors.dm
> +	if (istype(src, /turf/simulated/floor/airless/plating/catwalks)) // "Guh" - Leah
```suggestion
	if (istype(src, /turf/simulated/floor/airless/plating/catwalk)) // "Guh" - Leah
```
typo

2023-12-09 12:40 UTC, CalliopeSoups commented
Ah right, I think I was preoccupied thinking if I left the changelog blank it wouldn't work.

2023-12-09 14:26 UTC, TobleroneSwordfish requested changes
More typo

2023-12-09 14:26 UTC, TobleroneSwordfish commented on code/turf/floors.dm
> +		catwalks.UpdateOverlays(null, "wet_overlay")
```suggestion
		catwalk.UpdateOverlays(null, "wet_overlay")
```

2023-12-09 14:26 UTC, TobleroneSwordfish commented on code/turf/floors.dm
> +		catwalks.UpdateOverlays(overlay, "wet_overlay")
```suggestion
		catwalk.UpdateOverlays(overlay, "wet_overlay")
```

2023-12-09 18:58 UTC, TobleroneSwordfish commented on code/turf/floors.dm
> +		catwalk.UpdateOverlays(null, "wet_overlay")
```suggestion
		catwalk?.UpdateOverlays(null, "wet_overlay")
```
Oh actually it needs this because `catwalk` is going to be null most of the time

2023-12-09 18:59 UTC, merged