remove santa's aa and tweak teleport times
goonstation/goonstation pull request #17402
Opened 2023-12-20 07:24 UTC by Retrino

## About the PR 

- takes away santa's captain spare
- ups the teleport time to be 80 seconds, like the rest of the shorter ability times
 
## Why's this needed? 

santa is a magical being who spawns on the wizard shuttle, why should he have a golden id and not the rest of the wizards?
seriously though, santa does not need aa. it makes him 1) a lootbox, and 2) interfere with jobs that normally have access locked equipment (ie, ordering things in cargo, making ai laws, dispensing medical equipment). he has the power to teleport, spawn a flurry of items, and heal. aa on top of that just isn't necessary, and often makes him a nuisance that can just teleport away to avoid consequences. 

tldr, it makes thematic sense, and the dude just needs a nerf

2023-12-20 14:15 UTC, RSG250 commented
will santa still be able to make announcement at the announcement computer

2023-12-21 00:27 UTC, ZeWaka requested changes

2023-12-21 00:27 UTC, ZeWaka commented on code/modules/holiday/spacemas.dm
> -/obj/item/card/id/captains_spare/santa
if you do this, please make some alternative all-access card that can be invoked with `spawn re/sa` or similar for adminning/devving purposes

2023-12-22 03:34 UTC, ZeWaka approved these changes
![](https://media1.tenor.com/m/_hUq1BSUsiMAAAAC/cat-cute.gif)

2023-12-23 23:23 UTC, merged