Electric Chair Refactor
goonstation/goonstation pull request #17465
Opened 2023-12-27 23:36 UTC by TealSeer

[REWORK] [GAME OBJECTS]
## About the PR 

- Move settings for electric chair from HTML menu accessed by right-click verb to context menu accessed by multitool (sprites by Joeled)
- Removes SPAWN in New() and changes proc signature to take constitute parts for assembly as args instead of waiting for caller to assign them
- Adds help message for accessing settings menu
- Adds option to configure the signal/code of the electric chair after it's been assembled
- Fix bug where electric chairs could be rotated and would break their sprite when rotated south
- Replace 0/1 usage in electric chair code with FALSE/TRUE defines

![image](https://github.com/goonstation/goonstation/assets/75404941/bb7fedc1-c796-456c-aa22-f6c5ff305108)

## Why's this needed? 

Right-click verbs are the devil and so are HTML menus and so is `SPAWN`

## Changelog 

```changelog
(u) TealSeer 
(+) The electric chair has a new settings menu that can be accessed by clicking with a multitool. (lethal, shock, and radio button sprites by Joeled)
```

2023-12-28 17:02 UTC, Tarmunora approved these changes

2023-12-30 00:29 UTC, ZeWaka requested changes

2023-12-30 00:29 UTC, ZeWaka commented on code/obj/item/assembly/shock_kit.dm
> +/obj/item/assembly/shock_kit/New(turf/newLoc, obj/item/clothing/head/helmet/helmet, obj/item/device/radio/electropack/electropack)
```suggestion
/obj/item/assembly/shock_kit/New(atom/newLoc, obj/item/clothing/head/helmet/helmet, obj/item/device/radio/electropack/electropack)
```
not a turf

2023-12-30 00:29 UTC, ZeWaka commented on code/obj/stool.dm
> +	New(turf/newLoc, obj/item/assembly/shock_kit/shock_kit)
```suggestion
	New(atom/newLoc, obj/item/assembly/shock_kit/shock_kit)
```
x

2023-12-30 00:29 UTC, ZeWaka commented on code/obj/stool.dm
>  /obj/stool/chair/e_chair
Please just move this stuff to a different file

2023-12-30 00:29 UTC, ZeWaka commented on code/obj/item/assembly/shock_kit.dm
> +		helmet = new /obj/item/clothing/head/helmet(src)
```suggestion
	helmet ||= new /obj/item/clothing/head/helmet(src)
```
use this for the rest also

2024-01-01 04:12 UTC, merged