Adds new candies/treats, brownies, and refactors existing wrapped candy code
goonstation/goonstation pull request #17553
Opened 2024-01-03 16:50 UTC by itsloley

[CATERING][CODE QUALITY][FEATURE][ADD TO WIKI]

## About the PR 

Adds a lot of melted sugar based recipes to the kitchen!
- Sugar can be melted by putting sugar and a tray in the oven for 5s on high or 10s on low. Reagents can be poured into the tray of sugar!
- The tray can be cut into strips, which can be put on rods or popsicle sticks to be turned into rock candy.
- Melted sugar strips can be cut into individual hard candy pieces, which can be wrapped in paper for presentation!
- Hard candy pieces can be put on a rod or popsicle stick to make small lollipops, similar to the ones found in medbay.
- Melted sugar strips can be used in-hand to make them into a circle which can be put on a rod or popsicle stick to make a swirly lollipop.
- Putting flour onto a melted sugar circle allows it to be folded in-hand, creating dragon's beard candy.
- Dragon's beard candy gets better the more times you fold it! It has a chance to break, but your chances are better if you're a skilled chef and apply flour before each fold.
- Dragon's beard candy can be cut into individual pieces.
- Also adds brownies, made with sweet dough, 2 eggs and a chocolate bar in the mixer, then putting the brownie batter in the oven for 7 seconds on high.
- Refactors wrapped candy code, combining candies that had a wrapper before into one parent type

## Why's this needed? 

Adds a lot more candy recipes for the chef to play with! Hand out comedically oversized lollipops to the crew, swap medbay's lollipops for dubious homemade ones, or just inject brownies with THC.

![yippee](https://github.com/goonstation/goonstation/assets/56316903/a13806be-2c3e-4e3b-a084-23ad5dda6719)

## Changelog 

```changelog
(u)Lyy, Beshemoth
(*)Added melted sugar cooking recipes, including rock candy, hard candy, craftable lollipops, swirly lollipops, and dragon's beard candy!
```

2024-01-03 16:55 UTC, imawxome commented
yippeee

2024-01-03 17:22 UTC, pali6 commented
Very neat!

2024-01-04 10:33 UTC, TobleroneSwordfish requested changes
Oh these look sweet! Only issue I can see at a glance is that the brownies are in cavalier perspective, they should be in cabinet perspective. See the discord #imspriter channel for details.

2024-01-08 06:16 UTC, ZeWaka reviewed
sprites still need to be fixed imo

2024-01-13 03:03 UTC, Roninnozlo commented
> Oh these look sweet! Only issue I can see at a glance is that the brownies are in cavalier perspective, they should be in cabinet perspective. See the discord #imspriter channel for details.

I think they're supposed to be 3/4th perspective, not either of those.

Anyway I saw in the channel that they do indeed have a 3/4 version of the brownie pans

2024-01-29 04:59 UTC, WALPVRGIS requested changes
Some sprite review stuff; these are the only things I want changed tbh and then I'm totally happy for this to be merged. Cute sprites :3 Love seeing new pretty recipes as fun art is kinda the main reward of cooking >:D

2024-01-29 04:59 UTC, WALPVRGIS commented on icons/obj/foodNdrink/food_candy.dmi
Doing a sprite review, candy looks good, though can you change the unwrapped candy (and blank wrapper) to look a bit more like this (or feel free to just copy this)?
![image](https://github.com/goonstation/goonstation/assets/78533030/ed2f5ec1-cdf8-493c-89b7-e81b00467329)
Currently it looks a bit odd to me, like a little blob on a plate, and I think it could be more readable as what it's meant to be with a wrapper thats more in like with what the unopened ones depict. :)

2024-01-29 04:59 UTC, WALPVRGIS commented on icons/obj/foodNdrink/food_candy.dmi
My other suggestion is to add a bit of a darker outline and more contrast to the rock candy, as it'll take to colour overlays better (its a bit tough to see the detail you've added with transparency + overlay which is a shame! but higher contrast helps with that a lot)
![image](https://github.com/goonstation/goonstation/assets/78533030/8d4c9cc8-0002-4e23-9c28-08e194ef6635)

2024-01-29 04:59 UTC, WALPVRGIS commented on icons/obj/foodNdrink/food_dessert.dmi
This is minor but i think at this scale, having a highlight at the nearest edge to the viewer + removing the dark outline in the middle of the brownie slice makes it read a little better :) as its quite dark atm
![image](https://github.com/goonstation/goonstation/assets/78533030/943ff1eb-cf5a-4530-bd5a-8bbfa8bdb72d)

2024-01-29 10:34 UTC, WALPVRGIS approved these changes

2024-01-29 13:18 UTC, TobleroneSwordfish requested changes
Some code nitpicks before I merge, never call `update_icon` directly.

2024-01-29 13:18 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/ingredients.dm
> +		src.update_icon()
```suggestion
		src.UpdateIcon()
```

2024-01-29 13:18 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/ingredients.dm
> +		src.update_icon()
```suggestion
		src.UpdateIcon()
```

2024-01-29 13:18 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/ingredients.dm
> +		update_icon()
```suggestion
		src.UpdateIcon()
```

2024-01-29 13:18 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/ingredients.dm
> +			update_icon()
```suggestion
			src.UpdateIcon()
```

2024-01-29 13:18 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/ingredients.dm
> +		.= 1
```suggestion
	New()
		..()
		src.flags |= OPENCONTAINER
```

2024-01-29 13:36 UTC, merged