🌻 Sunflowers 🌻
goonstation/goonstation pull request #17626
Opened 2024-01-11 22:05 UTC by Azrun

## About the PR 
Leverages the existing sprite to have... SUNFLOWERS.  Seeds will automatically show up in the vendor.
If you take the flower and use them in your hands, hit them, or you hit something with them the seeds will pop out.  Eat the seeds for a chance to get seeds you can grow.
🌻🌻🌻🌻🌻🌻

## Why's this needed? 
We already have the sprite, might as well allow it for decorative purposes.

I would love for these to be around when bouquets happen.

## Changelog 

```changelog
(u)Azrun
(+)Sunflowers can now be grown! Whack 'em for sunflower seeds!
```

2024-01-11 23:12 UTC, NibChocolateeny commented on code/modules/food_and_drink/plants.dm
> +	desc = "Even though the coffee beans are seeds, they are referred to as 'beans' because of their resemblance to true beans.."
dont forget to change descrpition!

2024-01-13 03:22 UTC, Tarmunora requested changes
Any reason to not just instantiate the seeds in `disperse_seeds()`?

2024-01-13 03:22 UTC, Tarmunora commented on code/modules/food_and_drink/plants.dm
> +				src.bites_left *= 1
```suggestion
```

2024-01-13 05:59 UTC, Azrun commented
Is there any reason not to just instantiate the seeds in `disperse_seeds () '?

I think it would necessitate the need to recalculate `quality_status 'and I wanted to keep the general flow consistent with how it would normally behave with the reference to the plantpot, but those aren't applicable with the override.

I'll poke again.  Also I was investigating a component that could seedify things like glass...

2024-01-14 21:10 UTC, merged