Adds a Donut 2 construction area
goonstation/goonstation pull request #17682
Opened 2024-01-16 11:58 UTC by Chatauscours

## About the PR 
Replaces the Donut 2 Auxiliary storage by a construction area.
The ABCU was moved into main storage.
The CartyParty vendor was removed since there's another one near the crew quarters.
The Books vendor was moved next to the CartyParty in crew quarters.
The Disk vendor was moved in front of the tech storage.
![Donut2Constr](https://github.com/goonstation/goonstation/assets/95481182/89ccc5a8-1c3b-430b-a27f-4a1c5938276d)

## Why's this needed? 
Inspired by this thread https://forum.ss13.co/showthread.php?tid=22180

## Changelog 

```changelog
(u)Chatauscours
(+)The Donut 2 Auxilary storage has been repurposed for a construction area.
```

2024-01-16 15:52 UTC, AXLFAN2000 commented
Love this

2024-02-01 12:14 UTC, TheTyrant25 commented
bump

2024-02-01 17:14 UTC, Sord213 requested changes
One of the cameras is on the wrong camnet.

2024-02-01 17:29 UTC, Chatauscours commented
Fixed!

2024-02-02 14:42 UTC, merged