Allows feeding viscerite to synthflesh pustules
goonstation/goonstation pull request #17768
Opened 2024-01-25 18:16 UTC by ThatFiveGuys

## About the PR 
Feeding pustules viscerite now gives the pustule 20 u of viscerite viscera per material. This chem heals 2.5 brute and burn, but deals +1.5 tox, purges chems at the same rate as calomel, and occasionally gives you weakened. The intent here is for it to serve as essientally a reverse pententic acid.

The pustule proceeds to digest the viscera into toxic martian flesh and synthflesh. In the process of digestion, the pustule occasionally emits sulfuric acid, with small/medium pustules doing so in relatively higher quantities with increased frequency. Small/medium pustules produce 7 units of synthflesh and martian flesh, alongside (on average) 4u of sulfuric acid per viscerite, large pustules produce 14 units synthflesh and 2.5 units martian flesh, alongside (on average) 1 units sulfuric acid.

## Why's this needed? 
Gives some neat usage to viscerite, interdepartmental cooperation and all that alongside making some cool new chems available. Also just seems like a neat and logical interaction,

## Changelog 

```changelog
(u)Ikea
(*)Feeding viscerite to synthflesh pustules generates viscerite viscera. The pustule proceeds to digest this chemical into synthflesh and martian flesh, all while offgassing sulfuric acid. Small/medium pustules produce 7 units of synthflesh and 7 units of martian flesh per viscerite, large pustules produce 14 units of synthflesh and 2.5 units of martian flesh per viscerite.
(+) A new chem has been added in the form of viscerite viscera. Currently only obtainable from synthflesh pustules, this chem heals 2.5 brute and burn, all while dealing 1.5 tox, purging other chems, and dealing weakened.
```

2024-01-27 11:44 UTC, TobleroneSwordfish requested changes
Neat idea, but I think it should come with some kind of downside to offset how easy it is to get a large quantity of viscerite. Maybe make it add some kind of toxic contaminant or emit weird eldritch smoke. Also probably reduce the efficiency a bit.

2024-01-27 11:44 UTC, TobleroneSwordfish commented on code/modules/chemistry/Chemistry-Tools.dm
> +		if(W.material == getMaterial("viscerite"))
```suggestion
		if(W.material?.isSameMaterial(getMaterial("viscerite")))
```
== doesn't account for weird mutable material cases

2024-02-01 14:07 UTC, TobleroneSwordfish requested changes
Hmmm, interesting idea but at that point why not just have the pustule keep the new chem instead of converting into synthflesh?

2024-02-01 14:07 UTC, TobleroneSwordfish commented on code/modules/chemistry/Chemistry-Tools.dm
> +							visc.UpdateStackAppearance()
A lot of this mess could likely be replaced with `change_stack_amount`

2024-04-10 01:48 UTC, ZeWaka commented
x

2024-04-10 06:21 UTC, ZeWaka reviewed
unsure on the feature but code looks alright enough

2024-04-10 06:21 UTC, ZeWaka commented on code/modules/chemistry/Chemistry-Tools.dm
> +				var/datum/reagents/smokeContents = new/datum/reagents/
```suggestion
				var/datum/reagents/smokeContents = new/datum/reagents()
```
gross

2024-04-10 06:21 UTC, ZeWaka commented on code/modules/chemistry/Reagents-Misc.dm
> +			description = "Looking at this makes you feel queasy"
```suggestion
			description = "Looking at this makes you feel queasy... ugh."
```

2024-05-11 06:49 UTC, ZeWaka commented
@TobleroneSwordfish

2024-05-13 19:16 UTC, merged