Announcement computer tgui
goonstation/goonstation pull request #17764
Opened 2024-01-24 12:15 UTC by Valtsu0

[UI]
## About the PR 
![image](https://github.com/goonstation/goonstation/assets/30974789/5204d109-1d1e-49a7-ae1a-a9363cc145c3)
![image](https://github.com/goonstation/goonstation/assets/30974789/c9bf92ed-6bc6-45cd-953e-be1960b598f5)

Also adds logging for alert message even when not transmitting it
## Why's this needed? 
tgui good

## Changelog 

```changelog
(u)Valtsu0
(+)Announcement computers now use tgui
```

2024-01-25 08:16 UTC, TobleroneSwordfish requested changes
The transmit button and message only update when you click away, meaning you can click a visually disabled button. Best to set the status of the button and the "input message" text on the frontend based on whether the textbox contains a message. See how `TextInputModal` does this for details (`useSharedState`)

2024-01-25 16:26 UTC, Valtsu0 commented
Actually, i see of no reason why the message box should be shared between users. Made it local

2024-01-25 19:13 UTC, Tarmunora approved these changes
light theme checks out

2024-01-25 23:55 UTC, Cherman0 commented
There is a maximum character limit to an announcement that is currently not visible in the UI, leading people to sometimes transmit cut-off messages. Would probably be good to add a "message length / max length" display so people can know about that.

2024-01-26 20:34 UTC, Valtsu0 commented
> There is a maximum character limit to an announcement that is currently not visible in the UI, leading people to sometimes transmit cut-off messages. Would probably be good to add a "message length / max length" display so people can know about that.

![image](https://github.com/goonstation/goonstation/assets/30974789/39a8cfe8-b674-4f7d-8749-bab463fb34c6)
well it was kinda in the pr, will fix that

2024-01-27 11:58 UTC, TobleroneSwordfish requested changes
The previous interface let you input a message and then hit transmit later, this one clears the message if you close the interface and sends if you hit enter. I think being able to input a message to transmit later is useful QoL and hitting enter to send is mostly just going to result in accidental transmissions as people try to insert newlines.
Other than that, this looks great!

2024-01-28 15:57 UTC, TobleroneSwordfish requested changes
The UI won't register a card if it's inserted when the UI is closed, and re-opening the UI sets the caret position to the start of the text.

2024-01-28 15:57 UTC, TobleroneSwordfish commented on tgui/packages/tgui/interfaces/AnnouncementComputer/automatic.tsx
> +  // Extract `health` and `color` variables from the `data` object.
```suggestion
```

2024-01-28 15:57 UTC, TobleroneSwordfish commented on tgui/packages/tgui/interfaces/AnnouncementComputer/manual.tsx
> +  // Extract `health` and `color` variables from the `data` object.
```suggestion
```

2024-01-28 15:57 UTC, TobleroneSwordfish commented on tgui/packages/tgui/interfaces/AnnouncementComputer/data.tsx
> +/**
This file should be called `type.ts` to be consistent with other interfaces.

2024-01-28 17:19 UTC, Valtsu0 commented
> re-opening the UI sets the caret position to the start of the text.

That seems to be an issue with tgui/inferno. Changing your character's name has the same issue.

clearing the message after transmitting should help a bit

2024-01-29 12:55 UTC, TobleroneSwordfish approved these changes

2024-01-30 10:23 UTC, merged