Mining tool refactor
goonstation/goonstation pull request #17815
Opened 2024-01-30 15:25 UTC by Cherman0

## About the PR 

Internally refactors mining tools, adding /obj/item/mining_tool/powered as a parent object to powered mining tools. Does some code cleanup and makes some minor noticeable changes.

## Why's this needed? 

The current implementation of powered mining tools is just a normal mining tool that changes its own stats in attack_self(). I was looking to create power mining tool upgrade modules in a future PR and the lack of a powered mining tool parent made that more difficult than it needs to be.

Not complete yet.

## Changelog

2024-03-08 06:34 UTC, ZeWaka commented
no changelog?

2024-03-08 14:09 UTC, Cherman0 commented
It didnt really seem pertinent since most of the changes are internal. I suppose I can add one though

2024-03-24 17:10 UTC, Tarmunora requested changes
you've changed the power costs on mining tools to be absurdly high for actually being useful for mining - previously, using mining tools as a weapon (hitting non-turfs) had a large power cost, but this PR puts that power cost onto mining as well

2024-03-26 04:18 UTC, Cherman0 commented
I found my mistake. I assumed that the process_charges() in afterattack() was always being used to handle discharging the battery after hitting something, but actually in the original version it specifically checked to make sure you werent hitting a turf because asteroids separately implemented the exact same code. And we wouldn't want to run it twice, now would we.

(Would definitely like to do asteroid rework and other mining reworks at some point too since theres more weirdness there)

Fixed by making hitting asteroids handle discharging the battery the same way as everything else, and multiplying by a variable (defined on the tool) for anything that isn't a turf. Default value for that variable is 5 and power costs were reduced by 5x to compensate. In the process, also fixed that power was being used twice when you mined the nadir decorative greebles, as they incorrectly also separately implemented discharging the battery.

Other fixes: Held icon now properly depowers when you run out of charge, and the hedron beam examine text and power usage is now correct.

2024-03-26 16:11 UTC, Tarmunora commented on code/obj/mining.dm
> +	power_usage = 1.2
eh, might as well round down to 1 imo

2024-03-26 16:11 UTC, Tarmunora approved these changes

2024-03-28 23:10 UTC, Cherman0 commented on code/obj/mining.dm
> +	power_usage = 1.2
sure

2024-03-29 04:45 UTC, merged