extra torn cloak, adventurous scarf and ten-gallon hat colors
goonstation/goonstation pull request #17888
Opened 2024-02-06 21:17 UTC by CoolKakapo

## About the PR 
Exactly what the title says.

<img width="128" alt="image" src="https://github.com/goonstation/goonstation/assets/120601289/449d39ba-c754-4a63-bcb7-65c89b2df3c2">

## Why's this needed? 
Variety! A good outfit is very important for some people, and it sucks when you just cant get your outfit right. this should maybe help that a little.

## Changelog 

```changelog
(u)The_Kakapo
(+)Adds some new Torn Cloak, Adventurous Scarf and Ten-Gallon hat colors
```

2024-02-10 07:15 UTC, WALPVRGIS requested changes
Sprite review; mostly about palettes used;

2024-02-10 07:15 UTC, WALPVRGIS commented on icons/mob/clothing/overcoats/worn_suit_gimmick.dmi
I don't think these palettes work either, they also just look kinda hue-shifted and a bit muddy. I made the original versions of these and would be down to add more colours myself that fit existing palettes better, honestly!

2024-02-11 20:49 UTC, CoolKakapo commented on icons/mob/clothing/overcoats/worn_suit_gimmick.dmi
I'd appreciate it if you would make some palettes, you are the creator of these after all. The custom color thing using the paint machine also sounds like a good idea, but I kind of lack the coding skills for that. I could turn the colors of the hats into ones that are already in the game, to make them a lot less horrible.

2024-02-14 05:19 UTC, WALPVRGIS commented on icons/mob/clothing/overcoats/worn_suit_gimmick.dmi
Aha, I wouldn't say it's horrible, but we use a different style of palettes on goon rather. I'm not at home rn, but I'll get some palettes here hopefully in the next day or two!

Also with the paint machine hat thing, you wouldn't need to do any additional code :) (I too have no code skills), the white hat just needs to be added to the game, and then players can go utilise the paint machine to make a paint bucket to use on it as per usual!

2024-03-10 00:50 UTC, closed without merging