Misc. Chaplain Additions
goonstation/goonstation pull request #17893
Opened 2024-02-07 04:28 UTC by SgtManGuy

## Labels
[CLOTHING] [MAPPING] [REWORK]

## About the PR 
Adds a new chaplain vending machine that replaces the chaplain locker while keeping it's contents.
adds 5 new outfits and 12 new prop books to the new vendor.

## Why's this needed? 
Chaplain is a role that's lacking in a few areas and relies heavily upon the player creating their own fun. Hopefully, these new items will make that east for chaplains to do so.
The new books don't function like the current bible since I feel it'd be unwise to either alter or add new items that function in the way the bible does.
Skeleton book sprites by Rubi. X, red/white, red/dark, blue/white book sprites by Paco. Descriptions by Large Amounts of Screaming, assistance from Tyrant. 

## Changelog 

```changelog
(u)What/SgtManGuy, Tyrant, Large Amounts of Screaming, Rubi, Paco
(*)Replaces the chaplain's locker with a vending machine.
(+)The new vending machine contains all of the old items.
(+)There are 5 new outfits and 12 new prop books in the vending machine.
```

2024-02-07 04:46 UTC, SgtManGuy commented
Huh. Sometime got messed up when when I made the pr. gotta fix that.

2024-02-07 07:45 UTC, SgtManGuy commented
[image](https://github.com/goonstation/goonstation/assets/14314992/e430fc71-5946-4dd5-b62b-cb6bfbaab6ef)
![image](https://github.com/goonstation/goonstation/assets/14314992/0c6e4247-43f9-42c0-8e0e-bdd20e793604)

2024-02-08 00:50 UTC, Sord213 commented
![Screenshot_794](https://github.com/goonstation/goonstation/assets/71185626/f4f46f37-9fc7-4a8a-9f13-fdcf8f63c571)

2024-02-08 03:16 UTC, SgtManGuy commented
ough. no idea how i missed that

2024-02-12 07:08 UTC, Laboredih123 requested changes
Some minor things noticed.

2024-02-12 07:08 UTC, Laboredih123 commented on code/__secret_public.dme
yo i dont think this belongs here

2024-02-12 07:08 UTC, Laboredih123 commented on code/obj/item/scripture.dm
> +		return
unneeded return

2024-02-12 07:08 UTC, Laboredih123 commented on code/obj/item/scripture.dm
> +	var/open = 0
TRUE and FALSE macros are preferred for boolean vars over 1 and 0.

2024-02-12 07:08 UTC, Laboredih123 commented on code/obj/item/scripture.dm
> +		src.open = 0
Ditto on True and False.

2024-02-12 07:20 UTC, ZeWaka commented on code/__secret_public.dme
deffo not

2024-02-12 09:10 UTC, SgtManGuy commented on code/__secret_public.dme
no clue how that got there, whoops. Lemme fix that

2024-02-12 09:16 UTC, SgtManGuy commented
Gonna close this and fix some shit in a second pr

2024-02-12 09:17 UTC, closed without merging