Adds a sabotage method for emergency-injectors
goonstation/goonstation pull request #17941
Opened 2024-02-11 20:35 UTC by M-Earthfire

[game objects][medical][feature]

## About the PR 

Enables autoinjectors to be manipulated with a cutting tool.

Once manipulated with a cutting tool, the internal of the autoinjector will snap and jam upon use, pouring their contents onto the ground

Also, this PR adds help messages to autoinjectors that point at its use and the possibility to manipulate them.

## Why's this needed? 

Small actions to sabotage station equipment are always nice to have and i would like to see more of them. Beyond this, this enables assisstants easier access to some chemicals for hobo-chemistry (e.g. antihistamine for crank or krokodil).

I don't expect someone to cut an injector that someone else tries to use later at a crucial moment, but you never know. It would be awesome.

## Changelog 

```changelog
(u)Lord_Earthfire
(+)You can cut the spring mechanism of auto-injectors with a knife to make them break and spill their contents upon use.
```

2024-02-12 13:01 UTC, IPling commented
I like it, hobo-chemistry doesnt have that many things you can do and giving more power to them is great. I also adore the situation of a crewmember in an emergency situation having to sip medicine off of the floor to live.

2024-02-12 20:14 UTC, ZeWaka requested changes

2024-02-12 20:14 UTC, ZeWaka commented on code/modules/chemistry/tools/emergency_injectors.dm
> +					playsound(user, 'sound/impact_sounds/Generic_Snap_1.ogg', 30, FALSE)
yeah no, boo copypaste code, please move this stuff to a helper proc so there's not 4 giant copypasted chunks here

2024-02-13 23:11 UTC, TobleroneSwordfish requested changes

2024-04-18 15:00 UTC, TobleroneSwordfish requested changes

2024-04-18 15:00 UTC, TobleroneSwordfish commented on code/modules/chemistry/tools/emergency_injectors.dm
> +			. += " This injector is empty and thus unuseable."
```suggestion
```
These are just duplicating information from desc.

2024-04-18 15:01 UTC, merged