Wizard spellbook TGUI
goonstation/goonstation pull request #17963
Opened 2024-02-14 10:10 UTC by IPling

## About the PR 
Changes:
* Added search bar
* Collapsible categories
* Removed junk code related to the wizard spellbook. (or atleast I hope it was junk code, the spellbook doesnt explode does it?)

![wizard_spellbook_showcase](https://github.com/goonstation/goonstation/assets/137294088/1303fb56-43d3-49e5-b891-bcdad8f3ea23)

## Why's this needed? 
TGUI is good.
## Changelog 

```changelog
(u)IPingu
(+)Converts wizard spellbook interface to TGUI
```

2024-02-15 13:58 UTC, MeggalBozale commented
LGTM on the code side, but I feel the menu could serve to be more compact in favor of user experience - while before you could see all the spells in a nice list, scrolling through various openable menus to have to select ones favorite loadout or compare spells sounds like a chore. Perhaps a list of all spells by name w/ a description in a hover tooltip as a top element could help this?

2024-02-15 13:59 UTC, MeggalBozale requested changes
LGTM on the code side, but I feel the menu could serve to be more compact in favor of user experience - while before you could see all the spells in a nice list, scrolling through various openable menus to have to select ones favorite loadout or compare spells sounds like a chore. Perhaps a list of all spells by name w/ a description in a hover tooltip as a top element could help this?

![image](https://github.com/goonstation/goonstation/assets/27376947/fa2e6c33-9e8f-4ddb-8c9f-96451aaa8385)
Here's the old menu for comparison, which does this -- I don't really mean in list-view which takes up a good chunk of the menu, rather just a bunch of spell name-labeled buttons in sequence.

2024-02-15 13:59 UTC, MeggalBozale commented on tgui/packages/tgui/interfaces/Wizard_Spellbook.js
> +                placeholder={"search by spell name"}
```suggestion
                placeholder={"Search by spell name"}
```
capitalization might be nice imo

2024-02-15 13:59 UTC, MeggalBozale commented on tgui/packages/tgui/interfaces/Wizard_Spellbook.js
> +              spell unavailable in VR
```suggestion
              Spell unavailable in VR
```
capitalization might look nicer

2024-02-15 17:39 UTC, ZeWaka commented
Could also compact cost to be on the line with the title of the spell also
**Rathen's Secret (1 Spell Slot)**

2024-02-15 22:28 UTC, TobleroneSwordfish requested changes
- Some of the section colours are pretty hard to make out on dark mode, consider having specific light/darkmode colours like chat classes do.
![image](https://github.com/goonstation/goonstation/assets/20713227/cdb0119a-7304-498c-bc2f-f571ac23baf4)
- The search should probably auto-expand sections otherwise it's not very useful.
- Maybe use the spell icons somehow?

2024-02-16 21:56 UTC, IPling commented
> * Some of the section colours are pretty hard to make out on dark mode, consider having specific light/darkmode colours like chat classes do.
Yeah I can tweak that a tiny bit, gonna work on it tommorow.
> * The search should probably auto-expand sections otherwise it's not very useful.
I would LOVE to, but I dont think its quite possible with Collapsibles, since looking at the ObserveMenu that is very similar, it doesnt have that feature either with that project also having a lot more knowledgable people on it. Maybe there is a way, but I got no clue what it would be.
> * Maybe use the spell icons somehow?
That is a nother thing I would love, and there is a good example of how its possible with seed_vendor TGUI, but I could not quite figure out how that code works, and I cant exactly copy and paste since spell icons are animated yet fruit icons arent and it was a headache. I would need someone a bit more knowledgable in that area to get it to work.

2024-02-16 22:09 UTC, IPling commented
> Could also compact cost to be on the line with the title of the spell also **Rathen's Secret (1 Spell Slot)**

I had tried that, but I never liked having spell information in two different sections, because I feel as if the spell cost is as important as its description and cooldown meaning they should be paired. Altough that could be nullified if I were to place the spells description in the title of the section like a button that one way or a nother shows the description when clicked or hovered, that could be interesting to check out. Since the descriptions of spells only need to be read once, it becomes unneeded filler after the first read so it would be good to hide it first and only show when the player needs it.

2024-02-17 11:15 UTC, IPling commented
I have tried this now, but I am not entirely sure I enjoy it, altough that might be from me not knowing how to decorate it properly.
![image](https://github.com/goonstation/goonstation/assets/137294088/cea047f6-7f84-4837-a8ff-3e1c93aa4e60)

2024-02-18 02:49 UTC, ZeWaka commented
Why even hide the descriptions?

2024-02-18 02:50 UTC, ZeWaka commented
You could also put the cooldown in the title bar and have the cost be in the purchase button

2024-02-19 07:47 UTC, IPling commented
> Why even hide the descriptions?

To make it more compact, since descriptions really only need to be read once for a person to understand what the spell does and after the fact it seems pointless, allowing the user to more freely traverse the list of spells. Altough a player who knows the spells would probably just use the search bar, rather than cataloguing the list. Mostly just testing stuff out and seeing what sticks since that isnt implemented yet and as said I dont quite like it.

2024-02-20 09:48 UTC, Valtsu0 commented
I'd prefer this having the default theme over ntos

Ideally we would have a wizard theme, but we don't (yet)

2024-02-20 10:27 UTC, IPling commented
Okay, I feel like the current NTOS theme and coloring is incredibly trivial to keep, since they feel much more like filler to replace the yet to be made wizard theme, and it would be more preferable to keep it a clean slate for when someone actually decides to make a wizard theme. It would be really great to have color since without it feels bare, but that is out of my expertise that I am not good at for now so maybe I or someone else in the future could make it.

Here is how it currently looks like, with some tweaks:
![wizard_spellbook_showcase_test](https://github.com/goonstation/goonstation/assets/137294088/dc9bd4ca-da14-422e-8e38-ca49c911a522)

2024-02-20 10:45 UTC, IPling commented
Updated the PR descriptions and some of the tweaks were adding a Divider to more clearly well... divide spells, and the cost is now stated in the purchase button, to make it a bit more compact. Decided to not go with a more compact description since it looks better that the description is more associated with the spell visually and hiding it didnt serve that much purpose when the search bar exists.

2024-02-20 22:39 UTC, ZeWaka approved these changes

2024-02-23 21:12 UTC, merged