Fixes #17275: Reagents applying to overlays on turfs which cause errors in lighting
goonstation/goonstation pull request #18099
Opened 2024-03-03 19:56 UTC by mloccy

[BUG][CATERING][CHEMISTRY]

## About the PR 
Fixes #17275 by not applying reagents to overlays.

## Why's this needed? 
Not sure reagents should be applied to overlays so it seems like a good fix.

2024-03-03 23:13 UTC, TobleroneSwordfish requested changes
Better to add an empty `reagent_act` definition to `/obj/overlay` to catch other cases where chems can be applied to overlays. In general they should probably just be merged into `/obj/effects` but that's a different PR.

2024-03-04 00:12 UTC, mloccy commented
> Better to add an empty `reagent_act` definition to `/obj/overlay` to catch other cases where chems can be applied to overlays. In general they should probably just be merged into `/obj/effects` but that's a different PR. 

Do you mean in addition to the lines added in the PR or instead of? Because the issue is in reagent.reaction_obj which is called on overlays if we remove the type check. We could also do a type check for overlays in the pizza reagent impl of reaction_obj instead.

2024-03-04 01:01 UTC, mloccy commented
> > Better to add an empty `reagent_act` definition to `/obj/overlay` to catch other cases where chems can be applied to overlays. In general they should probably just be merged into `/obj/effects` but that's a different PR.
> 
> Do you mean in addition to the lines added in the PR or instead of? Because the issue is in reagent.reaction_obj which is called on overlays if we remove the type check. We could also do a type check for overlays in the pizza reagent impl of reaction_obj instead.

Maybe a better fix could be putting the check in /atom/proc/setMaterial

2024-03-04 18:16 UTC, TobleroneSwordfish commented
Ehh this is fine for now actually

2024-03-04 18:16 UTC, merged