Fixes Blind staff dropping their stuff in arrivals
goonstation/goonstation pull request #18196
Opened 2024-03-13 02:38 UTC by Esstoo

[FIX][CLOTHING][TRAIT]

## About the PR 
People with Either the Blind, Short-Sighted or Deaf Trait combined with a Background Trait no longer spawn their stuff in arrivals at roundstart

## Why's this needed? 
Should Fix all of these:
#16758
#10323 
#12975 
#15270

2024-03-13 06:23 UTC, ZeWaka requested changes
yeah no, this code is super wack, and please indent your function bodies on a newline like i said

2024-03-13 22:40 UTC, Esstoo commented
> alternatively, do the heavy sleeper thing and glue the old items onto the newly spawned person instead. Is it jank? yeah. Is it established precedent? Also yeah ([61b4859](https://github.com/goonstation/goonstation/commit/61b4859d288b0bbc4f264b668cba1df2886de028))

Makes more sense in my head if it stores it in your inventory.
If the backpack is full, it ends up in your hand, which will already glue the item to you anyway if you're a heavy sleeper.

2024-03-14 17:47 UTC, pgmzeta requested changes
two small tweaks, looks good otherwise.

2024-03-14 17:47 UTC, pgmzeta commented on code/mob/living/carbon/human.dm
> +	else qdel(I)
`else` would only trigger if the *last* `if` is false
```suggestion
	qdel(I)
```

2024-03-14 17:47 UTC, pgmzeta commented on code/mob/living/carbon/human.dm
> +/mob/living/carbon/human/proc/stow_in_available(obj/item/I)
small doc-comment to explain functionality
```suggestion
///Tries to put an item in an available backpack, pocket, or hand slot; will delete the item if unable to place.
/mob/living/carbon/human/proc/stow_in_available(obj/item/I)
```
```

2024-03-15 01:12 UTC, TobleroneSwordfish approved these changes

2024-03-21 05:13 UTC, merged