Implement autofocus functionality for tgui input number modals
goonstation/goonstation pull request #18206
Opened 2024-03-13 23:58 UTC by Sovexe

## About the PR 
* implements auto focus for `tgui_input_number` and `tgui_input_number_async` enabled by default

## Why's this needed? 
* Improved user experience

2024-03-30 16:20 UTC, mordent-goonstation commented
LGTM. When we upgrade Inferno -> React would be worth looping back around to porting these back upstream so we're all in sync.

2024-03-30 16:20 UTC, mordent-goonstation approved these changes

2024-04-04 02:22 UTC, ZeWaka commented
!merge_upstream

2024-04-04 03:17 UTC, ZeWaka commented
!merge_upstream

2024-04-04 03:42 UTC, ZeWaka commented
L+conflict+ratio

2024-04-04 03:42 UTC, ZeWaka commented
!merge_upstream

2024-04-04 03:58 UTC, ZeWaka commented
!merge_upstream

2024-04-04 04:06 UTC, ZeWaka commented
what a shame, L

2024-04-04 04:06 UTC, ZeWaka commented
!merge_upstream

2024-04-04 23:23 UTC, Sovexe commented
converting back to a draft...there are some bugs to be addressed

2024-04-05 05:04 UTC, Sovexe commented
Something I noticed with this (and with upstream) the input proc in dm still has an arg named `round_input` (`round_value` in upstream) but if its set to true you won't ever have anything to round. This is because the way the sanitization works numbers like `1.7` become `17`, the decimal is treated as a bad character to be stripped out. The round call does still occur in dm, but unless someone is exploiting shouldn't ever have a decimal to round. 

But that's how upstream has it so that's how it's been implemented here

2024-04-05 05:14 UTC, ZeWaka requested changes
zewaka needs to check licenses

2024-05-19 18:39 UTC, ZeWaka approved these changes

2024-05-19 18:39 UTC, ZeWaka commented on tgui/packages/tgui/components/RestrictedInput.js
> + * @license
```suggestion
 * @license MIT
```

2024-05-19 18:39 UTC, ZeWaka commented
!merge_upstream

2024-06-03 01:11 UTC, merged