Add some traits to medical record disability lists
goonstation/goonstation pull request #18226
Opened 2024-03-16 21:33 UTC by pgmzeta

[QOL][STATION-SYTEMS][MEDICAL]

## About the PR 
When generating the medical record for players on manifest, add major and minor disabilities based on the following traits:
* Major: Deaf, Blind, Stumped, Puritan
* Minor: Short-sighted, Hemophilia, Frail Constitution, Hyperallergic

These specific traits were included because they are medically relevant and likely to be recorded in medical records. Some traits use medical-themed verbiage instead of the trait name verbatim. The list of traits will still show the trait name; this is not providing any details that wouldn't already be known if you remember the trait description.

## Why's this needed? 

Make it clearer to doctors what the impact of traits to their job duties in an unobtrusive and in-universe way.

"Don't clone a puritan!!!" How would you know that unless you *already* knew what the Puritan trait was/meant?

## Screenshot
An in-game screenshot showing a medical record with a large number of disabilities via both PDA and MedTrak.
![image](https://github.com/goonstation/goonstation/assets/91498627/0b0cdacd-ec0d-40f7-a988-59f4eb9abea8)

## Changelog 

```changelog
(u)glowbold
(+)Medical records now include a select summary of a patient's disabilities.
```

2024-03-16 22:18 UTC, TobleroneSwordfish requested changes
Cool idea, makes sense

2024-03-16 22:18 UTC, TobleroneSwordfish commented on code/datums/datacore.dm
> +			if(istype(T, /datum/trait/deaf))
Don't do this with a big if tree, put the data on the trait instead

2024-03-17 16:28 UTC, TobleroneSwordfish approved these changes

2024-03-29 01:20 UTC, ZeWaka approved these changes

2024-03-29 01:20 UTC, ZeWaka commented on code/datums/datacore.dm
> +	if(minorDisabilities.len)
```suggestion
	if(length(minorDisabilities))
```

2024-03-29 01:20 UTC, ZeWaka commented on code/datums/datacore.dm
> +	if(majorDisabilities.len)
```suggestion
	if(length(majorDisabilities))
```

2024-03-29 05:19 UTC, merged