gang leader delegation
goonstation/goonstation pull request #18366
Opened 2024-03-31 04:11 UTC by TDHooligan

[BUG]
## About the PR 
when gang leaders enter cryo with no locker, they are immediately replaced with another gang member 
(if they have a locker, there is already a 7.5 minute timer until the role can be claimed)

## Why's this needed? 
gang leader cryoed so hard all my mitigating factors broke down. gang sad ):

2024-03-31 04:11 UTC, TDHooligan commented on _std/defines/gang.dm
lowered this - 15 minutes is enough to set a gang back probably too long

2024-04-01 04:50 UTC, ZeWaka requested changes

2024-04-01 04:50 UTC, ZeWaka commented on code/datums/gamemodes/gangwar.dm
> +			broadcast_to_gang("Your leader has entered temporary cryogenic storage. You can claim leadership at your locker in 7.5 minutes.")
use the define

2024-04-04 09:01 UTC, TobleroneSwordfish requested changes

2024-04-04 10:36 UTC, TDHooligan commented on code/obj/cryotron.dm
> +								antagonist.handle_cryo()
good catch.

2024-04-05 05:14 UTC, ZeWaka approved these changes

2024-04-05 08:13 UTC, merged