Borgs can now get buff in the gym on the weight machines.
goonstation/goonstation pull request #18373
Opened 2024-04-01 21:00 UTC by Francisco-Franks

[A-Silicons][C-Feature]
## About the PR 
Click-Drag added to the 2 weight lifting machines. Click-Drag yourself as a Borg into the weight machine to pump iron for no actual benefit.

## Why's this needed? 

Borgs should be allowed to strive for physical excellence. Also this will open RP opportunities.

## Changelog 

```changelog
(u)MetaReferencer
(+)Borgs can click-drag themselves onto weight machines (for no benefit).
```

2024-04-02 06:06 UTC, ZeWaka requested changes

2024-04-02 06:06 UTC, ZeWaka commented on code/obj/item/fitness.dm
> +			return
use the helper functions

2024-04-03 17:30 UTC, Francisco-Franks commented on code/obj/item/fitness.dm
> +			return
helpered

2024-04-05 21:19 UTC, ZeWaka approved these changes

2024-04-08 04:51 UTC, merged