Random Event: "Illegal" trinkets count as contraband
goonstation/goonstation pull request #18372
Opened 2024-04-01 20:14 UTC by pgmzeta

## About the PR 
Random event to mark all player trinkets named with a specific set of "illegal" words as level 3 contraband.

## Why's this needed? 
Give security some low-stakes cases to tackle.

## Changelog 

```changelog
(u)glowbold
(+)NanoTrasen randomly screens trinkets for contraband.
```

2024-04-01 21:05 UTC, TDHooligan commented
fun idea, will sec actually follow up on these though?

2024-04-02 02:35 UTC, cheekybrdy commented
Other then a small typo on the centcom message looks good!

2024-04-02 06:07 UTC, ZeWaka requested changes

2024-04-02 06:07 UTC, ZeWaka commented on code/modules/events/minor/illegal_trinkets.dm
> +	centcom_message = "The NanoTrasen Logistics Screening Team has confirmed the possibility of stolen, smuggled, or counterfit items aboard."
```suggestion
	centcom_message = "The NanoTrasen Logistics Screening Team has confirmed the possibility of stolen, smuggled, or counterfeit items aboard."
```

2024-04-03 04:17 UTC, ZeWaka approved these changes

2024-04-05 21:18 UTC, merged