Added a new Rabbit Suit to Honkington!
goonstation/goonstation pull request #18428
Opened 2024-04-06 23:43 UTC by nerkson

[CLOTHING] [SPRITES]

## About the PR 
Added a Rabbit suit for sale from Geoff Honkington! In the box is a Rabbit Suit and Rabbit Hat, so mix and match to your hearts content!
![Screenshot 2024-04-06 194219](https://github.com/goonstation/goonstation/assets/108430764/570d9d90-e5c0-456b-a21f-86af1e4bf299)

## Why's this needed? 
I had wanted to add this in ahead of time for Easter but I was prevented from doing it. All the same it's a nice seasonal type costume to have! 

## Changelog 

```changelog
(u)Carthridge / Nerkson
(*)Added Rabbit Costume to the Game
```

2024-04-07 00:04 UTC, 444Portal requested changes
everything code-wise and sprites-wise looks good, could probably use a minor (+) changelog entry that tells you its in geoffs stock

2024-04-07 00:04 UTC, nerkson commented
> everything code-wise and sprites-wise looks good, could probably use a minor (+) changelog entry that tells you its in geoffs stock

Updated, thank you!

2024-04-07 01:40 UTC, 444Portal approved these changes
ya looks good

2024-04-10 10:57 UTC, amylizzle approved these changes
This is great. Can't wait to be deeply unsettled by someone wearing this in a dark maint corridor.

2024-04-10 12:18 UTC, nerkson commented on code/obj/item/clothing/hats.dm
> +	seal_hair = 1
Thank you! Made the change.

2024-04-19 04:00 UTC, merged