Adds party animal trait as new background
goonstation/goonstation pull request #18717
Opened 2024-05-02 23:07 UTC by Glamurio

[Traits] [Feature]

## About the PR 
This PR adds the new trait "Party Animal" to the background category.

This trait spawns you with a random ethanol amount in your blood stream in the bar, with a chance to spawn more groggy.
It tries to do so my placing you near chairs, just because that generally resulted in better placement inside the bar.
It also spawns some party clutter items around your character as the aftermath of a party that happened last night.

Late-joiners will instead wake up underneath a random bar table and slowly roll out from under it.
This does not spawn clutter.

A new TR_CAT was added, `TR_CAT_PARTY_CLUTTER`, tracking the amount of party clutter spawned to limit to 50% of the area's max size.
Additionally, this adds a tracker to `/obj/table`, and moves the tracker from `/obj/stool/bed` to `/obj/stool`.

Furthermore, it adds a new attribute `spawn_delay` to traits to avoid having to hardcode spawn delays in various files.

It also adds a new proc `getTraitWithCategory` that returns any trait within a given category.
This was added to simplify some of the hard-coded exclusions for other background traits such as Heavy Sleeper and Pilot.

## Why's this needed? 
More traits, more expression, more fun.

## Changelog 

```changelog
(u)Glamurio (Ryou)
(*)Adds a new trait, Party Animal, which will have you (and anyone else with the trait) wake up groggy from last night's party.
```

2024-05-06 21:22 UTC, Tarmunora requested changes

2024-05-06 21:22 UTC, Tarmunora commented on code/mob/new_player.dm
> +						character.layer = initial(character.layer)
merge these SPAWNs

2024-05-06 21:22 UTC, Tarmunora commented on code/procs/jobprocs.dm
> +			)
put these onto TYPEINFO for the trait rather than hardcoding them into here

2024-05-06 21:22 UTC, Tarmunora commented on code/procs/jobprocs.dm
> +			var/list/area_turf = get_area_turfs(/area/station/crew_quarters/bar, 1) + get_area_turfs(/area/station/crew_quarters/cafeteria, 1)
Expensive, should cache this rather than iterate for each person with the trait

2024-05-06 21:22 UTC, Tarmunora commented on code/procs/jobprocs.dm
> +					var/list/spawn_range = range(1, stool) - range(0, stool) // Skip the actual stool
```suggestion
					var/list/spawn_range = orange(1, get_turf(stool))
```

2024-05-06 21:22 UTC, Tarmunora commented on code/mob/new_player.dm
> +							continue
instead of rolling your own checks here and elsewhere, consider using `jpsTurfPassable()`

2024-05-06 21:22 UTC, Tarmunora commented on code/procs/jobprocs.dm
> +							thing.set_loc(spot)
is this additional set_loc() needed?

2024-05-07 08:03 UTC, TobleroneSwordfish requested changes

2024-05-07 20:31 UTC, Glamurio commented
I've gone ahead and also added `/obj/random_item_spawner/pizza/one` and `/obj/random_item_spawner/cola/one` because no party is a good party without pizza and soda, but I only want one per tile.

2024-05-08 17:43 UTC, TobleroneSwordfish approved these changes

2024-05-08 18:54 UTC, merged