Gives HoP PDA a new cartridge instead of the standard command one.
goonstation/goonstation pull request #18732
Opened 2024-05-03 14:12 UTC by cheekybrdy

## About the PR 
Gives HoP a unique PDA cartridge in their PDA instead of the standard command one.

## Why's this needed? 
Previous standard command one that the HoP did have had alot of sec programs in it, this changes the HoP's PDA to have programs related to their home department and ensuring that there is no messaging in game to make people stray towards dreaded secHoPing.

## Changelog 

```changelog
(u)Cheekybrdy
(+)HoP has their own dedicated PDA cartridge related to the civilian department instead of the old general command one.
```

2024-05-03 14:25 UTC, pgmzeta requested changes
HoP can approve fines, needs to have the security ticket program to do so.

Really dislike sharing a cart image with hydroponics, should use the existing records one or a new icon.

Could you please place this up where the rest of the head carts are?

2024-05-03 23:16 UTC, TobleroneSwordfish commented
I'd be fine with taking away the forensics scanner and maybe sec records? (although the HoP is kind of the record person so 🤷) But they definitely should still have the ticketmaster.

2024-05-04 01:20 UTC, cheekybrdy commented
one thing I've noticed looking through this file, should the CE really have the ability to ticket people? MD and RD don't have the program

2024-05-11 10:53 UTC, TobleroneSwordfish commented on code/obj/item/device/pda2/cartridges.dm
> +			src.root.add_file( new /datum/computer/file/text/handbook_botanist(src))
```suggestion
			src.root.add_file( new /datum/computer/file/pda_program/power_checker(src))
```

2024-05-11 10:53 UTC, TobleroneSwordfish commented on code/obj/item/device/pda2/cartridges.dm
> +		desc = "For everything a person managing a civilian department would need if they actually were going to do that, as if."
```suggestion
		desc = "For everything a person managing a civilian department would need."
```

2024-05-11 10:54 UTC, merged