Fixes a runtime caused by recoil attempting to trigger on non-mob users
goonstation/goonstation pull request #18817
Opened 2024-05-08 19:53 UTC by Ilysen

## About the PR 

`handle_recoil` is now enclosed in an `ismob(user))` check.

## Why's this needed? 

`handle_recoil` expects a mob user, but the place where it's called doesn't do a type check to make sure the user is actually human. This leads to runtimes when a gun goes off without a mob user (such as when it's fired by a gun component); it *seems* like a harmless error, but it does spam the log, so it's a good thing to fix anyway.

## Testing

I jumped into a local server and fired a few different types of spawned-in gun myself and as part of a gun component assembly. No runtimes anymore, and everything seemed to work as intended.

2024-05-08 21:30 UTC, Tarmunora commented on code/obj/item/gun/gun_parent.dm
> +		if (ishuman(user) && src.add_residue) // Additional forensic evidence for kinetic firearms (Convair880).
```suggestion
		if (ismob(user) && src.add_residue) // Additional forensic evidence for kinetic firearms (Convair880).
```

2024-05-08 21:31 UTC, Tarmunora requested changes
why not just put an `if(user)` check before doing the camera recoil in `handle_recoil`?

2024-05-10 01:18 UTC, Ilysen commented
could work! there actually is a sanity check in that proc for if the user exists, but not for if it's a mob or not. I can add in an istype to the proc easily enough.

2024-05-11 03:54 UTC, ZeWaka approved these changes

2024-05-11 03:55 UTC, merged