Sillier EMAG effects for the lawbringer
goonstation/goonstation pull request #19004
Opened 2024-05-18 22:26 UTC by MeggalBozale

[Feature] [Game-Objects]
## About the PR 
Adds a more fitting set of emag effects for the lawbringer.
- When you shoot the lawbringer while it's emagged, it will pick between random modes for you.
- There is a 1% chance to force you to scream out "I AM THE LAW" and trigger the explosion
- Emagged lawbringers have no sense of laws, and so the HoS is not immune to the explosion for saying these words.
- Moves over switching code to a proc so that it can be accessed from other places in the code. There's a lot of custom varediting in there, so it should be exposed to more parts of the code for use. Like this!

## Why's this needed? 

https://github.com/goonstation/goonstation/assets/27376947/043818af-9cec-48ac-88c3-1c08b341d7cc

```changelog
(u)MeggalBozale
(+)The emag effect for the lawbringer has been modified slightly.
```

2024-05-18 22:26 UTC, MeggalBozale commented
Note that while prob(1) is prob(1) i cut out like 30 seconds of me spamming it to trigger the IATL effect

2024-05-18 22:44 UTC, MeggalBozale commented
ALSO IMPORTANT TO CLARIFY I FORGOT!!!
this doesnt stop you from getting access to the lawbringer yourself, current emag effect isnt removed :)

2024-05-18 23:30 UTC, TheRyeGuyWhoWillNowDie commented
seems not fun? now even if you kill the head of security, steal their gun, and have an emag, the lawbringer is little more than a toy, and worse yet extended use will get you gibbed

2024-05-18 23:45 UTC, MeggalBozale commented
You can fabricate a new one or just not emag the thing. It's an emag! Weird things can happen!

2024-05-19 00:34 UTC, TobleroneSwordfish requested changes

2024-05-19 00:34 UTC, TobleroneSwordfish commented on code/obj/item/gun/energy.dm
> +				src.are_you_the_law(user, "I AM THE LAW") // the thoughts won
Funny but probably a bad idea

2024-05-19 02:23 UTC, MeggalBozale commented on code/obj/item/gun/energy.dm
> +				src.are_you_the_law(user, "I AM THE LAW") // the thoughts won
fine :(

2024-05-19 12:46 UTC, TobleroneSwordfish approved these changes

2024-05-19 14:26 UTC, Glamurio approved these changes

2024-05-22 12:40 UTC, merged