Makes donator figurines prioritize players
goonstation/goonstation pull request #19110
Opened 2024-05-23 15:34 UTC by MintyPhresh

## About the PR
Whenever a donator figurine is rolled from a capsule, there is a 20% chance it will be your own (if you have one), and a 20% chance it will be one that belongs to a donator (other than you) that logged in that round. 

This replaces the original 30% chance to get your own figurine.

## Why's this needed?
Having a figurine of an active coworker is far more fun than having one of a character that isn't in the round (and who you likely won't recognize). I've heard a horror story on the discord of a player opening [1500+ capsules](https://discord.com/channels/182249960895545344/890223118482800790/1201223607855095988) in search of a single player's figurine-- This should ease the search a little for future endeavors.

## Changelog 
```changelog
(u)CodeDude
(+)Increased chance to get figurines of donators that joined the round.
```

2024-05-24 00:22 UTC, TobleroneSwordfish requested changes

2024-05-24 00:22 UTC, TobleroneSwordfish commented on code/modules/items/gimmick/figurine.dm
> +	for (var/datum/figure_info/patreon/fig as anything in concrete_typesof(/datum/figure_info/patreon))
That's quite a long list to be iterating in `client/New`, maybe generate a list of donator ckeys on roundstart and then check if the ckey is in that list each time instead.

2024-05-24 00:22 UTC, TobleroneSwordfish commented on code/modules/items/gimmick/figurine.dm
> +			var/list/figure_patreon_online_nouser = figure_patreon_online
`=` isn't a copy operation, so any modifications here *will* be reflected in the global list. Not sure what "nouser" means but I'm guessing this isn't what you want

2024-05-24 00:22 UTC, TobleroneSwordfish commented on code/modules/items/gimmick/figurine.dm
> +						if (figure_patreon_online_nouser.len)
```suggestion
						if (length(figure_patreon_online_nouser))
```
Always use `length()` rather than `.len`

2024-06-02 22:23 UTC, ZeWaka requested changes

2024-06-02 22:23 UTC, ZeWaka commented on code/modules/items/gimmick/figurine.dm
> +						break
Use .Find, this is dumb

2024-06-03 04:20 UTC, ZeWaka approved these changes

2024-06-10 03:12 UTC, merged