Alcohol Resistance grants full immunity to ethanol addiction
goonstation/goonstation pull request #19284
Opened 2024-06-02 19:24 UTC by MintyPhresh

## About the PR 
The alcohol resistance effect, which can be gotten either through genetics, the career alcoholic trait, or by being a certain job, already grants full immunity to ethanol's effects (so long as there's no moonshine in there). This PR grants them a greater resistance to ethanol addiction, too; quartering the chance it happens and making it take four times as long to start rolling.

## Why's this needed? 
I've taken the gene that grants alcohol resistance before, expecting it to have this behavior, since it's the hardest symptom of ethanol to treat and the most persistent. What's the point of alcohol resistance if you can't resist taking more of it?

## Changelog
```changelog
(u)mintyphresh
(+)Alcohol resistance from genetics, jobs, and traits now helps stave off addiction, too.
```

2024-06-02 20:39 UTC, mordent-goonstation requested changes
Would prefer this was done on the ethanol reagent only, rather than on every reagent datum. Would require restructuring a little bit to let ethanol call the parent proc (`..()`) with appropriate changes.

2024-06-02 20:39 UTC, mordent-goonstation commented on code/modules/chemistry/Chemistry-Reagents.dm
> +				if (src.id == "ethanol" || isalcoholresistant(H))
Should be `&&`?

2024-06-03 01:22 UTC, MintyPhresh commented on code/modules/chemistry/Chemistry-Reagents.dm
> +				if (src.id == "ethanol" || isalcoholresistant(H))
Yeppp

2024-06-03 03:14 UTC, MintyPhresh commented
Changed to make it ethanol reagent only-- thanks for the comment, I learned something new about DM today!

2024-06-03 06:21 UTC, mordent-goonstation commented on code/modules/chemistry/Chemistry-Reagents.dm
> +				src.handle_addiction(M, deplRate, addProb)
```suggestion
				src.handle_addiction(M, deplRate, addiction_prob)
```

2024-06-06 13:30 UTC, TobleroneSwordfish requested changes

2024-06-06 13:30 UTC, TobleroneSwordfish commented on code/modules/chemistry/Reagents-Base.dm
> +		..()
```suggestion
		..(M, rate, addProb)
```
I *think* DM will handle the modified argument fine without this, buut it's much clearer what you're doing when it's written like this.

2024-06-10 02:42 UTC, merged