Make blob player left clicks automatically cast the spread ability
goonstation/goonstation pull request #19341
Opened 2024-06-05 03:02 UTC by FlameArrow57

[GAME MODES][PLAYER ACTIONS][FEATURE][QoL][ADD TO WIKI]

## About the PR 
Makes it so that when a blob player left clicks something, it will attempt to call the spread ability on the tile.

## Why's this needed? 
-Allows easier use of main spammable ability without disrupting much
-Allows other abilities to be hotkeyed
-Hopefully reduces some of the hovering over tiles that is needed and skill gap required to play

## Changelog 

```changelog
(u)FlameArrow57
(*)As a blob, left clicking a tile will now attempt to spread to that tile, meaning you don't need to click or hotkey the ability button at all!
```

2024-06-05 15:51 UTC, TobleroneSwordfish requested changes
Good PR, but the way it's currently written prevents blobs from examining, it shouldn't override default alt examine behaviour unless an ability is bound to alt.

2024-06-05 20:13 UTC, BatElite commented
Didn't left click previously teleport you? Does that mean this affects the viewport thing blobs for some reason get? (I think you could like, click those for quick travel anyway...)

2024-06-05 23:38 UTC, FlameArrow57 commented
> Good PR, but the way it's currently written prevents blobs from examining, it shouldn't override default alt examine behaviour unless an ability is bound to alt.

I don't think they're meant to, parent is never called to do so in the click() proc

2024-06-05 23:38 UTC, FlameArrow57 commented
> Didn't left click previously teleport you? Does that mean this affects the viewport thing blobs for some reason get? (I think you could like, click those for quick travel anyway...)

nah it's right click that teleports you

2024-06-06 13:19 UTC, TobleroneSwordfish approved these changes
Pfff okay then!

2024-06-07 18:15 UTC, MeggalBozale commented
Sounds nice for new blobs and for blobs in general to free up a hotkey. On top of making it easier to do the most basic task :heart:

2024-06-07 19:53 UTC, merged