Reduce client-side load from manufacturers
goonstation/goonstation pull request #19425
Opened 2024-06-09 15:52 UTC by MeggalBozale

[Performance] [Internal]
## About the PR 
Offloads the requirement checking from the TSX end to the DM end, to take the load from each viewing client to the server.

## Why's this needed? 
I thought the TSX end would be the performance improvement, honestly, but it turns out that the server might be better equipped to process this information than the clients. Helps improve performance when multiple people are viewing the same one anyway, I guess, so there's that.
Fixes #19400 

@TobleroneSwordfish

2024-06-11 17:35 UTC, MeggalBozale commented
DNM - waiting on #19440 to add further performance improvements

2024-07-05 03:15 UTC, MeggalBozale commented
Going to just rename this PR and try to get it in before the feature freeze, my focus is elsewhere right now so I don't have much time to wrap up this overall thing.

2024-07-05 03:16 UTC, MeggalBozale commented
!merge_upstream

2024-07-15 17:34 UTC, ZeWaka commented
Closed due to the TGUI feature freeze, https://github.com/goonstation/goonstation/discussions/19808

2024-11-24 03:49 UTC, MyNameIsRomayne commented
Attempting to reopen due to the feature freeze being over, marking as draft because now there is also the ability to profile things and get to work with memoization.

2024-11-25 14:31 UTC, Garash2k commented on tgui/webpack.config.js
Weewoo weewoo unintentional file commit alert!

2024-11-25 14:38 UTC, Garash2k commented on tgui/packages/tgui-dev-server/link/client.cjs
> +  if (!window.WebSocket) {
and here

2024-11-25 15:55 UTC, MyNameIsRomayne commented on tgui/webpack.config.js
Intentional, I don't want to fret over what files to commit/not to commit while working on this. It will be resolved when I open this for review, let me know if any files are leftover then

2024-11-26 00:13 UTC, mordent-goonstation commented
No need for changelog, we don't typically include them for internal performance things.

2024-11-26 00:45 UTC, mordent-goonstation requested changes

2024-11-26 00:45 UTC, mordent-goonstation commented on code/obj/machinery/manufacturer.dm
> +		return output
This seems decently expensive to generate each time in `ui_data`.

2024-11-26 00:45 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Manufacturer/components/BlueprintButton.tsx
> +  );
Need to have populated deps arrays.

2024-11-26 00:45 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Manufacturer/components/BlueprintButton.tsx
> +  );
Is this not just `Object.values(blueprintProducibilityData).some(x => !x)`? If not, there's some weirdness here that I'm not getting.

2024-11-26 00:45 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Manufacturer/components/BlueprintButton.tsx
> +  }, [blueprintProducibilityData]);
This doesn't do anything.

2024-11-26 00:45 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Manufacturer/components/BlueprintButton.tsx
> +          onClick={memoizedOnVendProduct}
Convention is to name `handleVendProduct`.

2024-11-26 00:45 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Manufacturer/components/BlueprintButton.tsx
> +    }
```tsx
const { blueprintData: prevBlueprintData, blueprintProducibilityData: prevBlueprintProducibilityData, ...prevRest } = prevProps;
const { blueprintData: nextBlueprintData, blueprintProducibilityData: nextBlueprintProducibilityData, ...nextRest } = n nextProps;
if (shallowDiffers(prevRest, nextRest)) {
  return false;
}
// use the destructured ones below
```

2024-11-26 00:45 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Manufacturer/index.tsx
> +  }
So this is invalidating a producibility_data/resource_data cache whenever resource_data changes? What about if producibility_data changes? Should this not be simply worrying about producibility_data? Iterating over a short list that is keyed by their byondRef will avoid most of the rendering cost of the materials list. Not sure much benefit to caching resource_data.

2024-11-30 19:56 UTC, MyNameIsRomayne commented
!merge_upstream

2024-11-30 21:28 UTC, mordent-goonstation reviewed
To test: what does unhacking the manufacturer while it is producing a hacked-only blueprint do?

EDIT: it shows the production bar but not the button that indicates what it is producing/lets you cancel it.

2024-12-01 01:11 UTC, mordent-goonstation approved these changes

2024-12-01 01:13 UTC, merged