Resprites station lights and gives them an overlay! (Thank you Herb)
goonstation/goonstation pull request #19761
Opened 2024-06-30 04:31 UTC by TemThrush

[Game Objects]
## About the PR 
Along with new sprites for bulbs, tubes, and floor-lights, this PR also gives them a separate bloom overlay on top of the sprites that doesn't burn your hand! (Everyone say thank you, Herb)

![image](https://github.com/goonstation/goonstation/assets/108035657/3f5854c2-f563-46df-ba42-9632fa1ba541)

[All the new sprites laid out with the current sprites for comparison]

![image](https://github.com/goonstation/goonstation/assets/108035657/c8163314-285e-405a-9040-7999739544fc)

[Ominous room with as many icon states as I can fit]

https://github.com/goonstation/goonstation/assets/108035657/c19f2a08-55d3-4cf5-9426-d8b0950a0a6a

[Video show-casing the emergency light animation]

## Why's this needed? 
Old sprites no longer meets current spriting standards. Plus I have a personnel vendetta against the nearly invisible pixels you could burn your hand on.

2024-06-30 04:42 UTC, DisturbHerb commented
only took me like two months to finish this in an afternoon 🎉

2024-06-30 05:01 UTC, Xkeeper0 commented
The burnt out ones don't really convey their burnt-out-ness; they just look like the ends are smudged, which isn't quite as clear as the entire-thing-looks-grimy-and-burnt style the current ones have.

i also think the off floor lights have too much shading, but eh, personal preference. i think of them as very smooth pot-light style bulbs

2024-06-30 07:46 UTC, Gannets commented
I liken these

2024-06-30 13:14 UTC, LaCumbiaDelCoronavirus commented
In my opinion, i (also) feel like the tube and floor lights look 'overshaded' or something of the sort. The floor lights also seem very yellow, i think that they'd be better in the same shade of yellow as the original ones.
Other than that, they all look very nice!

2024-07-01 06:59 UTC, ZeWaka commented
> The burnt out ones don't really convey their burnt-out-ness; they just look like the ends are smudged, which isn't quite as clear as the entire-thing-looks-grimy-and-burnt style the current ones have.

to be fair that's somewhat what burnt out flouroscent tubes look like, but i think  in this case they could be conveyed by a bit more interior soot yeah

2024-07-01 06:59 UTC, ZeWaka requested changes

2024-07-01 06:59 UTC, ZeWaka commented on code/modules/power/lighting.dm
> +	var/obj/dummy/light_overlay // Light overlay object to place in `src.vis_contents`
clear this on disposing

2024-07-01 19:58 UTC, Azrun reviewed
Like it once disposing resolved.

2024-07-03 05:29 UTC, ZeWaka commented
i think the burnt out ones are a vast improvement over the shitty existing ones, we can tweak further if we want

2024-07-03 05:29 UTC, merged