Move Nukie field medic satchel supplies to the pouch
goonstation/goonstation pull request #19763
Opened 2024-06-30 15:58 UTC by JORJ949

## About the PR 
Removes the field medic nuclear operative's medical satchel and puts the defibrillator and fire extinguisher into the pouch, also lets the pouch hold them

## Why's this needed? 
The satchel is a straight downgrade to the bag you spawn with, essentially just making it a trap for new players

2024-06-30 16:55 UTC, pgmzeta commented
why not make the satchel bigger instead?

2024-06-30 17:15 UTC, JORJ949 commented
> why not make the satchel bigger instead?

Because whats the point in giving them a second bag when they already have one?

2024-06-30 17:44 UTC, pgmzeta commented
> Because whats the point in giving them a second bag when they already have one? 

for the team to identify which of the nukies will stand them up after they RPG themselves

> If the pouch feels weird I could give them a medical belt instead for them

pouch holding 2 items that don't fit into pockets definitely feels weird to me, I think a belt seems reasonable (they could still hold the fire extinguisher in their pack)

2024-06-30 23:05 UTC, JORJ949 commented
> pouch holding 2 items that don't fit into pockets definitely feels weird to me, I think a belt seems reasonable (they could still hold the fire extinguisher in their pack)
I imagine it as 2 clips on the side of the pouch that clip them on

2024-07-19 23:12 UTC, TobleroneSwordfish requested changes
I agree with zeta, putting large items in pouches like that feels weird, may as well just increase the capacity of the satchel.

2024-07-20 16:11 UTC, JORJ949 commented
I considered giving them a medical belt and removing the pouch altogether, or just putting defib qnd extinguisher loose for use in bag, I don't see much point in giving them the exact same bag tbh, if they want a satchel they can just go get one from the post

2024-07-27 14:32 UTC, JORJ949 commented
Closing to make a better solution in the future

2024-07-27 14:32 UTC, closed without merging