Kondaru Toxins Update!
goonstation/goonstation pull request #19814
Opened 2024-07-03 20:16 UTC by thebee03

# I hope I made this PR correctly :) 

## About the PR 
This just makes a few changes to Kondaru's toxins to make it more in line with other maps' toxins!
 ping me on the goonstation discord @thebee03 if anything has to be changed

## Why's this needed? 
Currently, toxins is almost unplayable on Kondaru. It's a pain in the ass to do anything with just one burn chamber, plus the layout is a bit cramped, and generally it's just not the best to look at. 

## Changes
Moved things around to make room for a second burn chamber
Im gonna be honest, this is a pretty close ripoff of donut 3's toxins, but why mess with greatness? 
Added some lab tables, cause those look cool 

## Before and After!
Before:
![image_2024-07-03_123035276](https://github.com/goonstation/goonstation/assets/170150086/1bf42c3c-fee4-4860-a552-22a74c9cada3)
After:
![image_2024-07-03_123204661](https://github.com/goonstation/goonstation/assets/170150086/d9765375-f447-455a-a74e-a15f3eb0732e)

2024-07-03 20:48 UTC, thebee03 commented
we are so back. should be 100% okay, but for real this time

2024-07-03 20:53 UTC, TealSeer reviewed
Might be worth swapping the gray tiles out for the white ones so it matches the rest of the science department

2024-07-03 20:55 UTC, thebee03 commented
> Might be worth swapping the gray tiles out for the white ones so it matches the rest of the science department

Can do!

2024-07-03 21:11 UTC, thebee03 commented
> > Might be worth swapping the gray tiles out for the white ones so it matches the rest of the science department
> 
> Can do! A part of me wanted it to be a darker color for when im being a nerd at 1am so the brightness doesn't get to me. But it totally makes sense for it to be more in-line with the rest of the department :)

Done! Its all switched out!

2024-07-03 21:21 UTC, TealSeer approved these changes

2024-07-03 21:26 UTC, Kubius commented
Thank you for enjoying my map enough to update it

![image](https://github.com/goonstation/goonstation/assets/12454065/0aef645c-9908-4cac-855f-ee685b323496)

1. Connecting catwalks to burn chamber outputs can allow heat to propagate backwards through the airlocks. **This is not necessarily something that needs changed**, just a note.
2. This little area looks a little goofy - possibly-misaligned button, definitely-misaligned lightbulb, could potentially also use a meter on the corner for this section.
3. Self-explanatory.

2024-07-03 21:33 UTC, thebee03 commented
> Thank you for enjoying my map enough to update it
> 
> ![image](https://private-user-images.githubusercontent.com/12454065/345626708-0aef645c-9908-4cac-855f-ee685b323496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIyNzgsIm5iZiI6MTcyMDA0MTk3OCwicGF0aCI6Ii8xMjQ1NDA2NS8zNDU2MjY3MDgtMGFlZjY0NWMtOTkwOC00Y2FjLTg1NWYtZWU2ODViMzIzNDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDIxMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjJiMDI5ODk4YTNlMjIxZjJkNzIyY2UxYmUwMTU2ZTAzMDlkMDJjNDk2MDE1ZDAyYzljMWJhY2Y2YWQ2MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4elkd4fJgZg9nO-tNg96qUGUxb_-FLzviv7MYcp9mcU)
> 
> 1. Connecting catwalks to burn chamber outputs can allow heat to propagate backwards through the airlocks. **This is not necessarily something that needs changed**, just a note.
> 2. This little area looks a little goofy - possibly-misaligned button, definitely-misaligned lightbulb, could potentially also use a meter on the corner for this section.
> 3. Self-explanatory.

1) I wanted a "safe" way to get to the burn chambers, as I (and other scientists) like to have easy-ish access to the chamber to set up stuff, especially if we are using molitz b, but i guess if the lattice is there, I should be good regardless. So im gonna remove it cause it also seems a bit out of place. 
2) Yeah, throwing a meter on there seems like itl be good, as for the bottom part, maybe I can make the pipe blue, to differentiate that it's the one going out to space that you can use to cool things down! Ill fix the lightbulb as well 
3) Hahahahah oops :)

2024-07-03 23:06 UTC, thebee03 commented
Okay, if everything goes according to plan, this is my final edit. I just figured out that some airless tiles were used in the change up, but thats fixed now. If there's anything else, just let me know, but hopefully it can be added to the game soon (tm)!

2024-07-04 07:35 UTC, itchybones commented
Seems like I'm the only one who likes Kondaru toxins as it is right now, but this is so much better.

2024-07-04 08:26 UTC, thebee03 commented
> Seems like I'm the only one who likes Kondaru toxins as it is right now, but this is so much better.

Aww thank you
Mainly thank whoever designed donut 3's chambers. I *can* say I did a bit of the decorations and adding the airlock out for easy access to the burn chambers via space! 
As for your other point, im one of those who can't stand one chamber, its just inefficient time-wise waiting for a chamber to fully clear to stop cross-contamination. But im a nerd so whatever :)

2024-07-04 19:45 UTC, TobleroneSwordfish requested changes
Looks good, one thing: take two oxygen canisters out of the storage room if you want to put two more on the mixer, just to keep the total number roughly in line with other maps.

2024-07-04 20:12 UTC, BatElite commented
My one complaint is it's just a big rectangle of a room now. That's not very interesting.

Top burn chamber also has the input/output colours wrong on the floor.

2024-07-04 20:24 UTC, thebee03 commented
> Looks good, one thing: take two oxygen canisters out of the storage room if you want to put two more on the mixer, just to keep the total number roughly in line with other maps.

![image](https://github.com/goonstation/goonstation/assets/170150086/8433a30a-2403-4fa7-b91d-54f9e9f88190)
Extra O2 cans removed. I wanted to have them on the ports, as its more in-line with a lot of other toxins, and so maybe beginners see where the canisters have to go.

2024-07-04 20:30 UTC, thebee03 commented
> My one complaint is it's just a big rectangle of a room now. That's not very interesting.
> 
> Top burn chamber also has the input/output colours wrong on the floor.

I fixed the colors, but as for your other point about it being just a big rectangle, I agree. But honestly all toxins look that that. Or at least the toxins with two burn chambers. Personally, I don't want the chamber on different side of the rooms, as its just more work, and tougher to watch both burns. Also I'm in a pretty constrained area, as there's the whole conveyor belt system on the outside of Kondaru, which I don't want to change.

2024-07-05 19:29 UTC, merged