AI Control Disabled maphelper
goonstation/goonstation pull request #20022
Opened 2024-07-17 21:09 UTC by JORJ949

## About the PR 
Add a maphelper to disable AI control on airlocks and adds it to all rotation maps
Fix https://github.com/goonstation/goonstation/issues/19993
(Also closes both #20015 and #19967)

## Why's this needed? 
I saw #20015 and it gave me a better solution to it and im bored so sprited it and stole @pgmzeta's code for it

2024-07-19 12:59 UTC, frawhst approved these changes

2024-07-19 16:27 UTC, pgmzeta requested changes
good helper

2024-07-19 19:01 UTC, ZeWaka requested changes
Review

2024-07-20 09:37 UTC, JORJ949 commented on maps/atlas.dmm
> +/obj/machinery/door/airlock/pyro/security,
Door names are automatically applied by area name no?

2024-07-20 09:39 UTC, JORJ949 commented
Am away until friday, feel free to commit any requested changes if you want this merged before then.

2024-07-27 11:09 UTC, JORJ949 commented on maps/atlas.dmm
> +/obj/machinery/door/airlock/pyro/security,
![image](https://github.com/user-attachments/assets/77c9f7e4-f28e-488f-bcc1-d8353963d6d2)
Airlocks inherit the name of their area, so there isnt much need to have a varedited name

2024-07-27 11:15 UTC, JORJ949 commented on maps/clarion.dmm
>  	req_access = null
Not something I did, may be worth going through some maps and removing all of these, 
![image](https://github.com/user-attachments/assets/c7aab638-fdb2-4389-a80a-92b1a91d75c2)
donut 3 has 112 "req_access = null" for example. Will fix the armory door ones though.

2024-07-27 11:22 UTC, JORJ949 commented
I haven't re-added the varedited names to the doors that have them because many maps dont varedit the name because airlocks inherit door name from area, you only need to varedit a door name if you want a name other than the name of the area (e.g. cog2's internal armory doors are "Weapons Storage". Maps could probably use a req_access = null cleanup aswell

2024-07-31 14:19 UTC, merged