Chem refactor
goonstation/goonstation pull request #2005
Opened 2020-08-30 22:37 UTC by j-awn

[CLEANLINESS]
## About the PR 
I changed the typepath of some chemical reagents to match the `reagent.id` field. Now every reagent's final typepath and 'id' should match. I also made THC and CBD lower-case, and changed `e.coli` to `ecoli`.

## Why's this needed? 

There were a lot of small differences, many of which seemed to not have any purpose. I also changed THC and CBD to not have all-caps chemical IDs and typepaths, which seemed like bad style; and E. Coli as well. 

## Changelog

N/A

2020-08-30 23:10 UTC, UrsulaMejor commented
Not sure if applicable, but just double checking that you've considered how changes in chem-ids might affect maps with hardcoded chem ids in instances; e.g., fluid spawners. Maybe some kinda regex would be cool to provide?

2020-08-31 00:59 UTC, j-awn commented
> Not sure if applicable, but just double checking that you've considered how changes in chem-ids might affect maps with hardcoded chem ids in instances; e.g., custom fluid spawners. Maybe some kinda regex would be cool to provide?

I hadn't considered that. I'd be a bit concerned if there was a custom fluid spawner for most, if not all of the chemicals I changed. E. Coli fluid spawners aren't custom, and those have been changed accordingly. Nothing on Z2 seems like it would be affected on first glance.

2020-08-31 04:46 UTC, Tarmunora commented
merger note: some secret content will need to be changed to match the new ids

2020-09-08 13:06 UTC, mordent-goonstation requested changes

2020-10-01 00:25 UTC, closed without merging