Common criteria for ejecting occupants from machines
goonstation/goonstation pull request #20104
Opened 2024-07-27 23:09 UTC by pgmzeta

[bug][game objects][player actions]
## About the PR 
Creates a common check for whether a mob can eject an occupant:
* Alive
* Not intangbile,
* Not ghost critters
* Not ghost drones
* Can act (i.e. not restrained/unconscious)

Applies to the `eject_occupant` verb on the following machines:
* port-a-brig
* clone scanner
* genetics scanner
* sleeper

## Why's this needed? 
Fix #20085

2024-07-27 23:35 UTC, JORJ949 commented
Does this change AI interaction, due to the eye being intangible

2024-07-28 19:11 UTC, pgmzeta commented
> Does this change AI interaction, due to the eye being intangible

only for the genetics scanner, and only for the verb itself

2024-07-28 22:33 UTC, TobleroneSwordfish requested changes

2024-07-28 22:33 UTC, TobleroneSwordfish commented on code/procs/gamehelpers.dm
> +	if (!isalive(user) || isintangible(user) || isghostcritter(user) || isghostdrone(user) || !can_act(user))
```suggestion
	if (isintangible(user) || isghostcritter(user) || isghostdrone(user) || !can_act(user))
```
Should be included in `can_act`

2024-07-28 22:33 UTC, TobleroneSwordfish commented on code/procs/gamehelpers.dm
> +	return TRUE
This could also just be a return rather than an `if`

2024-07-28 22:33 UTC, TobleroneSwordfish commented on code/procs/gamehelpers.dm
> +/proc/can_eject_occupant(mob/user)
Any reason this isn't on `/obj/machinery` or a more specific parent?

2024-07-31 10:48 UTC, merged