Make NTSC a roundstart job
goonstation/goonstation pull request #20147
Opened 2024-07-31 20:25 UTC by JORJ949

## About the PR 
Makes the Nanotrasen Security Consultant a roundstart job that doesn't require a Head of Security
Add counts_as logic to non-latejoin job assigner to account for the security officer slot it takes

## Why's this needed? 
With NTSC taking up an officer slot it is now essentially a different loadout for an officer, the gear is not as powerful as HoS and this just lets whitelisted players play as NTSC over HoS if they want to, removing the HoS from the round.

## Changelog 

```changelog
(u)JORJ949
(*)Nanotrasen Security Consultant is now a roundstart job
```

2024-07-31 20:39 UTC, Tarmunora commented
I see no reason to revert the changes made in #3331.

2024-07-31 20:41 UTC, JORJ949 commented
> I see no reason to revert the changes made in #3331.

I was unaware this was previously a roundstart role.

2024-07-31 20:52 UTC, Tarmunora requested changes

2024-07-31 20:52 UTC, Tarmunora commented on code/datums/jobs.dm
> -	requires_supervisor_job = "Head of Security"
Not against letting NTSC be chosen roundstart, but DNM unless supervisor requirement is re-implemented for roundstart roles and put back on the job datum.

2024-08-01 11:35 UTC, Glamurio commented
If you want to move this to roundstart only, you should probably change the description of the PR.

2024-08-01 13:19 UTC, JORJ949 commented
Done, will work on supervisor job at some point.

2024-08-06 05:07 UTC, JORJ949 commented
Closing due to both lack of confidence I could reimplement supervisor and I have changed my mind and think NTSC should remain latejoin (even though most NTSCs join immediately after roundstart)

2024-08-06 05:07 UTC, closed without merging