Showing off auth disk
goonstation/goonstation pull request #20179
Opened 2024-08-03 22:32 UTC by Valtsu0

[Object][Feature]
## About the PR 
![image](https://github.com/user-attachments/assets/71ac8ce0-2b49-4bc0-bd45-ce4b04bec052)
Adds showing off the authentication disk

## Changelog 

```changelog
(u)Valtsu0
(+)You can now also show off the authentication disk
```

2024-08-03 22:54 UTC, TobleroneSwordfish requested changes
Oof okay these actions badly need a common parent, I know the original PR kind of copy-pasted them but if we're going to make it apply to more things it needs to start using inheritance.

2024-08-04 16:41 UTC, Valtsu0 commented
Didn't end up using inheritance, but it's better now

2024-08-04 19:53 UTC, TobleroneSwordfish requested changes
Oh that's better, but the pixel offsets are slightly different between the item types so you'll have to either make subtypes or pass the offsets in `New` (probably the latter?)

2024-08-05 01:07 UTC, TobleroneSwordfish approved these changes

2024-08-05 18:05 UTC, Azrun commented on code/datums/actions/actions.dm
> +		src.user.dir = SOUTH
`set_dir()` or do so we need to bypass that for some reason?

2024-08-05 20:46 UTC, merged