Rework atlas post
goonstation/goonstation pull request #20269
Opened 2024-08-11 21:19 UTC by JORJ949

## About the PR 
Reworks atlas post a bit to add medical supplies
![image](https://github.com/user-attachments/assets/e40b0ac0-5c58-4806-aee9-537649bf05e9)

## Why's this needed? 
Listening posts should have medicine (even if its just donk pockets+medibot) and atlas had none, also a little landing pad is nice and some post gear was missing e.g. syndicate hologram module

2024-08-12 15:40 UTC, Cherman0 commented
Are those windows indestructable? Otherwise it would not be hard to break in. It could also use a light or two on that docking pad.

2024-08-12 17:44 UTC, TobleroneSwordfish commented
Not sure about the full medical area, most listening posts just have the donks and mayybe a medkit. Would make more sense to have a bunk area like the original I think, as this is meant to be a long term surveillance outpost.

2024-08-12 22:17 UTC, JORJ949 commented
> Are those windows indestructable? Otherwise it would not be hard to break in. It could also use a light or two on that docking pad.

Those are indestructable yes, and I have since added a light

2024-08-12 22:18 UTC, JORJ949 commented
> Not sure about the full medical area, most listening posts just have the donks and mayybe a medkit. Would make more sense to have a bunk area like the original I think, as this is meant to be a long term surveillance outpost.

If its long term, they need somewhere to shower (and eat pizza in the shower??? (idk why I did this))

2024-08-16 15:14 UTC, TobleroneSwordfish requested changes

2024-08-16 15:14 UTC, TobleroneSwordfish commented on maps/atlas.dmm
> +/obj/item/storage/firstaid/oxygen,
Again, this is a lot more medical supplies than any other listening post has (afaik). Try to keep them relatively standardized.

2024-09-05 19:27 UTC, merged