minor changes for kondaru science
goonstation/goonstation pull request #20311
Opened 2024-08-15 01:27 UTC by TheRyeGuyWhoWillNowDie

## About the PR 

goon3 is practically a 24/7 kondaru server, so these two tiny changes make science better

this adds a valve to the heat exchangers in toxins (allowing you to disable them) and changes the button that opens the requirement-less door to a button that toggles the outer pad shutters independently

## Why's this needed? 

solves annoyance with my inner nerd

## Changelog 

```changelog
(u)gus
(+)Added a valve to Kondaru toxins
(+)added an exterior shutters button to kondaru toxins
```

2024-08-15 18:06 UTC, TheTyrant25 approved these changes

2024-08-15 20:43 UTC, MyNameIsRomayne approved these changes
Tested changes, both work. Very nice

2024-08-15 23:09 UTC, TobleroneSwordfish requested changes
Minor thing but that valve is kind of overlapping the light fitting, can you move the light to one side or make it a floor light or something?

2024-08-18 21:08 UTC, TheRyeGuyWhoWillNowDie commented
> Minor thing but that valve is kind of overlapping the light fitting, can you move the light to one side or make it a floor light or something?

sure lol

2024-08-26 23:52 UTC, merged