Fixes player vending machines registering MechComp signals
goonstation/goonstation pull request #20484
Opened 2024-08-30 10:48 UTC by MetricDuck

[BUG] [GAME OBJECTS]
## About the PR 
Player vending machines, like all vending machines, are registered for the "Vend Random" and "Vend by Name" signals. These signals use procs that interact with the vending machines product_list. 

However, ppayer vending machines store their inventory in a player_list : the upshot is player vending machines can receive mechcomp signals but nothing will actually happen if they're triggered (as their product_list is always empty). 

This PR makes it so player vending machines aren't registered for the two MechComp signals.

## Why's this needed? 
Fixes #20362

2024-08-30 10:48 UTC, MetricDuck commented
![image](https://github.com/user-attachments/assets/a776b8c0-f3cb-421e-8e57-8f1aa810ab85)

2024-08-30 10:50 UTC, MetricDuck commented
A nicer long-term fix that could be pursued after the TGUI feature freeze could be to add a new button to the UI, much like the "Loading Chute" button, called "MechComp Enabled".

2024-09-05 20:10 UTC, TobleroneSwordfish requested changes
Better to make it a flag variable, ie `var/uses_mechcomp = TRUE` or an overridable proc, ie `proc/register_mechcomp()`
`istype(src, ...)` is code smell that makes things harder to maintain by hiding child functionality in the parent class.

2024-09-13 20:06 UTC, MetricDuck commented
> Better to make it a flag variable, ie `var/uses_mechcomp = TRUE` or an overridable proc, ie `proc/register_mechcomp()` `istype(src, ...)` is code smell that makes things harder to maintain by hiding child functionality in the parent class.

Makes sense!

2024-09-25 06:01 UTC, merged