More Carty Party Vend Qty
goonstation/goonstation pull request #2064
Opened 2020-09-05 00:58 UTC by MarkNais

[QoL]
## About the PR 
Adds more stock to the non-hidden Carty Party items. Generally doubled each line item.

## Why's this needed? 
An increase in the count of high-power flashlight modules was requested, and given the recent-ish darkness-buff, seems reasonable.
The rest I increased, because 2 cartridges-each seemed thematically unreasonably low for a vending machine.

I'd happily accept an argument that some numbers (like PDA stock count) should stay low to encourage restock-orders through QM.

## Changelog

```
(u)MarkNstein:
(+)CartyParty vends stock more high-power flashlight modules
```

2020-09-05 01:25 UTC, Sovexe commented
Unsure how I feel about adding even more network diagnostics carts

2020-09-05 01:31 UTC, MarkNais commented on code/modules/vending/vending.dm
> +		product_list += new/datum/data/vending_product(/obj/item/disk/data/cartridge/diagnostics, 5, cost=70)
```suggestion
		product_list += new/datum/data/vending_product(/obj/item/disk/data/cartridge/diagnostics, 2, cost=70)
```
manually revert line

2020-09-05 01:32 UTC, MarkNais commented
Back to 2

2020-09-08 02:28 UTC, flrsh approved these changes

2020-09-08 05:15 UTC, ZeWaka approved these changes

2020-09-09 05:45 UTC, UrsulaMejor requested changes

2020-09-09 05:45 UTC, UrsulaMejor commented on code/modules/vending/vending.dm
> +		product_list += new/datum/data/vending_product(/obj/item/disk/data/cartridge/mechanic, 5, cost=40)
The analysis made easy cartridge is just a cheaper and slightly better version of the networking cartridge. I recommend dumping it from this vendor. If you do, I'll merge this.

2020-09-09 08:20 UTC, merged