AI "Go offline" command to replace their brain with a latejoin one
goonstation/goonstation pull request #20658
Opened 2024-09-11 04:34 UTC by JORJ949

## About the PR 
Adds a command for AIs to use that ghosts them and replaces their brain with a latejoin one, announcing that they have done so to the crew.

Code probably sucks and I know the warning for doing this also sucks but im PRing this so you can tell me which bits suck

Credit to meaow589 (AKA: Tanuki Singuloose) on the forums for the idea https://forum.ss13.co/showthread.php?tid=23151

## Why's this needed? 
When an AI has to go it can be a pain to replace them or build a latejoin one, so much so that most crews dont bother, this provides an easy way for AI players to leave the game if they need to.

## Changelog 

```changelog
(u)JORJ949
(*) AIs now have a "Go Offline" command to replace themselves with a latejoin AI, announcing to the crew this has happened. 
```

2024-09-11 05:46 UTC, TobleroneSwordfish requested changes
Neat idea, makes sense.

2024-09-11 05:46 UTC, TobleroneSwordfish commented on code/mob/living/silicon/ai.dm
> +		src.mind.register_death()
Ghostize should remove the mind, so this should go above.

2024-09-11 05:46 UTC, TobleroneSwordfish commented on code/mob/living/silicon/ai.dm
> +		src.mind.assigned_role = "AI"
Not sure what this is doing, but again ghostize should have removed the mind by this point

2024-09-11 05:46 UTC, TobleroneSwordfish commented on code/mob/living/silicon/ai.dm
> +		command_alert("Station AI unit malfunction detected, attempting download of new mind from Central Command database.","Artificial Intelligence Update", alert_origin = ALERT_STATION)
```suggestion
		command_alert("Station AI unit [pick("crash", "kernel panic", "unrecoverable error")] detected, attempting automated download of new personality from Central Command database...","Artificial Intelligence Update", alert_origin = ALERT_STATION)
```
"Malfunction" can mean something very different in the context of AIs...

2024-09-11 05:46 UTC, TobleroneSwordfish commented on code/mob/living/silicon/ai.dm
> +	var/confirm = tgui_alert(message_mob, "Become a ghost and permanently replace yourself with a latejoinable AI? (WARNING: YOU CANNOT BE LAWED TO DO THIS AND YOU CANNOT BE REVIVED.)", "Permanently Sui
```suggestion
	var/confirm = tgui_alert(message_mob, "Become a ghost and allow other players to join into your core? (WARNING: YOU CANNOT BE LAWED OR ORDERED TO DO THIS AND YOU CANNOT BE REVIVED.)", "Permanently Shut Down?", list("Yes", "Cancel"))
```

2024-09-11 17:43 UTC, Glamurio commented
This is such a scuffed solution, I realize that there's no better way to go about it, but I just find it amusing.

2024-09-12 00:07 UTC, Tarmunora approved these changes

2024-09-12 18:17 UTC, merged

2024-09-18 13:35 UTC, FronkyGeniuZ commented
hey it me tanuki thank for PR this appricate alot !