Cleaning up some of the hardcoded lists to much
goonstation/goonstation pull request #20770
Opened 2024-09-20 18:14 UTC by Loaded4Bears

cleaner concrete_typesof

Attempting to clean up some hardcoded lists that can be easily simplified, expanded the cola and booze spawner, fixed icon for the pizza and cola spawners.

## Why's this needed? 

Toooo many hardcoded lists

2024-09-20 18:25 UTC, JORJ949 requested changes
If I understand concrete_typesof properly then this removes and adds stuff to these spawners, such as syndicate tables, old medkits and various other things. Probably best leaving these as lists so you dont end up with /obj/item/clothing/mask/gas/swat/syndicate in an otherwise clean random gimmick mask spawner, or any /obj/item/reagent_containers/food/drinks/bottle/poison_that_instagibs_everything (example) in a random booze spawner.

2024-09-20 18:25 UTC, JORJ949 commented on code/obj/random_spawners.dm
> -						/obj/item/aiModule/experimental/historic)
Outdated.

2024-09-20 18:55 UTC, Loaded4Bears reviewed
Reverted the first aid kits, masks, shoes, guardbot tools. 

Mines should be ok, pizza looks ok, the 'bad' booze is under /food/drinks and the 'regular shelf' stuff is under food/drinks/bottle.

Furniture parts and gimmick clothing doesn't seem to have anything traitor/secret/OP

2024-09-20 21:00 UTC, Glamurio requested changes
Always happy for refactoring, however this isn't a simple refactor, you're changing a lot of core functionality of some spawners. For some of them that's fine, but for some others that would really change their function.

Also, `SpaceStop.dmm` is a new prefab, please atomize this PR and make a separate one for the map or the cleanup, but not both at once.

2024-09-20 21:30 UTC, JORJ949 commented
> 
> Furniture parts and gimmick clothing doesn't seem to have anything traitor/secret/OP

You should also consider future items that could be added there, I think the set list or a var as to "do i spawn in random spawner" (like how surplus crates work) would be better than just anything of this type.

2024-09-21 02:32 UTC, Loaded4Bears reviewed
didn't mean to include the new map, i'll close this entire pull and come back for a  2nd try.

2024-09-21 02:32 UTC, closed without merging