Add WA-V3 QoL stuff (Wrench, Size)
goonstation/goonstation pull request #20804
Opened 2024-09-22 23:47 UTC by Glamurio

[QoL] [Game Objects]

## About the PR 
Sets the size of  `/obj/item/gun/sprayer` to `W_CLASS_POCKET_SIZED` and the same for the contents of `/obj/item/reagent_containers/glass/backtank`.

Adds `/obj/item/wrench/purple` and puts it in "WA-V3 Crate" as well as the JaniTech Vendor.

## Why's this needed? 
It's odd that the sprayer for the backtank doesn't fit inside the backtank, you'd think that'd be the one item to fit in there. I was trying to meet both of them in the middle to not make the backtank too big or the sprayer too small, and I think this should be fine. Was trying to avoid coding a specific exception for the sprayer, but will do that if it's preferred.

Now that Janitors have a semi-dedicated piece of equipment that requires a wrench, I think it's fine to give them a special wrench that comes prepackaged with the set. Doctors get to have a crowbar, so Janitors get to have a wrench.

## Changelog 

```changelog
(u)Glamurio (Ryou)
(+)JaniTech Vendors now stock wrenches of the purple variety.
```

2024-09-23 03:42 UTC, Tarmunora requested changes

2024-09-23 03:42 UTC, Tarmunora commented on code/obj/item/mops_cleaners.dm
> +		src.create_storage(/datum/storage, max_wclass = W_CLASS_POCKET_SIZED, slots = 3, opens_if_worn = TRUE)
Explicit check for the sprayer type is conveniently supported by storage datums
```suggestion
		src.create_storage(/datum/storage, can_hold = list(/obj/item/gun/sprayer), check_wclass = TRUE, max_wclass = W_CLASS_SMALL, slots = 3, opens_if_worn = TRUE)
```

2024-09-23 19:51 UTC, TobleroneSwordfish reviewed
Ehh not huge on either of these changes honestly. It seems kind of unnecessary to give janitors a stock of wrenches for a niche use of a thing they have to go out and buy anyway, and the sprayer not fitting in the tank storage is intentional - it's meant to be a tiny little pouch for Misc Gubbins that you get as compensation for not having a backpack.

2024-09-24 23:05 UTC, Tarmunora commented
> Ehh not huge on either of these changes honestly. It seems kind of unnecessary to give janitors a stock of wrenches for a niche use of a thing they have to go out and buy anyway, and the sprayer not fitting in the tank storage is intentional - it's meant to be a tiny little pouch for Misc Gubbins that you get as compensation for not having a backpack.

closing per above

2024-09-24 23:05 UTC, closed without merging