Access implant for admin mice
goonstation/goonstation pull request #20826
Opened 2024-09-23 14:48 UTC by flappybatpal

## About the PR 
Gives admin mice a new infinite implant equivalent to HoS and Centcom.
As far as I can see in testing implants don't drop and can't be removed from critters.

## Why's this needed? 
Admin mice couldn't interact with everything, particularly consoles.
They still have issues with things requiring ID cards but such is life when you are a small amaranth rodent.

2024-09-23 14:57 UTC, JORJ949 commented
Reminder that HoS doesnt have AA anymore, so for example no interacting with QM consoles.

2024-09-23 15:19 UTC, flappybatpal commented
> Reminder that HoS doesnt have AA anymore, so for example no interacting with QM consoles.

Stupid HoS!

2024-09-24 04:00 UTC, ZeWaka requested changes

2024-09-24 04:00 UTC, ZeWaka commented on code/obj/item/implant.dm
> +				access.access = get_access("Captain") + get_access("Head of Security") + access_centcom
```suggestion
				access.access = get_access("Admin")
```
https://github.com/goonstation/goonstation/commit/cb56bec537e2338001f4f6a5ff7f33a2ff86d5b5

2024-09-24 16:53 UTC, merged