Jailbird trait sends wanted posters to all printers
goonstation/goonstation pull request #20876
Opened 2024-09-27 03:37 UTC by pgmzeta

[FEATURE][REWORK][TRAITS]
## About the PR 
* Joining the round as a jailbird causes a wanted poster to be printed at all printers
* Remove the special arrest status interaction between stowaway and jailbird (and removes the stowaway trait)

## Why's this needed? 
* Limit special casing/interaction between jailbird trait and stowaway job to on join, instead of having to keep track on all security scanners
* Allows more crew have a chance to interact with jailbirds about their trait choice.
* Idea taken from a forum thread here: https://forum.ss13.co/showthread.php?tid=23217

## Screenshot
TBA

## Changelog 

```changelog
(u)glowbold
(+)Joining the round as a jailbird prints a wanted poster at all printers. Keep an eye out!
```

2024-09-27 16:42 UTC, 444Portal commented
this is amazing

2024-09-27 17:16 UTC, flrsh commented
Good PR. Still not a fan of jailbird in general, but I very much appreciate trying to make it better and more interactive.

2024-09-27 17:18 UTC, flrsh approved these changes

2024-09-27 19:02 UTC, TobleroneSwordfish requested changes
Won't the removal of the stowaway interactions mean that jailbird stowaways won't have arrest status at all?

2024-09-29 06:11 UTC, pgmzeta commented
> Won't the removal of the stowaway interactions mean that jailbird stowaways won't have arrest status at all?

thought about this a bit and while the original intent was to replace the jailbird&stowaway special-casing for arrest status with just a poster, I've just added it back in because I couldn't justify removing it. It's still a weird interaction, but the poster should hopefully be enough of a way to clue security into what's going on with Rando McArrestme without giving them a full record.

2024-09-29 06:36 UTC, pgmzeta commented
> making it print out on ALL Printers may lead to a bit of spam. Why not pick something like 10 random printer on station Z level and make only these print out the posters?
> 
> Overall, i like this PR.

Limited the printing to station Z, and did a check on how many printers each station has.

| Map | Printer Ct. |
| ------------- | ------------- |
| Atlas | 3 |
| Clarion | 10 |

| Clarion | 10 |

| Clarion | 10 |

| Clarion | 10 |

2024-09-30 20:28 UTC, MintyPhresh commented
Jailbird Stowaways should probably just get their own sec record (possibly missing stuff like fingerprints and blood ID) so that they have crimes and arrest status. Could have a couple not-real sec records so that Central doesn't magically know which wanted stowaways are stowing away

2024-10-02 18:48 UTC, TobleroneSwordfish commented
I'm going to just merge this for now, might be cool to do the fake record entries at some point but that can be a separate PR since this one is now maintaining the current behaviour.

2024-10-02 18:48 UTC, merged