Radioactive Farts
goonstation/goonstation pull request #20943
Opened 2024-10-02 18:37 UTC by amylizzle

## About the PR 
Adds a gene combo: farty + radioactive = radioactive farts

Makes your farts do a little toot of fallout gas :radioactive: 

## Why's this needed? 
I just thought it'd be kinda funny tbh.

## Changelog 

```changelog
(u)Amylizzle
(+)Adds a new gene combination: Radioactive + Farty 
```

2024-10-02 18:50 UTC, TobleroneSwordfish requested changes
Amy type PR 🙈

2024-10-02 18:50 UTC, TobleroneSwordfish commented on code/modules/medical/genetics/combo_recipes.dm
> +	result = /datum/bioEffect/reversedSounds
```suggestion
	result = /datum/bioEffect/radioactive_farts
```

2024-10-02 18:53 UTC, amylizzle commented
I am very tired

2024-10-03 01:39 UTC, TobleroneSwordfish approved these changes

2024-10-04 06:59 UTC, merged