The Return of Digbot
goonstation/goonstation pull request #2100
Opened 2020-09-07 10:27 UTC by MarkNais

## About the PR 
Revives digbot — a once removed, now restored and polished fab/craftable robot that mines rocks. It can be turned off and on, told to mine or avoid suspicious rocks (object, gem, etc), and told to target a threshold of hardness. 

Animations have been added, there's unique build-step sprites, it has a tiny-blue tooltip UI instead of a chatlog UI, it points to each rock it targets, and it makes a small clang whenever it's deactivated (as it's hover drive shuts off)

Credits:
Original base sprite ???
New animations & overlays - The Gorog - https://github.com/TheGorog

## Why's this needed? 
Helpful to miners, and adds another cute robot to the game.
@UrsulaMejor told me too, and many people were excited for it's return.

## Changelog

```
(u)MarkNstein:
(*)Digbot revived: a bot for miners. Craftable and has a blueprint in robotics and mining fabs.
```
[FEATURE]
![bKMBbaBltI](https://user-images.githubusercontent.com/9563541/92377878-b258c700-f0b9-11ea-9ffd-e30fb5f2539f.gif)
![Oijo4TVCXA](https://user-images.githubusercontent.com/9563541/92377886-b4bb2100-f0b9-11ea-8d1f-eb086d5ab90a.gif) ![dreamseeker_TZ9hLr53Pl](https://user-images.githubusercontent.com/9563541/92377895-b8e73e80-f0b9-11ea-8862-53957162794c.png) ![dreamseeker_3NyTSMSfVR](https://user-images.githubusercontent.com/9563541/92377898-bb499880-f0b9-11ea-91a3-7378f2b6373e.png) ![dreamseeker_vluVQBXodc](https://user-images.githubusercontent.com/9563541/92377903-be448900-f0b9-11ea-861c-f1d95d71e950.png)

2020-09-07 10:33 UTC, MarkNais commented
I forgot to reimplement behavior locking in the UI change — But also, not sure if I care to reimplement it, since it's not "dangerous" (it can't trigger explosive-asteroids AFAIK, since it's not a mob). 
I'll likely trim the "access" code next time I'm awake and coding.

2020-09-07 16:32 UTC, UrsulaMejor commented
ARISE, DIGBOT

2020-09-07 17:13 UTC, UrsulaMejor requested changes

2020-09-07 17:13 UTC, UrsulaMejor commented on code/modules/robotics/bot/mining.dm
> +				new /obj/machinery/bot/mining/drill(user.loc)
why not get_turf(src)? See my other comment on this

2020-09-07 17:13 UTC, UrsulaMejor commented on code/obj/item/clothing/helmets.dm
> +			new /obj/item/digbotassembly(get_turf(user))
why not get_turf(src)? This kinda awkwardly moves it to your tile if you're mass producing digbot assemblies on the floor

2020-09-08 02:10 UTC, MarkNais commented on code/obj/item/clothing/helmets.dm
> +	attackby(var/obj/item/T, mob/user as mob)
Ultimately I don't care, but I've added a type check to make it hardhats only.

2020-09-08 02:39 UTC, MarkNais commented
Recent changes tested, still craftable, and now operates slightly faster.

2020-09-08 11:30 UTC, Gannets commented
I think digbot could benefit from a full resprite in the future, but this is great for now!

2020-09-09 05:06 UTC, UrsulaMejor approved these changes

2020-09-09 05:08 UTC, UrsulaMejor commented
Mark said he tested it and that's good enough for me!

**RISE, DIGBOT.**

2020-09-09 05:08 UTC, merged