Adds the "atheist" trait
goonstation/goonstation pull request #2108
Opened 2020-09-08 03:05 UTC by monochromatism

## About the PR 

Adds a new trait, "atheist", that affects how you interact with prayer and chaplains. Namely:

- Prayer is disabled, yielding nonthreatening oxygen damage.
- Bible-based healing automatically fails, but the brain damage from this failure is halved for fairness.
- Holy water-based brain damage healing fails as well.
- Player cannot biblefart.

## Why's this needed? 

It's funny and flavorful.

## Changelog
(+) Added the "atheist" trait. No more faith healing for you!

2020-09-08 05:13 UTC, ZeWaka requested changes
Please fix your changelog format.

2020-09-08 05:13 UTC, ZeWaka commented on code/datums/traits.dm
> +	cleanName="Atheist"
```suggestion
	cleanName = "Atheist"
```
please be consistent

2020-09-08 05:13 UTC, ZeWaka commented on code/modules/chemistry/Reagents-Base.dm
> +						if (M?.traitHolder?.hasTrait("atheist"))
```suggestion
						if (M.traitHolder?.hasTrait("atheist"))
```
not needed to check, already done above

2020-09-08 05:13 UTC, ZeWaka commented on code/obj/item/storage/bible.dm
> +			if ((ishuman(H) && prob(60) && !(M?.traitHolder?.hasTrait("atheist"))))
```suggestion
			if ((ishuman(H) && prob(60) && !(M.traitHolder?.hasTrait("atheist"))))
```
already done

2020-09-08 05:13 UTC, ZeWaka commented on code/obj/item/storage/bible.dm
> +					if (M?.traitHolder?.hasTrait("atheist"))
```suggestion
					if (M.traitHolder?.hasTrait("atheist"))
```
already done

2020-09-08 05:13 UTC, ZeWaka commented on code/obj/item/storage/bible.dm
> +		if (user?.traitHolder?.hasTrait("atheist"))
```suggestion
		if (user.traitHolder?.hasTrait("atheist"))
```
already done

2020-09-08 05:13 UTC, ZeWaka commented on code/obj/item/storage/bible.dm
> +			return
return a value

2020-09-08 11:00 UTC, Gannets commented
Funny little flavour trait, I'd probably pick this on some characters. 👍

2020-09-08 13:12 UTC, mordent-goonstation commented
As I sometimes encourage players to use `pray` to talk to me (as an admin) about some in-round stuff (e.g. if they're running a gimmick and I'm trying to ask them questions about how to spice it up), if they have to resort to adminhelps because they can't use `pray` that sucks.

2020-09-08 22:42 UTC, monochromatism commented
Oops. I hadn't really considered that. I haven't had an admin help me with spicing up my gimmicks in months. Maybe allowing atheists to pray after a few failed attempts, along with a message about feeling ridiculous, would be alright then?

2020-09-08 23:49 UTC, Tarmunora commented
I think just letting the prayer go through, along with a funny message to the player, would suffice

2020-09-09 01:14 UTC, monochromatism commented
Now it tells you you feel silly when praying. Trait description altered accordingly.

2020-09-09 10:29 UTC, pali6 commented
Maybe it could show the admins something like `PRAYER (atheist): ...` so we can ignore / poke fun at the person appropriately.

2020-09-09 17:20 UTC, monochromatism commented
Good idea. Added.

2020-09-09 23:11 UTC, pali6 approved these changes
I wonder if resistance to biblefarts might be too powerful for a trait but we'll see.

2020-09-09 23:15 UTC, Tiggersaurus commented
Brown note spammers for one ...

2020-09-10 00:14 UTC, Tarmunora approved these changes
Doesn't look like it affects brown note at all - atheists forcing people to fart on the bible will still gib the atheist (a good thing)

2020-09-12 08:26 UTC, merged