Robot artifacts
goonstation/goonstation pull request #21384
Opened 2024-11-21 18:14 UTC by amylizzle

## About the PR 
Adds a new artifact type: Automatons

Intended for the clockwork artifacts (#21375), but also ancient origin.

When activated, the artifacts become robot mobs that do one of a few things:

- wandering
- smashing walls
- replacing floors with a randomly chosen type
- placing walls on empty floors (not space)
- attacking people

## Why's this needed? 
It's a base for an artifact type that fits with the clockwork theme

## Changelog 

```changelog
(u)Amylizzle
(*)Adds a new artifact type: Automatons
```

2024-11-21 21:16 UTC, TobleroneSwordfish requested changes
Woe, `New` argument inheritance: 
![image](https://github.com/user-attachments/assets/22c69a5a-9c46-44f2-938b-f7865f75b568)

Ordering issue on death gib:
![image](https://github.com/user-attachments/assets/fa9f6344-e24b-4acd-bcc3-48f3cc0c4c7b)

Maybe the robot mobs should have brullbar-like stamina stun immunity, it looks weird to see an artifact get stamina crit with a chair.

Not sure if this an artifact of the init runtimes but they currently seem to pick a new AI each time they're activated/deactivated, ideally I think that should be persistent.

2024-11-21 21:16 UTC, TobleroneSwordfish commented on code/mob/living/critter/ai/artifact_robot.dm
> +	for(var/turf/simulated/wall/W in view(src.max_dist, src.holder.owner))
Make it target girders too so it does actual deconstruction?

2024-11-22 11:07 UTC, amylizzle commented on code/obj/artifacts/artifact_machines/robot.dm
> +	var/static/list/turf/floor_types = list(/turf/simulated/floor/industrial, /turf/simulated/floor/mauxite, /turf/simulated/floor/circuit/vintage, /turf/simulated/floor/glassblock/transparent, /turf/si
huh it does not.

additional opendream bug discovered :laughing:

2024-11-22 11:58 UTC, amylizzle commented
Ah it was supposed to be persistent ai types but I accidentally left some debug code in place. Fixed now.

2024-11-28 07:16 UTC, TobleroneSwordfish requested changes
The actionbars and sounds are great, I love watching them fight each other over walls.
- The mauxite floors don't seem to be changing the floor texture? I swear they were before but 🤷 
- New runtime:
![image](https://github.com/user-attachments/assets/29f4e64d-f734-4d2b-91fd-bcb8a38840ac)
Occurs on artifact activation, seems like the `huds` list is an instance.

2024-11-28 23:44 UTC, merged