Add medals for older azones
goonstation/goonstation pull request #21457
Opened 2024-11-26 17:52 UTC by FlameArrow57

[MEDAL][FEATURE]

## About the PR 
Adds some medals for older azones that didn't have medals tied to them in any way. Ones added for ice moon, lava moon, mars, and ainlee

These are all secret on the Byond website, not visible before earning

1.
Name: To the Moon!
Pic:
![lunar](https://github.com/user-attachments/assets/dde3bf60-479e-4552-95f6-dff65cf41ae1)
Desc: Visit the Lunar Museum

2.
Name: Where are the Ghosts?
Pic:
![mars](https://github.com/user-attachments/assets/ba3ddef4-a477-4c81-a90d-d924a7860bc2)
Desc: Discover what the Mars facility holds

3.
Name: What's Buried Stays Buried
Pic:
![lavamoon](https://github.com/user-attachments/assets/bbd455d5-9955-4c78-bbb4-30246103738a)
Desc: Bury something on Io

4.
Name: Ice Cold
Pic:
![icemoon](https://github.com/user-attachments/assets/c2cf6eb6-25fa-44f5-8701-b7536b600c2c)
Desc: Solve an old puzzle on Senex

5.
Name: I HATE Hospitals
Pic: 
![ainlee](https://github.com/user-attachments/assets/683cbc35-a23a-4ef6-8bf1-3f82f108f361)
Desc: Survive the horror of Ainlee Asylum

## Why's this needed? 
Either fun (lunar museum) or medal worthy

## Changelog 

```changelog
(u)FlameArrow57
(*)Added a medal for completing a certain task in each of Lunar Museum, Mars, Lava moon, Ice moon, and Ainlee Asylum.
```

2024-11-26 18:30 UTC, 444Portal commented
To the moon already exists and is tied to a specific thing on lunar, no?

2024-11-26 18:35 UTC, FlameArrow57 commented
> To the moon already exists and is tied to a specific thing on lunar, no?

There may be, I couldn't find it

2024-11-26 19:09 UTC, Tarmunora requested changes
> To the moon already exists and is tied to a specific thing on lunar, no?

`code/z_adventurezones/luna.dm:733`

2024-11-28 04:59 UTC, ZeWaka approved these changes

2024-11-28 06:07 UTC, merged