Replace a ton of manual checks with can_act calls
goonstation/goonstation pull request #2155
Opened 2020-09-11 15:25 UTC by BatElite

[cleanliness]
## About the PR 
A lot of things in a lot of places do checks that amount (or should/nearly amount) to calling ```can_act```.  This PR makes them use ```can_act``` instead. Did you know that there were 24 results for searching "can_act(" previously (including the proc definition)? This PR bumps that up to 230.

The third commit focuses on all the checks that are incomplete compared to what ```can_act``` does. Often these don't check one of the status effects, or they don't have an isalive/stat check. I've tried to only replace those that made sense.

Whoever will review this might notice that there's several copies of near-identical procs being poked. Moving those to later . I've also not fixed the galaxybraining going on in frenzy.dm that stuns the user and then immediately aborts because the user is stunned.

misc notes:
-Some of the files poked are adventure zone stuff. I'm pretty sure none of them should be meaningfully altered.
-I've tested it a bit and the whole thing compiles without any issues, but I don't know how I'd check everything in here.
-Not all of this stuff might actually be in use.

## Why's this needed? 
Cleeeen code, at least somewhat. 

At least one check was partially borked, and a good number of places weren't checking everything they should.
(Maybe can_act should check for pinning too, but that's for another PR)

2020-09-11 15:55 UTC, BatElite commented on code/obj/item/clothing/injector_mask_belt.dm
> +		if(!can_act(M, 0)) return 1
I want to point out that as it is the new code will trigger on death when the old one didn't, but I don't expect it to be an important difference. Dying without going unconscious first is somewhat of a tall order anyway.

2020-09-11 16:20 UTC, Tarmunora commented
Haven't read through yet, but I'd be concerned about explicit checks for paralyzed/KOed being changed to include stunned/weakened. Stuff like talking and table-surgery comes to mind

2020-09-11 16:21 UTC, Tarmunora commented on code/modules/medical/surgery_procs.dm
> +	else if (locate(/obj/table, patient.loc) && !can_act(patient, 0)) // is the patient on a table and incapacitated or dead?
Note: this allows table surgery on stunned but not KOed people

2020-09-11 16:24 UTC, Tarmunora commented on code/obj/critter/bee.dm
> +			if (!can_act(M, 0))
Similarly here (and throughout this file) we have 'is-asleep' checks being changed to 'is-stunned'

2020-09-11 16:36 UTC, Tarmunora requested changes
A number more places where checks for only stat/paralysis (i.e.: mob is knocked out) are replaced with can_act. Some might be fine as can_act, but others should not be changed to can_act, notably the hearing/sight checks and table surgery.

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item.dm
> +	if (!can_act(usr, 1) || !can_reach(usr, src) || usr.sleeping || usr.lying || isAIeye(usr) || isAI(usr) || isrobot(usr) || isghostcritter(usr) || (over_object && over_object.event_handler_flags & NO_
Mechanical change here

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item/brain.dm
> +	if(!(locate(/obj/machinery/optable, M.loc) && M.lying) && !(locate(/obj/table, M.loc) && !can_act(M, 0)))
table surgery check again

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item/chem_pill_bottle.dm
> +		if (!can_act(user, 1) || user.sleeping || user.lying)
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item/clothing/gimmick.dm
> +			if (istype(H.w_uniform, /obj/item/clothing/under/gimmick/owl) && can_act(user, 0))
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item/generic_box.dm
> +		if (!can_act(user, 1) || user.sleeping || user.lying)
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item/gun/kinetic.dm
> +		if (!can_act(usr, 1) || !can_reach(usr, src) || usr.sleeping || usr.lying || isAIeye(usr) || isAI(usr) || isghostcritter(usr))
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item/misc_wizard_stuff.dm
> +	if (!can_act(usr, 1))
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/item/tool/weldingtool.dm
> +					if (!(locate(/obj/machinery/optable, M.loc) && M.lying) && !(locate(/obj/table, M.loc) && !can_act(M, 0)) && !(M.reagents && M.reagents.get_reagent_amount("ethanol") > 10 && M == user))
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/mopbucket.dm
> +	if (!in_range(user, src) || !can_act(user, 1) || user.sleeping || user.lying || user.buckled)
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/rack.dm
> +	if (!isitem(O) || !in_range(user, src) || !in_range(user, O) || !can_act(user, 1) || user.sleeping || user.lying)
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/storage/large_storage_parent.dm
> +		if (!in_range(user, src) || !in_range(user, O) || !can_act(user, 1) || user.sleeping || user.lying || isAI(user))
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/obj/table.dm
> +		if (!in_range(user, src) || !in_range(user, O) || !can_act(user, 1) || user.sleeping || user.lying)
mechanical change

2020-09-11 16:36 UTC, Tarmunora commented on code/procs/mob_procs.dm
> +	if (consciousness_check && (!can_act(src, 0) || src.sleeping || src.hibernating))
Being stunned should not blind

2020-09-11 16:36 UTC, Tarmunora commented on code/procs/mob_procs.dm
> +	if (consciousness_check && (!can_act(src, 0) || src.sleeping))
being stunned should not blind

2020-09-11 16:36 UTC, Tarmunora commented on code/procs/mob_procs.dm
> +	if (consciousness_check && (!can_act(src, 0) || src.sleeping))
being stunned should not deafen

2020-09-11 16:36 UTC, Tarmunora commented on code/procs/mob_procs.dm
> +	if (consciousness_check && (!can_act(src, 0) || src.sleeping))
being stunned should not deafen

2020-10-06 23:47 UTC, BatElite commented
I was going to revert the surgery-related checks so there was something happening in this PR (and then look at the other cases individually) but now I'm not so sure - can_act does a ```stat``` check, so if that's how being asleep is checked then shouldn't surgery be fine? I've done surgery on a monkey with N2O internals on this branch earlier and that worked.

Maybe weakened and stunned aren't necessarily appropriate in that case, I more or less reasoned that "unable to take any actions" included being a problem for a surgeon. :P 

(Will look into the blinding & bee checks though, tomorrow)

2020-10-12 07:44 UTC, Tarmunora requested changes

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/HaineWhatever.dm
> +		if (!the_mob || !can_act(the_mob, 0))
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/cryospawn.dm
> +		if (user && (!can_act(user, 1) || user.sleeping))
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/tug.dm
> +		if (!in_range(user, src) || !in_range(user, C) || !can_act(user, 1) || user.sleeping || user.lying)
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/tug.dm
> +		if (!user || !(in_range(user, src) || user.loc == src) || !in_range(src, over_object) || !can_act(user, 1) || user.sleeping || user.lying)
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/tug.dm
> +		if (!in_range(user, src) || !in_range(user, C) || !can_act(user, 1) || user.sleeping || user.lying)
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/misc/hunter_gearspawn.dm
> -		if (M == null || !ishuman(M) || !isalive(M) || M.getStatusDuration("paralysis") > 0 || !transform)
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/misc/werewolf_transform.dm
> -		if (M == null || !ishuman(M) || !isalive(M) || M.getStatusDuration("paralysis") > 0 || !transform)
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/werewolf/werewolf_transform.dm
> -		if (M == null || !ishuman(M) || M.stat != 0 || M.getStatusDuration("paralysis") || !transform)
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/wizard/phaseshift.dm
> +	if (!can_act(H, 0))
***critical mechanical change***

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/wizard/teleport.dm
> -	if (src.getStatusDuration("paralysis") || !isalive(src))
***critical mechanical change***

2020-10-12 07:44 UTC, Tarmunora commented on code/mob/melee_attack_procs.dm
> +	if (ignoreStuns || can_act(src, 0))
mechanical change - this was specifically changed in past from stun+weak+para check to just para

2020-10-12 07:44 UTC, Tarmunora commented on code/modules/antagonists/changeling/abilities/changeling.dm
> +		return !can_act(M, 0)
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/critter/bee.dm
> +		if (!can_act(M, 0))
mechanical change

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/uplinks.dm
> +//#define CHECK2 (usr.getStatusDuration("stunned") > 0 || usr.getStatusDuration("weakened") || usr.getStatusDuration("paralysis") > 0 || !isalive(usr) || usr.restrained())
excise

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/uplinks.dm
> +//#undef CHECK2
excise

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/cryospawn.dm
> +		if (user && (!can_act(user, 1) || user.sleeping))
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/HaineWhatever.dm
> +		if (!the_mob || !can_act(the_mob, 0))
revert or justify

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/tug.dm
> +		if (!in_range(user, src) || !in_range(user, C) || !can_act(user, 1) || user.sleeping || user.lying)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/tug.dm
> +		if (!user || !(in_range(user, src) || user.loc == src) || !in_range(src, over_object) || !can_act(user, 1) || user.sleeping || user.lying)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/WorkInProgress/tug.dm
> +		if (!in_range(user, src) || !in_range(user, C) || !can_act(user, 1) || user.sleeping || user.lying)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/misc/hunter_gearspawn.dm
> -		if (M == null || !ishuman(M) || !isalive(M) || M.getStatusDuration("paralysis") > 0 || !transform)
probably doesn't matter, they can do this in a closet in maint anyways

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/misc/werewolf_transform.dm
> -		if (M == null || !ishuman(M) || !isalive(M) || M.getStatusDuration("paralysis") > 0 || !transform)
revert or justify

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/werewolf/werewolf_transform.dm
> -		if (M == null || !ishuman(M) || M.stat != 0 || M.getStatusDuration("paralysis") || !transform)
revert or justify

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/wizard/phaseshift.dm
> +	if (!can_act(H, 0))
revert

2020-10-12 07:44 UTC, Tarmunora commented on code/datums/abilities/wizard/teleport.dm
> -	if (src.getStatusDuration("paralysis") || !isalive(src))
revert

2020-10-12 07:44 UTC, Tarmunora commented on code/mob/melee_attack_procs.dm
> +	if (ignoreStuns || can_act(src, 0))
revert

2020-10-12 07:44 UTC, Tarmunora commented on code/modules/antagonists/changeling/abilities/changeling.dm
> +		return !can_act(M, 0)
revert or justify

2020-10-12 07:44 UTC, Tarmunora commented on code/modules/medical/surgery_procs.dm
> +	else if (locate(/obj/table, patient.loc) && !can_act(patient, 0)) // is the patient on a table and incapacitated or dead?
revert

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/critter/bee.dm
> +		if (!can_act(M, 0))
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item.dm
> +	if (!can_act(usr, 1) || !can_reach(usr, src) || usr.sleeping || usr.lying || isAIeye(usr) || isAI(usr) || isrobot(usr) || isghostcritter(usr) || (over_object && over_object.event_handler_flags & NO_
test this. PDAs etc should still be usable when stunned but not paralyzed by clickdragging to self I think - does this break that functionality?

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/brain.dm
> +	if(!(locate(/obj/machinery/optable, M.loc) && M.lying) && !(locate(/obj/table, M.loc) && !can_act(M, 0)))
Revert

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/chem_pill_bottle.dm
> +		if (!can_act(user, 1) || user.sleeping || user.lying)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/clothing/gimmick.dm
> +			if (istype(H.w_uniform, /obj/item/clothing/under/gimmick/owl) && can_act(user, 0))
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/generic_box.dm
> +		if (!can_act(user, 1) || user.sleeping || user.lying)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/gun/kinetic.dm
> +		if (!can_act(usr, 1) || !can_reach(usr, src) || usr.sleeping || usr.lying || isAIeye(usr) || isAI(usr) || isghostcritter(usr))
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/misc_wizard_stuff.dm
> +	if (!can_act(usr, 1))
revert or justify

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/item/tool/weldingtool.dm
> +					if (!(locate(/obj/machinery/optable, M.loc) && M.lying) && !(locate(/obj/table, M.loc) && !can_act(M, 0)) && !(M.reagents && M.reagents.get_reagent_amount("ethanol") > 10 && M == user))
surgery check, revert

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/mopbucket.dm
> +	if (!in_range(user, src) || !can_act(user, 1) || user.sleeping || user.lying || user.buckled)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/rack.dm
> +	if (!isitem(O) || !in_range(user, src) || !in_range(user, O) || !can_act(user, 1) || user.sleeping || user.lying)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/storage/large_storage_parent.dm
> +		if (!in_range(user, src) || !in_range(user, O) || !can_act(user, 1) || user.sleeping || user.lying || isAI(user))
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/obj/table.dm
> +		if (!in_range(user, src) || !in_range(user, O) || !can_act(user, 1) || user.sleeping || user.lying)
probably doesn't matter

2020-10-12 07:44 UTC, Tarmunora commented on code/z_adventurezones/lavamoon.dm
> +		if (!can_act(M, 0))
probably doesn't matter

2020-10-12 07:52 UTC, Tarmunora commented
re surgery checks: that would let you debrain someone with a flash/stunbaton/taser, which can only end poorly imo
wizard phaseshift/teleport: I'm going to need serious convincing that preventing wizards from using their get-me-out-of-heres while stunned is a good idea
changeling powers / ww transform: similar concerns to above

2021-06-18 23:14 UTC, BatElite commented
This branch is so far behind (IIRC months ago some tooling changes made it really annoying) that this PR is never getting updated.

May revisit the idea sometime, but do it in chunks rather than all at once.

2021-06-18 23:14 UTC, closed without merging