Space phoenix antagonist
goonstation/goonstation pull request #21597
Opened 2024-12-07 17:47 UTC by FlameArrow57

[GAME MODES][FEATURE]

## About the PR 
This PR is working draft for a new antagonist, the Space Phoenix

Design doc - https://hackmd.io/@FlameArrow57/ByHp--aQyg
Project - https://discord.com/channels/182249960895545344/1314793532640464950

Note: This is not guaranteed to be merged into the game. Will at least likely go through a playtest though

## Why's this needed? 
See design doc. Goal is to create a unique antagonist

## Changelog 

```changelog
(u)FlameArrow57
(*)TBD
```

2025-02-01 12:29 UTC, flappybatpal commented
I gave this a try and had some concerns that it's fairly inconsequential as an antag and will probably end up being squished in Classic and treated as a mascot on RP. There's nothing too _unusual_ about that for midrounds but it leaves me a bit cold on the antag (pun intended) right now.

2025-02-01 12:31 UTC, flappybatpal commented
Ice tunnels would also need to be Z locked to the station, I don't see that check ATM.

2025-02-03 11:32 UTC, TobleroneSwordfish requested changes
Okay right, sorry this took so long to get to. Some basic things before we can properly playtest:

2025-02-03 11:32 UTC, TobleroneSwordfish commented on code/mob/living/critter/icephoenix.dm
> +		playsound(get_turf(src), "sound/impact_sounds/Glass_Shatter_[pick(1, 2, 3)]", 75, TRUE)
```suggestion
		playsound(get_turf(src), "sound/impact_sounds/Glass_Shatter_[pick(1, 2, 3)].ogg", 75, TRUE)
```

It's a lot easier to test PRs if you at least run through it once with runtime halting enabled to catch stuff like this 🥺

2025-02-03 11:32 UTC, TobleroneSwordfish commented on code/area.dm
> +	proc/remove_permafrost()
Removing permafrost doesn't appear to work, random tiles get replaced with space, atmos throws 600 runtimes and the snow remains.

2025-02-03 11:32 UTC, TobleroneSwordfish commented on code/datums/abilities/critter/icephoenix.dm
> +	desc = "Channel to gain a large movement speed buff while in space for 20 seconds"
This is the wrong duration, also a 60 second cooldown and a 10 second channel for a minor 10 second movement speed buff seems extremely useless(?)

2025-02-03 11:32 UTC, TobleroneSwordfish commented on code/mob/living/critter/icephoenix.dm
> +		new /turf/simulated/ice_phoenix_ice_tunnel(T, get_dir(src, T))
This runtimes, use `ReplaceWith`

2025-02-03 13:17 UTC, FlameArrow57 commented on code/datums/abilities/critter/icephoenix.dm
> +	desc = "Channel to gain a large movement speed buff while in space for 20 seconds"
Buffed, LMK if it seems fine

2025-02-03 13:18 UTC, FlameArrow57 commented on code/mob/living/critter/icephoenix.dm
> +		playsound(get_turf(src), "sound/impact_sounds/Glass_Shatter_[pick(1, 2, 3)]", 75, TRUE)
Ty for review. Think I might've had runtimes turned off by accident :/

2025-02-04 07:23 UTC, TobleroneSwordfish requested changes

2025-02-04 07:23 UTC, TobleroneSwordfish commented on code/mob/living/critter/icephoenix.dm
> +				playsound(get_turf(src), 'Glass_Shards_Hit_1.ogg', 75, TRUE)
```suggestion
				playsound(get_turf(src), 'sound/impact_sounds/Glass_Shards_Hit_1.ogg', 75, TRUE)
```
![test your code](https://github.com/user-attachments/assets/647ac546-26bd-4713-92ac-5baf9f349781)
(same for the rest of these in this file)

2025-02-04 09:21 UTC, FlameArrow57 commented on code/mob/living/critter/icephoenix.dm
> +				playsound(get_turf(src), 'Glass_Shards_Hit_1.ogg', 75, TRUE)
oops

2025-02-09 01:41 UTC, TobleroneSwordfish commented
Some miscellaneous issues from the playtest in no particular order:
- Snow floors are transparent when crowbarred
- Phoenixes show up as `null` names on the spectator list
- They're very quiet right now. Could do with some sound effects, whether that's custom sounds or generic effect sounds we already have.
- The ice statue beam should proobably have `mouse_opacity = 0` to avoid it being clicked on accidentally, maybe look at using one of the `drawLine` procs instead of whatever ancient hackery `showLine` is.
- Some people reported framerate issues with the snow effects
- The statues should leave behind either ice or water when destroyed

Generally I think the birds played pretty well, they were annoying and dangerous but not too immediately murderous on their own. They lose to pods pretty hard but are reasonably hard to catch if they've set up a couple of burrows and statues.

2025-03-02 23:07 UTC, TobleroneSwordfish commented
More more feedback in no particular order:
- Snowy tiles probably shouldn't be pryable otherwise removing the snow duplicates floor tiles (also you can't tell which tiles are snowy if they get pried)
- Some areas which are technically `/area/station` probably shouldn't trigger the on station effects: solars, shield/turret protected areas etc. Might actually be better to make it check for standing on a solid tile AND being in a station area, otherwise entering blown up/otherwise removed parts of the station will trigger it too.
- Shovels should do bonus damage to snow walls
- Ice statues should melt in high heat (eg plasma fire)
- Ice tunnels should probably remove grilles?
- Immortal bird of eternal doom:
![image](https://github.com/user-attachments/assets/31b333db-4947-4501-ad14-e09e5a4753bb)
- Lots of this runtime too, possibly related to turf replacements?
![image](https://github.com/user-attachments/assets/2217f0a3-371d-4c6f-9aa0-fe1f3e77f60a)

Balance opinions: the wall cooldown might be a little short and spammable and the weapon switching module for pods seems extremely strong vs phoenixes especially with the taser/laser hot swap combo. Honestly that module might just be too strong in general.

2025-03-05 01:04 UTC, TobleroneSwordfish requested changes
Okay final big review looking through all the code!

2025-03-06 03:10 UTC, FlameArrow57 commented on code/datums/abilities/critter/icephoenix.dm
> +				if (L.bodytemperature <= 255.372) // 0 degrees fahrenheit
Maybe, I'm just doing a Fahrenheit to Kelvin conversion here, this is Fahrenheit -> Celsius -> Kelvin?

2025-03-06 03:12 UTC, FlameArrow57 commented on code/mob/living/critter/icephoenix.dm
> +/image/phoenix_temperature_indicator
It was intentional, to make it a part of the "magic" in the ice chills it has

2025-03-06 03:14 UTC, FlameArrow57 commented on code/mob/living/critter/icephoenix.dm
> +		src.transform = turn(src.transform, 180)
The revive has an early return so this isn't called then

2025-03-07 09:14 UTC, FlameArrow57 commented on code/area.dm
> +			T.temperature = 269
I was doing a straight Fahrenheit -> Kelvin conversion here, not Celsius -> Kelvin

2025-03-07 22:21 UTC, FlameArrow57 commented on code/datums/abilities/critter/icephoenix.dm
> +			if (src.hits_left > 0)
This is just the message check

2025-03-07 22:23 UTC, FlameArrow57 commented on code/mob/living/critter/icephoenix.dm
> +				qdel(floor)
It's to refresh its lifetime which is SPAWN based

2025-03-07 22:31 UTC, FlameArrow57 commented on code/datums/limb.dm
> +	var/has_space_pushback = TRUE
Moved, it's just for a common parent type I believe. Fire elementals use /datum/limb/gun/kinetic too

2025-03-07 22:32 UTC, FlameArrow57 commented on code/datums/abilities/critter/icephoenix.dm
> +		if (src.target.bodytemperature <= 227.59) // -50 degrees fahrenheit
Dunno, I was just looking for a Fahrenheit -> Kelvin conversion, not Fahrenheit -> Celsius -> Kelvin

2025-03-07 22:45 UTC, FlameArrow57 commented on code/area.dm
> +			T.air.temperature = 269
What proc would that be?

2025-03-08 12:46 UTC, TobleroneSwordfish commented on code/area.dm
> +			T.temperature = 269
I don't really know what you mean but we don't use Fahrenheit anywhere so -4 is a lot easier to read than 269

2025-03-08 12:49 UTC, TobleroneSwordfish commented on code/area.dm
> +			T.air.temperature = 269
You'll need to choose whether you want to set the air-group's temperature (might affect other area's turfs too) or suspend group processing and set each turf's air temperature individually (slower but more accurate)

2025-03-08 12:52 UTC, TobleroneSwordfish commented on code/datums/abilities/critter/icephoenix.dm
> +			if (src.hits_left > 0)
Isn't it still the wrong way round though? The way this is written currently it will always destroy on the first hit.

2025-03-08 12:58 UTC, TobleroneSwordfish commented on code/mob/living/critter/icephoenix.dm
> +		src.transform = turn(src.transform, 180)
Admins revives need to work too though

2025-03-08 13:15 UTC, TobleroneSwordfish commented on code/mob/living/critter/icephoenix.dm
> +/image/phoenix_temperature_indicator
Oookay, maybe make it linger for longer then?

2025-03-08 13:17 UTC, FlameArrow57 commented on code/mob/living/critter/icephoenix.dm
> +		src.transform = turn(src.transform, 180)
Okay I added it to full_heal()

2025-03-08 13:20 UTC, FlameArrow57 commented on code/mob/living/critter/icephoenix.dm
> +/image/phoenix_temperature_indicator
The time its longest is when using wind chill which gives up to 10 seconds of shivering, I think that should be enough?

2025-03-08 13:21 UTC, FlameArrow57 commented on code/area.dm
> +			T.temperature = 269
Mmm I was meaning it was just a coincidence that it happened to be really close to 273.15 K, it wasn't based off it

2025-03-08 13:24 UTC, FlameArrow57 commented on code/datums/abilities/critter/icephoenix.dm
> +			if (src.hits_left > 0)
Nvm I was looking at the wrong spot

2025-03-08 13:31 UTC, FlameArrow57 commented on code/area.dm
> +			T.air.temperature = 269
I went for the first option, LMK if I did it wrong

2025-03-22 13:09 UTC, merged