Buff AI Disguised law module
goonstation/goonstation pull request #21624
Opened 2024-12-08 16:46 UTC by JORJ949

[SILICONS][FEATURE]
## About the PR 
The AI disguised module now comes with a remote
When inserted into slots 1-3 in an AI law rack the module will disguise itself as the matching asimov module and will be that law until the remote is used
When the remote is used the module immediately activates the hidden law
Inserting the law into slot 4+ will immediately show the hidden law.

## Why's this needed? 
The disguised law is incredibly underused and this has a unique use of allowing you to create "sleeper agent" silicons and it makes it much more disguised

## Changelog 

```changelog
(u)JORJ949
(*)Disguised AI law modules now hide themselves as the matching asimov law when inserted into slots 1-3 on a law rack until the accompanying remote is activated
```

2024-12-08 20:36 UTC, TobleroneSwordfish commented
I like what this is trying to achieve but I think the way the slot number changes the behaviour is too confusing. Kind of radical suggestion buut: maybe it should just be a separate item that attaches to a law module (and can be added while it's still in the rack?) which then changes the content of that module later on a trigger.

2024-12-09 01:55 UTC, JORJ949 commented
Interesting idea but I want there to be some evidence to destroy when you do this, for example earlier today someone saw the first law hit their pod (but then we came up with an excuse for it because the law 1 replacement was "You may injure" and thet thought it was the same). I think something in chat like "as you insert the module into the rack the built in stealth circuit activates" would make it clearer what happened, and good use of this item already requires a fair understanding of ai laws and how they work

2024-12-09 02:16 UTC, TobleroneSwordfish commented
Ookayy, what about letting it be swapped with other law modules in place and still only causing an update when triggered? I really really don't like it changing functionality based on what slot it's in, there shouldn't be anything special about the first 3 slots.

2025-03-10 13:14 UTC, JORJ949 commented
Added your hotswap suggestion, although not as cleanly as I would like as I'm not a TGUI person so don't want to touch it, would love to move the function to be on the remove button without editing present lawrack functionality of the button being greyed out when it can't be removed.

2025-03-22 12:48 UTC, TobleroneSwordfish requested changes
Sorry, didn't realise you re-opened this!
- The traitor buy menu should explain the new functionality.
- The remote should spawn in your hand if possible at the time.
- The remote shouldn't be obviously called "Disguised AI law module remote"
- Swapping the modules shouldn't trigger a law update, otherwise it's very obvious to all silicons that they just got a disguised law whenever they hear "dooDING" and don't get any law changes
- Clicking the "Remove" button with the law module in hand should also trigger the swap action, currently it just removes the existing module.
- There should be some feedback when you press the remote and a law change actually takes place.
- The "Remove" button should become active on all modules while you're holding the disguised module in your active hand, if you don't know how to do this feel free to ping me on discord.

2025-03-22 16:28 UTC, JORJ949 commented
Suggestions implemented, I didn't implement remove button changing if you are holding a disguised module because 1) I don't know how and 2) you aren't supposed to know if you are holding a disguised module and the button changing colour would out it.

2025-03-22 19:39 UTC, JORJ949 commented
Back in the oven

2025-03-22 19:39 UTC, closed without merging