TGUI Keybind Menu
goonstation/goonstation pull request #21681
Opened 2024-12-14 06:12 UTC by Garash2k

## About the PR 
Ports the Keybind Menu from CHUI to TGUI
![image](https://github.com/user-attachments/assets/220de7ab-d178-49e5-8f0e-81540793a1cd)

## Why's this needed? 
Besides the technology upgrade, current CHUI menu is kinda broken, it autocloses after trying to change a binding if used while alive.

Old UI:
![261892373-7317fd5f-3030-4feb-ae88-58c9bbdfbd5a](https://github.com/user-attachments/assets/84840bd1-ad32-4611-9717-04bc22b0f4f3)

## Changelog 

```changelog
(u)Garash
(+)The keybind menu has been is now less buggy
```

[UI][QoL][Feature]

2024-12-14 06:21 UTC, ZeWaka commented
How does The binding mechanism work? Is it a straight character input or does it capture keyboard input? The latter would be a lot nicer, other servers have implementations we can use

2024-12-14 06:21 UTC, ZeWaka commented
How does The binding mechanism work? Is it a straight character input or does it capture keyboard input? The latter would be a lot nicer, other servers have implementations we can use

2024-12-14 06:30 UTC, Garash2k commented
Straight character input is how both the old ui and this version works, but I agree capturing keyboard input is absolutely the way to go, adding it as a todo

2024-12-14 13:48 UTC, FlameArrow57 commented
Nice

2025-01-08 03:43 UTC, ZeWaka commented
X

2025-01-08 14:12 UTC, TobleroneSwordfish commented
This looks good, will need testmerging but we have another TGUI PR testmerged right now so will have to wait.
The only thing I'd say it could use is a modified notification like the character setup page, oh and in theory a way to block the browser shortcuts so you can bind something to CTRL + N without getting IE jumpscared. Not sure how possible that is but suuurely we can capture that somehow??

2025-01-14 20:39 UTC, mordent-goonstation requested changes

2025-01-14 20:39 UTC, mordent-goonstation commented on code/modules/interface/keybind_menu_chui.dm
> +			ui = new(user, src, "Keybinds", "Keybinding Customization")
Stick the title on the actual UI instead, I guess. It's how we do the vast majority, and this one doesn't have a special reason to customize the title or whatever.

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Footer.tsx
> +        color={!hasChanges ? null : 'good'}
Verify, but I think `undefined` is preferred to `null` for when we're not changing the color.

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Footer.tsx
> +        {!resetting ? 'Reset All' : 'Confirm?'}
Having both a `Confirm` button (the one before this) and this one (`Confirm?` after you've pressed `Reset All` once) is a bit odd. I also don't see a way to get out of the resetting state short of saving your keybinds.

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +  isFocused: BooleanLike;
```suggestion
  isFocused: boolean;
```
`BooleanLike` is for when it's coming from the backend data, we're actually setting this prop to `true`/`false` so it's an actual `boolean`.

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +            setFocusedKey('');
Feels odd to not have a `return` here, especially given that you then also do `setFocusedKey('')` shortly after.

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +          return act('changed_key', { id: keybind.id, value });
```suggestion
          act('changed_key', { id: keybind.id, value });
```
`act` doesn't return anything, so no need to return it.

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +        color={isFocused ? 'good' : null}
Check re: `undefined` vs. `null`.

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +        {isFocused ? '...' : keybind.changedValue || keybind.savedValue}
Possibly consider `??` over `||`. Not verified but I assume `changedValue` is a string with the new key thing, which should be fine as `||` here, but e.g. `changedValue` of empty string is falsey. Is that the behavior you want?

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/KeybindList.tsx
> + * @copyright 2024
```suggestion
 * @copyright 2025
```

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> + * @copyright 2024
```suggestion
 * @copyright 2025
```

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Footer.tsx
> + * @copyright 2024
```suggestion
 * @copyright 2025
```

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +      <Button
Should these be children, or the `buttons` prop of the `LabeledList.Item` above?

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/KeybindList.tsx
> +        {keys.sort(sortKeys).map((k) => (
Find with there being a sort for alphabetizing, trying to get my head around what actions might have an id of numbers to warrant use of the custom sort function. Could you give some examples?

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/KeybindList.tsx
> +  }
```suggestion
  }
  return k1.id.localeCompare(k2.id);
```
No actual change here, but good practice to have the last return not in an `else`. Means a future change is less likely to break it (though TS should catch it).

2025-01-14 20:39 UTC, mordent-goonstation commented on tgui/packages/tgui/interfaces/Keybinds/types.ts
> + * @copyright 2024
```suggestion
 * @copyright 2025
```

2025-01-14 20:42 UTC, mordent-goonstation commented
> This looks good, will need testmerging but we have another TGUI PR testmerged right now so will have to wait. The only thing I'd say it could use is a modified notification like the character setup page, oh and in theory a way to block the browser shortcuts so you can bind something to CTRL + N without getting IE jumpscared. Not sure how possible that is but suuurely we can capture that somehow?? (do we have `preventDefault`?)

To my knowledge some of the brower-level keybinds can't be blocked. As this is a port, I imagine the current chui one has this problem already? We could augment at a later date by allowing to to e.g. manually click on some modifier buttons for the case where you can't press the bind directly.

2025-01-15 00:59 UTC, mordent-goonstation commented
> > To my knowledge some of the brower-level keybinds can't be blocked.
> 
> Seems like `preventDefault` does work to supress those, I was surprised too. Maybe worth putting a snippet globally somehow to prevent IE browser shortcuts? I guess that would be an upstream PR.

Neat. In fairness that *would* be something that is browser dependent, so we'd have to make sure we hit the browser version we care about in our method. Quick Google implies that `keyDown` is the event that matters, but would need to verify.

2025-01-20 22:36 UTC, Garash2k commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +        {isFocused ? '...' : keybind.changedValue || keybind.savedValue}
I'm not sure how someone would end up as an empty string as a keybind, but I guess in that case we should show that an empty string is being used and not the initial value.

2025-01-20 22:40 UTC, Garash2k commented on tgui/packages/tgui/interfaces/Keybinds/Keybind.tsx
> +      <Button
I think in this case, the button is the content/focus of the list, so in makes sense to be children. As opposed to elsewhere, where most of the time, the button serves to do an action on the list's content.

2025-01-20 22:56 UTC, Garash2k commented on tgui/packages/tgui/interfaces/Keybinds/KeybindList.tsx
> +        {keys.sort(sortKeys).map((k) => (
Yup, example:

- Top of the list should be Up with id:2
- Down:4, Left:8, Right:16
- Then there's stuff like Run:32, Point:128 and Pull:512
- And then the rest of the IDs should be alphabetical: Say:say, OOC:ooc, Grab Intent:grab, Target Left Leg:l_leg.

If we were to sort them alphabetically, Point would be put above Up, and Run would be put between Up and Down. We can't sort the numerically because most of them are strings.

2025-01-20 22:59 UTC, Garash2k commented on tgui/packages/tgui/interfaces/Keybinds/Footer.tsx
> +        {!resetting ? 'Reset All' : 'Confirm?'}
I was suggested have the same behavior as the Character Setup "Reset All" button, for which you can't get out of the resetting state either. Looking it up now though, it's a Button.Confirm so I'll use that, and I'll use "Confirm Reset All?" to disambiguate.

2025-01-21 03:07 UTC, merged

2025-01-21 08:05 UTC, ZeWaka commented
Thanks for helping clean up my spite code