Replace HoS gun with a wrestlebelt on wrestlemap
goonstation/goonstation pull request #21745
Opened 2024-12-19 03:35 UTC by JORJ949

## About the PR 
On wrestlemap, the HoS' egun is instead a wrestling belt.

## Why's this needed? 
Funny feature for a funny map

2024-12-19 07:53 UTC, pgmzeta requested changes

2024-12-19 07:53 UTC, pgmzeta commented on code/obj/item/storage/backpack_belt_etc.dm
> +	/obj/item/device/prisoner_scanner)
less dupe pls (could still add tasershotgun in New like the shotgun belt does i guess)
```suggestion
	can_hold = /obj/item/storage/belt/security::can_hold
```

2024-12-19 07:53 UTC, pgmzeta commented on code/obj/storage/secure_closets.dm
> +	/obj/item/clothing/belt/wrestling/hos
```suggestion
	/obj/item/storage/belt/wrestling/hos
```

2024-12-19 08:22 UTC, pgmzeta commented on code/obj/storage/secure_closets.dm
> +	/obj/item/storage/belt/wrestling/hos
```suggestion
	/obj/item/storage/belt/wrestling/hos,
```

2024-12-19 08:30 UTC, pgmzeta commented on code/obj/item/storage/backpack_belt_etc.dm
> +		src.check_wclass = 1
what you had here didn't work but this did; pls test changes

```suggestion
	can_hold = /obj/item/storage/belt/security::can_hold
	check_wclass = 1

	New()
		..()
		src.can_hold += /obj/item/gun/energy/tasershotgun
```

2024-12-19 18:16 UTC, pgmzeta approved these changes

2024-12-20 01:20 UTC, Retrino commented
there's already one in the armory, dont really see the point of taking the hos's egun specifically

2024-12-20 02:15 UTC, JORJ949 commented
> there's already one in the armory, dont really see the point of taking the hos's egun specifically

The one in the armory is a fake one that only works in the ring and does no damage

2024-12-21 07:33 UTC, Retrino commented
still dont understand why its going to the hos and not someone like the captain, the head authority on station. kind of just feeding into the main character energy stereotype that surrounds hos

2024-12-22 04:44 UTC, JORJ949 commented
> still dont understand why its going to the hos and not someone like the captain, the head authority on station. kind of just feeding into the main character energy stereotype that surrounds hos

I would be open to expanding it to replacing the captain's gun, but its easier to give a whitelist-only role a strong item than a job treated like AA staffie with a history of abuse (see old armory auth disk interaction)

2024-12-23 21:04 UTC, Chatauscours commented
It's a gimmick map that's ran almost exclusively under admin supervision, i heavily doubt powergaming will be a problem if it's given to captains, considering the egun can be just as deadly than the belt if misused

2024-12-24 02:01 UTC, closed without merging

2024-12-24 02:01 UTC, Tarmunora commented
> still dont understand why its going to the hos and not someone like the captain, the head authority on station. kind of just feeding into the main character energy stereotype that surrounds hos

Agreed. This one is a swing and a miss I think.