Medbay Pocket Guide Second Edition
goonstation/goonstation pull request #21753
Opened 2024-12-19 14:06 UTC by AnomalousPotato

[Game Objects][Feature]

## About the PR 
Updates the Medbay Pocket Guide to be far more comprehensive, useful, and up-to-date.

## Why's this needed? 
Every time I get a medical trainee, they talk about reading the pocket guide, which is years old and sometimes the opposite of helpful given how much the game has changed. If they are going to read it, I would prefer it to be helpful.

## Changelog 

```changelog
(u)AnomalousPotato
(+)Updated Medbay Pocket Guide to be more up-to-date, comprehensive, and useful.
```

2024-12-19 14:57 UTC, JORJ949 commented on code/obj/item/book.dm
> +		name = "Medbay Pocket Guide, Second Edition"
This isnt the second edition one
```suggestion
		name = "Medbay Pocket Guide"
```

2024-12-19 14:58 UTC, JORJ949 commented
Why not just replace the old one like was done for space law a while back? Doesn't seem necessary to keep outdated guidebooks.

2024-12-22 21:45 UTC, flappybatpal commented
I'm not sure we want author credits, generally because this causes issue if someone gets banned and so we have been avoiding player references.

2024-12-23 09:01 UTC, AnomalousPotato commented
> I'm not sure we want author credits, generally because this causes issue if someone gets banned and so we have been avoiding player references.

I mean, if it's a problem, I'll remove it. I was following in line with the previous edition, it's not a big issue for me.

2025-01-01 21:23 UTC, AnomalousPotato commented
holiday bump

2025-01-25 15:40 UTC, Sord213 requested changes
Looks good2me otherwise

2025-01-25 15:40 UTC, Sord213 commented on strings/books/medbay_pocket_guide.txt
> +<p>Radiation causes tox and burn damage, but it's fairly simple to heal. Just inject potassium iodide from the NanoMed, and keep up with the escalating damages. The potassium iodide will reduce remov
"will reduce remove radiation"

2025-01-26 19:34 UTC, merged