Restrict fishing rod storage to food items
goonstation/goonstation pull request #21784
Opened 2024-12-22 05:47 UTC by pgmzeta

[balance][game objects]
## About the PR 
Restrict fishing rod bait storage to food items.

## Why's this needed?

2024-12-22 06:49 UTC, LorrMaster commented
Maybe only apply the change to cyborg fishing rods? That way players can use use credits or something as bait for whatever reason.

2024-12-22 22:15 UTC, pgmzeta commented
Want to avoid cyborg/human item divergence unless absolutely necessary. The current bait pools are just food items.

2024-12-24 02:08 UTC, Tarmunora requested changes
should update `fishing_lootpools.dm` to make it explicit that expected lures should be food only, if adding a hard restriction on what items can be used as lures.

2024-12-24 06:17 UTC, Tarmunora approved these changes

2024-12-24 16:09 UTC, merged