Gang lockers hide under floorboards
goonstation/goonstation pull request #21868
Opened 2024-12-30 16:09 UTC by TDHooligan

[EXPERIMENTAL][GAMEMODES][BALANCE]
## About the PR 
Gang lockers now hide under the floorboards. Gang members can unhide them by emptyhanding the floor tile. They can hide them with the same action, or walk way, whereby the locker will hide itself.

Should be testmerged for a bit - I'm not certain how security players will react to this.

## Why's this needed? 
Security will sweep maintenance once for gang lockers and from that point on, there's no secrecy to gang operations. The gangs have no way to handle this.

The exact knowledge of their clubroom at all times also leads to a lot of unhealthy behaviours. Security cause excessive friction with gangs by staring at the locker etc. This PR introduces a lot of uncertainty, and having some level of uncertainty allows gang members some breathing room.

Prudent gang members will be able to keep their clubroom clear & misdirect security. Messier gangs will be more engaging to investigate, as you can't just look for the big "THIS IS A GANG ROOM" locker.

## Changelog 

```changelog
(u)TDHooligan
(*)Gang lockers now hide under the floor when not in use. Gang members can uncover them by clicking the floor with an empty hand.
```

2024-12-30 16:39 UTC, DisturbHerb commented
as a regular security player, please for the love of god make this a thing

2024-12-30 20:49 UTC, Chatauscours commented
Yeah this seems like a great idea

2025-01-03 11:53 UTC, TobleroneSwordfish requested changes
Very cool PR, a few small code issues.

2025-01-03 11:53 UTC, TobleroneSwordfish commented on code/datums/controllers/process/gang.dm
> +				var/should_hide = TRUE
This var doesn't actually do anything because the loop returns if it finds a ganger

2025-01-03 11:53 UTC, TobleroneSwordfish commented on code/datums/gamemodes/gangwar.dm
> +		var/mob/user = attacker
```suggestion
	proc/turf_attacked(target, mob/user)
		if (!ismob(user))
			return
```

2025-01-03 11:53 UTC, TobleroneSwordfish commented on code/datums/gamemodes/gangwar.dm
> +		if(!isliving(user))
Maaybe also make sure they're not a silicon so borged gangers can't reveal it?

2025-01-03 11:53 UTC, TobleroneSwordfish commented on code/datums/gamemodes/gangwar.dm
> +			animate_slide(floorturf, 0, 0, 4)
Please don't copy paste these, either make an animation library proc or at least make this a single method with arguments.

2025-01-06 12:09 UTC, TDHooligan commented on code/datums/controllers/process/gang.dm
> +				var/should_hide = TRUE
good spot. brain farded

2025-01-07 16:20 UTC, merged