initial
goonstation/goonstation pull request #2187
Opened 2020-09-15 15:55 UTC by flappybatpal

## About the PR 
Bug fix for https://github.com/goonstation/goonstation/issues/2096

## Why's this needed? 
Chameleon was comparing world.timeofday to owner.l_move_time which didn't make sense. From what I can tell this was totally broken.
I've changed this around to keeping track of the world time. The logic may not be perfect but it behaved in testing.
We should improve the way the cloak is dropped as right now you could stand still and fire a SPES 12 invisibly!

2020-09-16 01:14 UTC, Sovexe commented
I feel like this might be better off registering the owner for `COMSIG_MOVABLE_MOVED` or something on `cast()`

That way if you walk or get bumped or whatever it just de-cloaks you, rather than checking if you moved and updating overlays and setting invisibility over and over

2020-09-27 21:47 UTC, flappybatpal commented
Having trouble with the signals. Movement is fine but I want to deactivate on attack/being attacked to be a closer match to the traitor cloak. Think it can't hear the attack signals from the datum, not sure how to proceed.

2020-09-28 14:44 UTC, Sovexe commented
We have a signal for being attacked not for attacking. Cloak ends on attacking because there are checks throughout the code that check if you have an active `cloaking_device` and then disable it

2020-10-03 19:25 UTC, flappybatpal commented
Changed to TIME and ditched COMSIG_ATTACKBY.

Can't work out how to get attacking to work. Would need to call the proc somehow from other DMs but I can't work out how to do it without nulls. Got an accidental merge in too with 2bf87fb and can't work out how to get rid of that either.

I'm leaving this alone now, it works as far as fixing the movement bug and slightly rebalancing chameleon to match invisibility so your cloak drops if you are attacked instead of being perma stealth until you are moved.

2020-10-05 16:37 UTC, pali6 commented on code/modules/medical/genetics/bioEffects/powers.dm
> +	var/last_moved = 0;
```suggestion
	var/last_moved = 0
```

2020-10-05 16:37 UTC, pali6 commented on code/modules/medical/genetics/bioEffects/powers.dm
> +			if ((TIME - last_moved) >= 30 && can_act(owner))
```suggestion
			if (TIME - last_moved >= 3 SECONDS && can_act(owner))
```

2020-10-05 16:37 UTC, pali6 commented on code/modules/medical/genetics/bioEffects/powers.dm
> +		boutput(world, "decloak")
```suggestion
```
*scream

2020-10-05 16:37 UTC, pali6 commented on code/modules/medical/genetics/bioEffects/powers.dm
> +			CH.RegisterSignal(owner, list(COMSIG_MOVABLE_MOVED, COMSIG_MOB_ATTACKED_PRE), /datum/bioEffect/power/chameleon/proc/decloak, FALSE)
```suggestion
			CH.RegisterSignal(owner, list(COMSIG_MOVABLE_MOVED, COMSIG_MOB_ATTACKED_PRE), /datum/bioEffect/power/chameleon/proc/decloak)
```
FALSE is already the default

2020-10-05 17:39 UTC, flappybatpal commented on code/modules/medical/genetics/bioEffects/powers.dm
> +		boutput(world, "decloak")
Jeez I was sure I removed this.

2020-10-05 17:48 UTC, pali6 requested changes
Actually one more thing
`OnRemove()` should also unregister the signals if they are registered.

2020-10-05 18:26 UTC, pali6 commented on code/modules/medical/genetics/bioEffects/powers.dm
> +			CH.UnregisterSignal(owner, list(COMSIG_MOVABLE_MOVED, COMSIG_MOB_ATTACKED_PRE))
```suggestion
			linked_power.UnregisterSignal(owner, list(COMSIG_MOVABLE_MOVED, COMSIG_MOB_ATTACKED_PRE))
```

2020-10-05 18:30 UTC, pali6 commented on code/modules/medical/genetics/bioEffects/powers.dm
> +			linked_power.UnregisterSignal(owner, list(COMSIG_MOVABLE_MOVED, COMSIG_MOB_ATTACKED_PRE))
```suggestion
			src.UnregisterSignal(owner, list(COMSIG_MOVABLE_MOVED, COMSIG_MOB_ATTACKED_PRE))
```

2020-10-05 19:05 UTC, pali6 approved these changes

2020-10-05 19:05 UTC, merged