adds popecrunch cereal radio ad
goonstation/goonstation pull request #2229
Opened 2020-09-20 17:03 UTC by Adharainspace

## About the PR 

voices: Puppet Master and HeadsmanStukka of the Black Pants Legion

backing audio: "Smooth Talker" by Apoxode 2019 - Licensed under Creative Commons Attribution (3.0)

editor: Phuzzy

(i added it to the ship one and the debris map)

## Why's this needed? 
more ad variety!!

## Changelog

```
(u)Phuzzy:
(*)Adds a new ad! Find it at your local space radio station!
```

2020-09-20 17:16 UTC, PhuzzySA commented
Thanks again to the fine folks in #imcoder for getting this put together. I also want to thank the guys at BPL for humoring me with this, and hope to continue that relationship.

2020-09-23 14:20 UTC, Sovexe requested changes
![image](https://user-images.githubusercontent.com/33204415/94025287-5616c800-fd86-11ea-9b76-006abc971fda.png)

2020-09-23 16:35 UTC, Adharainspace commented
![image](https://user-images.githubusercontent.com/37386904/94042182-db9f7580-fd90-11ea-8008-e2d1849fb718.png)
fixed!

2020-09-23 16:35 UTC, Adharainspace commented
fixed it!

2020-09-23 16:52 UTC, Sovexe commented on code/modules/telescience/radiostation.dm
> +	The music is Smooth Talker by Apoxode licensed under Creative Commons Attribution (3.0)"}
```suggestion
/obj/item/radio_tape/advertisement/pope_crunch
	name = "compact tape - 'Pope Crunch'"
	audio = "sound/radio_station/pope_crunch_cereal.ogg"
	name_of_thing = "Pope Crunch Cereal"
	desc = {"A small audio tape. Though, it looks to big to fit in an audio log.<br>
	The music is Smooth Talker by Apoxode (CC BY 3.0)"}
```
consistency with other tapes

2020-09-23 17:58 UTC, Adharainspace commented on code/modules/telescience/radiostation.dm
> +	The music is Smooth Talker by Apoxode licensed under Creative Commons Attribution (3.0)"}
got it thanks

2020-09-23 18:28 UTC, Sovexe approved these changes

2020-09-23 18:28 UTC, Adharainspace commented
ok now ive really fixed it

2020-09-23 18:28 UTC, merged