Adds resprites of existing guns + new sprites
goonstation/goonstation pull request #2230
Opened 2020-09-20 23:22 UTC by schwicky-schwag

## About the PR 
Adds some much-needed re-sprites for existing guns, including adding updated old gun sprites to match newer ones. Also contains a couple new sprites for guns to be used in the future, and new golden gun sprites.

## Why's this needed? 
Some of the golden gun sprites are out of date, and none of them currently feature in-hand sprites. This PR adds updated sprites for old guns, gold sprites for newer guns, and in-hand sprites for all the golden guns.

## Changelog

```
(u)schwicky-schwag:
(*)Added a whole bunch of new gun sprites (with in-hands included) to replace old ones, and ones for coders to use in the future.
```

2020-09-21 00:23 UTC, Gannets commented
Very pleased to see some of these in the game.

2020-09-21 00:47 UTC, ZeWaka requested changes
Looks like none of these, save the bling blaster and the shotgun inhand, are actually in use
I'm not so keen on adding a bunch of sprites that aren't even used anywhere.
Could you please set the various weapons to use the sprites?

2020-09-21 01:06 UTC, Tarmunora commented
I'll be handling implementation

2020-09-21 03:48 UTC, Tarmunora commented
@Gannets I poked the nukeop gun sprites to recenter them

2020-09-21 04:01 UTC, Tarmunora commented
unused: g11, M16, bolt-actions for rifles, glocks, hi-point, bretta, deagle, unfolded spes, sawn-off, mac10

2020-09-21 04:33 UTC, schwicky-schwag commented
> unused: g11, M16, bolt-actions for rifles, **glocks**, hi-point, bretta, deagle, unfolded spes, sawn-off, mac10

shouldn't the new glock sprites replace the old ones?

2020-09-21 20:06 UTC, ZeWaka requested changes

2020-09-21 20:06 UTC, ZeWaka commented on code/mob/living/carbon/human.dm
> +			var/regex/off2 = new(@"^(CENTER[+-]\d:)(\d+)(.*)$")
could you document this cursed behemoth so people know what it does if they can't read through it?

2020-09-21 20:06 UTC, ZeWaka commented on code/mob/living/carbon/human.dm
> +			I.screen_loc = "[off2.group[1]][text2num(off2.group[2])-(text2num(offset.group[1])-32)/2][off2.group[3]]"
ditto

2020-09-22 00:08 UTC, ZeWaka approved these changes
♥

2020-09-22 04:44 UTC, merged