Makes Port-a-Medbay send PDA notifications
goonstation/goonstation pull request #2235
Opened 2020-09-21 18:27 UTC by BatElite

[feat]
## About the PR 
This PR makes the Port-a-Medbay send out PDA messages to the medbay and med research mailing groups if it's sent home with someone inside. There's three types of messages: one for corpses, one for patients in crit (pictured) and one for general patients.

![PaM-preview](https://user-images.githubusercontent.com/31984217/93805483-1c3fa780-fc48-11ea-987e-02e0da51b105.png)

## Why's this needed? 
Alerts doctors to emergencies and bodies coming in automatically. People using it in-game have been resorting to yelling at medbay over the radio to check the port-a-med after they send it, because it'd otherwise often go unnoticed.

## Changelog

```
(u)BatElite:
(*)The Port-a-Medbay now sends notifications to medical PDAs when sent to home turf with someone inside.
```

2020-09-21 18:44 UTC, jan-antilles commented
AMAZING QoL change, both for doctors and those who end up in the portamed!

2020-09-21 19:34 UTC, Tarmunora approved these changes

2020-09-21 22:37 UTC, MarkNais approved these changes
Code looks good (I did some PDA changes a month ago).
Also, very good QoL change.

2020-09-22 00:17 UTC, ZeWaka requested changes

2020-09-22 00:17 UTC, ZeWaka commented on code/obj/machinery/sleeper.dm
> +	var/list/mailgroups = list(MGD_MEDBAY, MGD_MEDRESEACH)
can you document what this list is for?

2020-09-22 00:17 UTC, ZeWaka commented on code/obj/machinery/sleeper.dm
> +/obj/machinery/sleeper/port_a_medbay/proc/PDA_alert_check() //Yell at doctors to check the thing when it's sent home
```suggestion
/// Yells at doctors to check the thing when it's sent home
/obj/machinery/sleeper/port_a_medbay/proc/PDA_alert_check()
```

2020-09-22 16:43 UTC, ZeWaka approved these changes

2020-09-22 16:43 UTC, ZeWaka commented on code/obj/machinery/sleeper.dm
> +	//Mailgroups it'll try to send PDA notifications to
```suggestion
	/// Mailgroups it'll try to send PDA notifications to
```

2020-09-22 17:52 UTC, merged