Proximity sensors tripped by ghosts
goonstation/goonstation pull request #2242
Opened 2020-09-22 19:53 UTC by Arivias

## About the PR 
Prevents proximity sensors from being triggered by ghosts.

## Why's this needed? 
https://github.com/goonstation/goonstation/issues/2239

## Changelog

2020-09-22 23:40 UTC, ThePotato97 requested changes
Use isobserver(x) instead of istype.

2020-09-22 23:40 UTC, ThePotato97 commented on code/obj/item/assembly/misc_assemblies.dm
> +	if (istype(AM,/mob/dead) || istype(AM, /obj/projectile))
```suggestion
	if (isobserver(AM) || istype(AM, /obj/projectile))
```

2020-09-22 23:40 UTC, ThePotato97 commented on code/obj/item/device/prox_sensor.dm
> +	if (istype(AM, /mob/dead) || istype(AM, /obj/projectile) || AM.invisibility > 2)
```suggestion
	if (isobserver(AM) || istype(AM, /obj/projectile) || AM.invisibility > 2)
```

2020-09-22 23:43 UTC, ThePotato97 commented
Shouldn't `AM.invisibility > 2` be checking if they're a ghost/wraith/anything invisible?

2020-09-23 00:27 UTC, ThePotato97 commented
Observers don't set off the proximity sensor, i just tested it but wraiths do fix would be editing
https://github.com/goonstation/goonstation/blob/146d2e57479d7e0bd3f27325f7d72e011155b8f2/code/modules/networks/computer3/mainframe2/misc_terms.dm#L2821
`if(isobserver(AM) || isintangible(AM) || AM.invisibility > 2) return`

2020-09-23 01:44 UTC, ThePotato97 approved these changes

2020-09-23 17:56 UTC, ZeWaka requested changes
intangible and wraiths

2020-09-23 17:56 UTC, ZeWaka commented on code/obj/item/assembly/misc_assemblies.dm
> +	if (isobserver(AM) || istype(AM, /obj/projectile))
```suggestion
	if (isobserver(AM) || iswraith(AM) || isintangible(AM) || istype(AM, /obj/projectile))
```

2020-09-23 17:56 UTC, ZeWaka commented on code/obj/item/device/prox_sensor.dm
> +	if (isobserver(AM) || istype(AM, /obj/projectile) || AM.invisibility > 2)
```suggestion
	if (isobserver(AM) || iswraith(AM) || isintangible(AM) || istype(AM, /obj/projectile)) || AM.invisibility > 2)
```
humans can be invisible too, which is why we check invisibility

2020-09-23 18:17 UTC, ZeWaka approved these changes

2020-09-25 02:16 UTC, merged