fixed a bug with mask choking
goonstation/goonstation pull request #2258
Opened 2020-09-24 14:10 UTC by zjdtmkhzt

## About the PR 
It seems that trying to grab someone with a mask incorrectly checked whether or not _you_ were already wearing a mask, rather than them. This meant you could not do it when you were wearing a mask.

I just removed the check entirely, seeing as wearing a mask already seems to prevent you from being choked, regardless of the type of choking.

## Why's this needed? 
fixes #2256

2020-09-24 18:46 UTC, Sovexe commented
While both head clothes and masks do default to `body_parts_covered` including `HEAD` there are a handful of items that also `COVER_MOUTH` without also covering your head, for example, bedsheets which set flags as follows

```
	c_flags = COVERSEYES | COVERSMOUTH
	body_parts_covered = TORSO|ARMS
```

these cases should be handled as well.

2020-09-24 18:48 UTC, Sovexe requested changes
While both head clothes and masks do default to `body_parts_covered` including `HEAD` there are a handful of items (all of which are suit slots, maybe?) that also `COVERSMOUTH` without also covering your head, for example, bedsheets which set flags as follows

```
	c_flags = COVERSEYES | COVERSMOUTH
	body_parts_covered = TORSO|ARMS
```

to name a few more off the top of my had, Im pretty sure the monkey suit and borg suits also do this. These should probably be handled as well, or we just say that they don't actually stop your from being mask choked

There may be additional items that I am unaware of

2020-09-24 20:02 UTC, zjdtmkhzt commented
I see what you mean, how's this?

2020-09-25 03:23 UTC, Sovexe approved these changes

2020-09-27 22:36 UTC, merged