Farts No Longer Stuck forever
goonstation/goonstation pull request #2289
Opened 2020-09-27 21:10 UTC by RSG250

## About the PR 
Changes it so Frozen Farts are no longer anchored 
also changes it so it drops out of inventory after 2 seconds instead of 1

## Why's this needed? 
Cant make thing in material science if they are frozen forever in the kitchen freezer, and thats a crying shame 

## Changelog

```
(u)RSG250:
(+)Frozen Farts are no longer anchored, Still pretty slippery
```

2020-09-27 23:09 UTC, ZeWaka requested changes

2020-09-27 23:09 UTC, ZeWaka commented on code/modules/materials/Mat_MaterialProcs.dm
> +*/
delete this

2020-09-28 00:23 UTC, RSG250 commented on code/modules/materials/Mat_MaterialProcs.dm
> +*/
deleted

2020-10-05 16:48 UTC, pali6 approved these changes
ye

2020-10-05 16:49 UTC, merged