UV Lamp: The Wrenchening
goonstation/goonstation pull request #2301
Opened 2020-09-28 16:03 UTC by RSG250

[QoL]
## About the PR 
adds code thats used to secure the high capacity water tanks to floor to the UV lamp 

## Why's this needed? 
Its annoying when other botanists accidentally move the UV lamp out of the perfect position you put it in

## Changelog

```
(u)RSG250:
(+)can now secure the UV lamp to the floor via Wrench or Screwdriver
```

2020-09-28 18:02 UTC, Sovexe requested changes

2020-09-28 18:02 UTC, Sovexe commented on code/obj/machinery/plantpot.dm
> +		if(istool(W, TOOL_SCREWING | TOOL_WRENCHING))
Use the macros

```dm
#define isscrewingtool(x) (istool(x, TOOL_SCREWING) || (istype(x, /obj/item/reagent_containers) && x:reagents:has_reagent("screwdriver")) ) //the joke is too good
#define iswrenchingtool(x) (istool(x, TOOL_WRENCHING))
```

2020-09-28 19:57 UTC, Sovexe commented on code/obj/machinery/plantpot.dm
> +		else if(iswrenchingtool(W))
```suggestion
		if(isscrewingtool(W) || iswrenchingtool(W))
```

you can still combine them

2020-09-28 19:58 UTC, RSG250 commented on code/obj/machinery/plantpot.dm
> +		else if(iswrenchingtool(W))
oh neat

2020-09-28 20:41 UTC, Sovexe approved these changes

2020-09-29 00:53 UTC, ZeWaka approved these changes
Could be more compact but nitpicking

2020-09-29 03:04 UTC, Sovexe commented on code/obj/machinery/plantpot.dm
> +			return
```suggestion
			if(!src.anchored)
				user.visible_message("<b>[user]</b> secures the [src] to the floor!")
			else
				user.visible_message("<b>[user]</b> unbolts the [src] from the floor!")
			playsound(src.loc, "sound/items/Screwdriver.ogg", 100, 1)
			src.anchored = !src.anchored
```
For Zewaka

2020-09-29 07:49 UTC, zjdtmkhzt commented
I was somehow under the impression you could secure those already??
Anyway, good feature!

2020-09-29 13:07 UTC, merged

2020-09-29 13:14 UTC, pali6 commented
Too late now but we now have a pretty handy action bar for anchoring / unanchoring objects.