Discount superhero
goonstation/goonstation pull request #2393
Opened 2020-10-09 23:49 UTC by Arivias

[FEATURE]

## About the PR 
Adds the discount superhero spooktober latejoin job.
DS starts with:
- A fancy costume
- eyebeams
- security access

DS cannot be a traitor/spy/etc.

## Why's this needed? 
Suggested by Mouse on the forum.

Provides a fun Spooktober themed latejoin security job.

## Changelog

```
(u)Sidewinder7:
(*)Added the Discount Superhero latejoin job.
```

2020-10-10 02:52 UTC, Kyle2143 commented
This is good, but I don't see any HALLOWEEN defines that specify that this role is only for Spooktober.  Also, it could probably have another useful gene, to make it superhero-y like adrenaline rush. Kinda OP, but hey, it's a superhero.

2020-10-10 05:21 UTC, Arivias commented
I've had a few more ideas since I posted this. I'll see what I can do.

2020-10-11 22:27 UTC, Sovexe commented on code/datums/jobs.dm
> +				eb.stun_mode = 1
this should probably still be marked as `altered` to prevent splicing

2020-10-11 22:29 UTC, Sovexe commented on code/datums/jobs.dm
> +				be.safety = 1
empowered, synchronized, stabilized genes that can't be cured by mutadone or scrambled away by genetics exceeds what I would consider "discount" that's more of an actual super hero

2020-10-11 22:29 UTC, Sovexe commented on code/datums/jobs.dm
> +		be.altered = 1
likewise

2020-10-11 22:30 UTC, Sovexe reviewed
I would also consider the possibility of tying the genetic effects to the suit itself. Such that they are lost when you remove the suit and regained when equipping it. Don't have to do this, just an idea.

2020-10-12 01:29 UTC, Sovexe approved these changes

2020-10-12 01:37 UTC, Sovexe requested changes

2020-10-12 01:37 UTC, Sovexe commented on code/modules/medical/genetics/bioEffects/powers.dm
> +					var/callback = (SL && SL.stun_mode) ? /datum/targetable/geneticsAbility/shoot_limb/proc/hit_callback : null
```suggestion
					var/callback = (SL?.stun_mode) ? /datum/targetable/geneticsAbility/shoot_limb/proc/hit_callback : null
```

2020-10-12 02:55 UTC, Sovexe approved these changes

2020-10-16 18:18 UTC, merged