Adds nice borders for genetic powers
goonstation/goonstation pull request #2426
Opened 2020-10-14 05:27 UTC by monochromatism

## About the PR 

Exactly what it says on the tin.  Adds new borders, made by me, to the genetic power icons that appear in the gene booth and on the player's UI.

![genetics_powers_resprite-export](https://user-images.githubusercontent.com/67069006/95947301-e9568280-0db3-11eb-9952-fe88b96f8c9c.png)

## Why's this needed? 

The new borders look nicer than what currently exists in their place.  
Might also pave the way for further genetic power icon improvements.

## Changelog

```
(u)Monochromatism:
(+)Added new borders to genetic power icons for use in player and genebooth UIs.
```

2020-10-15 20:36 UTC, Sovexe commented
Why is `tk-2` deleted?

2020-10-18 22:21 UTC, ZeWaka requested changes
tk-2

2020-10-19 21:53 UTC, monochromatism commented
Sorry.  As I mentioned in my commit it's just called "tk", same as telekinetic pull. I'd thought it was unused or something. My bad.

2020-10-20 23:40 UTC, Sovexe approved these changes

2020-10-21 03:28 UTC, ZeWaka approved these changes

2020-10-21 03:31 UTC, merged