when joining the game, checks for vpn use. if its detected, kicks you w/ message
goonstation/goonstation pull request #2590
Opened 2020-11-04 01:22 UTC by Adharainspace

[ENHANCEMENT] [CLEANLINESS]

## About the PR 
checks for vpn use with an api. caches results in a global list on a per round basis - each ip is only evaluated once. vpn use is only checked if the account is relatively new to our servers, which should help circumvent a ban evasion technique. if we paid money, we could just check every incoming ip. but money bad. this does do some sleeps in client/New(), but those are only for when the person is being kicked, and it's because (for some reason) if you dont sleep for 3 seconds, the "this is why youve been kicked" screen doesnt show up. 

also did one tiny cleanliness change - make_player calls find player already. 

tested this all locally and it works as far as i can tell. has some logging too (maybe too much? idk). 

also wire said some things that went a bit over my head. i think i need to reach out about getting the api key put somewhere in the secret repo? ill modify my code to reflect that once its done. 

## Why's this needed? 
ban evaders use vpns and some other stuff to evade bans. disabling vpn use severely cripples that. 

## Changelog

```
(u)adharainspace:
(+)if you run into an issue where you can't join because of a vpn and you need to use one, please join the goonstation discord (https://discord.gg/zd8t6pY) and we'll see what we can do.
```

2020-11-04 01:24 UTC, Adharainspace commented
changelog needs phrasing worked on. will fix once i eat
perhaps popup window could have some better phrasing too

2020-11-04 01:44 UTC, Tarmunora commented
Would be nice if we could cache the IP list cross-round, Would cut down on API calls a lot.

2020-11-04 01:56 UTC, Adharainspace commented
> Would be nice if we could cache the IP list cross-round, Would cut down on API calls a lot.
*knocks on wires door*
"honey its time for ur daily add more api stuff for adharas code"

2020-11-04 03:33 UTC, bobbahbrown commented on code/client.dm
> +								<title>we detected that youre using a vpn</title>
```suggestion
								<title>we detected that you&apos;re using a vpn</title>
```

2020-11-04 05:06 UTC, Sovexe requested changes

2020-11-04 05:06 UTC, Sovexe commented on code/client.dm
> +		logTheThing("diary", src, null, "[address] is using a vpn that they've already logged in with during this round.", "debug")
`admin` log seems more appropriate I believe

2020-11-04 05:06 UTC, Sovexe commented on code/client.dm
> +											<h1>please disable your vpn, close the game, and rejoin.</h1><br>
same notes as above

2020-11-04 05:06 UTC, Sovexe commented on code/client.dm
> +			logTheThing("diary", src, null, "error: [response.error], address: [address] - CONSIDER DOING A MANUAL CHECK ON [address] at https://vpnapi.io/vpn-detection", "debug")
`admin` log seems more appropriate I believe

2020-11-04 05:06 UTC, Sovexe commented on code/client.dm
> +				logTheThing("diary", src, null, "[ret["message"]], address: [address]. CONSIDER DOING A MANUAL CHECK ON [address] at https://vpnapi.io/vpn-detection", "debug")
`admin` log seems more appropriate I believe

2020-11-04 05:06 UTC, Sovexe commented on code/client.dm
> +					logTheThing("diary", src, null, "[address] is using a vpn. vpn info: [json_encode(ret["network"])]", "debug")
`admin` log seems more appropriate I believe

2020-11-04 17:27 UTC, Adharainspace commented
as of right now, I'm gonna stop actively doing stuff with this branch, as Wire expressed an interest of taking over and finishing up what I didn't finish

2020-11-04 21:48 UTC, Cyprex commented
Consider notifying admins instead.

2020-11-05 16:02 UTC, Sovexe approved these changes
only other change I can think of is maybe having a server toggles for admins to disable the check on a per round basis in case of unseen and extenuating circumstances. Though whether or not such situation would ever arise I can not say

2020-11-05 18:59 UTC, Wirewraith commented
If someone can add the server toggle verb for this I'd be grateful.

2020-11-05 19:11 UTC, Adharainspace reviewed
ill add server toggles, and potentially a smarter way of handling this (disables all buttons / commands, doesnt del client, since this behaviour is inconsistent)

2020-11-05 19:11 UTC, Adharainspace commented on code/client.dm
> +					logTheThing("diary", src, null, "unable to check VPN status of [src.address] because: [data["message"]]", "debug")
```suggestion
					logTheThing("diary", src, null, "unable to check VPN status of [src.address] because: [data["message"]]", "admin")
```

2020-11-05 19:11 UTC, Adharainspace commented on code/client.dm
> +			logTheThing("diary", src, null, "unable to check VPN status of [src.address] because: [e.name]", "debug")
```suggestion
			logTheThing("diary", src, null, "unable to check VPN status of [src.address] because: [e.name]", "admin")
```

2020-11-13 05:09 UTC, merged