Wizard Hats
goonstation/goonstation pull request #2863
Opened 2020-11-28 18:02 UTC by binarysudoku

we are considering santa a wizard otherwise there are gonna be TOO MANY PRs

2020-11-28 18:36 UTC, flrsh requested changes
For the blue and pink wizard hats (same goes for red + gold hat when it gets added), could you try removing some of the darker shading pixels between the brim and the tip, to maintain the arch?
Can you also try a slightly lighter green for the shading on the green wizard hat?

Santa looks great, and I really like the bubblegum colors for the pink wizard hat. Rest of the hats also look really nice, and I'm a fan of the more vibrant colors.

2020-11-29 18:25 UTC, flrsh commented
I think @binarysudoku said that they were gonna slightly touch the green wizard hat?

2020-11-29 18:25 UTC, binarysudoku commented
@flrsh 

> I think @binarysudoku said that they were gonna slightly touch the green wizard hat?

oh fuck i didnt submit it? rip
 one moment please

2020-11-29 18:34 UTC, flrsh approved these changes

2020-11-29 21:38 UTC, merged