Fixes (sea)monkeys, adds lizard hair button, and refactors much of mutantcode
goonstation/goonstation pull request #2885
Opened 2020-11-30 03:14 UTC by Superlagg

## About the PR 

Seamonkeys get the right appendages, and humanizing monkeyclones should work properly now.

Added a button to admin polymorph to set someone's hair override, allowing hairless mutants to have hair. Enables barbering on these hairy lizard monsters.

When a head is severed, its flagged as a transplant, which makes a few vars unable to be changed. Vars like icon, state, and skin color (unless its a lizard's head attached to a lizard, then they can change that color all they want).

Refactored? the way mutants store and define their extra features. Such as:
- Instead of three details being hard-set to their corresponding customization colors and mutantrace dmi, they can now define their own icon and state, and pick which customization color through a var. Couldnt really figure out a decent way to do that *and* let people define a specific color, but its not impossible.
- Removed color flags, they were originally just there cus I was worried about hitting the bit limit thing. Also removed some unused and pointless flags and replaced them with various vars.
- Split normal hair and mutant head-things into two groups: Hair and special hair. This allows lizards and such to have their head things without it messing with their normal hair vals. This also means hairless mutants can be forced to have hair and it is *weird*.
- Moved most skintone flag checks to the mutant initialization procs. Lot easier to keep track of it here.

2020-12-01 03:13 UTC, Tarmunora requested changes
Also, some things to test:
 cloning mutantrace, cloning mutantrace with genetic analysis mode on, cloning with a mutantrace gene in the gene power, cloning a mutantrace with genetic analysis and also having a different mutantrace gene in gene power module.

Cycling a mob through many (all?) mutantraces sequentially

2020-12-01 03:23 UTC, Superlagg commented on code/mob/living/carbon/human/procs/update_icon.dm
> +						src.detail_standing_oversuit.overlays += human_detail_image
As far as I know, that's how the rest of the proc handles it. I'm also not super sure of the usage, Pali tried explaining it to me at least a few times and I still don't fully get how to use it.

2020-12-01 03:33 UTC, Superlagg commented on code/datums/mutantraces.dm
> +	* NOT_DIMORPHIC prevents the renderer from trying to render a non-existent female sprite, since none of the mutants are dimorphic.
Changed it to actually make sense now.

2020-12-01 07:21 UTC, Tarmunora commented on code/mob/living/carbon/human/procs/update_icon.dm
> +						src.detail_standing_oversuit.overlays += human_detail_image
mood

2020-12-02 02:11 UTC, Superlagg commented
Okay:
- Fixed invisible item limbs both being invisible and infecting the rest of the limbs with invisibility
- Made shamblers drop a skintoned human head when beheaded. Still going to look awful until they get chunked.
- Hulk/mutant interaction improved, should maintain the right skintone when combined with mutantraces. leaves you with hulk hair if you lose hulk as a mutant then return to human. 
- Heads should inherit their owner's name properly now. 
- Lizards have the right colors applied to their limb stumps.

2020-12-02 21:37 UTC, merged