Diving helmets
goonstation/goonstation pull request #2892
Opened 2020-11-30 20:12 UTC by binarysudoku

[HUMAN RESPRITE]

2020-11-30 22:44 UTC, flrsh requested changes
I think you're PRing to the wrong branch, you want the `human-resprite` one.

2020-11-30 22:49 UTC, binarysudoku commented
> I think you're PRing to the wrong branch, you want the `human-resprite` one.

shit, fixed; thanks for pointing that out

2020-11-30 23:13 UTC, flrsh approved these changes
These all look really nice to me! I especially like your take on the emergency suit and how you slightly changed the helmet on the side sprites and made it bulkier. Sorta reminds me of being a goldfish in space. One minor thing is that the industrial diving suit looks like its shoulders are hunched, though it could also maybe just be a stylistic thing? I think @Gannets made the original sprite.

2020-12-01 05:32 UTC, ZeWaka approved these changes

2020-12-01 23:37 UTC, flrsh approved these changes

2020-12-02 00:15 UTC, merged