Make killswitch timer count REAL ACTUAL SECONDS
goonstation/goonstation pull request #2947
Opened 2020-12-04 23:33 UTC by BenLubar

[BALANCE]

## About the PR

Empirically, the killswitch timer usually takes 180 seconds, so the timer has been changed from 60 mystery time units to 3 minutes.

The killswitch timer now records the timestamp for when it should end rather than the number of seconds remaining, making it more closely match the nuclear bomb timer.

## Why's this needed?

Nondeterministic self-destruct sequences are confusing and weird.

## Changelog

```
(u)BenLubar:
(+)The AI's killswitch now lasts 3 minutes rather than 60 mystery time units, each almost but not quite equal to 3 seconds.
```

2020-12-04 23:33 UTC, BenLubar commented
marking as draft because I haven't had a chance to test yet

2020-12-05 00:06 UTC, BenLubar commented
Alright, it works but it'll end up with "KILLSWITCH TIMER 0:-2" in some cases on the tick where the AI dies.

I believe the nuke does something similar, so probably not too big of an issue.

It'd be nice to have interpolated timers, but this is what we have available to work with for now.

2020-12-05 00:24 UTC, BenLubar commented
There appears to be a runtime when the AI's brain is ejected after it's already been ejected, but that's not new with this change. May be a good idea to auto-cancel the killswitch when it finishes so that it doesn't run again on the next tick.

2020-12-05 11:16 UTC, pali6 approved these changes

2020-12-07 06:34 UTC, Tarmunora commented
Wouldn't using the `TIME` macro be more accurate to realtime?

2020-12-10 20:15 UTC, pali6 commented
It would.

2020-12-25 16:59 UTC, BenLubar commented
Should I change it to use `TIME` or should I keep it using the method that nukes use?

2021-01-02 00:59 UTC, ZeWaka requested changes
I'd rather this used `TIME`

2021-01-03 08:47 UTC, ZeWaka approved these changes

2021-01-04 23:50 UTC, merged