Less shit botanist xp
goonstation/goonstation pull request #2976
Opened 2020-12-07 21:55 UTC by keiyakins

## About the PR 
Botanist XP sucks. I removed the percent chance for harvesting and rolling blunts, and I added some XP for using the PlantMaster to encourage players to experiment with seeds. 

## Why's this needed? 
Bring botanist XP more in line with player expectations - currently, you can harvest enough high quality weed to freeze the game for 30 seconds when the pile gets set on fire, in a 60 minute round, and get 10 xp. Fuck that.

## Changelog

```
(u)Keiya:
(*)Significantly increase Botanist XP rewards. You can also get XP from splicing and infusing seeds now!
```

2020-12-11 23:02 UTC, Kyle2143 requested changes
These changes look much too high. I can understand raising them a bit as right now botany xp is lower than most even considering it's the newest job xp, but not flatly like this.

Botany xp amounts are artificially low, which I always err on the side of when making new job xp. I hadn't checked on the numbers in a while so that's my bad.

Ideally I'd like the seed harvast to matter based on seed quality based on seed attributes. But not exactly correlating to the quality var.

2020-12-16 17:31 UTC, keiyakins commented
I probably overshot a bit, yeah. I frankly kind of forgot you can just splice together random seeds instead of only doing it when you want the result.

Is there a target XP-per-hour for a reasonable playstyle that I should be aiming for? No one has this documented anywhere.

2020-12-20 08:25 UTC, Kyle2143 commented
Whoops, forgot about this. Yeah, Keelin made the first job XP for janitors and I've made all the rest, I mostly tried to base base the numbers around the janitor's by eye. There is a blurb about how much you should expect to earn in an hour I think somewhere, but I'd have to go looking, I think it was moved by zewaka a while ago when he split up the define macros. It might just be the cap for xp you can earn in one round which I thiiiiink might be 6k? But that sounds really high so idk, I'll look later, perhaps I should change it to be lower if it is that high.

I never really thought about the ideal xp you'd expect to earn for an hour of decent playtime, but if I had to hazard a guess, I'd say about 300-500 points. And then, since exp generation is throttled, it I wouldn't expect more than double that if you're trying super hard, doing activities that grant xp.

2020-12-23 13:27 UTC, frawhst commented
from macros/job_xp:
`
/**
	* This much XP is allowed per XP_THROTTLE_TICKS. Should prevent people from exploiting certain things.
	* This cap is ignored if a person if awarded XP in excess of this cap in one burst.
	*
	* Roughly 2 times the expected XP per minute, currently.
	*/
#define XP_THROTTLE_AMT 10
`
so 300 is the 'expected' XP per hour. I think the most botanist XP I've earned is ~30 in a 2 hour round, so even if this is dialed back a bit, I'd really like to see the XP changed somehow.

2021-01-14 01:01 UTC, closed without merging