Equips medical doctors with medical belts and medical pouches on spawn.
goonstation/goonstation pull request #2985
Opened 2020-12-08 15:35 UTC by Carbadox

## About the PR 
Give Medical Doctors medical belts and pouches already equipped onto them.

## Why's this needed? 
Medical doctors having to fight over storage space is dumb. This should make things easier for them

## Changelog

```
(u)Carbadox
(*)Medical doctors now start with medical belts and pouches already equipped onto them.
```

2020-12-08 16:15 UTC, mordent-goonstation requested changes

2020-12-08 16:15 UTC, mordent-goonstation commented on code/datums/jobs.dm
> +	slot_poc2 = /obj/item/storage/medical_pouch
Hard disagree on adding the pouch. These are intended for Nuke Ops "Combat Medics", not regular doctors.

2020-12-08 16:15 UTC, mordent-goonstation commented on code/obj/item/storage/ammo_pouches.dm
> +	does_not_open_in_pocket = 0
Even the nerfed version seems ridiculously good - you're essentially giving doctors another 3 pockets. Strong disagree on adding this.

2020-12-08 16:20 UTC, Gerhazo commented
Don't personally think inventory management needs to be trivialized further or that the change's necessary.

Personal opinions aside, as some input in terms of code, with the original currently existing /obj/item/storage/medical_pouch being present for nukeops and an /obj/item/storage/medical_pouch/medic being intended for regular use, it'd probably make more sense to have the architecture be structured the other way around, with /obj/item/storage/medical_pouch for the more general regular pouch and /obj/item/storage/medical_pouch/syndicate (or some other wording of the sort to reflect nuclear operatives, probably in line with what other nukeop-labeled things in code are) for the more specific sort of medical pouch.
At least that's what I think would be more optimal and self-descriptive pathing requiring no use of "used by regular doctors" code comments.

2020-12-09 08:28 UTC, Awfullyfishy commented
I strongly agree with the medical belt part, as Engineers and Mechanics start with Utility Belts and yet Medical Staff have to fight over Medical Belts and there's rarely more than 2-3 depending on the map. The pouch I however strongly disagree with. While nice, it's a bit too much.

2020-12-10 18:36 UTC, mordent-goonstation approved these changes

2020-12-10 18:36 UTC, merged