Tug can pull a wheeled cart
goonstation/goonstation pull request #3324
Opened 2021-01-14 06:00 UTC by EnterpriseProgrammer

## About the PR 
Adds two OR statements to allow tug vehicles to pull a single wheeled cart. Flatbeds are not able to be attached to the back of a wheeled cart.

I imagine that tugs could be used to move the emergency equipment already set up (Medbay, Engineering repairs, Forensics) more quickly, either if mechanics makes one for the departments or if more tugs are included in the maps. Either way, this change allows for more tug utility beyond delivering cargo crates.

## Why's this needed? 
Adds to the utility of the tug and further completes the logic for wheeled emergency carts of different purposes.

## Changelog

Tugs can now pull wheeled carts.

2021-01-14 08:47 UTC, ZeWaka commented
Please follow the proper changelog format, otherwise it won't get picked up.

2021-01-16 09:48 UTC, ZeWaka commented on code/WorkInProgress/tug.dm
> +			if (istype(C, /obj/tug_cart) || istype(C, /obj/storage/cart))
umm what, why is there two of these????

2021-01-16 15:51 UTC, EnterpriseProgrammer reviewed
Removed the redundant double-if at Line 23/24.

2021-01-16 16:24 UTC, EnterpriseProgrammer commented
Welp, apparantly that double if statement is necessary for some reason, according to the checks.

2021-01-16 20:22 UTC, ZeWaka requested changes

2021-01-16 20:22 UTC, ZeWaka commented on code/WorkInProgress/tug.dm
> +			if (istype(C, /obj/tug_cart) || istype(C, /obj/storage/cart))
No, it's not necessary, you're just not grasping that DM is indentation sensitive and therefore you can't just remove if statements without adjusting the inner body.

2021-01-16 23:43 UTC, ZeWaka commented on code/WorkInProgress/tug.dm
>  			var/obj/tug_cart/connecting = C
this will runtime on line 27 due to a miscast

2021-02-11 03:03 UTC, ZeWaka approved these changes

2021-02-14 04:40 UTC, merged