Adds action bar to power cell swapping
goonstation/goonstation pull request #3418
Opened 2021-01-21 15:58 UTC by Sord213

[BALANCE]

## About the PR 
Adds a short action bar to power cell swapping

## Why's this needed? 
Right now swapping power cells is an instant effect and can be done on the move mid-combat. This would slightly slow down combat by making it a more active decision to swap your cell out when need be, rather than the current run and gun swap 5 cells out of your pocket it is now.

## Changelog

```changelog
(u)mbc and Sord:
(*)Added short action bar to power cell swapping
```

2021-01-21 16:27 UTC, Carbadox commented
Kinetic guns reload instantly but energy guns aren't supposed to? 

🤔

2021-01-21 16:32 UTC, PrimeNumb commented
Also if this is unfinished then consider making it a draft PR.

2021-01-21 16:58 UTC, flappybatpal commented
> Kinetic guns reload instantly but energy guns aren't supposed to?
> 
> 🤔
> 
> Also this come of as a very reactionary change against a specific person

No reason a similar thing couldn't be done although kinetic varies a lot in capacity so a one size fits all reload might not make sense.
Regardless, energy stun weapons are considered stronger than kinetic right now.

2021-01-21 18:32 UTC, Tarmunora commented
> Also this come of as a very reactionary change against a specific person

This came about as a result of internal discussion about power cells because of the inclusion of extra cells as utility items in #3413.

2021-01-21 19:31 UTC, Carbadox commented
> > Kinetic guns reload instantly but energy guns aren't supposed to?
> > 
> > 🤔
> > 
> > Also this come of as a very reactionary change against a specific person
> 
> No reason a similar thing couldn't be done although kinetic varies a lot in capacity so a one size fits all reload might not make sense.
> Regardless, people generally say kinetic guns aren't very good.

That kind of change affects Nuclear Operatives as a whole too. Unless there was some sort of trait added that let Nukies reload instantly but in that case I don't see Security wouldn't be eligible for a similar trait for energy weapons. 

I don't see a correlation between what the PR wants to change and the example that's given. Learning to navigate your backpack and reload mid combat is a part of learning the game.

Someone who has 5 cells in his bag is sacrificing 5 inventory spaces which could be used to store other vital items, whether it's a medkit, stun baton, barrier, box of tools, lethal gun, bomb, box of drinking glasses with hellchems, hand tele, whatever. 

If anything, removing the ability to reloading by smacking guns against ammo would resolve the issue presented

2021-01-21 21:08 UTC, Sord213 commented
> 
> That kind of change affects...
>
If down the line action bars were added to kinetic weapons there would be a bit more involved in balancing the reload times. Something like the LMG would most likely have a longer reload time but a pistol would be quick. But that's a discussion for another time.

Like Tarm said this wasn't aimed at anyone or any playstyle specifically, it was just a change that seemed pretty well needed in terms of balancing combat. Something like the NTSpecialO has a pouch with 5 power cells for their laser assault rifle. Adding a short timer to reloading where you have to stop moving in combat makes you have to think about your actions more. Same with tasers or eguns. You can't just magdump people then instantly swap cells and keep blastin.

2021-01-30 19:24 UTC, ZeWaka requested changes

2021-01-30 19:24 UTC, ZeWaka commented on code/obj/item/gun/ammo.dm
> +
```suggestion
```

2021-01-30 19:24 UTC, ZeWaka commented on code/obj/item/gun/ammo.dm
> +
```suggestion
```

2021-01-30 19:24 UTC, ZeWaka commented on code/obj/item/gun/ammo.dm
> +
```suggestion
```

2021-01-30 19:24 UTC, ZeWaka commented on code/obj/item/gun/ammo.dm
> +	duration = 10
```suggestion
	duration = 1 SECOND
```

2021-01-30 19:24 UTC, ZeWaka commented on code/obj/item/gun/energy.dm
> +				actions.start(new/datum/action/bar/icon/powercellswap(user,pcell,src), user)
```suggestion
				actions.start(new/datum/action/bar/icon/powercellswap(user, pcell, src), user)
```

2021-02-12 02:53 UTC, ZeWaka approved these changes

2021-02-12 03:26 UTC, merged