fix crate dragging with traders
goonstation/goonstation pull request #3548
Opened 2021-01-30 23:16 UTC by zjdtmkhzt

## About the PR 
Apparently this has been broken for a while?
There is a pinned issue for it, to be honest, I never see those because I never look to the pinned issue area.
fixes #2061
@pali6 writes that it should be it's own proc, honestly, I don't see the need for that, it seems like a simple typecheck to me but what do I know.
Anyway, even if the way I fixed it is bad, it's probably better than leaving it broken for another 5 months.^^

## Why's this needed? 
It's a pretty cool feature!

## Changelog

```changelog
(u)zjdtmkhzt
(+)Dragging crates onto traders to sell their contents should now work again.
```

2021-01-30 23:22 UTC, zjdtmkhzt commented
Is the issue something like white weed vs normal weed?
In that case we could either just take care with the order in which commodities are stored, or we first check for exact matches and then just types.
Not sure if we already have a thing like that for regular trades? I didn't see one.

2021-01-30 23:42 UTC, zjdtmkhzt commented
Yeah, lol, don't merge this yet, right now you get the money for all the types your item applies to.^^

2021-01-31 00:26 UTC, zjdtmkhzt commented
ok, done, moved it to its own proc!

2021-01-31 06:57 UTC, ZeWaka requested changes

2021-01-31 06:57 UTC, ZeWaka commented on code/modules/economy/trader.dm
>  				for (var/obj/M in O.contents)
M? For an OBJ????

2021-01-31 06:57 UTC, ZeWaka commented on code/modules/economy/trader.dm
> +	for(var/datum/commodity/N in goods_buy)
specify the type of list in the proc argument and make this an `as()`

2021-01-31 16:23 UTC, pali6 approved these changes

2021-02-01 17:59 UTC, ZeWaka approved these changes

2021-02-01 19:56 UTC, merged