make rarer artifacts more likely to vary in appearance
goonstation/goonstation pull request #3610
Opened 2021-02-05 04:42 UTC by zjdtmkhzt

## About the PR 
This makes artifacts with a lower rarity_weight (which appear less often) more likely to have some of the random appearance variations (mostly) based on their origin.

Some of the variations were already so common that I just made the rarity not affect their probability.

Right now the highest tier of artifact will make some things about 5x more likely, so you end up with probabilities like 25%/50%.
The most common artifacts (what used to be tier 1 and 2) will have only slightly higher probabilities.
The numbers are kind of made up, so I am open to suggestions on changing them!
## Why's this needed? 
Ever since the appearance variations are added, I get a little excited when I see a weird looking artifact, thinking, "I wonder what that would do!".
I think it'd be neat if that were actually a small clue that it might be a more special kind of artifact!

2021-02-05 08:29 UTC, pali6 requested changes
I don't think the scaling is all that well thought out here. I'd expect the `get_rarity_mod()` proc to return a number in range 0-1 (let's say with 0.1 for lowest tier and 1.0 for highest tier or something like that). In that case doing `prob(10 * rarityMod)` makes it so you set the upper bound of the probability of the effect to 10%. While currently the number is sorta arbitrary.

To compensate this change the base probabilities should likely be increased.

2021-02-05 08:29 UTC, pali6 commented on code/datums/controllers/artifact_controls.dm
>  		if(prob(40))
Who not the colour variation too?

2021-02-05 08:35 UTC, pali6 commented
Wild thought: To ensure the 0-1 range of the rarity mod it could be exponential. Something like `2 ** (-rarity_weight / some_constant)`.

2021-02-05 19:45 UTC, zjdtmkhzt commented
Yeah, using an exponent sounds like a much better idea!

2021-02-06 13:33 UTC, pali6 approved these changes

2021-02-06 13:33 UTC, merged