Adds drains under ChemiCompilers
goonstation/goonstation pull request #3671
Opened 2021-02-10 17:13 UTC by Carbadox

## About the PR 
Adds drains under ChemiCompilers

## Why's this needed? 
This comes from a feature request from someone (I forgot who, Im sorry).
The CC has a function to dump it's contents out, which spills it out on the floor. Someone asked if drains could be added onto the floor so that it doesnt keep making a mess.

2021-02-10 18:58 UTC, Azrun commented on maps/clarion.dmm
> +/obj/machinery/drainage,
And a voice rang out, "No changes to Clarion are currently permitted".

2021-02-10 22:02 UTC, Azrun commented
Should the drain be adjacent to the ChemiCompiler instead?  Seems like you could use the ChemFuck to time and mix/release a hellchem that you want to fill the room.  You would be able to `ctrl+alt+shift` and clog the drain, but it would improbable for anyone else to realize that is what happened or how to deal with it (except for 🤓).

2021-02-20 20:42 UTC, ZeWaka commented
yeah i don't like having the drain be under the machine, that limits mechanics like flooding the room

drains adjacent would be fine though

2021-02-20 20:43 UTC, ZeWaka requested changes
x

2021-03-02 20:47 UTC, Azrun commented
Looks like some of the drains directly under the ChemiCompilers are still there. (As per Map Diff Render of 0ef6dc9)

Kondaru
![kondaru](https://camo.githubusercontent.com/f869a3b52499c0b5474fa97cf9d42b5d4e9f2ee130659a42e38482e1a0ed2764/68747470733a2f2f6d64622e616666656374656461726330372e636f2e756b2f46696c65732f3235323034373438332f313938303835373436372f352f61667465722e706e67)

Horizon
![horizon](https://camo.githubusercontent.com/4c2fa2ecfa378a2f6db519f1b586e20de2043a768da4030ceb7a6840858ce3c3/68747470733a2f2f6d64622e616666656374656461726330372e636f2e756b2f46696c65732f3235323034373438332f313938303835373436372f342f61667465722e706e67)

Oshan
![image](https://user-images.githubusercontent.com/1017374/109712406-d838c300-7b54-11eb-817e-2d6664f677f7.png)

2021-03-06 02:31 UTC, ZeWaka requested changes
X

2021-03-15 18:36 UTC, geneva-breaker commented
Not a huge fan. 
This is one of those "If the mapper intended to do this, they would have done this" situations in my opinion. One of the CC's strenghths is its use in flooding and foaming on the floor, and if someone wanted to install a drain I think they could do that in-round. 

If it's a common-enough irritant, maybe providing chemistry departments with One ready-to-deploy drain in a box would be a good QoL improvement, they could use it wherever they like.

2021-03-15 19:37 UTC, closed without merging