Using a screwdriver on a credit transfer devices will now unanchor them.
goonstation/goonstation pull request #3717
Opened 2021-02-14 12:21 UTC by Carbadox

## About the PR 
Using a screwdriver on a credit transfer devices will now unanchor them.

## Why's this needed? 
Not being able to manipulate items isn't great and currently you can only smash it completely but only with a wrench which is just bizzare.

## Changelog

```changelog
(u)Carbadox
(+)Using a screwdriver on a credit transfer devices will now unanchor and let you move them.
```

2021-02-14 18:11 UTC, glassofmilk commented
Wrench is normally the tool for anchoring/unanchoring - I think it might make more sense to use a wrench for this instead of a screwdriver.

2021-02-14 19:13 UTC, Carbadox commented
> 
> 
> Wrench is normally the tool for anchoring/unanchoring - I think it might make more sense to use a wrench for this instead of a screwdriver.

The item already uses wrenches, but only for destroying the item for whatever reason. I kept it there in case someone would say it's best for it to stay there. But if people say otherwise, I can make it use wrenching and screwing instead

2021-02-14 21:30 UTC, MatheusIsNotAvailable commented
Some stuff uses both wrenches and screwdrivers like the plant trays, dosen't really matter wich one you pick imo

2021-02-14 21:59 UTC, BatElite commented
For consistency's sake you can replace the wrenching thing with the anchoring code. I kinda feel 1/3 chance to break it is superfluous when you can use a deconstructor.

2021-02-16 23:10 UTC, ZeWaka requested changes

2021-02-16 23:10 UTC, ZeWaka commented on code/obj/machinery/cashreg.dm
> +				src.anchored = 0
```suggestion
			user.visible_message("<b>[user]</b> [anchored ? "unbolts the [src] from" : "secures the [src] to"] the floor.")
			playsound(src.loc, "sound/items/Screwdriver.ogg", 80, 1)
			src.anchored = !src.anchored
```

2021-02-25 23:43 UTC, ZeWaka approved these changes

2021-02-25 23:44 UTC, merged