Using cameras allows one viewport
goonstation/goonstation pull request #3728
Opened 2021-02-15 08:04 UTC by Borkatator

## About the PR 
This PR allows creating one viewport from the security cameras windows.

This viewport cannot be opened if another one exists, if you are not adjacend to the security computer, and closes automatically if you move away, or close the security camera window, in order to avoid exploits.

## Why's this needed? 
As a secoff, I sometimes like to watch cameras. However it takes the whole screen and I cannot see my colleagues anymore.
This PR would allow me to still see and talk to my colleagues while watching cameras, but hard limits on being able to open only 1 viewport, and not being able to move prevent this from being too powerful.

## Changelog

```changelog
(u)Borkatator
(*)Allow creating one viewport when watching camera feeds
```

2021-02-15 09:29 UTC, Superlagg commented
Can you connect mechcomp things from the viewport to the main window with a multitool?

2021-02-15 09:34 UTC, Borkatator commented
> Can you connect mechcomp things from the viewport to the main window with a multitool?

I'm not sure I understand the question.
Like using a multitool on a component in the viewport, and dragging to the main window to connect them together ?


I haven't tested this. I guess if this worked with previous viewports, it would still work.

2021-02-18 04:35 UTC, ZeWaka commented
> Can you connect mechcomp things from the viewport to the main window with a multitool?

not if they use in_interact_range or similar....

2021-02-18 04:49 UTC, Superlagg commented
> > Can you connect mechcomp things from the viewport to the main window with a multitool?
> 
> not if they use in_interact_range or similar....

Unless it's changed in the past year, you could use a camera to connect mechcomp things across the station. I know now it's limited in range, but i think it should still be possible if they're close enough.

2021-02-20 08:11 UTC, Borkatator commented
> > > Can you connect mechcomp things from the viewport to the main window with a multitool?
> > 
> > 
> > not if they use in_interact_range or similar....
> 
> Unless it's changed in the past year, you could use a camera to connect mechcomp things across the station. I know now it's limited in range, but i think it should still be possible if they're close enough.


I just tested it, and yes, it tells me if they are more than 14 tiles apart, but aside from distance it doesn't prevent it.

I also pushed a new commit as I found a case where an Index error was raised.

2021-02-21 20:59 UTC, ZeWaka requested changes

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security/security_cameras_chui.dm
> +
```suggestion
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security/security_cameras_chui.dm
> +			if(viewports.len >= 1)
```suggestion
			if(length(viewports))
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security.dm
> +	src.using_viewport = 0
```suggestion
	src.using_viewport = FALSE
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security/security_cameras_chui.dm
> +				owner.using_viewport = 1
```suggestion
				owner.using_viewport = TRUE
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security/security_cameras_chui.dm
> +				boutput( clint, "<b>You need to select a camera before creating a viewport.</b>" )
```suggestion
				boutput(clint, "<b>You need to select a camera before creating a viewport.</b>")
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security.dm
> +				src.using_viewport = 0
```suggestion
				src.using_viewport = FALSE
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security.dm
> +	proc/move_security_camera(/*n,*/direct,client/clint)
```suggestion
	proc/move_security_camera(direct, client/clint)
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security.dm
> +		var/mob/living/carbon/user = clint.mob
we can't assume this type

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security.dm
> +	var/using_viewport = 0
```suggestion
	var/using_viewport = FALSE
```

2021-02-21 20:59 UTC, ZeWaka commented on code/obj/machinery/computer/security.dm
> +				if(get_dist(src,subscriber.mob) > 1 && viewports.len > 0)
```suggestion
				if(get_dist(src,subscriber.mob) > 1 && length(viewports))
```

2021-02-21 22:51 UTC, Borkatator commented
Thanks for the review.

I have also found that when using the viewport, selecting a camera changes the main view and not the viewport so i corrected this.

Since this caused a problem with the using_viewport flag, and found no good way to detect when the viewport window was closed, I ended up getting rid of the flag, and just checking the presence of a "cameras: Viewport" type viewport.

I have applied the other requested changes.

I have also tested it as a silicon, since I think that is what you meant by your comment:
`we can't assume this type`

2021-02-22 01:06 UTC, ZeWaka approved these changes

2021-02-22 01:06 UTC, ZeWaka commented on code/obj/machinery/computer/security.dm
> +		var/mob/user = clint.mob
Yeah I was just commenting on how you don't necessarily know that a human is interacting with it, you only know a mob is

2021-02-22 10:44 UTC, Borkatator commented
@ZeWaka sorry about that last rivet request, it's a misclick

2021-02-24 09:26 UTC, merged