Updating tour guide speech rate to better use maptext
goonstation/goonstation pull request #3776
Opened 2021-02-20 10:18 UTC by Azrun

[bug - minor]
## About the PR 
Allows tourguide "presentations" to be further broken up to to be displayed as maptext.
![tour_pause](https://user-images.githubusercontent.com/1017374/108592244-cd468d00-7321-11eb-8abc-20385167fbff.png)

- [ ] Add pic on beta build.

*  Original presentation in chat is maintained. 
![image](https://user-images.githubusercontent.com/1017374/108591546-27455380-731e-11eb-8760-f4c0c5e2707a.png)

* Add chat style for bots (Consolas looks great in chat but terrible as maptext)

Tourguide transition out of "presenting" is based on the tour text and process rate of guide.

Added spawn to some code paths to help ensure `machines` `doWork` wasn't put to sleep.

- [ ] Make pass on tours to ensure there isn't anything goofy.
- [ ] Make sure azone tour behaves as "expected".
- [ ] Ensure timings for text are consistent but account for comedic timing.

## Why's this needed? 
Improve tour guide experience.

## Changelog

```changelog
(u)Azrun
(+)Improve tour guide floating chat display.
```

2021-03-04 17:02 UTC, ZeWaka requested changes

2021-03-04 17:02 UTC, ZeWaka commented on code/modules/robotics/bot/guardbot.dm
> +
```suggestion
```

2021-03-04 17:02 UTC, ZeWaka commented on code/modules/robotics/bot/guardbot.dm
> +			SPAWN_DBG(0) // do not delay doWork
:)

2021-03-05 02:44 UTC, Azrun commented on code/modules/robotics/bot/guardbot.dm
> +			SPAWN_DBG(0) // do not delay doWork
waht

2021-03-05 02:47 UTC, Azrun commented on code/modules/robotics/bot/guardbot.dm
> +			SPAWN_DBG(0) // do not delay doWork
🙀

2021-03-05 06:26 UTC, ZeWaka approved these changes

2021-03-06 02:30 UTC, merged