Adds some basic ways to earn Job XP for Chefs
goonstation/goonstation pull request #3778
Opened 2021-02-20 12:12 UTC by Carbadox

## About the PR 
Adds some basic ways to earn Job XP for Chefs. Will expand more to methods later on hopefully

## Why's this needed? 
To help expand the Job XP system for chefs

## Changelog

```changelog
(u)Carbadox
(+)Added some basic ways to earn Job XP for Chefs.
```

2021-02-20 12:55 UTC, BatElite commented on code/modules/food_and_drink/cakes.dm
> +				JOB_XP(user, "Chef", 1)
Applies for every change, but I think the `JOB_XP` macro already checks if their job matches before giving XP.

2021-03-09 17:50 UTC, ZeWaka requested changes
you have a review.

2021-03-30 10:51 UTC, Carbadox commented
Its been over a month

2021-04-09 21:55 UTC, flrsh approved these changes

2021-04-09 21:55 UTC, flrsh commented on code/obj/kitchenspike.dm
> +			JOB_XP(user, "Chef", 1)
```suggestion
		JOB_XP(user, "Chef", 2)
```
Imo.

2021-04-10 03:16 UTC, Kyle2143 reviewed
These seem good to me at first glance. The values are a bit low, and there is plenty more room to add things to get exp like butchering, frying, gibbing. But it's a good start, and it's better to start with lower xp rates when it's new IMO.

Just fix that one line, and as flourish suggested, it would probably be fine to increase the values a bit more or remove probs if they are on things that aren't too repeatable. But idk enough about the chef role and these objects to say which they are.

2021-04-10 03:16 UTC, Kyle2143 commented on code/modules/food_and_drink/ingredients.dm
> +		if (prob(25))
For safety I'd move this conditional above the qdel(src). Probably would never cause a problem, but it just doesn't make sense to have code to be executed om an object after you have it slated for garbage collection.

2021-04-11 22:51 UTC, Kyle2143 approved these changes

2021-04-11 23:14 UTC, ZeWaka requested changes

2021-04-11 23:14 UTC, ZeWaka commented on code/modules/food_and_drink/ingredients.dm
> +			JOB_XP(user, "Chef", 1)
did you forget to delet this

2021-04-15 17:22 UTC, merged