Add a golden crayon for the head of personnel to have.
goonstation/goonstation pull request #3781
Opened 2021-02-20 17:20 UTC by stonepillars

## About the PR 
Add a golden crayon, which is distinct from a gold-plated crayon, as this one can write in gold material forever<sup>\*</sup>. It can be found in the Head of Personnel's office on all rotation maps, other than Manta.

<sup>\* Technically, 123,456 times. Good as forever!</sup>

## Why's this needed? 

The Head of Personnel lacks a consistent theft objective item. The only one they have is the First Dollar on Manta. The golden crayon has been added for the other maps. It's also a smaller but equally awesome counterpart to the Captain's golden toilet.

## Changelog

```changelog
(u)Stonepillar
(*)Added the golden crayon. It can be found in the Head of Personnel's office. Beware of possible theft!
```

2021-02-21 21:10 UTC, flrsh approved these changes

2021-02-21 23:14 UTC, Carbadox commented
How about making it a possible job reward?

2021-02-21 23:20 UTC, stonepillars commented
> 
> 
> How about making it a possible job reward?

This is more along the lines of the Captain's golden toilet, or the HoS's war medal, its something you can use (You can take a shit on the golden toilet, or wear the HoS medal). This is no different, you can use it to streak the floors in golden crayon wax.

Something more appropriate for a HoP job reward would be a special ID card, a fancy stamp, maybe a cooler chair? This is something meant to be there every round (unless something similar exists, see Manta's First Bill)

2021-02-22 07:28 UTC, ZeWaka commented on maps/clarion.dmm
> +/obj/machinery/firealarm{
no changes are permitted to clarion at this time

if you wish to make changes you must ask dions

2021-02-22 07:29 UTC, ZeWaka requested changes
^

2021-02-27 01:32 UTC, ZeWaka approved these changes

2021-02-28 21:21 UTC, merged