Artifact selling and classification
goonstation/goonstation pull request #3818
Opened 2021-02-24 12:28 UTC by zjdtmkhzt

## About the PR 
Adds some form type stuff that you can use to describe artifacts, specifically their origin, type, and activation method.
There's also some freeform fields for describing faults and other stuff.
They work like stickers, if you slap one on an artifact and all the info is correct, it'll make the artifact have the real name. 
(They will no longer have the real name just from being activated.)

You can also sell artifacts via cargo now, how much money you get depends on the rarity of the artifact and whether or not it has a sticker with the correct info about it stuck to it.
The price ranges from about 300 to 900 for the more common artifacts up to 12.000 for the very rare ones.
(These prices are when fully analyzed, when unanalyzed it is only a third.)
If you're lucky, you might also get a new artifact sent in at cargo a few minutes after having one sent out.
(This also scales with the rarity of the artifacts that were sent out.)

Beware the terrible codersprites and also terrible coder-ui.
![image](https://user-images.githubusercontent.com/35579460/109000540-20af3700-76a4-11eb-944f-141708984c1a.png)

## Why's this needed? 
- I find that documenting information about artifacts gives the artlab even more of a "sciencey" feel.
- Selling artifacts is a feature that I often see requested.
- This will give at least some use to stuff like lamps/gravity wells/noisemakers.
- The artlab getting more artifacts from cargo and cargo getting money from the artlab should foster interdepartmental cooperation.
- It gives more options for the artlab to get more artifacts without having to bugger off to space when mining isn't very active and without having to metagame all the guaranteed artifact spawn locations.
## Changelog

```changelog
(u)zjdtmkhzt
(*)Artifacts are now sellable, details in the popup thing
(+)Money depends on artifact rarity.
(+)Artlab has these forms you can fill out. If you fill it out correctly and slap it on an artifact, you'll get a lot more money for it.
(+)Sometimes cargo might get new artifacts sent in if they previously sent nice ones out.
```

2021-02-24 12:29 UTC, zjdtmkhzt commented
I still need to polish the UI a little and add the form dispensers to the other maps, but since the code is basically done, I just thought I'd put this up to get feedback in the meantime.

2021-02-24 18:09 UTC, Boxlta commented
Vry good, looks cool, Selling arts is one thing that felt like it could be a cool system.

2021-02-24 19:40 UTC, ZeWaka commented
what is the 'popup thing'

2021-02-24 22:28 UTC, Azrun commented
Seems like a number of the artifact types can be condensed (bombs, wand/non-wand, power cells) from a player perspective.  Bomb types seem to be differentiated based on xray feedback which seems like it would require previous experience or a code dive?  I’d expect groups similar to wiki.  Being able to reward for the differentiation is neat though, seems like a great use of additional info but would then require _PARSING_.

Is the name “Precursor” appropriate?  Outside of the wiki didn't really find anything that called them out as such, but my lore is weak.

Really like that most of this is generated programmatically. 👨‍💻 

Might be neat to roll in lastAnalysis correctness into how crate is received.  Maybe improve/adjust delay or rarity of artifacts.  “You have been identified as a critical artifact researcher! You have been rewarded with more work!”

2021-02-25 00:19 UTC, ZeWaka requested changes

2021-02-25 00:19 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/ArtifactPaper.js
> +        <h4>{artifactName===""?"unknown":artifactName}</h4>
spacing please

2021-02-25 00:19 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/ArtifactPaper.js
> +          backgroundColor="#DDDDDD"
hardcoded colors boo

2021-02-25 05:10 UTC, zjdtmkhzt commented
Hmm, I guess they are never explicitly referred to as Precursors in the game, but they aren't really ever referred to anything ingame.
The wiki calls them Forerunners, but that title is absolutely never used ingame, I think, and it does mention that Precursor is another name for them.

Honestly, I always call them Precursor ingame, seeing as there's no actual name that is ever given and Precursor sounds way cooler. I think people will figure it out, based on the wiki?

2021-02-25 05:11 UTC, zjdtmkhzt commented on code/obj/artifacts/artifactanalysis.dm
> +		if(length(A.triggers) == 0 || A.automatic_activation)
I considered using !, but seeing as it's not a boolean kind of thing but actually an integer, I felt using a proper comparison would be clearer?

2021-02-25 05:19 UTC, zjdtmkhzt commented on code/obj/artifacts/artifactanalysis.dm
> +		if(length(A.triggers) == 0 || A.automatic_activation)
But I guess I don't mind changing it either.

2021-02-25 05:57 UTC, zjdtmkhzt commented
That reminds me, I should probably use the nice names for the bomb alerts, now that we have them.

2021-02-25 08:21 UTC, ZeWaka approved these changes

2021-02-25 10:14 UTC, zjdtmkhzt commented
Added to all the player pickable maps except Clarion now.

2021-02-26 20:24 UTC, merged