Update scanners.dm
goonstation/goonstation pull request #3860
Opened 2021-02-28 00:59 UTC by F-OS

[BALANCE]
## About the PR 
Allows the detective scanner to scan objects up to 2 tiles away.
## Why's this needed?
This fixes the oversight where you put scanners into containers while allowing the detective to have a bit more latitude when conducting cases by scanning objects at a distance. I think this would increase quality of life for detective players, while not messing up game balance too much. This is a webeditor PR but the code was tested and confirmed to work in DM.
## Changelog

```changelog
(u)Fosstar
(+)Allows the detective scanner to scan objects up to 2 tiles away.
```

2021-03-03 19:03 UTC, ZeWaka commented on code/obj/item/device/scanners.dm
> +		return
useless

2021-03-10 19:48 UTC, ZeWaka requested changes

2021-03-10 19:48 UTC, ZeWaka commented on code/obj/item/device/scanners.dm
> +		if(get_dist(user, target) > 1 && get_dist(user, target) <= 2)
IN_RANGE

2021-03-13 20:36 UTC, Tarmunora requested changes
Could we get this *only* for a "detective's personal scanner" item? Would be nice to reinforce the feel that they are better equipped than standard security for forensics work.

2021-03-14 08:32 UTC, ZeWaka commented
/unique is a bad path name

2021-03-14 20:47 UTC, Tarmunora approved these changes

2021-03-14 20:47 UTC, merged