stop pulling stuff if it's inside other stuff
goonstation/goonstation pull request #3899
Opened 2021-03-05 10:41 UTC by zjdtmkhzt

## About the PR 
This stops the pulling process if the item you are trying to pull is inside another thing. 
Not sure if this is the best way to implement this, but this is what I came up with.
## Why's this needed? 
Mainly because recently there is a really annoying bug where if you are pulling a thing that is inside another thing, for some reason you walk two or three times for every time you press a walk button and I couldn't find the actual cause of that.
The walk process seems to be triggered several times, but by what?? It's a mystery.

Apparently the get_dist check uses the loc of the container if the pulled thing is inside something? Who knew!

It mainly happens when you pull around artifacts and then put them into pods/artlab machines and suddenly you zoom around and can't control yourself until the pulling stops itself, which is really annoying.

2021-03-05 10:50 UTC, zjdtmkhzt commented
Just saw that there's also a macro called IN_RANGE that does something similar, not sure if I should use that instead or keep it simple like this for performance or something?

2021-03-06 00:03 UTC, ZeWaka commented
> Just saw that there's also a macro called IN_RANGE that does something similar, not sure if I should use that instead or keep it simple like this for performance or something?

in range is this though, so yes i'd use that

2021-03-06 15:56 UTC, zjdtmkhzt commented
Hmm, because IN_RANGE does the get_step(0) thing though, it doesn't work for stopping pulling when the object is inside a container. I'd need to check if the loc of the pulled thing is a turf or not, I guess?

2021-03-06 17:53 UTC, ZeWaka requested changes

2021-03-06 17:53 UTC, ZeWaka commented on code/mob/input.dm
> +							if ((!IN_RANGE(old_loc, src.pulling, 1) && !IN_RANGE(src, src.pulling, 1)) || !isturf(src.pulling.loc) || src.pulling == src) // fucks sake
can you fix this ambig. grouping with parentheses?

2021-03-06 18:00 UTC, ZeWaka approved these changes

2021-03-06 18:01 UTC, ZeWaka commented
Side effect:
consider the situation where you're dragging a dude. you stop for a second, and another dude closes a locker on their lying down body. you will not be able 'drag them out' of the locker

this is therefore a balance change

2021-03-06 18:40 UTC, zjdtmkhzt commented
I suppose that's true.
I guess it would make sense it would stop dragging though!

2021-03-08 05:24 UTC, merged