Makes specific antag garb acid immune(wizards excluded)
goonstation/goonstation pull request #3950
Opened 2021-03-09 09:14 UTC by vode-code

## About the PR 
This PR adds a flag that makes items immune to sulfuric and fluorosulfuric acid, and applies it to the garb of nukies, safari kit traitors, football kit traitors, hunters, and the bowling suit, along with updating the syndicate clown mask to use this flag. This PR also makes spaceproof headwear soak acid before your mask does, which means that the acid immune nukie helmet will preserve the ever so important internals of nuclear operatives.

## Why's this needed? 
Cheesing antag gear by using acid to delete critical garb is unfun and this drastically reduces that.

## Changelog

```changelog
(u)Chickenish
(*)Nuclear Operative garb and some other antag garb is now immune to acid splashing, see minor changes for details.
(+)The Syndicate space suit and helmet, the Safari hat and clothing, the Football armor, helmet, pants, and cleats, the Hunter suit, mask, belt, boots, and the Bowling suit are now all immune to acid. The transition from the inside of a beaker to the outside of clothes may have removed the fire immunity property of that coating, but it looks like it acid-proofs just fine!
```

2021-03-12 15:17 UTC, Gannets commented
Can't speak to the code, but in concept I agree with nuke ops gear being acid proof.

2021-03-13 20:30 UTC, Tarmunora requested changes

2021-03-13 20:30 UTC, Tarmunora commented on code/obj/item/clothing/masks.dm
> -	acid_proof = 1
remove this var from masks

2021-03-13 21:27 UTC, Tarmunora approved these changes

2021-03-29 02:31 UTC, flrsh requested changes
I'd like a message for when you try to melt an acid proof item. For instance, "you splash the greenish acidic substance onto the thing, but nothing happens!".

2021-04-19 20:04 UTC, ZeWaka approved these changes

2021-04-19 21:18 UTC, merged