Fixes an issue where vampires could inadvertently be booted to null space
goonstation/goonstation pull request #4044
Opened 2021-03-16 20:11 UTC by PrimeNumb

## About the PR 
Title. This happened when a vampire's coffin was destroyed while they were en route to it using the Coffin Escape ability.

## Why's this needed? 
fixes https://github.com/goonstation/goonstation/issues/2734

2021-03-17 16:07 UTC, Tarmunora approved these changes

2021-03-20 03:16 UTC, ZeWaka requested changes

2021-03-20 03:16 UTC, ZeWaka commented on code/datums/abilities/vampire.dm
> +	var/obj/storage/closet/coffin/vampire/traveling_to_coffin = null
var name is incorrect descriptor now

2021-03-20 21:55 UTC, ZeWaka approved these changes

2021-03-20 22:27 UTC, merged