Ice dispenser adjustments
goonstation/goonstation pull request #4049
Opened 2021-03-17 11:37 UTC by Carbadox

## About the PR 
Bumped up total amount of ice chunks to 10000 since you cant restock the ice dispenser, removed the 28 Y pixel shift, made the dispsenser not display the total amount of ice as well as buffed the cooling power of ice. Now, a ratio of 1 ice to 2 reagent will make the mix cold. 

## Why's this needed? 
Polishing some minor oversights and making ice colder should make it more usable

2021-03-18 22:23 UTC, vode-code commented
You could make the ice dispenser actually be "hooked into the station water mains" and refill, which would also prevent people from taking out a giant amount of ice at once and just using it for matsci or whatever.

2021-03-22 11:18 UTC, Carbadox commented
> 
> 
> You could make the ice dispenser actually be "hooked into the station water mains" and refill, which would also prevent people from taking out a giant amount of ice at once and just using it for matsci or whatever.

Cleaner and less effort to just make it be alot ¯\_(ツ)_/¯

2021-03-23 13:13 UTC, geneva-breaker commented
> Cleaner and less effort to just make it be alot of ice ¯_(ツ)_/¯

Less effort perhaps. 
Vode is right though.

2021-03-24 12:19 UTC, Carbadox commented
No ones gonna abuse ice. If they do then a fix can be made. Otherwise, I see no difference in making the amount of ice be alot vs making it replenish. There's no difference in functionality and it's honestly a pointless nit pick for a minor feature meant to enchance bartendering

2021-03-26 18:16 UTC, ZeWaka commented
> No ones gonna abuse ice. 

you would be surprised. ice is just more useful water

2021-03-28 03:52 UTC, Tarmunora commented on code/obj/item_dispensers.dm
> +		src.create_reagents(10)
?

2021-03-29 02:12 UTC, Azrun commented
Miners send ice to catering! Rockbox integration!

2021-04-13 05:56 UTC, ZeWaka requested changes
x

2021-04-13 20:54 UTC, ZeWaka approved these changes

2021-04-14 18:01 UTC, merged