Replaces old sticky notes + A bunch of donut 3 improvements
goonstation/goonstation pull request #4109
Opened 2021-03-22 22:49 UTC by Camryn-Buttes

[BUG][MAPPING][FEATURE][QOL]
## About the PR 

Completely excises old sticky note pads from all maps and storage objects. 
They were very broken. (They literally force-spawned a new stickynote box on the same turf 😱 )

Makes some needed additions to donut 3

Mostly adding additional office supply wall-cabinets, but also adding some tracking implants to security, a forensics cart full of supplies to the detective's office, a second GTM in maintenance, a surgical spoon to the medical booth, an artistic toolbox to the chaplain's office, an oxygen canister to the armory, a costume eyepatch to the costume dresser in the chapel, and some other miscellaneous improvements.

## Why's this needed? 

FUCK OLD STICKY NOTES

Also, donut 3 improvements

## Changelog

```changelog
(u)Camryn Buttes
(+)Made a bunch of minor improvements and additions to donut 3, finally got around to replacing old sticky notes with new sticky notes 
```

2021-03-22 23:25 UTC, TTerc requested changes

2021-03-22 23:25 UTC, TTerc commented on maps/oshan.dmm
> +/obj/item/item_box/postittit,
```suggestion
/obj/item/item_box/postit,
```

2021-03-22 23:25 UTC, TTerc commented on maps/oshan_xmas.dmm
> +/obj/item/item_box/postittit,
```suggestion
/obj/item/item_box/postit,
```

2021-03-22 23:25 UTC, TTerc commented on maps/pamgoc.dmm
> +/obj/item/item_box/postittit{
```suggestion
/obj/item/item_box/postit{
```

2021-03-22 23:25 UTC, TTerc commented on maps/pamgoc.dmm
> +/obj/item/item_box/postittit{
```suggestion
/obj/item/item_box/postit{
```

2021-03-22 23:25 UTC, TTerc commented on maps/pamgoc.dmm
> +/obj/item/item_box/postittit{
```suggestion
/obj/item/item_box/postit{
```

2021-03-23 01:02 UTC, Camryn-Buttes commented
Okay, so I'm trying to merge the suggestions, but it's just throwing an error at me and saying the diff was recently updated and I need to refresh and try again

2021-03-23 02:59 UTC, geneva-breaker commented
why is this not two PRs

2021-03-23 12:38 UTC, Camryn-Buttes commented
> why is this not two PRs

Because the old sticky notes kept spawning boxes of new sticky notes on the same tile as the office supply wall cabinets that I added. It was really ugly, so I had to address the issue in SOME way. 

I figured I probably shouldn't half-ass it, so I went ahead and replaced *every* instance of the old sticky notes, except for their definition.

2021-03-23 12:55 UTC, geneva-breaker commented
> I figured I probably shouldn't half-ass it, so I went ahead and replaced _every_ instance of the old sticky notes, except for their definition.

right, but why is this in the same PR as your assorted donut fixes. 
this puts me in an awkward position of wanting to merge the stickynote fix, but being unable to do so because I'm not trusting "some other miscellaneous improvements" without review. 

And i'm not reviewing Donut3 because it's not a map i'm intimate with.

2021-03-23 13:11 UTC, Camryn-Buttes commented
> > I figured I probably shouldn't half-ass it, so I went ahead and replaced _every_ instance of the old sticky notes, except for their definition.
> 
> right, but why is this in the same PR as your assorted donut fixes.
> this puts me in an awkward position of wanting to merge the stickynote fix, but being unable to do so because I'm not trusting "some other miscellaneous improvements" without review.
> 
> And i'm not reviewing Donut3 because it's not a map i'm intimate with.

I can provide an exhaustive list of changes later today after I manually push the fix for those postit typos.

2021-03-23 13:17 UTC, Camryn-Buttes commented
Actually wait, I could just split it into two

2021-03-23 13:40 UTC, Camryn-Buttes commented
There we go, reverted the postit changes, will be making a separate PR for them

Also, will write up an exhaustive list of changes in a bit.

2021-03-23 13:45 UTC, geneva-breaker commented
cool and good thank you

2021-03-23 13:54 UTC, Camryn-Buttes commented
> 
> 
> cool and good thank you

https://github.com/goonstation/goonstation/pull/4115

there we go

2021-03-23 14:06 UTC, Camryn-Buttes commented
and there's the exhaustive list of changes

2021-03-30 12:03 UTC, Camryn-Buttes commented
Hrrrgggg fukken merge conflicts

I'll fix em today

2021-04-09 20:35 UTC, ZeWaka approved these changes

2021-04-10 00:16 UTC, flrsh approved these changes

2021-04-10 00:16 UTC, flrsh approved these changes

2021-04-10 00:22 UTC, merged