Shitty grills can anchor can be toggled with screwdrivers/wrenches
goonstation/goonstation pull request #4352
Opened 2021-04-18 10:16 UTC by Carbadox

## About the PR 
Shitty grills can anchor can be toggled with screwdrivers/wrenches

## Why's this needed? 
QoL

## Changelog

```changelog
(u)Carbadox
(+)Shitty grills can now be moved with screwdrivers/wrenches
```

2021-04-22 04:31 UTC, mordent-goonstation requested changes

2021-04-22 04:31 UTC, mordent-goonstation commented on code/obj/machinery/shitty_grill.dm
> +			src.anchored = !src.anchored
Needs to `return` after this, I think?

2021-04-22 04:33 UTC, mordent-goonstation commented
I would want to confirm with a better grillmaster that this being unanchored isn't going to cause problems.

2021-07-05 16:22 UTC, Bram-KEP commented
Seems like a neat change

2021-07-13 16:27 UTC, ZeWaka commented
can always revert i guess

2021-07-13 16:27 UTC, merged