Removes ass tearing message on Rathens Secret
goonstation/goonstation pull request #4408
Opened 2021-04-21 06:44 UTC by Carbadox

## About the PR 
Removes ass tearing message on Rathens Secret

## Why's this needed? 
Previous iterations of Rathen Secret included smoke. Now that the smoke is removed, the chat is prone to heavy spam from wizards. It's better to remove the message entirely because it's not neccesaray to provide a description for something that is plainly visible and understandable to the player.

## Changelog

```changelog
(u)Carbadox
(+)Rathen's Secret no longer describes how your ass falls off. This should prevent chat spam on places like the shuttle.
```

2021-04-21 15:27 UTC, Azrun commented
The flavor is cool but the spam is bad.  It would be neat to be reworked to have a generic ass loss message so it would be stacked.

Could this removal be limited to Rathens Secret?  Right now it also removes the message for pipebombs and... the _Flatulent Anomaly_.  Are are those cases often problematic as well?

2021-04-22 16:42 UTC, Superlagg commented
Maybe instead of removing the message, just change it to a boutput so the user knows for sure that their ass fell off, but doesnt spam everyone else with your removed ass.

2021-04-25 08:34 UTC, Carbadox commented
Added suggested change

2021-04-26 23:46 UTC, ZeWaka requested changes

2021-04-26 23:46 UTC, ZeWaka commented on code/modules/events/gimmick/bigfart.dm
> +		H.show_text("<span class='alert'><b>[H]</b>'s [magical ? "arse" : "ass"] tears itself away from \his body[magical ? " in a magical explosion" : null]!</span>",\
grammar is wrong now

2021-04-26 23:46 UTC, ZeWaka commented on code/modules/events/gimmick/bigfart.dm
> +	H.show_text("<span class='alert'>[is_bot ? "Oily chunks of twisted shrapnel" : "Wadded hunks of blood and gore"] burst out of where <b>[H]</b>'s [magical ? "arse" : "ass"] used to be!</span>",\
ditto

2021-04-26 23:46 UTC, ZeWaka commented on code/modules/events/gimmick/bigfart.dm
> +	H.show_text("<span class='alert'>[is_bot ? "Oily chunks of twisted shrapnel" : "Wadded hunks of blood and gore"] burst out of where <b>[H]</b>'s [magical ? "arse" : "ass"] used to be!</span>",\
also double?

2021-05-12 03:57 UTC, flrsh commented
@Carbadox some requested changes from Zewaka.

2021-06-03 01:37 UTC, closed without merging