Fixed bug where you can use the teleport scroll when you normally wouldn't
goonstation/goonstation pull request #4442
Opened 2021-04-23 19:29 UTC by PrimeNumb

## About the PR 
Title. This was done by keeping the teleport scroll window open and then clicking Teleport whenever. Now you can't do that.

## Why's this needed? 
Old, _old_ bug that's been in the game for a while but I think it's about time we kill this exploit.

2021-04-23 21:55 UTC, ZeWaka requested changes

2021-04-23 21:55 UTC, ZeWaka commented on code/obj/item/misc_wizard_stuff.dm
> +			if (usr.getStatusDuration("paralysis") || usr.getStatusDuration("weakened") || !isalive(usr) || usr.restrained())
use `is_incapacitated` or `can_act`
i would say the second

2021-04-23 21:58 UTC, Camryn-Buttes commented
It's an emergent feature rather than a bug at this point.

Needs a balance tag and probably a forum thread imo.

2021-04-24 03:32 UTC, Tarmunora approved these changes

2021-04-24 19:44 UTC, ZeWaka approved these changes

2021-04-26 06:57 UTC, flrsh approved these changes

2021-04-26 06:57 UTC, merged