feature: add hugs/love to the hypo whitelist for medical wholesomeness
goonstation/goonstation pull request #4511
Opened 2021-04-27 22:41 UTC by imnotjames

## About the PR 

Updates the Hypo chem whitelist to add Hugs & Love to it.  This also applies to the NT Syringe gun.

## Why's this needed? 

sometimes, the shift is tough.  as MD you just need to go on a rampage
of wholesomeness with the NT Syringe gun.  if meth is in the whitelist,
why not allow for love and hugs to be as well?

## Changelog

```changelog
(u)imnotjames
(+)Allow love and hugs to be used in the hypo & NT Syringe gun.  Why can't we just all be friends?
```

2021-04-28 00:30 UTC, ZeWaka approved these changes

2021-04-28 10:19 UTC, TDHooligan commented
isn't love technically debilitating? i guess it isn't harmful.

2021-04-28 19:08 UTC, imnotjames commented
> isn't love technically debilitating? i guess it isn't harmful.

It does make you stop and hug everyone for a while.  ...This might be a valid strategy on nukie rounds?

However, the chem whitelist has some other stuff that's questionable as far as being debilitating - meth will amp you up quickly but then you'll be having a bad time.

2021-04-29 00:41 UTC, TDHooligan commented
> It does make you stop and hug everyone for a while. ...This might be a valid strategy on nukie rounds?
> 
> However, the chem whitelist has some other stuff that's questionable as far as being debilitating - meth will amp you up quickly but then you'll be having a bad time.

by debiliating i mean it forces you to change off of harm intent, which can be a big deal if the chem tick plays ball

2021-04-29 20:11 UTC, flrsh requested changes
I don't think it makes sense for these chems to be on the hypospray whitelist. They're not medical and I don't really want to start a list of "not really medical but should be okay" chems that people will be able to shove into hypos. Syringe guns with pure hugs or love does sound cool, but I would rather that be a separate unique item.

2021-04-30 01:15 UTC, imnotjames commented
Where would something like that get placed?

![love-gun](https://user-images.githubusercontent.com/1551593/116636749-09a0f580-a930-11eb-8455-304f257ed65f.png)

2021-04-30 06:14 UTC, flrsh commented
> Where would something like that get placed?

Some ideas - debris field crates, safes, a trader, maybe a prefab?

(shoutout to the lovefilled syringe gun in Rodney's office)

2021-04-30 08:15 UTC, imnotjames commented
I'll close this PR out then and open up a new PR with the Love Gun

2021-04-30 08:15 UTC, closed without merging