Plague touch big buff
goonstation/goonstation pull request #4630
Opened 2021-05-08 15:50 UTC by MatheusIsNotAvailable

[BALANCE] [WIKI] [INPUT]

## About the PR 
Makes plague touch also instantly put the target on a choke grab, reduces it's cool down from 180 seconds to 75 seconds and makes it get unlocked much earlier, at 600 blood which is the same level you get frost bats in. also renames the ability from "plague touch" to "Grave grasp" to fit with it's new effect. this is a very powerful ability, good for starting fights, makes vampires way more scary.
## Why's this needed? 
Grave touch is a very underwhelming ability, it giving people a disease that is at it's worst annoying simply won't do, vampire is also a very weak antag. 
## Changelog

```changelog
(u)CodeDude
(*)The vampire ability, plague touch has gotten a big buff, it has a lower cooldown and you need less blood to unlock it. it also instantly puts it's target on a choke grab, it also got renamed to "Grave Grasp" the goal was to make vampires more scary as an antag and not one you can defeat easily

2021-05-08 15:57 UTC, Momoberry commented
Definitely think this is a good thematic addition, cause grave touch barely works currently, takes like 25 minutes to even be lethal, and has no real interaction with the person, similar to sleepy pen. It's more just like giving people cooties.

 This can hopefully make vamp a bit more aggressive and not afraid of a staffie with a welder, even if its just to throw em away or something.

2021-05-08 23:09 UTC, Tarmunora requested changes
either change from chokehold to aggressive grab in code, or change messaging/descriptions/etc to reflect that it's a chokehold and not an aggressive grab

2021-05-09 14:17 UTC, Tarmunora approved these changes

2021-05-10 01:24 UTC, MatheusIsNotAvailable commented
I have been thinking about raising it's blood cost to something like 100 and lowering it's cooldown a little. To make it an ability you have to follow up on as you will probably be drinking blood off of the person you use it on.

 Also been thinking about making the disease cause slowdown on people on all of it's 3 stages(it only does this on it's 3rd stage currently) and lowering the damage a little. So it is harder to run away after it gets used on you. What do yall think of this?

2021-05-12 03:41 UTC, flrsh requested changes
Mbc and I talked about this, and we think that this brings vamp closer to the niche of ling (with a guaranteed "I get you" ability). I think instead of replacing plague touch with this new ability, you should just buff plague touch.

2021-05-12 16:10 UTC, Momoberry commented
Just raw stat changes? Won't that just fall into the entire issue pathology had and why it's literally no longer in the game currently? I think the ability itself should just be reworked. If not the grasp idea, then keep the unlock cost at like 2000 blood, make it cost 750 to use and have it turn somebody into a vampire over five minutes with various flavour text messages that are about feeling urges for blood, etc. Idk. 

The reason friendly vampires are common is because there's no danger to letting a vamp have blood beyond 600 cause of ice bats. None of the later abilities are even moderately threatening compared to frost bats, including how grave touch is. And if you buff it so it's strong, it's gonna have the same issue ling sting has where theres no interaction for the victim of the touch and either they meta knowledge purge it or they probably die.

2021-05-12 16:19 UTC, MatheusIsNotAvailable commented
I dunno, I don't think turning people into vampires with an ability is good, people would just either ask to be turned or vampires would offer themselves to turn people into vampires too wich in both cases is lame, I am giving it some time to see if I can think of anything special for the ability to do, I don't think just changing the stats would be enough to make it ok, If I can't think of anything I will just change the stats.

2021-05-14 17:28 UTC, flrsh commented
Thanks! Can you also lag adjust it (use the mult thing) to compensate for changes in the tickrate of the life loop?

2021-05-31 01:46 UTC, flrsh approved these changes
Sorry I overlooked this!

2021-05-31 14:01 UTC, Tarmunora requested changes

2021-05-31 14:01 UTC, Tarmunora commented on code/modules/medical/diseases/vamplague.dm
> +		affected_mob.changeStatus("stunned", stuntime SECONDS * mult)
double-compensating

2021-05-31 14:01 UTC, Tarmunora commented on code/modules/medical/diseases/vamplague.dm
> +			affected_mob.changeStatus("slowed", 3 SECONDS * mult)
doublecompensating

2021-06-01 17:35 UTC, Tarmunora commented on code/modules/medical/diseases/vamplague.dm
> +		if (probmult(33))
```suggestion
		if (prob(33))
```

2021-06-01 17:35 UTC, Tarmunora approved these changes

2021-06-01 17:35 UTC, merged