Removes earning the banned medal on being banned.
goonstation/goonstation pull request #4671
Opened 2021-05-11 14:16 UTC by Carbadox

## About the PR 
Removes earning the banned medal on being banned. This only removes the line of code that gives you the medal on getting banned, one of the developers with medals access would be needed to fully remove it.

## Why's this needed? 
As far as I know, the medal isn't used for any administrative purposes and depsite people being old that having the medal isnt a badge of honour, people continue to do so. It's best to just remove it

2021-05-12 03:50 UTC, flrsh approved these changes
Personally I'm fine with this. I feel like the ban medal message is intended to be received with "haha look at that schmuck, they got banned", which isn't very great, given the wide range of things you might get banned for, and how we don't actually want to encourage laughing at people for understandable mistakes (e.g. lots of new players might not understand "don't grief" when they first start playing, but that doesn't mean we should laugh at them). 

(also the ban medal message has been broken for a while anyways, and I don't think a lot of people have missed it)

2021-05-12 04:02 UTC, Tarmunora approved these changes

2021-05-14 23:25 UTC, Kyle2143 commented
I think your reasons for this removal are lacking and I don't see a reason to do this. It's just a joke medal, like a good half of our medals.

I didn't know that the medal was currently broken, we should fix it instead.

2021-05-22 03:59 UTC, Kyle2143 requested changes
We decided not to merge this change. You can either make the banned medal just not publicly announce in-game or just close this pr. I think that either would be equally acceptable to the team.

2021-05-28 10:32 UTC, closed without merging