O2 vendor relocation to vending.dm
goonstation/goonstation pull request #4775
Opened 2021-05-17 23:22 UTC by MatheusIsNotAvailable

## About the PR 
Moves air vendors to vending.dm instead of them being their own weird thing + adds a var called can_hack to vending.dm which when is set to 0 makes people unable to open the machine's panel with screwdrivers, this is needed because the air vendors do nothing when hacked and have no products. + it dispenses the air tank to your hand instead of the ground when you eject it now.
## Why's this needed? 
Originally I was just going to make the vendors fall on people but it already has a lot of copy and pasted code from vending.dm so I decided to move it there so It doesn't need to be updated whenever someone adds a new feature to vending machines and so it is more like other vending machines.

2021-05-18 01:07 UTC, ZeWaka requested changes

2021-05-18 01:07 UTC, ZeWaka commented on code/modules/vending/vending.dm
>  	var/panel_open = 0 //Hacking that vending machine. Gonna get a free candy bar.
```suggestion
	var/extended_inventory = FALSE //can we access the hidden inventory?
	var/can_fall = TRUE //Can this machine be knocked over?
	var/can_hack = TRUE //Can this machine have it's panel open? TRUE by default

	var/panel_open = FALSE //Hacking that vending machine. Gonna get a free candy bar.
```

2021-05-18 01:07 UTC, ZeWaka commented on code/modules/vending/vending.dm
> +	acceptcard = 1
```suggestion
	can_hack = FALSE
	pay = TRUE
	acceptcard = TRUE
```

2021-05-19 17:17 UTC, Azrun commented on code/modules/vending/vending.dm
> +
air_vendor used to have different deconstruct flags
`deconstruct_flags = DECON_CROWBAR | DECON_WRENCH | DECON_MULTITOOL`
These seem to fit better with lack of `can_hack` thus `DECON_SCREWDRIVER` - >`DECON_CROWBAR`

2021-05-26 21:59 UTC, merged