Adds Vocal Translators to Valuchip Machines
goonstation/goonstation pull request #4799
Opened 2021-05-19 18:16 UTC by COOLVAPE

## About the PR 
This PR adds vocal translators to Valuchimp machines.

## Why's this needed? 
Currently, vocal translators are limited to the ones that spawn on map and being ordered through the cardlocked monkey crate.  Given that being able to talk is a key part of such a social game, adding more sources  of vocal translators enables players who get turned into monkeys to continue to communicate with the crew, even if QM is unable/unwilling to order more. Longer term, I think the monkey crates should be replaced entirely with buildable valuchimps, and as such vocal translators need a new location. The machines seem fitting, and enable monkeys to get vocal translators from: the kitchen, genetics, and science. I see at the same time there's also an "add vocal translators to medical manufacturers" PR, I don't think it would be in conflict to have them in both places.

## Changelog

```changelog
(u)COOLVAPE
(+)Added vocal translators to Valuchimp Machines.
```

2021-05-20 23:41 UTC, Kyle2143 requested changes
I think that this is the way to go for adding more of this item to the round. But I think it adds way too much. It should probably have 1 or 2, and be a hidden option that you have to hack the machine to vend.

2021-05-21 04:27 UTC, COOLVAPE commented
updated it to only have 1-2 vocal translators, changed it to hidden, and removed log to vend.

2021-05-21 16:37 UTC, imnotjames commented
Worst case you can ask QM for a recharge to get more!

I'm definitely a fan of this.

2021-05-21 19:02 UTC, nefarious6th commented
can i ask for a [wiki] tag on this?

2021-05-21 19:03 UTC, DimWhat commented
> can i ask for a [wiki] tag on this?

no

2021-05-24 03:01 UTC, Kyle2143 approved these changes

2021-05-25 04:01 UTC, merged