Tweak spy targets
goonstation/goonstation pull request #4827
Opened 2021-05-22 15:53 UTC by flappybatpal

[BALANCE]

## About the PR 
Adds the ocean map head items as some new bounties, the secure briefcase and toxin briefcase and a couple of low tier items.
Small refactor on head items to make a single instance of their item as contents instead of creating/deleting them, this is required for spy bounty logic to find them.

Added item HoP's Golden Crayon at the medium reward tier.
Added item HoP's First Bill at the medium reward tier.
Added item MD's Medical License at the medium reward tier.
Added item RD's degree at the medium reward tier.
Added item secure briefcase at the medium reward tier.
Added item toxin briefcase at the medium reward tier.
Added item handheld vacuum at the low reward tier.
Added item hypospray at the low reward tier.
Added item judge robe at the low reward tier.
Added item paramedic suit at the low reward tier.
Added item firesuit at the low reward tier.
Added item packet sniffer at the low reward tier.

Added big object morgue at the low reward tier.
Added big object Valuchimp vending machine at the low reward tier.

Increase HoS headset value to 3, on part with Captain and NTSO.
Remove Port-A-Sci.

## Why's this needed? 
More items gives more variety. The new head bounties should result in spies targeting offices more. The briefcases should also be in medium security areas.
Port-A-Sci is a unique item that cannot be replaced and hobbles A-zone explorers for the round.

## Changelog

```changelog
(u)Flappybat
(+)Added some new spy bounties, removed the Port-A-Sci bounty,
```

2021-05-22 22:03 UTC, pali6 requested changes

2021-05-22 22:03 UTC, pali6 commented on code/obj/decal/poster.dm
> +				src.contents.Add(M)
```suggestion
				var/obj/item/clothing/suit/hosmedal/M = new(src)
				M.desc = src.desc
```

2021-05-22 22:03 UTC, pali6 commented on code/obj/decal/poster.dm
> +						var/obj/item/clothing/suit/hosmedal/M = locate() in src.contents
```suggestion
						var/obj/item/clothing/suit/hosmedal/M = locate() in src
```

2021-05-22 22:03 UTC, pali6 commented on code/obj/decal/poster.dm
> +				src.contents.Add(M)
Mirror these changes to the other items too (or even better move it to a common parent and reduce duplicated code but only if you feel like doing that).

2021-05-23 14:26 UTC, Awfullyfishy commented
> Added item handheld vacuum at the low reward tier.

At least add it to janitor cargo crate, janitor vendor or fabs first, as there's rarely more than one on maps and janitors will sob without them.

2021-05-23 19:15 UTC, BatElite commented
List of changes seems good to me, the only one I disagree with is the hypospray - they're pretty easy to get from a medical fab, so it's not something you necessarily need to steal.

2021-05-26 08:53 UTC, flappybatpal commented
> List of changes seems good to me, the only one I disagree with is the hypospray - they're pretty easy to get from a medical fab, so it's not something you necessarily need to steal.

So, we already have staple gun and circular saw for medical among other somewhat rare stuff. I don't know if it matters to have another?

2021-05-27 12:30 UTC, Tarmunora commented
Add portasci remote if you're going to remove portasci from the list

2021-05-28 11:09 UTC, flappybatpal commented
Added all the remotes. Took out vacuum as it might be a bit too hard to get a new one.

Remove emergency suit, backpack and civilian headset for being way too common, I'm pretty sure every job starts with an emergency suit in a box. You can get a backpack from the clothing fab. We have a bunch of silly items but you still have to go find them.

2021-05-31 13:45 UTC, Tarmunora commented
Mmm, remove sec helmets (far too common, you can just hack a secvend for them iirc), and the non-portasci remotes (portasci remote was specified in particular because it's a "RD" item, as opposed to the other porter remotes which are more of "department" items, if you get what I mean)

2021-06-01 09:17 UTC, flappybatpal commented
This is labelled as conflict but VSC found none in the merge and all tests are passing.

2021-06-01 17:30 UTC, Tarmunora approved these changes

2021-06-01 17:33 UTC, merged