Shows what hat the AI is wearing on examine
goonstation/goonstation pull request #4908
Opened 2021-05-27 11:38 UTC by frawhst

[qol]
## About the PR 
Lets anyone examining the AI see the name of the hat they're wearing.
![image](https://user-images.githubusercontent.com/67879783/119819595-63e89400-bea5-11eb-8f44-2c23a4d71b2e.png)

## Why's this needed? 
Sometimes I buy the AI hat spacebux thing and I have no clue what the hat I'm wearing is called (or in some cases, what it's even supposed to be). Also allows people observing the AI to know what hate they're wearing if it isn't obvious at a glance.

2021-05-27 12:18 UTC, BatElite commented
Maybe using "\an [hat]" instead of "the [hat]" might be slightly more natural.

2021-05-27 12:36 UTC, frawhst commented
> Maybe using "\an [hat]" instead of "the [hat]" might read slightly more natural.

Because the icon is between the a(n) and the hat name, just inserting the `\an` doesn't work. Moving the icon to the end would be inconsistent with the first line, so I'd rather not do that. I could just remove the icon altogether, but I like it being there. 

I do agree that a(n) sounds better, though. Hm.

2021-05-27 18:40 UTC, ZeWaka requested changes

2021-05-27 18:40 UTC, ZeWaka commented on code/mob/living/silicon/ai.dm
> +		. += "<span class='notice'>[src.name] is wearing the [bicon(src.hat)] [src.hat.name]."
You need to end the span

2021-05-28 00:43 UTC, frawhst commented on code/mob/living/silicon/ai.dm
> +		. += "<span class='notice'>[src.name] is wearing the [bicon(src.hat)] [src.hat.name]."
oops

2021-05-28 05:45 UTC, ZeWaka approved these changes

2021-05-29 05:31 UTC, flrsh approved these changes

2021-05-29 05:31 UTC, merged