Fix spy organ selection logic
goonstation/goonstation pull request #5017
Opened 2021-06-04 11:51 UTC by flappybatpal

[BUG]

## About the PR 
Spies would not always get four limb bounties despite many valid targets. From testing I believe this to be caused by the retry logic. This has been rewritten to not be stinky (probably).

## Why's this needed? 
RNG would result in less bounty targets than intended.

2021-06-04 13:07 UTC, flappybatpal commented
I think this is robust? Items are picked randomly and removed from the same list we are reading, we can't pick an item twice and we will only read for the list length so everything will be checked once in a random order until we have the max items or we went all the way through the list.

2021-06-06 03:11 UTC, ZeWaka requested changes

2021-06-06 03:11 UTC, ZeWaka commented on code/datums/gamemodes/spy_theft.dm
> +	var/organs_length = O.len
```suggestion
	var/organs_length = length(O)
```
There is never a reason to use .len and it's slower.

2021-06-06 03:11 UTC, ZeWaka commented on code/datums/gamemodes/spy_theft.dm
> +	var/found_organs = 0;
```suggestion
	var/found_organs = 0
```

2021-06-08 22:32 UTC, merged