Customizable Banners!
goonstation/goonstation pull request #5036
Opened 2021-06-06 01:54 UTC by MatheusIsNotAvailable

## About the PR 
Adds Banners which can be made by using cloth on a wall, the banner inherits the cloth's material, the banner can then be colored by using a crayon on it, after it has been colored you can draw various patterns or letters on it, there is no limit to how many you can draw they are the same color as the crayon you used to draw them too, you can clear it of it's color and drawings by click dragging it, and you can remove it completely by using a wire cutter or similar on it which will give you the cloth you used back.

## Why's this needed? 
It is cool, lets players customize places in a cool way
![Banners!](https://user-images.githubusercontent.com/74429191/120909952-f7ae2300-c650-11eb-9fd0-11598ca8f637.png)

## Changelog

```changelog
(u)Arthur Holiday
(*)Added Customizable banners, use cloth on a wall to make one, color and draw on it with crayons.
```

2021-06-06 04:07 UTC, ZeWaka commented
![](https://external-preview.redd.it/INBHMCNdcPNCBvgGn3yQ-RH4jiAhFP4bde7-wCC2xiw.png?auto=webp&s=7fbcf884991ea6c916da84752af364fbf962687b)

2021-06-06 07:26 UTC, Gannets commented
Can't speak to the code quality but this is a really nice idea, sprites look good too. 👍

2021-06-06 10:51 UTC, PrimeNumb requested changes

2021-06-06 10:51 UTC, PrimeNumb commented on code/obj/decal/poster.dm
> +	var/colored = 0
```suggestion
	var/colored = FALSE
```

2021-06-06 10:51 UTC, PrimeNumb commented on code/obj/decal/poster.dm
> +		src.colored = 0
```suggestion
		src.colored = FALSE
```

2021-06-06 10:51 UTC, PrimeNumb commented on code/obj/decal/poster.dm
> +			if(src.colored == 1)
```suggestion
			if(src.colored == TRUE)
```

2021-06-06 10:51 UTC, PrimeNumb commented on code/obj/decal/poster.dm
> +				src.colored = 1
```suggestion
				src.colored = TRUE
```

2021-06-06 10:52 UTC, PrimeNumb commented on code/obj/decal/poster.dm
> +	popup_win = 0
looks like `popup_win` is never used?

2021-06-06 11:01 UTC, PrimeNumb requested changes

2021-06-06 11:01 UTC, PrimeNumb commented on code/obj/decal/poster.dm
> +			if(src.colored == 0)
```suggestion
			if(src.colored == FALSE)
```

2021-06-07 23:28 UTC, ZeWaka requested changes

2021-06-07 23:28 UTC, ZeWaka commented on code/modules/materials/Mat_RawMaterials.dm
> +			if(locate(/obj/decal/poster/banner,A))
```suggestion
			if(locate(/obj/decal/poster/banner, A))
```
consteienycy

2021-06-07 23:28 UTC, ZeWaka commented on code/modules/materials/Mat_RawMaterials.dm
> +				logTheThing("station", user, null, "Made [B] at [log_loc(user)].")
weirdly worded please be more clear

2021-06-07 23:28 UTC, ZeWaka commented on code/modules/materials/Mat_RawMaterials.dm
> +				user.visible_message("<span class='notice'>[user] Makes [B]!.</span>")
poorly worded

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +	name = "\proper banner"
if it's proper why do you have it lowercase

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +	flags = TGUI_INTERACTIVE
doubtful

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/item/pens_writing_etc.dm
> +			if (istype(target, /obj/decal/poster/banner)) // so they alter color when used on a banner
why are you doing afterattack and not attackby on the actual banner object - this block of code does not make sense to me

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +	proc/clear()
clear what?

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +		else src.color = "#ffffff" // In case the material is null
indent your blocks

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +		return
```suggestion
```
uselsss

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +		var/static/image/banner_holder = image(src.icon, , "banner_holder")
umm why is there a blank argument what's going on here!!!

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +		..()
```suggestion
		. = ..()
```

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +			if(src.colored == TRUE)
```suggestion
			if(src.colored)
```
uncnessary

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +				chosen_overlay = tgui_input_list(user, "What do you want to draw?", null, choosable_overlays)
null? i like titles on my windows don't you?

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +			if(src.colored == FALSE)
```suggestion
			else
```

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +		else return
please indent your blocks after a control statement

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +		else if(tgui_alert(usr, "Are you sure you want to clear the banner?","Confirmation",list("Yes","No")) == "Yes")
please be consistent in your usage of spaces for arguments
```suggestion
		else if(tgui_alert(usr, "Are you sure you want to clear the banner?", "Confirmation", list("Yes", "No")) == "Yes")
```

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +		if(istool(W,TOOL_SNIPPING| TOOL_CUTTING | TOOL_SAWING))
```suggestion
		if(istool(W,TOOL_SNIPPING | TOOL_CUTTING | TOOL_SAWING))
```
AUGH

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +			else C.setMaterial(getMaterial("cotton")) // In case the material is null
spaces after multipronged control statements plase

2021-06-07 23:28 UTC, ZeWaka commented on code/obj/decal/poster.dm
> +				src.overlays.Add(new_overlay)
consider using overlay manager

2021-06-08 14:17 UTC, Carbadox reviewed
Tested locally and it works as intended.

My own suugestions would be to make that splashing a banner with acetone would reset it back to the original clean state and maybe also make acid destroy it. 

All in all though, very cool.

2021-06-08 18:06 UTC, MatheusIsNotAvailable commented
Github mobile hid a bunch of the earlier reviews so I missed some stuff, gonna do the rest today probably, sorry for requesting a review when it isn't done yet

2021-06-21 21:28 UTC, virvatuli-gh reviewed
Looks good 2 me but I'll wait for Zewaka to check in before merge

2021-06-25 22:24 UTC, ZeWaka approved these changes

2021-06-26 01:34 UTC, merged