Makes it possible to resist out of straightjackets
goonstation/goonstation pull request #5075
Opened 2021-06-09 05:42 UTC by nefarious6th

[wiki][balance]

## About the PR 
Makes it possible to resist out of straightjackets with a 90 second actionbar that can be interrupted by moving, being moved, acting, and being stunned (all the same flags as handcuffs and shackles).

## Why's this needed? 
There's no way to resist out of straightjackets on your own currently; I think every other method of restraining someone has the ability to resist out of it, whether it's handcuffs or the PortABrig, so I think straightjackets should have that ability too. 
I think the 90 seconds is accomodating for whatever legitimate uses someone might have for using a straightjacket on someone, but if the agreed decision is that they're too weird to have in the game or that handcuffs and the PortABrig are really meant to be the tools used for that, I'd be open to removing the straightjacket outright.

## Changelog
```changelog
(u)Asche
(+)You can now resist out of a straightjacket by pressing "Z" and holding very still for 90 seconds.
```

2021-06-09 12:47 UTC, Camryn-Buttes commented
Hrmmm.

On the one hand, it makes sense, but on the other hand... this kinda defeats the whole purpose of straight jackets.

On the OTHER OTHER hand, I've wanted to do a straight jacket escape gimmick for god knows how long 🤔 

This gets my support, but I'd also like to see a sequel PR where wizards can escape from straight jackets near instantly with accompanying sparkles or other special effects

2021-06-09 13:00 UTC, DimWhat commented
Make it deal brute damage as you probably broke something while trying to escape.

2021-06-09 20:05 UTC, nefarious6th commented
> On the OTHER OTHER hand

How many hands do you have? 👁️ 

The wizard idea would be very fun though; I dunno if I'd implement a framework for hulks or whoever to bust out of a straightjacket instantly, but Wizards don't have unique interactions with any of the handcuffs that I know of, so I think the idea of making them all into Houdinis with this would be really funny. Definitely will put a pin in it for down the road!

2021-06-09 20:07 UTC, nefarious6th commented
> Make it deal brute damage as you probably broke something while trying to escape.
Not against this; curious on your thoughts on adding this but maybe shortening the actionbar from 90 seconds then to something like 70? I think some risk/downside to the payoff of getting out is good, and that was translated mostly to a really long actionbar that's easily interrupted, but maybe accounting for some of that with damage is a good idea?

2021-06-09 21:50 UTC, ZeWaka commented
!BIG! balance change

2021-06-09 23:49 UTC, Kyle2143 requested changes
Ok, I'm gonna list all the things that I've heard/said in the admin chat discussion on this that sound amenable to me which I think will work well in conjunction.
- let aggressive grabs or pins stop handcuffs from resisting.
- make bucklecuff resisting a visible progress bar.(maybe make punches stop bucklecuff resisting)
- straightjackets have have a long timer where they can thrash about and move and hurt themselves trying to escape. Only stuns or pins will stop the progress bar. The bar is visible.

_________________
If you don't feel like making these changes since it's rather more involved than your original pr, I can just do it myself tonight or tomorrow.

2021-06-10 00:24 UTC, nefarious6th commented
> If you don't feel like making these changes since it's rather more involved than your original pr, I can just do it myself tonight or tomorrow.

These all sound okay; if you or any other devs were able to implement those in a commit and then close this PR, or rework what's here to do that, I would prefer that; this was definitely out of my realm coding-wise so I don't think I'd be able to implement the ideas that you offered with where I'm at skill-wise right now.

2021-06-20 02:40 UTC, nefarious6th commented
Going to close this one out pending someone more skilled than I to try and take a crack at it, and given most feedback said straight resist was not the way to go with this.

2021-06-20 02:40 UTC, closed without merging