Ocular implanter
goonstation/goonstation pull request #5125
Opened 2021-06-12 23:51 UTC by flappybatpal

[QOL][FEATURE][ADDTOWIKI]

## About the PR 
Replaces the ocular prothesis (SecHUD) kit with a terrifying fully automated eye implanter. 
Has a ten second action bar and does one eye at a time. Causes slight bleeding.
Sprites by Gannets.

## Why's this needed? 
The ocular prothesis kit can spawn in surplus crates and as spy bounties but can easily be manufactured.
Eye surgery is also relatively risky.

First element of the sound: [DVD drive spinning up, reading, spinning down(ogg)](https://freesound.org/people/Darth_Biomech/sounds/398441/) by [Darth_Biomech](https://freesound.org/people/Darth_Biomech/), used under [CC BY](https://creativecommons.org/licenses/by/3.0/)
Second element: https://freesound.org/people/deleted_user_7146007/sounds/383446/ used under [CC0](https://creativecommons.org/publicdomain/zero/1.0/)
Third element: https://freesound.org/people/joeliomartini/sounds/89603/ used under [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

https://user-images.githubusercontent.com/70909958/121791403-6a834500-cbe1-11eb-8c76-473eaef87466.mp4
It's not that loud...

## Changelog

```changelog
(u)Flappybat & Gannets
(*)Replaced the ocular prothesis (SecHUD) kit from surplus crates with a fully automatic implanter.
```

2021-06-12 23:58 UTC, flappybatpal commented
This has code as if it could do both eyes but I couldn't work out a menu to do it. You can choose left or right because that's how eye surgery currently works.
The sound is pretty long and AFAIK there's no way to cut it. If the action bar is interrupted this could make for a jank experience.

2021-06-14 16:44 UTC, virvatuli-gh requested changes
With this long of a sound there really should be a code prevention in place to prevent it from being spammed like an `ON_COOLDOWN`, for at least as long as it takes for the sound to fully play (especially since the sound is deliberately a little abrasive). Optimally the sound should cut off if the action bar is interrupted but unsure about the feasibility of doing this.

2021-06-17 18:01 UTC, flappybatpal commented
Changed this to a short start and end sound.

2021-06-21 17:51 UTC, virvatuli-gh requested changes
Just a few grammatical things. Doing the sounds this way works! The end sound caught me off guard and gave me a giggle. Everything else looks good to me and functions fine!

2021-06-21 17:51 UTC, virvatuli-gh commented on code/obj/item/device/ocular_implanter.dm
> +			boutput(H, "<span class='alert'>Your headware covers your eyes, you need to remove it first.</span>")
```suggestion
			boutput(H, "<span class='alert'>Your headwear covers your eyes, you need to remove it first.</span>")
```
makes it consistent with "eyewear" above

2021-06-21 17:51 UTC, virvatuli-gh commented on code/obj/item/device/ocular_implanter.dm
> +	desc = "A worrying looking medical device for automated eye implants, this model is for SecHUDs. The suction cup fill you with dread."
```suggestion
	desc = "A worrying looking medical device for automated eye implants, this model is for SecHUDs. The suction cup fills you with dread."
```

2021-06-21 18:58 UTC, virvatuli-gh approved these changes

2021-06-21 18:58 UTC, merged