Makes more things deconstructable + few deconstruction adjustments
goonstation/goonstation pull request #5189
Opened 2021-06-17 22:19 UTC by MatheusIsNotAvailable

[FEATURE] [QOL]

## About the PR 
Makes big instruments such as the jukebox, portable material reclaimers, the kitchen monkey spike, drone rechargers and botany plant pots all deconstructable makes it so that when you hit a vending machine with a decon tool or a device analyzer it doesn't hit the machine, also makes it so the decon tool menu welder option looks for a tool with the weld flag instead of a welding tool.

## Why's this needed? 
Deconstructing stuff is cool, taking the risk of a vending machine falling on my head every time I want to decon one is funny but annoying, and the omnitool welder should work on the decon menu.

2021-06-17 23:10 UTC, penny64 commented
There's too much comedic value to the machines falling on you for scanning/deconstructing them. It's what nerds should get.

2021-06-18 19:57 UTC, Awfullyfishy commented
You should look into making the firelocks deconstructable as well, they tend to be left after any construction work

2021-06-18 22:54 UTC, MatheusIsNotAvailable commented
> You should look into making the firelocks deconstructable as well, they tend to be left after any construction work

I plan on doing that in the future yeah, it would just require a little more work because I need to make sure they work right when reconstructed, same with light switches, fire alarms and other things that depend on their area. Expect those things in a PR if this one gets approved

2021-06-25 23:37 UTC, Tarmunora requested changes

2021-06-25 23:37 UTC, Tarmunora commented on code/obj/item/material.dm
> +	deconstruct_flags = DECON_SCREWDRIVER | DECON_WRENCH | DECON_CROWBAR
```suggestion
```
skip the portable reclaimer decon and this is good

2021-06-26 05:07 UTC, Tarmunora approved these changes

2021-06-26 05:07 UTC, merged