Allows the ID computer to save and apply custom jobs to ID cards
goonstation/goonstation pull request #5195
Opened 2021-06-18 06:32 UTC by 112358sam

[QoL]

## About the PR 
Adds three slots for custom jobs on the menu of the ID card computer. Each saves the job name and access list and can apply it to other cards with the press of a button. Save a job by setting the name and access and hitting save then it can be applied to future cards.

Also adds security assistant to the list of default jobs on the ID computer.

## Why's this needed? 
It was requested on the forums https://forum.ss13.co/showthread.php?tid=16609 
It saves the HoP time when trying to give the same access level out multiple times or lets the HoP easily build and distribute custom jobs and access levels.

## Changelog

```changelog
(u)112358sam
(+)Adds custom job save slots to the ID card computer.
```

2021-06-18 19:55 UTC, Awfullyfishy commented
Is it possible to save the access and name of an ID to the slot? Meaning you could copy the HoS special access?

2021-06-18 21:46 UTC, 112358sam commented
I didn't realize HOS had the unique access. I can remove it if it is an issue that it could be copied. Copying it would require having their card in the first place, but I can add a check to prevent it once I am back at my computer.

2021-06-18 22:15 UTC, Crackaduck commented
> I didn't realize HOS had the unique access. I can remove it if it is an issue that it could be copied. Copying it would require having their card in the first place, but I can add a check to prevent it once I am back at my computer.

idk I think its fine, the only way it comes into play is if hos willingly gives it away to someone else. You'd have to have the Hos's card to do it without their consent in the first place, at which point, youve probably already killed them and taken the id for yourself. Besides that I think it actually adds flavor, the only way to get hos's acess on the computer is to get the card from them. TLDR its not a bug its a feature :)

2021-06-19 01:18 UTC, 112358sam commented
I went ahead and removed the ability to store the HoS special access. I can easily revert this if we want to go the feature route.

2021-06-19 02:16 UTC, Crackaduck commented
> I went ahead and removed the ability to store the HoS special access. I can easily revert this if we want to go the feature route.

can it still store their office or are they one in the same?

2021-06-19 08:52 UTC, 112358sam commented
At least on cog 2 where I tested it, the armory access and HoS office use the same access.

2021-06-19 21:45 UTC, nefarious6th commented
armory and office access are tied together, yea.

2021-06-20 17:57 UTC, ThatFiveGuys commented
Make sure it cant copy listening post access from agent id cards too.

2021-06-21 00:45 UTC, 112358sam commented
> 
> 
> Make sure it cant copy listening post access from agent id cards too.

I've updated the limit to block all azone accesses and syndicate outpost from being copied

2021-06-28 23:26 UTC, Crackaduck commented
I disagree with it being unable to save certain locations access, as I'd like it better if it could save and access and save ALL access areas, but I understand for balance reasons why that could be bad (I think it would be fair but clearly im in the minority). should be a fun PR regardless, and good luck on your next projects!

2021-07-12 15:25 UTC, mordent-goonstation requested changes

2021-07-13 00:10 UTC, 112358sam commented on code/obj/machinery/computer/card.dm
> +			var/list/securityjobs = list("Security Officer", "Security Assistant", "Detective")
Removed and PR'd separately. #5485

2021-07-13 04:19 UTC, 112358sam commented on code/obj/machinery/computer/card.dm
> +			src.modify.access = src.custom3_list.Copy()
Fixed!

2021-07-13 04:19 UTC, 112358sam commented on code/obj/machinery/computer/card.dm
> +			body += " [src.custom3_name] <a href='?src=\ref[src];save=custom3'>save</a> <a href='?src=\ref[src];apply=custom3'>apply</a>"
Done!

2021-07-13 04:20 UTC, 112358sam commented on code/obj/machinery/computer/card.dm
> +	var/list/banned_access_list = list(access_maxsec,access_syndicate_shuttle,access_owlerymaint,access_owlerysec,access_owlerycommand,access_syndicate_4,access_syndicate_8,access_syndicate_16,access_sy
Done!

2021-07-14 01:29 UTC, ZeWaka approved these changes

2021-07-18 01:01 UTC, merged