Changing Minimum and Maximum times for the nuclear charge
goonstation/goonstation pull request #5234
Opened 2021-06-22 00:58 UTC by AmazingDragon353

## About the PR 

## Why's this needed? 

This changes the nuclear charge's (the one activated using nukeman) minimum and maximum time from 30 and 440 to 120 and 600 seconds respectively. It also sets the default time to 180 seconds. This is because setting off a nuke on a 30 second timer is currently near impossible to defuse, and people deserve a chance to deal with it. It also increases the maximum time for a little more wiggle room if you want to rp a bomb threat without it accidentally going off and lets you cosplay as actual nukies! 

## Changelog

(u)AmazingDragons
(+)Changes the minimum, maximum, and default times (in seconds) on the nuclear charge to 120, 600, and 180 respectively.

```changelog
(u)CodeDude
(*)Added soft soft pizza to the game - a tasty drink found in soda machines!
(+)Made some small sprite changes to the base pizza sprite.
```

2021-06-22 01:10 UTC, Tarmunora requested changes
cleaner to use `clamp(value, low, high)` instead of `max(min(value, high), low)`

2021-06-22 15:07 UTC, AmazingDragon353 commented
> cleaner to use `clamp(value, low, high)` instead of `max(min(value, high), low)`

Done!

2021-06-23 04:08 UTC, Tarmunora requested changes

2021-06-23 04:08 UTC, Tarmunora commented on code/modules/networks/computer3/mainframe2/misc_terms.dm
> +#define MAX_NUKE_TIME 600
move to `_std/defines/computer.dm`

2021-07-07 21:24 UTC, Tarmunora requested changes

2021-07-07 21:24 UTC, Tarmunora commented on code/modules/networks/computer3/mainframe2/misc_terms.dm
> +				boutput(world, "<span class='alert'><b>[src.time] seconds until nuclear charge detonation.</b></span>")
```suggestion
```
snip

2021-07-07 21:24 UTC, Tarmunora commented on code/modules/networks/computer3/mainframe2/os_drivers.dm
> +				var/newtime = max(0, min(data["time"], MAX_NUKE_TIME))
could use clamp here too

2021-07-08 19:16 UTC, Tarmunora approved these changes

2021-07-08 19:32 UTC, merged