/obj/machinery/door/
goonstation/goonstation pull request #5267
Opened 2021-06-24 09:37 UTC by flappybatpal

[BALANCE][WIKI][FEEDBACK]

## About the PR 
Reduce door health by around 50%.
Scales explosive and 

## Why's this needed? 
Recommended by MBC to reduce door health by around 70%.
Doors are incredibly strong. It takes 5-6 hits (15 seconds) of a Breaching Hammer to get through the flimsiest door and 12 hits (40 seconds) to get through command doors. This is with a dedicated, two handed tool that does 125 damage to doors!
The next strongest common melee weapon, a baseball bat, takes 50 hits to break a standard door, with most doors actually having 1200 health.

## Changelog

```changelog
(u)Flappybat
(*)Made doors half as strong, you can now break them this century. Explosive/fire/projectile scaling is adjusted so it will still take the same number of bullets to destroy a door.
```

2021-06-24 20:38 UTC, Tarmunora commented
while ur at it make windoors (the unhackable thindow kind) have a bit less health than a normal airlock maybe

2021-06-25 10:19 UTC, flappybatpal commented
Might be an issue with pod doors - /obj/machinery/door/poddoor
Due to the new scaling they will be twice as resistant against bombs and weapons.

I think this would be resolved by a flag or variable to change the scaling or add variables for door damage scaling to the door parent so it can be adjusted per subtype.

2021-06-25 13:44 UTC, Tarmunora requested changes

2021-06-25 13:44 UTC, Tarmunora commented on code/obj/machinery/door/door_parent.dm
> +			take_damage(health_max/12)
these shouldn't be changed, as they are relative to max HP already

2021-06-25 20:22 UTC, Tarmunora approved these changes

2021-06-25 20:23 UTC, merged