Frog Flu progresses much slower
goonstation/goonstation pull request #5305
Opened 2021-06-27 12:53 UTC by unfunnyperson

[BALANCE]
## About the PR 
For how easy sheltestgrog is to make the effects are much better than the other critter transforming chems. This reduces the stage prob from 15 to 4 which is closer to the other diseases.

## Why's this needed? 
Sheltestgrog is a bit overpowered in its current state due to how quick it progresses.

## Changelog

```changelog
(u)UnfunnyPerson
(+)Frog Flu progresses much slower
```

2021-07-01 20:17 UTC, Tarmunora requested changes
match similar diseases

2021-07-01 20:17 UTC, Tarmunora commented on code/modules/medical/diseases/frog_flu.dm
> +	stage_prob = 4
```suggestion
	stage_prob = 5
```

2021-07-02 21:07 UTC, unfunnyperson commented
done

2021-07-02 22:24 UTC, Tarmunora approved these changes

2021-07-02 22:24 UTC, merged