Fixes automenders still working when dropped/put away
goonstation/goonstation pull request #5418
Opened 2021-07-08 11:28 UTC by TTerc

[bug]

## About the PR 

Title
In case of humans/mutantraces/critters the automender will work only if it's in your hands
In case of cyborgs, the automender will work if it's in one of the active module slots (switching between tools won't stop it from working)

The isrobot/!isrobot thing exists because critters have hands too, unlike cyborgs.

## Why's this needed? 

Fixes #5371

2021-07-08 13:26 UTC, Sovexe commented
MBC has commented that this behavior is by design in the past

2021-07-08 16:13 UTC, BatElite commented
(chem) patch enthusiasts rise up

2021-07-08 16:52 UTC, MarkNais approved these changes
> MBC has commented that the current behavior is by design in the past

I think this change is for the better. Seems odd that a mender would keep working while in a pocket/dropped to the floor. Sure this removes a small-amount of "ease" from healing people, but the behavior is very counter intuitive.

2021-07-10 20:21 UTC, ZeWaka approved these changes
i agree w/ above

2021-07-12 14:46 UTC, Tarmunora requested changes
The cyborg handling does not work as stated - that code makes it work so long as cyborg has any tool selected - they can store the mender and switch to another tool and it will keep mending

2021-07-12 15:43 UTC, TTerc commented
Oops true, quickly storing the tool and switching to another one was breaking it. Fixed, tested and working now

2021-07-12 16:22 UTC, Tarmunora commented
any reason not to just use `find_in_hand()` for all mob types?

2021-07-12 16:50 UTC, TTerc commented
there is no find_in_hand in human.dm

2021-07-12 16:56 UTC, TTerc commented
yea, I wasn't aware find_in_hand works for humans aswell (why does is_in_hands exist then too?)
:flooshed:
fixed

2021-07-12 17:06 UTC, Tarmunora approved these changes

2021-07-12 17:06 UTC, merged