Adds several new clothing items and backpacks, changes hoodie sprites, and swaps out discount godzilla's clothing
goonstation/goonstation pull request #5424
Opened 2021-07-08 18:48 UTC by DimWhat

[WIKI] [SPRITES]

## About the PR 
Adds several sprites by Kobold Commando to the game including: 

- Several Hoodies and a resprite of the hooded and object version of hoodies 
- Dinosaur pajamas
- A reference to monkey island
- Three new hats
- Two new backpacks (With satchel versions!)
![image](https://user-images.githubusercontent.com/40079883/124974269-376e7e80-dff2-11eb-9915-4b16d53ca733.png)
Monkey versions by me.
This PR also changes up the attire of the discount godzilla Halloween role to a much goofier set.
## Why's this needed? 
More clothing items is good, also the hoods on hoodies could use some work as well as the item versions of them. Also, i can't get over how silly discount godzilla would look like during halloween.
![image](https://user-images.githubusercontent.com/40079883/124965506-d5108080-dfe7-11eb-9544-559c35520609.png)

## Changelog

```changelog
(u)Kobold Commando & DimWhat
(*)Added several new clothing items to the clothing booth and two backpacks to Geoff Honkington.
(+)Changed the clothing of a certain lizardy halloween role
```

2021-07-08 22:01 UTC, BatElite commented
Isn't the sock hat pretty much the pajama hat?

2021-07-08 22:46 UTC, DimWhat commented
> Isn't the sock hat pretty much the pajama hat?

When making this I never compared the two sprites, yeah it's pretty much exactly the PJ hat. Kobold seemed to not know we even had a PJ hat in the game. I'll take it out.

2021-07-13 16:46 UTC, DimWhat commented
oh crap pressed the wrong button

2021-07-14 23:55 UTC, Sovexe requested changes

2021-07-14 23:55 UTC, Sovexe commented on code/modules/vending/clothingbooth_items.dm
> +	cost = PAY_TRADESMAN/2
should be under the costume subtype

2021-07-14 23:55 UTC, Sovexe commented on code/modules/vending/clothingbooth_items.dm
> +	cost = PAY_TRADESMAN
should be under the head subtype

2021-07-15 14:59 UTC, Sovexe approved these changes

2021-07-21 14:08 UTC, merged