Buff the agent card removing the single use element.
goonstation/goonstation pull request #5425
Opened 2021-07-08 18:50 UTC by Carbadox

## About the PR 
Buffed the agent card by removing the limit of being able to set your ID name, assingment, colour once. Now you can do change it indefinetely.

With this changed, the price of an agent card was raised to 3 and old agent card behaviour is kept the same for the ones nukies get as well as agent card found in the spec ops crate.

## Why's this needed? 
Underused item and frankly the limitation felt pointless and only hampered the use of the item.

## Changelog

```changelog
(u)Carbadox
(+)Buffed traitor PDA agent cards. You can now set your assignment, colour and name however many times you want. This change does not apply to the agent cards that Nukies get or the one found in the Spec Ops crate from QM.
```

2021-07-08 18:53 UTC, MatheusIsNotAvailable commented
I would rather this be a different item, like an agent card deluxe or something, I like being able to get agent cards as they are now for 1 TC

2021-07-08 18:55 UTC, MarkNais requested changes
I'm not a "balance" guy, so this is just code-review on my part.

2021-07-08 18:55 UTC, MarkNais commented on code/obj/item/card.dm
> +	name = "agent card"
```suggestion
	name = "reusable agent card"
```

May as well make it explicit.

2021-07-08 18:57 UTC, MarkNais approved these changes
Ignoring balance: code seems fine.

2021-07-08 18:58 UTC, ThatFiveGuys commented
Echoing Matheius's claim, rn agent cards are a good "I only have 1 TC purchase left and this will help" purchase. Making em 3 TC would kinda ruin that niche.

2021-07-08 18:59 UTC, flappybatpal commented
I vote 2TC. The name functionality is a bit so-what when traitors usually get access to an identity computer.

2021-07-08 19:07 UTC, Carbadox commented
Lowered the price to 2 due to feedback

2021-07-08 21:22 UTC, Bram-KEP commented
Spec Ops crate one should share the effect imo as it makes sense and would incentivise using it as the crate is rarely used.

2021-07-11 16:47 UTC, PrimeNumb commented
Definitely make this a separate item. Agent cards (as they are currently) are in a really good spot balance-wise.

2021-07-16 07:37 UTC, closed without merging