Fixes compatibility issues with xray mutation and vision-modifying goggles
goonstation/goonstation pull request #5534
Opened 2021-07-16 21:53 UTC by PrimeNumb

## About the PR 
- Xray mutation is now compatible with mesons, thermals, ecto goggles, etc
- Parts of sight code refactored to use mob properties

## Why's this needed? 
fixes https://github.com/goonstation/goonstation/issues/5529
cleans up sight code ever so slightly

2021-07-16 22:47 UTC, alexeric123 commented
Does this also work with other interactions other than the x-ray mutation?
Such as night vision mutation+mesons/thermals
or night vision mutation + xray mutation

2021-07-17 01:03 UTC, Tarmunora commented
Might be worth adding handling to the sight properties to run the sight process when the property changes

2021-07-17 07:28 UTC, PrimeNumb commented
> Does this also work with other interactions other than the x-ray mutation?
> Such as night vision mutation+mesons/thermals
> or night vision mutation + xray mutation

Correct.

> Might be worth adding handling to the sight properties to run the sight process when the property changes

Done.

2021-07-17 07:30 UTC, PrimeNumb commented on _std/macros/mob_properties.dm
> +	_M.lifeprocesses[/datum/lifeprocess/sight].process(); \
tmk there should be no instance where this lifeprocess does not exist (outside of disposing)

2021-07-17 08:23 UTC, PrimeNumb commented on _std/macros/mob_properties.dm
> +	_hudprocess.process(); \
hud process is for tinting
not sure how expensive this gets for large amounts of players

2021-07-17 08:29 UTC, PrimeNumb commented on code/obj/item.dm
> +/obj/item/proc/after_unequip(var/mob/user)
`unequipped()` has this quirk where the item is technically still in the slot during the proc call.
I suspect a _shitton_ of things rely on this behavior, so I added `after_unequip()`. 
See `code/mob/living/carbon/human.dm` and `code/datums/hud/human.dm` on how it's called.

2021-07-17 15:54 UTC, Tarmunora requested changes

2021-07-17 15:54 UTC, Tarmunora commented on _std/macros/mob_properties.dm
> +	if(!istype(target, /mob/living)) return; \
```suggestion
	if(!isliving(target)) return; \
```

2021-07-17 15:54 UTC, Tarmunora commented on _std/macros/mob_properties.dm
> +	_M.lifeprocesses[/datum/lifeprocess/sight].process(); \
```suggestion
	_M.lifeprocesses?[/datum/lifeprocess/sight]?.process(); \
```

2021-07-17 22:57 UTC, Tarmunora approved these changes

2021-07-17 22:58 UTC, merged