Fix end of game antag roles
goonstation/goonstation pull request #5593
Opened 2021-07-23 12:53 UTC by flappybatpal

[BUG]

## About the PR 
Fixes critter antags showing as blank.
Adds poltergeist special role and to former_antags,
Adds special roles to changeling critters.
Rewrites bad_traitorify and use it to handle pests.
Stops some antag roles showing up twice on the scoreboard?

## Why's this needed? 
Scoreboard should display roles.

2021-07-23 12:53 UTC, flappybatpal commented
It's very likely some of this is bad as it took a lot of trial and error, please advise.

2021-07-28 18:43 UTC, ZeWaka requested changes

2021-07-28 18:43 UTC, ZeWaka commented on code/datums/abilities/wraith.dm
> +		if (!lucky_dude.former_antagonist_roles.Find(lucky_dude.special_role))
use `in`, you don't need Find's idx

2021-07-28 18:43 UTC, ZeWaka commented on code/modules/antagonists/changeling/abilities/hivemind.dm
> +			if (!spider.mind.former_antagonist_roles.Find(spider.mind.special_role))
in

2021-07-28 18:43 UTC, ZeWaka commented on code/modules/antagonists/changeling/abilities/hivemind.dm
> +			if (!spider.mind.former_antagonist_roles.Find(spider.mind.special_role))
in

2021-07-28 18:43 UTC, ZeWaka commented on code/modules/antagonists/changeling/abilities/hivemind.dm
> +			if (!spider.mind.former_antagonist_roles.Find(spider.mind.special_role))
in

2021-07-28 18:43 UTC, ZeWaka commented on code/modules/antagonists/changeling/abilities/hivemind.dm
> +			if (!crab.mind.former_antagonist_roles.Find(crab.mind.special_role))
in

2021-07-29 11:11 UTC, flappybatpal commented
Pruned the former_antagonist_roles additions. From looking at it, this did not seem suitable for changeling limbs and would be a new addition.
Changed the poltergeist to be added to agimmicks, looks like they weren't tracked as being an antag at all.

Changed the tips popup for generic antag.

2021-07-30 22:23 UTC, ZeWaka commented on code/procs/jobprocs.dm
> +		if (!(H.mind in ticker.mode.Agimmicks))
|=

2021-07-30 22:23 UTC, ZeWaka commented on code/procs/jobprocs.dm
> +		if(!(H.mind in ticker.mode.traitors))
|=

2021-07-30 22:23 UTC, ZeWaka commented on code/datums/abilities/wraith.dm
> +		if (!(lucky_dude in ticker.mode.Agimmicks))
|=

2021-08-01 19:13 UTC, merged