Lets you chug from ALL the drinking containers
goonstation/goonstation pull request #5709
Opened 2021-08-09 12:20 UTC by TTerc

[feat]

## About the PR 

This PR simply moves the clickdrag chugging proc from /obj/item/reagent_containers/food/drinks/drinkingglass to /obj/item/reagent_containers/food/drinks, letting you chug from all the drinking containers

## Why's this needed? 

You ever wished you could chug the entire cup of Discount Dan's Noodles? Now you can.

![0](https://user-images.githubusercontent.com/62990808/128704998-fdd92477-5af4-4106-a8ac-fe2188b74dfa.png)

## Changelog

```changelog
(u)TTerc
(+)You can now chug from all the drinking containers, not just glasses and pitchers.
```

2021-08-09 19:31 UTC, Tarmunora approved these changes

2021-08-09 22:24 UTC, millicentjwi commented
YES FUCK YES

2021-08-10 03:39 UTC, Tarmunora commented
doublecheck that closed cans etc still work as expected ie, cannot chug a sealed can

2021-08-10 09:48 UTC, TTerc commented
Good point. Fixed, no more chugging from sealed cans

2021-08-10 14:43 UTC, Tarmunora commented
Hm. Consider a `can_chug` var on drinks instead, and set/unset as needed. Probably don't want to allow chugging from juice-o-matics, cocktail shakers(!), and maybe also disallow some stuff like water-coolers, fueltanks, and coffee carafes

2021-08-10 14:47 UTC, TTerc commented
yeah, artpitchers aswell perhaps

2021-08-10 15:10 UTC, TTerc commented
Cocktail shakers, juice-o-matics, artpitchers, fuel tanks, water cooler bottles and coffee carafes are now blacklisted

2021-08-10 15:13 UTC, Tarmunora requested changes

2021-08-10 15:13 UTC, Tarmunora commented on code/modules/food_and_drink/drinks.dm
> +
use `can_chug` instead (default false, set to true in `attack_self()`)

2021-08-10 15:13 UTC, Tarmunora commented on code/modules/chemistry/tools/food_and_drink.dm
> +			boutput(C, "<span class='alert'>You try to lift the [src.name] and attempt to chug from it but it's too heavy!</span>")
```suggestion
			boutput(C, "<span class='alert'>You can't seem to chug from [src.name]! How odd.</span>")
```
cocktail shakers etc probably aren't that much heavier than a full pitcher 🤷

2021-08-10 16:46 UTC, Tarmunora approved these changes

2021-08-10 16:46 UTC, merged