Is this a rain?
goonstation/goonstation pull request #5735
Opened 2021-08-14 06:13 UTC by Azrun

## About the PR 
Added new dialog to Swampify:

![image](https://user-images.githubusercontent.com/1017374/129435260-7b98cdc7-ca1a-4d28-bd3e-091404b08d88.png)

- Yes.

![rain](https://user-images.githubusercontent.com/1017374/129435374-8cc25b0a-8640-450d-b423-4aba610b0142.gif)
- No.
  - No change. 
- Particles
![RainParticles](https://user-images.githubusercontent.com/1017374/129435579-a23d242b-0ace-4802-a19f-f85434e799e7.gif)
![RainParticles2](https://user-images.githubusercontent.com/1017374/129435598-9bdde724-8f0f-4a16-b51d-cb3cffa0b693.gif)

This currently places an effect on each tile swampified turf that generates up to 8 particles from the upper left and will travel partway into south and east turf.
![RainParticles3](https://user-images.githubusercontent.com/1017374/129435960-cedd721f-e19e-47a3-8ad5-f43194f7e2f7.gif)
 

Note: This currently causes reduced performance on the client when surrounded by that many particle generators. This seems to manifest in reduced responsiveness of other animations.  Glides are pretty chunky,

## Why's this needed? 
I want this for _Artemis_.  This is a great way for these features to be viewed and evaluated by admin/devs and for gimmickry.

2021-08-14 06:15 UTC, Azrun commented
Hmmm, this also now has the particle effect I demoed for welding that is more of an example than anything.

2021-08-15 04:07 UTC, Tarmunora requested changes

2021-08-15 04:07 UTC, Tarmunora commented on code/obj/effects/particles.dm
> +		particles = new/particles/spark/directed
atomize PR

2021-08-15 04:07 UTC, Tarmunora commented on code/obj/effects/precipitation.dm
> +		particles = new/particles/snow/grey
Atomize PR

2021-08-15 04:07 UTC, Tarmunora commented on goonstation.dme
> +#include "code\obj\effects\particles.dm"
Atomize PR

2021-08-15 05:42 UTC, Tarmunora approved these changes

2021-08-15 05:43 UTC, merged