Mars-ify
goonstation/goonstation pull request #5879
Opened 2021-09-02 05:50 UTC by Azrun

[feature]
## About the PR 
Cool RP tools for Cool kids.  PUNISHMENT TO THOSE ON CLASSIC FOR FAILING TO FOLLOW INSTRUCTIONS! 😈 
-Rescales _thematic_ elements to not **destroy** players immediately.
-Ambient light gradient used across station z-level to nievely approximate a sunrise, some randomization to avoid visible banding.

## Why's this needed? 
![image](https://user-images.githubusercontent.com/1017374/131788448-2260f373-bf36-4677-a41e-26a0cb083fa3.png)

Can I? ✔️ 
Should I? 🤷

2021-09-25 21:44 UTC, Sovexe commented on code/modules/admin/terrainify.dm
> +    "Mars Station"=/client/proc/cmd_marsify_station,
woops
```suggestion
		"Mars Station"=/client/proc/cmd_marsify_station,
```

2021-09-25 22:16 UTC, Sovexe requested changes

2021-09-25 22:16 UTC, Sovexe commented on code/datums/mapgen/MarsGenerator.dm
> +					jerk.changeStatus("weakened", 5 SECONDS)
possible alternative. If you don't like this then instead just be sure to add a `force_laydown_standup` after the weakened effect is addded 
```suggestion
					jerk.do_disorient(stamina_damage = 100, weakened = 3 SECONDS, disorient = 5 SECOND)
```

2021-09-25 22:16 UTC, Sovexe commented on code/datums/mapgen/MarsGenerator.dm
> +						playsound(src.loc, 'sound/impact_sounds/Flesh_Stab_2.ogg', 50, 1)
```suggestion
						playsound(src, "sound/impact_sounds/Flesh_Stab_2.ogg", 50, 1)
```
Play the sound on the turf not the turf's area, also double quotes to use the sound cache

2021-09-26 04:08 UTC, Azrun commented
- [ ] Cleaning up handling the shipping path, as it appears possible for the `obj/machinery/light/beacon` and `/turf/unsimulated/wall/setpieces/martian/auto` to block.

2021-09-27 02:33 UTC, Sovexe approved these changes

2021-09-27 02:34 UTC, merged