Fix #5946 - Brig teleporting
goonstation/goonstation pull request #5948
Opened 2021-09-09 08:59 UTC by flappybatpal

[BUG]

## About the PR 
Checks for occupant in brig contents before attempting to set their loc.
Gives a message if the brig is empty.

## Why's this needed? 
If for whatever reason, such as recall artifact or admin intervention, a mob was teleported out of the brig it would still set their loc back to the brig tile when emptied.
This will now check for an occupant and give a visible message to indicate something unknown has happened to the occupant.

2021-09-09 09:05 UTC, flappybatpal commented
Could change process to always run while occupied and check for occupants, unless there is an event that gets fired by contents changing? I think process might be overkill.

2021-09-09 09:46 UTC, Gerhazo commented
Edited to reflect referring to port-a-brig, as it took me a while to understand what the PR was about at first.

2021-09-09 18:20 UTC, Tarmunora commented
> 
> 
> Could change process to always run while occupied and check for occupants, unless there is an event that gets triggered by contents changing? I think process might be overkill.

`Exited()` proc

2021-09-09 22:12 UTC, Tarmunora requested changes

2021-09-09 22:12 UTC, Tarmunora commented on code/obj/machinery/porters.dm
> +		src.occupant = null
should check that the movable exiting is actually the occupant

2021-09-10 14:04 UTC, Tarmunora commented on code/obj/machinery/porters.dm
>  			UnsubscribeProcess()
indent

2021-09-10 14:10 UTC, flappybatpal commented on code/obj/machinery/porters.dm
>  			UnsubscribeProcess()
Good catch

2021-09-10 15:14 UTC, Tarmunora approved these changes

2021-09-10 17:06 UTC, UrsulaMejor approved these changes

2021-09-10 18:57 UTC, merged