Resprites 40u chemical bottles
goonstation/goonstation pull request #5955
Opened 2021-09-10 07:09 UTC by DisturbHerb

## About the PR 
Resprited the 40u chemical bottles that come in Syndicate poison bottle kits as well as medicines from the Nanomed. They're funky now, and have coloured caps depending on the reagent they start with.
![image](https://user-images.githubusercontent.com/66253095/132814021-ce7c0f65-a9dd-41d9-9326-459a88e336f1.png)

Sprite comparisons woo:
![image](https://user-images.githubusercontent.com/66253095/132814284-503ddd17-eba1-4dd2-99c0-94a56594fb3a.png)

## Why's this needed? 
Old sprite flat. New sprite _round._ Ooga booga.

2021-09-10 12:20 UTC, Alexalmighty502 commented
I'm worried that this will make it difficult to quickly judge how many units you have left just from sight alone.

2021-09-10 12:54 UTC, DisturbHerb commented
> I'm worried that this will make it difficult to quickly judge how many units you have left just from sight alone.

Personally, I felt that it was difficult enough with the old sprites, but I think that could just be me.

2021-09-10 17:26 UTC, MatheusIsNotAvailable commented
They look like they have almost nothing in them, specially the first one, even though they are full.

2021-09-11 02:03 UTC, DisturbHerb commented
Made some changes per Matheus' suggestions.

![image](https://user-images.githubusercontent.com/66253095/132932692-804c2cba-3edf-4851-b0af-a34d03080481.png)
![image](https://user-images.githubusercontent.com/66253095/132932699-29230503-5490-4fff-9920-e46b58391067.png)

2021-09-11 04:05 UTC, DisturbHerb commented
even newer changes. they now gots fluid levels. original post edited

2021-09-11 19:52 UTC, ZeWaka requested changes

2021-09-11 19:52 UTC, ZeWaka commented on code/modules/chemistry/tools/bottles.dm
> +				color_HSL[3] = 80
```suggestion
			color_HSL[3] = max(80, color_HSL[3]) // minimum lightness
```

2021-12-27 10:10 UTC, DisturbHerb commented
Closing so I can figure out what to do with this later.

2021-12-27 10:10 UTC, closed without merging