Prefab - Gnomish Warship
goonstation/goonstation pull request #5987
Opened 2021-09-12 15:19 UTC by vocalpocal

[mapping][feature][sprites][input wanted]

## About the PR 
This is a contest entry for https://forum.ss13.co/showthread.php?tid=16992
Summary:

- Size: 11x14
- Probability: 25
- Enemies: 2 (Maneaters)
- Merchant: David the Gnome
- Other: Two garden gnomes which water plants
- Equipment: Three hydroponic trays which spawn with strange seeds in them - otherwise regular trays, four arable soil trays, and some green clothes

## The gnomish warship
![image](https://user-images.githubusercontent.com/25270027/132992214-b1ee48b9-f22e-4234-b3e3-77071693179b.png)
The cockpit is fiercely defended by two very hungry maneaters. The engine room has been renovated into a laboratory for alien plant research for the time being. The ship is manned by two gnome critters, who are keep the garden pretty.  In the cockpit there is also a merchant, David the Space Gnome!

## David the Space Gnome
![image](https://user-images.githubusercontent.com/25270027/132992286-07e365ba-fdba-4a27-b801-8da29b9c57fc.png)
![image](https://user-images.githubusercontent.com/25270027/132993178-e4f660d6-3f86-452b-a59b-c2161235a0f0.png)

David sells many useful botany supplies, including fertilizers, strange seeds and an extremely expensive LUCA splicing module, which enables splicing of very distant species. He is quite stingy, so his wares don't come cheap! He himself buys honey (because it is tasty), human and monkey meat (to feed the maneaters), but not synth meat. Also, if you are lucky, he might have a golden secret item in stock-- but not always!

## Gnome critters
![image](https://user-images.githubusercontent.com/25270027/132992798-35e06fc8-3b38-4745-840b-2729082d9c90.png)
These helpful fellows water plants when they need it the most. You can hug them. They cry when you hurt them.

## Why's this needed? 
This is a contest entry. Gnomes are cute. 
The merchant sells many useful (yet expensive) tools for botanists to counteract some of the unintended side effects of piss nerfing -- botany actually suffered a lot from it and countless strats were invalidated when saltpetre output dropped by over 90%. You can get saltpetre through other means (such as QM, fabricating more GardenGears) but emptying dozens of tiny bottles into bigger containers makes it very tiresome. David sells saltpetre in larger bottles, making the process a bit easier (if you have the money). 
The 50000 credit splicing module enables very interesting strategies which have not been feasible before. When installed to your Plantmaster Mk3, it improves its minimum splice chance from 0% to 30%. If you somehow get past the maneaters, and have the money for the module, then you have almost unlimited potential in your splices -- but failures are still possible.

## Changelog

```changelog
(u)Vocalpocal
(*)Added a gnomish warship prefab. Go say hi to David the Space Gnome, who sells hydroponics supplies!
```

2021-09-12 20:25 UTC, Crackaduck commented
Amazing, only complaint is that there's no cargo pad at the to more easily get stuff to it.

2021-09-13 00:42 UTC, Zonespace27 commented
Reiterating on what was said on the forums, the LUCA seems incredibly overpowered, considering it _gives a permanent 30% splice chance, regardless of genome_, which I sense that the "easy" ways of getting 50k will be quickly rushed, should the prefab appear on the mining map PDA app.

2021-09-13 03:25 UTC, Tarmunora requested changes
Remove the trader and its commodities and this is good to go I think

2021-09-13 11:53 UTC, vocalpocal commented
> Reiterating on what was said on the forums, the LUCA seems incredibly overpowered, considering it gives a permanent, minimum 30% splice chance, regardless of genome, which I sense that the "easy" ways of getting 50k will be quickly rushed, should the prefab appear on the mining map PDA app.

The 30% chance matters only on very distant species, it does not increase splicing chances of species that are already quite similar. My gut feeling says that this is could make some weird mixes possible at 20 minute mark (and not any earlier) while it was possible in 50-70 minutes before. Although 20 is still very slow when compared to some other antag stuff in the game, I was thinking of ways to make it even slower. In order to unlock LUCA, you must deliver a Jumbo-sized produce to prove that you are a strong enough botanist to handle such alien tech! This would easily add 10 or 15 minutes to even the most rigorous speedrunners... And they would also have to know how to do botany in the first place.

> Remove the trader and its commodities and this is good to go I think

But without the trader there is no loot in the ship and it loses its purpose. Are you sure there are no compromises you are ready to take here?

2021-09-13 15:15 UTC, Azrun commented
>
> But without the trader there is no loot in the ship and it loses its purpose.

Preferably it would be worth visiting because it was interesting, not just because there is loot to gather.  I think it seems goofy and fun. 😃

2021-09-13 18:35 UTC, Tarmunora commented
> >
> > But without the trader there is no loot in the ship and it loses its purpose.
> 
> Preferably it would be worth visiting because it was interesting, not just because there is loot to gather.  I think it seems goofy and fun. 😃 

Additionally, there are still the garden gnomes which seem to automatically seek out and water crops

2021-09-13 18:38 UTC, vocalpocal commented
> Additionally, there are still the garden gnomes which seem to automatically seek out and water crops

They are technically nothing new for botany gameplay. They are just Botanical Misters with legs.

2021-09-14 00:49 UTC, unfunnyperson commented
Removing the trader would take the fun out of the prefab in my personal opinion, just remove the splicing module or whatever and its fine.

2021-09-14 04:10 UTC, virvatuli-gh requested changes
Where did you get the sound files, are they licensed correctly? Additionally, they're unnecessarily stereo and could easily be compressed by quite a bit. Did you read the audio guidelines?

2021-09-14 11:26 UTC, vocalpocal commented
Sounds are from the same source as the original gnome chuckle -- they are just cut parts from the original video. For the compression part I just did what the original gnomechuckle.ogg did and applied the same to these new sound files.

2021-09-14 14:42 UTC, Sovexe commented
We would need a proper and compatible license from the author to add their sounds to the repo unless this all open domain 😕

2021-09-14 15:33 UTC, Azrun commented
Perhaps this is a silly question... What makes this a warship?

2021-09-14 17:16 UTC, vocalpocal commented
> Perhaps this is a silly question... What makes this a warship?

I was planning to add turrets outside the ship which fire seething tomatoes... Needs some work but I might be able to push it before the deadline. The name just stayed that way, even though its current version does not have guns. The ship is shapes like a gnome head though.

2021-11-08 13:27 UTC, vocalpocal commented on code/obj/critter/gnome.dm
> +	ai_think()
Wait, I think the critter parent already does this on its own, unless I am completely mistaken.

2021-12-22 03:07 UTC, closed without merging