Allows item specials to smack bots (secbots/medibots/etc)
goonstation/goonstation pull request #5998
Opened 2021-09-13 03:44 UTC by frawhst

## About the PR 
Does that.

## Why's this needed? 
Fighting emagged/evil medibots can be annoying because special attacks don't work. Ditto for secbots.

```changelog
(u)CodeDude
(+)Special attacks can now be used to bonk securitrons, medibots, and other small robots.
```

2021-09-13 20:07 UTC, Tarmunora requested changes
Items specials previously could safely assume that any valid targets would be of type `mob/living`.
Please ensure that existing itemspecials will not runtime when used on a bot

2021-09-13 23:52 UTC, frawhst commented
> Items specials previously could safely assume that any valid targets would be of type `mob/living`.
> Please ensure that existing itemspecials will not runtime when used on a bot

Item specials also already accept `/obj/critter` as valid targets, which... already causes runtimes in testing (baton special, probably others). I'll go through and fix those as I find them.

2021-09-14 00:39 UTC, Tarmunora commented
> 
> 
> > Items specials previously could safely assume that any valid targets would be of type `mob/living`.
> > Please ensure that existing itemspecials will not runtime when used on a bot
> 
> Item specials also already accept `/obj/critter` as valid targets, which... already causes runtimes in testing (baton special, probably others). I'll go through and fix those as I find them.

lol rip

2021-09-14 00:45 UTC, frawhst commented
spark was the only one I found that consistently broke, everything else should work fine.

2021-09-14 00:56 UTC, Tarmunora approved these changes

2021-09-14 14:21 UTC, Sovexe requested changes

2021-09-14 14:21 UTC, Sovexe commented on code/WorkInProgress/ItemSpecials.dm
> +					B.explode()
this is not a safe way to handle damage. 
* This bypasses other procs to wake up hibernating critters up and is exploitable
* This bypasses critter vulnerabilities and defenses
* You should not be handling deaths in the weapon special

2021-09-14 14:21 UTC, Sovexe commented on code/WorkInProgress/ItemSpecials.dm
> +						B.explode()
ditto

2021-09-15 07:59 UTC, frawhst commented
Removed the effects on the spark special from critters/bots- only affects mobs now. Basically, same behavior as before, but no runtime.

2021-09-15 15:07 UTC, Sovexe commented
having it it the bots and critters is fine, but you would probably want to either make something like `special_act` or just some sort of generic take damage equivalent for obj critters and bots like mobs are using

2021-09-15 19:03 UTC, Tarmunora approved these changes

2021-09-15 23:50 UTC, frawhst commented
I'd be open to creating generic `TakeDamage` procs for critters/bots, but there's a bunch of places those should probably be used (fireflashes, etc), and I'd rather not do all of that in this PR, considering that would get way out of scope. Something for later.

2021-09-16 21:35 UTC, Sovexe commented on code/WorkInProgress/ItemSpecials.dm
> +					M.bodytemperature += 4 * mult
```suggestion
					M.bodytemperature += (4 * mult)
```

2021-09-16 21:35 UTC, Sovexe commented on code/WorkInProgress/ItemSpecials.dm
> +				M.bodytemperature += 4 * mult
```suggestion
				M.bodytemperature += (4 * mult)
```

2021-09-27 04:13 UTC, Sovexe approved these changes

2021-09-27 19:51 UTC, merged