Adds 3 new hats + extra mime beret colours
goonstation/goonstation pull request #6019
Opened 2021-09-15 03:18 UTC by WALPVRGIS

[SPRITES] [WIKI]

## About the PR 

- Adds baseball caps in 8 colours; these can be used inhand to flip them backwards (so you can be radicool).
- Adds costume goggles in 5 colours; these count as hats and can only be worn on your head, for that good space mechanic aesthetic.
- Adds pirate hats in 2 colours; I just wanted these for spooktober aaaa. 👻 
- Adds some recolours of the mime beret, named French berets.
- Moves hairclips to the accessory section in the clothing booth as opposed to headwear (made sense to me).

![hats1](https://user-images.githubusercontent.com/78533030/133364661-6fb82853-9362-4917-a5c8-5205eaf96c11.png)

Sorry if my baseball cap flipping code is stinky. :( Feel free to critique/offer suggestions for better methods.

## Why's this needed? 

- Character customization 😸 
- Spooktober!

## Changelog

```changelog
(u)Walpvrgis
(*)Added a few new hats in multiple colours; baseball caps, goggles (worn as a headband) and pirate hats, as well as some extra mime beret colours. These can be found in the clothing booth under Accessories and Headwear.
```

2021-09-15 04:07 UTC, Zonespace27 requested changes

2021-09-15 04:07 UTC, Zonespace27 commented on code/obj/item/clothing/hats.dm
> +	var/hatflip = 1
```suggestion
	var/hatflip = TRUE
```

2021-09-15 04:07 UTC, Zonespace27 commented on code/obj/item/clothing/hats.dm
> +				src.hatflip = 1
```suggestion
				src.hatflip = TRUE
```

2021-09-15 04:07 UTC, Zonespace27 commented on code/obj/item/clothing/hats.dm
> +				src.hatflip = 0
```suggestion
				src.hatflip = FALSE
```

2021-09-15 04:09 UTC, WALPVRGIS commented on code/obj/item/clothing/hats.dm
> +				src.hatflip = 0
Prayer hands emoji thank you!!

2021-09-15 14:23 UTC, Zonespace27 requested changes

2021-09-15 14:23 UTC, Zonespace27 commented on code/obj/item/clothing/hats.dm
> +		if(user.r_hand == src || user.l_hand == src)
```suggestion
		
```
This is probably redundant but I'm reviewing this on mobile so I can't guarantee that it's unneeded.

2021-09-15 14:23 UTC, Zonespace27 commented on code/obj/item/clothing/hats.dm
> +			return
```suggestion
			
```
Unneeded return

2021-09-16 09:37 UTC, WALPVRGIS commented on code/obj/item/clothing/hats.dm
> +			return
Thanks again! :D

2021-09-16 17:29 UTC, Sovexe requested changes

2021-09-17 06:57 UTC, WALPVRGIS commented on code/modules/vending/clothingbooth_items.dm
> +	name = "Baseball Cap"
LOL OH NO I can't believe I've done this 😔 🤣

2021-09-17 07:15 UTC, WALPVRGIS commented on code/obj/item/clothing/hats.dm
> +			boutput(user, "<span class='notice'>You flip your baseball cap around. Now it's backwards.</span>")
Made this change, but kept the `"basecapflip_[hatcolour]"`s just to keep the item/icon state swap working. :)

2021-09-19 05:28 UTC, merged