feature/musical instrument redesign
goonstation/goonstation pull request #6100
Opened 2021-09-26 20:17 UTC by ruben-svensson

## About the PR 
### This PR add's a new layout and new sounds to the piano and jazz as seen by the following examples: 

Full range piano

https://user-images.githubusercontent.com/29916243/134821968-16065725-2986-4407-8e87-3f3d32f15261.mp4

Full range saxophone

https://user-images.githubusercontent.com/29916243/134821980-f0d3f594-1369-445d-ba9a-a2dc94aecef2.mp4

Piano example

https://user-images.githubusercontent.com/29916243/134821988-e7eb2195-59ab-4d72-886c-56fcd768cd1a.mp4

Saxophone example

https://user-images.githubusercontent.com/29916243/134821986-ba1acdef-1883-4980-a6b1-74998f133036.mp4

The piano has been equipped with a total of 39 notes and the saxophone 30, I've gone through every single one of them and checked them (using FL Studio's tool Edison) to make sure they sound good, kept the file size low while not lowering the quality and made sure the volume is the same as the original.

My plan is to get every instrument updated with the new interface and new sound in the future.

The sound has been sourced from the following places:
Piano: https://www.reddit.com/r/piano/comments/3u6ke7/heres_some_midi_and_mp3_files_for_individual/ (by /u/SingleInfinity)
Saxophone: https://freesound.org/people/MTG/packs/20247/ (by MTG)

## Why's this needed? 
This PR will fix what multiple people have stated that the current layout of the notes is difficult to use, for example with the trumpet:
![image](https://user-images.githubusercontent.com/29916243/134822333-2805c5ae-6000-4b66-b06a-57aacb2cbcdc.png)
The current instruments also lack enough notes to create most songs, which this PR will fix for the piano and saxophone.

## Changelog

```changelog
(u)Grokberg
(+)Adds a new interface and new sound to the piano and saxophone.
```

2021-09-26 22:01 UTC, Gannets commented
This is much better!

2021-09-27 02:54 UTC, Sovexe requested changes

2021-09-27 02:54 UTC, Sovexe commented on code/modules/interface/multiContext/context_layouts.dm
> +		var/finalOff = spacingX * (buttons.len-3)
```suggestion
		var/finalOff = spacingX * (length(buttons)-3)
```

2021-09-27 02:54 UTC, Sovexe commented on code/modules/interface/multiContext/context_layouts.dm
> +			//	offY -= spacingY
```suggestion
```

2021-09-27 02:54 UTC, Sovexe commented on code/modules/interface/multiContext/context_layouts.dm
> +		for(var/i in 1 to blackKeys.len)
```suggestion
		for(var/i in 1 to length(blackKeys))
```

2021-09-27 02:54 UTC, Sovexe commented on code/obj/item/instruments.dm
> +	// special_index = 13
```suggestion
```

2021-09-27 02:54 UTC, Sovexe commented on code/obj/item/instruments.dm
> +		for (var/i in 1 to 37) // 12
The magic number 37 should be replaced by a define or a length proc

2021-09-27 02:54 UTC, Sovexe commented on code/obj/item/instruments.dm
> +		for (var/i in 1 to 29) // 12
is 29 correct here, there are 30 notes in the above list. 

This magic number 29 should be replaced by a define or a length proc

2021-09-27 02:54 UTC, Sovexe commented on code/modules/interface/multiContext/context_layouts.dm
> +		// var/octaveIndex = 1
```suggestion
```

2021-09-27 08:12 UTC, virvatuli-gh approved these changes
Not commenting on the code aspect of this but it's a great idea and all the sound-related stuff seems A-OK to me! Letting people have a wider range of notes to make some cool tunes is good in my books.

2021-09-27 19:08 UTC, ruben-svensson commented
Thanks for suggestions @Sovexe , please check again if I did it correct. :)

2021-09-27 20:26 UTC, ruben-svensson commented on code/modules/interface/multiContext/context_layouts.dm
> +		var/finalOff = spacingX * (buttons.len-3)
Change made

2021-09-30 14:04 UTC, Sovexe approved these changes

2021-10-04 08:33 UTC, merged