Cog1 Catering Maint Expansion
goonstation/goonstation pull request #6684
Opened 2021-11-14 21:39 UTC by Nexusuxen

## About the PR 

IMAGES AT THE BOTTOM OF THIS SECTION

Adds new back rooms to Catering Maintenance on Cogmap1, and gives the left and right entrances to the maintenance shaft bartender and chef access (though not to the construction area). Expands the Catering Router by a couple tiles, putting tables in the new tiles with a produce satchel and wrapping paper and scissors.

The 'Catering Backroom' - the larger boarded up room - contains the following additions:

- A modified version of Warcrimes' Meat4Cash vendor, renamed to FreshFlesh (the original vendor has been made a child of a new abstract obj, which is also the parent of the 'station-friendly' variant). The current stock is as follows (does not show the hidden 5 pieces of human meat, sold for 1k credits each)
![image](https://user-images.githubusercontent.com/28785926/141698962-9d8ddb59-01f6-471f-8ffc-8e66507d0d99.png)
Modification was made due to concerns that 42 pieces of meat available to the chef (and really anyone with maint access) for very cheap broke some balancing factors and trivialized the time-honored tradition of harvesting monkey meat.
- A broken gibber that, while useless, may be deconstructed and removed. People noted having an actual gibber in a cameraless maint backroom on-station would trivialize body disposal just a bit too much. The decorative variant is also more thematic.
- A Shitty Grill, for the wandering staffie to make their own backwater kitchen, and for the chef to grill things on
- Assorted catering equipment, including plates, 3 folding tables, beer in a box, a produce satchel, and a spare meatspike. Also random weird stuff, including a trowel, cardboard tube, monkey plushie, hand labeler, and the Swedish Fisk has been moved from the kitchen to this back room.
- Some random objects scattered across the floor, including a fancy pen, clipboard, briefcase, and NT beret, which clearly have no connection to one another, or so says the previous chef that worked here.
- NO CAMERAS, giving this general region a decent place to hide from the prying eyes of the AI.

A secondary maint nook has also been added, accessed via false wall, just to the right of the Catering Backroom. It includes:
- A "sleeping bag"
- A chair
- Assorted dirt and debris
- A trash pickle (delicious!)
- A ??? pill bottle
- A dried up joint
- A junk Spawner
- A great view ~into the solar array~ into space

In-game view (with fullbright enabled)
![image](https://user-images.githubusercontent.com/28785926/141698820-c7dde3f2-2197-40dd-98bd-4a5ca0a7c28e.png)

In-game view (with fullbright disabled)
![image](https://user-images.githubusercontent.com/28785926/141698828-b3c06fcb-0987-4b95-b8e4-523a5e921353.png)

Map editor view
![image](https://user-images.githubusercontent.com/28785926/141698859-c20719b6-c68a-4151-844f-450d6b5a90ee.png)

## Why's this needed? 

There aren't really that many places to hide from the AI in the vicinity of Catering - just about everywhere has camera coverage, save for small parts of the chapel. This helps to rectify that issue.

More maint backrooms with weird stories also adds some life to maint, and makes it feel more lived-in and used.

Provides genuinely useful things, especially to the chef, hopefully without causing imbalance issues. The meat vendor hopefully provides the chef a way to get rarer meats if botany is not cooperating, albeit at a ludicrous price to limit how much can be purchased. The grill and tables are also nice if a chef wants to use them - the tables in particular can be used to set up food displays in other departments, and the chef normally doesn't have access to a general fabricator, and as such can't get any normally.

Consistency with the general pattern of having crew being able to access their own maintenance shafts, even if they normally don't have maint access. (The bartender and chef were already able to access this area anyways, so giving them access to the other 2 entrances just makes sense)

## Changelog

```changelog
(u)Nexusuxen
(+)Catering maintenance on Cogmap1 has been expanded. Check it out!
```

2021-11-22 22:10 UTC, ZeWaka approved these changes

2021-11-22 22:10 UTC, ZeWaka commented on code/WorkInProgress/warcrimes.dm
> +	create_products()
```suggestion
	desc = "An exotic meat vendor."

	create_products()
```

2021-11-27 01:12 UTC, flrsh requested changes
Having a meat vending machine seems pretty out of theme with the rest of the map. Would be much better suited to some space derelict or prefab.

2021-11-27 01:24 UTC, Nexusuxen commented
> Having a meat vending machine seems pretty out of theme with the rest of the map. Would be much better suited to some space derelict or prefab.

While I disagree, if need be I can remove it. I implemented it since it was thematic to the sort of meat processing equipment the room has, given the 'spare' gibber and monkey spike. It was also intended to provide some rarer kinds of meat that are harder to get if botany isn't cooperating. If another dev/maintainer/admin could weigh in, or multiple, I'd really appreciate that. If I don't get any significant feedback regarding it the next few days I'll remove it.

2022-01-16 14:11 UTC, Nexusuxen commented
I have not been maintaining this due to the combination of:
- Semi-frequent updates to Cog1 requiring consistent merge conflict resolution
- Lack of response to requested re-reviews and lack of further reviews

I am still interested in keeping this open, so I'll try to resolve the merge conflicts later today to avoid the conflicts becoming too severe.

2022-01-17 09:13 UTC, ZeWaka commented
@Nexusuxen 
> I have not been maintaining this due to the combination of:
> 
> * Semi-frequent updates to Cog1 requiring consistent merge conflict resolution
> * Lack of response to requested re-reviews and lack of further reviews
> 
> I am still interested in keeping this open, so I'll try to resolve the merge conflicts later today to avoid the conflicts becoming too severe.

I'd like to merge this, with the redaction of the vending machine for now.

2022-03-17 20:59 UTC, Nexusuxen commented
Merge conflict resolved & vendor removed.

NOTE: In the time that this PR has been gathering dust, a Random Room was added here, and as such this PR will necessitate its removal.

2022-03-17 23:16 UTC, ZeWaka approved these changes
We can re-add the random room elsewhere or back there later.

2022-04-21 17:54 UTC, TTerc commented
!merge_upstream

2022-04-21 18:00 UTC, TTerc approved these changes

2022-04-21 18:01 UTC, merged