Fixes #6711: Makes kudzu check for DNR
goonstation/goonstation pull request #6719
Opened 2021-11-18 04:46 UTC by Yellow-Mushroom

## About the PR 

This PR makes it that, before someone becomes a kudzuperson, they have their DNR status checked. 

If they have set DNR, they will be gibbed before the bulb is opened, having the bulb open to a pretty grotesque scene with some flavor text. 

(I can add a video if requested)

## Why's this needed? 

DNR should be respected

2021-11-18 04:55 UTC, Zonespace27 commented on code/modules/events/gimmick/kudzu.dm
> +					sleep(10)
```suggestion
					sleep(1 SECOND)
```

2021-11-18 05:00 UTC, Zonespace27 commented
Put "Fixes #6711" in PR body for autoclose of the issue

2021-11-18 05:55 UTC, ZeWaka requested changes

2021-11-18 05:55 UTC, ZeWaka commented on code/modules/events/gimmick/kudzu.dm
> +				if(!isalive(M) && M.ghost && M.ghost.mind && M.ghost.mind.dnr)
try using `?.` syntax here :)

2021-11-19 05:19 UTC, Yellow-Mushroom commented on code/modules/events/gimmick/kudzu.dm
> +				if(!isalive(M) && M.ghost && M.ghost.mind && M.ghost.mind.dnr)
should be fixed by 7e3c12c

2021-11-19 07:06 UTC, ZeWaka commented on code/modules/events/gimmick/kudzu.dm
> +					src.visible_message("<span class='alert'>The bulb opens, having drained all the nutrients from [M.name]!</span>")
```suggestion
					src.visible_message("<span class='alert'>The [src] opens, having drained all the nutrients from [M]!</span>")
```

2021-11-19 07:06 UTC, ZeWaka commented on code/modules/events/gimmick/kudzu.dm
> +					new/obj/decal/opened_kudzu_bulb(get_turf(src.loc))
unnecessary
```suggestion
					new/obj/decal/opened_kudzu_bulb(get_turf(src))
```

2021-11-19 17:28 UTC, ZeWaka approved these changes

2021-11-19 17:37 UTC, merged