makes extinguishers toggle being an open container based on safety, replaced the SAFETY = 0 and SAFETY = 1 with FALSE and TRUE
goonstation/goonstation pull request #6774
Opened 2021-11-25 16:15 UTC by ZWRh3

…eplaces the 0 and 1 with TRUE and FALSE

[XS] 
## About the PR 

Made fire extinguisher toggle between being an open/closed container based on the safety
this change has a side effect of allowing steam in fire extinguishers

## Why's this needed? 

i hated the fact that smoke powder could get out of an obviously closed container

## Changelog

```changelog
(u) ZWRh3
(+) Made fire extinguisher toggle between being an open/closed container based on the safety
```

2021-11-25 16:16 UTC, ZWRh3 commented
I hope i didnt fuck anything up since this is the first PR i have made ever.

2021-11-25 16:24 UTC, flappybatpal commented
You don't need to add a label like [XS], that is automated.
I would say the labels for this is [BALANCE].
No real need to note that you change the 1 and 0 to TRUE and FALSE for such a small PR and simple change. Coders will easily understand why this is changed.
The changelog entry is accurate but probably not descriptive enough for players to actually understand what this does.

2021-11-25 16:36 UTC, ZWRh3 commented
edited the changelog

2021-11-25 18:00 UTC, Zonespace27 requested changes

2022-01-09 03:59 UTC, ZeWaka approved these changes

2022-01-09 03:59 UTC, ZeWaka commented on code/modules/chemistry/tools/extinguisher.dm
> +		ADD_FLAG(src.flags,OPENCONTAINER)
```suggestion
		ADD_FLAG(src.flags, OPENCONTAINER)
```

2022-01-09 03:59 UTC, ZeWaka commented on code/modules/chemistry/tools/extinguisher.dm
> +		REMOVE_FLAG(src.flags,OPENCONTAINER)
```suggestion
		REMOVE_FLAG(src.flags, OPENCONTAINER)
```

2022-01-09 03:59 UTC, ZeWaka commented on code/modules/chemistry/tools/extinguisher.dm
>  	return
```suggestion
```

2022-01-09 04:06 UTC, merged