Phone Datum System & Landline Phone Refactor
goonstation/goonstation pull request #6938
Opened 2021-12-16 22:21 UTC by Nexusuxen

[FEATURE]

## About the PR 

Implements a new telephone system with an emphasis on modularity and flexibility with the potential to be usable with almost any atom. Refactors the current landline phones to use this new system, including the new TGUI that this datum uses. New features and fixes of the current phones, not including backend fixes and features for coders, include:
* Unique 7-digit phone numbers assigned to each phone at roundstart
* A TGUI window which lets you both directly dial phones as you could before, or manually dial based on a number
* Some new sounds, including DTMF tones for each dialpad button (though no previous sounds have been replaced)
* Phone handsets will now only talk_into nearby intercoms if the intercoms' microphones are actually on
* That bug where wall phones revert to regular phones is also fixed here if that PR to fix them didn't get merged yet

Planned features which may or may not be added during the review process of this PR depending on their size:
* Ability to make phones unlisted in contact lists via multitool while not barring people from calling the number directly
* Listing contacts in alphabetical order
* Finalizing the ability to separate landline phones and their handsets through the destruction of one of them to make an improvised weapon out of either

The new Datum Phone behavior is split up between 3 general areas:
* The Phone Datum
* The Atom that the phone datum belongs to
* Phonecall datums

The phone datum functions as both control and interface between whatever atom it is designed to work with, and phonecall datums. These phonecall datums are intended to work with any phone datum of any kind, and will relay information between all members of a call, such as when someone disconnects or joins, and speech from call members. Interactions between phonecall and members is intended to be done almost entirely through customizable procs to better ensure that distinct, potentially radically different behavior is still compatible with the standard behavior or other similarly radically different behavior.
This would conceivably let a cell phone contact a landline without needing to modify either of the code defining their behavior to make this specific contact possible. Technically, you'd even be able to contact a phone that is being used by a machine like the mainframe without any fuss, assuming such a phone datum were present in said machine.

Modularity and future-proofing is, again, an emphasis in this system. You likely will not need to make any changes to the base phone or phonecall datums, or create your own phonecall datum type, in order to implement devices which have phone interactions. There is support for custom checks to make a phone not render in contact lists, not render in the contact list for specific phones, not be contactable even with manual dialing, etc. Again, much of the behavior is highly modular and split between dozens of procs. This is documented in the main phone.dm file; most procs also include some documentation (some of which may be outdated, but I do plan to review my documentation more to make sure it's sufficient). The precise customizable behavior could let you make things like private phone networks, PNET based phones, mainframe-hosted chat rooms, phones that explode when they're vaped through, etc.

As I've implied, there is also support for group calls; however, as landlines will not be supporting them yet/at this time, I am leaving them in a mostly-finished state. It's unnecessary for the refactored landlines to work. It's mostly functional and minimally buggy, but I've yet to implement several key features to really make them work well, so I would recommend against using group calls. However, the entire system is still designed to work with them, including more niche things like vaping and voltronning into phones.

I normally document all the changes/added procs in my PRs, but 1) There is a lot, and 2) Much of the documentation exists in the code as-is. I hope the above descriptions are sufficient to explain the general idea of this PR.

## Why's this needed? 

* General cleanliness, as previous phone code was a little messy and had some bugs, with poor ability to interact with other kinds of phones
* I want to add phones for AIs to use without making a runtimey buggy mess of butchered old phone code
* CHUI -> TGUI conversion
* A hopefully thorough and at least fairly robust system to support all kinds of phones and phone accessories, like cellphones and PDA phone modules, and even MechComp or mainframe based phones, or machine-machine packet-like communication with phones (god help us)
* You get to hear the beep beep sounds when you click on the dial pad :)
* Assorted minor bug changes, such as previously being able to use an intercom to hear through a phone even if the mic was off

I'm sorry for the extremely large PR, but rest assured that I love my comments and spacing, so the numbers of changed lines won't reflect reality. It's still a lot of new lines though. I really racked my brain as to how I could atomize this but I really couldn't think of a way to without risking breaking things. Maybe I overloooked a really fucking obvious way to do it, though. Additionally, I know there are absolutely oversights, but it's really hard to keep track of things on a project this large, so I'll be continuing to work on this and fix things as I go.

## Images
The new phone UI.
![image](https://user-images.githubusercontent.com/28785926/146455058-ba72025d-e8e6-46d9-b1ae-9cbee2cecc59.png)

How the screen will display a fully dialed phone number
![image](https://user-images.githubusercontent.com/28785926/146455156-f0d34a53-6b2b-42d5-9057-c3d93bb866cd.png)

The dialpad does not scale, but making the window bigger will not cause weird behavior.
![image](https://user-images.githubusercontent.com/28785926/146455236-7657ed9e-f60b-42bc-aad1-41eb69289cd8.png)

Neither will making the window very small.
![image](https://user-images.githubusercontent.com/28785926/146455285-700bc245-102b-4d94-b622-b985a05ffa76.png)

## Changelog

```changelog
(u)Nexusuxen
(*)Phones completely refactored with a shiny new TGUI and phone number system. Please report any odd or buggy behavior!
```

2021-12-16 22:25 UTC, ZeWaka commented
What's with the dash and parenthesis? Looks weird. The dash should appear when you put in the 4th number.

2021-12-16 22:45 UTC, Nexusuxen commented
> What's with the dash and parenthesis? Looks weird. The dash should appear when you put in the 4th number.

Fixed

2021-12-17 02:09 UTC, ZeWaka commented on _std/compatibility.dme
> +// END_FILE_DIR
No

2021-12-17 02:09 UTC, ZeWaka commented on config/admins.txt
> +aft2001 - Host
No

2021-12-17 02:12 UTC, Nexusuxen commented on config/admins.txt
> +aft2001 - Host
oh god fucking- Sorry!

2021-12-17 02:17 UTC, Nexusuxen commented on _std/compatibility.dme
> +// END_FILE_DIR
fixed

2021-12-17 02:26 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/PhoneDefault.js
> +    <Button m={0.5} height={5} width={7.75} fontSize={2.25} bold={1} fontFamily={'Sans-serif'} backgroundColor="red"
Did you run the formatter? This probably shouldn't be on one line

2021-12-17 02:26 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/PhoneDefault.js
> +      <Box backgroundColor="#86ab6c" textColor="black" bold={1} opacity={1} height={3} fontSize={2.9} fontFamily="monospace">
Ditto

2021-12-17 02:26 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/PhoneDefault.js
> +    <Button m={0.5} height={5} width={7.75} fontSize={2.25} bold={1} fontFamily={'Sans-serif'} disabled={(currentCall | incomingCall)}
Ditto

2021-12-17 02:26 UTC, ZeWaka commented on code/modules/phones/phones.dm
> +	var/static/keyTones = list( // Keys and their tone sound .oggs; also doubles as input validation.
Doc comments.

2021-12-17 02:26 UTC, ZeWaka commented on code/modules/phones/phones.dm
> +	var/allowJoinRequests = FALSE // can people join without an invite?
Ditto

2021-12-17 02:40 UTC, Nexusuxen commented on tgui/packages/tgui/interfaces/PhoneDefault.js
> +    <Button m={0.5} height={5} width={7.75} fontSize={2.25} bold={1} fontFamily={'Sans-serif'} backgroundColor="red"
I did not; I just poked around and couldn't find any instructions regarding the term 'formatter' in neither the vscode. I'll ask on the discord.

2021-12-17 02:50 UTC, Nexusuxen commented on tgui/packages/tgui/interfaces/PhoneDefault.js
> +    <Button m={0.5} height={5} width={7.75} fontSize={2.25} bold={1} fontFamily={'Sans-serif'} backgroundColor="red"
I assumed you meant for each prop to be on its own line, so if that wasn't the case then I'll change it again (hopefully if/when I can find that formatter). Won't resolve issue since I'm not sure if it actually is resolved.

2021-12-17 03:31 UTC, Nexusuxen commented
As a note I'm considering moving doRing() to the base phone datum, but I likely won't be doing that tonight.

2021-12-18 18:56 UTC, Nexusuxen commented
Converted to draft as I am still working on cleaning up and organizing my code; I probably jumped the gun on making this PR. However, feedback & reviews are still very much so welcome.

2021-12-18 22:22 UTC, ZeWaka requested changes

2021-12-18 22:22 UTC, ZeWaka commented on code/obj/machinery/phone.dm
> +	var/nameOverride = FALSE // for mappers who want to have custom phone names; set the actual name var of the phone, and this to TRUE
doc comments

2021-12-18 22:22 UTC, ZeWaka commented on code/modules/phones/landline.dm
> +	var/obj/machinery/phone/ourHolder = null /// we can't override holder, so we make our own for when we need to refer to a handset or something
this is not how doc comments work

2021-12-18 22:22 UTC, ZeWaka commented on code/modules/phones/phones.dm
> +	var/atom/holder = null /// the atom we belong to; you'll have to define a new var for your specific atom type if you need to
this is not how doc comments work

2022-01-10 22:50 UTC, Cboyjet4 commented
goonstation devs overcomplicating simple things that only like 4 people will ever use to the full extent to explode a bomb or something

2022-01-14 14:46 UTC, Nexusuxen commented
Haven't had the motivation to work on this recently, but I still would like to continue at some point. I'll leave it open as a draft though since I'll always welcome feedback/input/suggestions; a lot of changes I've really liked stemmed from or were based on said feedback.

Currently I need to figure out what I was doing and revert some unnecessary changes, then work on making the whole contact list alphabetizing process be done in TGUI rather than in BYOND. I also need to work heavily on cleaning up and renaming the procs and other logic being done, though my inexperience is gonna make that a bit slow.

2022-03-17 20:33 UTC, closed without merging

2022-03-17 22:11 UTC, Conchuckter commented
I might have a look at working on it, I really like the idea of more communication methods.

2022-03-18 01:29 UTC, DisturbHerb commented
i am crying and shaking rn 😭😭