Fix single maintenance-inner-central tile designation
goonstation/goonstation pull request #6977
Opened 2021-12-23 20:15 UTC by pgmzeta

## About the PR 
Replaces one EVA tile with an inner-maintenance tile on oshan and oshan-xmas

## Why's this needed? 
Founds by radstorms affect the EVA tile, but not maintenance tiles.
Fixes https://github.com/goonstation/goonstation/issues/6922

## Notes
* I don't know why the changes to each map resulted in different diffs (???)
* First PR here, please double-check my work <3

2021-12-23 20:38 UTC, ZeWaka commented
It resulted in different diffs due to how the map files are encoded.

2021-12-23 20:40 UTC, ZeWaka requested changes
`/area/station/maintenance/inner` is not a valid area, per the error in the runtime checker

2021-12-23 23:47 UTC, ZeWaka commented on maps/oshan.dmm
> +/area/station/maintenance/inner)
still didn't change it

2021-12-24 00:20 UTC, pgmzeta commented on maps/oshan.dmm
> +/area/station/maintenance/inner)
thank you 🙏

2021-12-24 01:34 UTC, merged