Changes capulettium to allow for more interactive RP changeling stings
goonstation/goonstation pull request #7120
Opened 2022-01-08 14:52 UTC by colossusqw

[LABEL][balance][feature]

## About the PR  This changes the effect of capu from a KO to a paralysis like effect that also stops you speaking, this won't change its efficacy as a KO chem, just allow whoever got injected it something to look at for the couple of minutes it lasts.

## Why's this needed?  Changeling stings on RP tend to be a bit of a "you're asleep for 2 minutes now, and then you're dead" kind of thing, and it seems many people on the RP chat don't quite enjoy it, so after some talk with them i decided to make it a bit more interesting for the person who just got ling stung to be able to see what the changeling is doing/whisper things to them, which hopefully will create some more RP.

## Changelog

```changelog
(u)Colossusqw
(+)Makes you aware of your surroundings instead of asleep during the capulettium effect, but still unable to speak or move.
```

2022-01-08 14:53 UTC, colossusqw commented
![image](https://user-images.githubusercontent.com/52242687/148648796-ff9f6ae8-05a4-4a7d-9df2-a73d4e0c6c34.png)
how the status effect that stops you from talking looks

2022-01-08 21:28 UTC, Tarmunora requested changes

2022-01-08 21:28 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Misc.dm
> +
```suggestion
```

2022-01-08 21:28 UTC, Tarmunora commented on code/modules/status_system/statusEffects.dm
> +	var/tickspassed = 0
```suggestion
```

2022-01-08 21:28 UTC, Tarmunora commented on code/modules/status_system/statusEffects.dm
> +	maxDuration = 2 MINUTES
```suggestion
```

2022-01-08 21:42 UTC, TobleroneSwordfish commented
As someone who makes way too much capulettium I really like this, any opportunity for villainous monologues is great.

2022-01-09 11:07 UTC, MACIEKBAKI commented
You could extend this functionality to the vampire's hypnosis ability as well. It is currently also a full knockout, not allowing for much RP with it honestly.

2022-01-09 12:28 UTC, colossusqw commented
> You could extend this functionality to the vampire's hypnosis ability as well. It is currently also a full knockout, not allowing for much RP with it honestly.

oooh that sounds good, if this gets merged i'm gonna PR it too then, thanks for the idea!

2022-01-10 14:26 UTC, virvatuli-gh commented
I like it, makes capulettium more interesting beyond just being sleepy time

2022-01-11 22:05 UTC, Tarmunora approved these changes

2022-01-13 11:03 UTC, merged