.
goonstation/goonstation pull request #7126
Opened 2022-01-08 20:23 UTC by DEAD-VICKY

due to abuse i will not be finishing this

2022-01-20 22:43 UTC, DimWhat commented
holy hell I haven't even look at everything and I'm already apalled by this. Hell no.

2022-01-20 22:51 UTC, Zonespace27 commented
Nice verified tags. Have you _actually_ tested any of this?

2022-01-20 23:10 UTC, DimWhat reviewed
Okay so this is only some of the stuff that I've seen. This needs a LOT of work and I'm not even talking about the mere idea of a black market.

2022-01-20 23:10 UTC, DimWhat commented on code/datums/commodity.dm
> +/datum/commodity/blackmarket/wrestler/laptop
You can already buy these.

2022-01-20 23:10 UTC, DimWhat commented on code/datums/commodity.dm
> +/datum/commodity/blackmarket/wrestler/hairballkey
Unable to even be found.

2022-01-20 23:10 UTC, DimWhat commented on code/datums/commodity.dm
> +	comname = "Pure Telecrystal Token"
Would prefer to use the name of whatever the traitor points are that round.

2022-01-20 23:10 UTC, DimWhat commented on code/datums/commodity.dm
> +	price = 605000
Way too much.

2022-01-20 23:10 UTC, DimWhat commented on code/datums/commodity.dm
> +/datum/commodity/blackmarket/wrestler/glitch_gun
Not able to be gotten at all.

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Stop with your big ascii art

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////
Stop.

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +/////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////////////
Stop.

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Stop.

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +/////////////////////////////////////////////////////////
Stop.

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +/////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +/////////////////////////////////////////////////////////
Stop

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +		src.goods_sell += new /datum/commodity/blackmarket/
Some of these paths don't do anything

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +		src.goods_buy += new /datum/commodity/blackmarket/wrestler/
Again, blank paths.

2022-01-20 23:10 UTC, DimWhat commented on code/modules/economy/trader.dm
> +//////////////////////////////////////////////////////////////////////
Stop.

2022-01-20 23:43 UTC, Zonespace28 commented
Hey there! Just for pure transparency, my main account, @Zonespace27, was blocked by @DEAD-VICKY, making me unable to comment on this PR, following
https://github.com/goonstation/goonstation/pull/7126#issuecomment-1017996494 this comment,
which followed this https://forum.ss13.co/showthread.php?tid=17721 forum thread, and I fully expect this account to get blocked, too!

2022-01-20 23:58 UTC, ZeWaka requested changes
1. incorrect changelog
2. no giant word ascii art headers
3. this doesn't even compile bro
4. follow the contributor guidelines
5. this PR isn't labeled and i won't look at it again until it is

2022-01-20 23:58 UTC, ZeWaka commented on code/datums/commodity.dm
> +				comtype = /obj/item/clothing/under/chameleon
^

2022-01-20 23:58 UTC, ZeWaka commented on code/datums/commodity.dm
> +				comtype = /obj/item/clothing/suit/armor/turd
no

2022-01-20 23:58 UTC, ZeWaka commented on code/datums/commodity.dm
> +				comtype = /obj/item/clothing/suit/armor/tdome/red
no

2022-01-20 23:58 UTC, ZeWaka commented on code/datums/commodity.dm
> +				comtype = /obj/item/clothing/shoes/swat/noslip
^

2022-01-20 23:58 UTC, ZeWaka commented on code/datums/commodity.dm
> +/datum/commodity/blackmarket/surplus/phaser
^

2022-01-21 00:07 UTC, Eagletanker commented on code/datums/commodity.dm
> +/datum/commodity/blackmarket/wrestler/katana_nukeop
(not a problem with code just want to leave a note)
Nuke Op's dont last long enough to reach the time when this trader would become active according to your post on the forums. I'd like to clarify too, that with all my stuff, I'm not a dev. I'm some dumbass who doesnt know how to get out of review mode in git and ended up in it on accident.

2022-01-23 20:05 UTC, closed without merging