Daggers throw stun gets better at range (and awful at pointblank)
goonstation/goonstation pull request #7169
Opened 2022-01-14 20:45 UTC by mc-oofert

[BALANCE]

## About the PR 
Daggers now get better with range, with a stronger disorient and stamina damage the more tiles it travels.
Ranges above 3 directly inflict a stun. Also its crap at pointblank. Still cuts people just fine though.
https://user-images.githubusercontent.com/70376633/149582328-a7a40219-6f72-4cfc-b960-354ddc0361c9.mp4
## Why's this needed? 
Some nerd rushing you with a dagger and permastunning you is never funny, especially on rev rounds.
Also, made sec drop their guns and get stunned for 5 seconds, which usually means security ends up getting stunned with their stuff, with little chance to fight back. This PR makes it better the farther it travels, and also makes it crap at pointblank throws.

## Changelog

```changelog
(u)Jimmyl
(+)Dagger stun is now based on tiles travelled, so you cant pointblank people for free instastuns.
```

2022-01-14 21:02 UTC, ThatFiveGuys commented
Personally feel as if itd be better if it just made you lie down so you couldnt chainthrow it

2022-01-14 22:01 UTC, Zonespace27 requested changes
ehh on the PR itself, review anyway

2022-01-14 22:01 UTC, Zonespace27 commented on code/obj/item/misc_weapons.dm
> +		var/R = thr.get_throw_travelled()
more specific variable name please

2022-01-14 22:01 UTC, Zonespace27 commented on code/obj/item/misc_weapons.dm
> +			A:force_laydown_standup()
never use :

2022-01-14 22:01 UTC, Zonespace27 commented on code/obj/item/misc_weapons.dm
> +		if(R > 3)
make this (the 3) into a variable on the knife itself

2022-01-14 22:01 UTC, Zonespace27 commented on code/obj/item/misc_weapons.dm
> +			C.do_disorient(stamina_damage = (R * 10), weakened = 0, stunned = 0, disorient = (R * 5), remove_stamina_below_zero = 1)
stamina damage feels too low

2022-01-15 00:45 UTC, Crackaduck commented
I feel like this is too big a nerf. It's strong, but this patch give's it too little utility at close range, where many stun weapons could also be considered too strong, and leaves it with too much risk and too little reward. I feel like it would just be better to just nerf the stun time, or make it so that it can't stun people in quick succession.

2022-01-15 08:47 UTC, mc-oofert commented
> I feel like this is too big a nerf. It's strong, but this patch give's it too little utility at close range, where many stun weapons could also be considered too strong, and leaves it with too much risk and too little reward. It would be better to just nerf the stun time, or make it so that it can't stun people in quick succession.

just use a stunbaton if you like permastunning people at melee range

2022-01-15 09:25 UTC, mc-oofert commented on code/obj/item/misc_weapons.dm
> +			A:force_laydown_standup()
doesnt work without it

2022-02-06 00:47 UTC, closed without merging