Hunter gear teleport ability
goonstation/goonstation pull request #7269
Opened 2022-01-23 15:35 UTC by flappybatpal

[FEATURE]

## About the PR 
Adds an ability to hunters to teleport their gear to their location on a 40 second cooldown.
Starts hunter spear and rifle in their backpack.

https://user-images.githubusercontent.com/70909958/150685198-887a0120-2102-43de-80d7-367dabb2f7c8.mp4

## Why's this needed? 
Hunters are gear based antags with limited other abilities (door opening, better melee) who lose a lot of their power if they drop their gear. Observing hunters reveals this is pretty common!
Spear and rifle would not spawn if you were missing an arm, which is not great!

## Changelog

```changelog
(u)Flappybat
(*)Added a Recover Gear ability to Hunters. Use it to teleport your rifle, spear or cloak back to your position if you lose them.
```

2022-01-25 22:30 UTC, pali6 requested changes

2022-01-25 22:30 UTC, pali6 commented on code/datums/abilities/misc/hunter_summongear.dm
> +	duration = 50
Should probably be `5 SECONDS`

2022-01-25 22:30 UTC, pali6 commented on code/datums/abilities/misc/hunter_summongear.dm
> +			if (istype(HG, /obj/item/gun/energy/plasma_gun/hunter))
In this part of the code `M.mind && M.mind.key == ...` could be replaced with `M.mind?.key = ...`.

Also the continue statements don't seem to be necessary as they are always at the end of each branch.

2022-01-25 22:30 UTC, pali6 commented on code/datums/abilities/misc/hunter_summongear.dm
> +			if (istype(HG, /obj/item/gun/energy/plasma_gun/hunter))
In this part of the code `M.mind && M.mind.key == ...` could be replaced with `M.mind?.key = ...`.

Also the continue statements don't seem to be necessary as they are always at the end of each branch.

2022-01-25 22:30 UTC, pali6 commented on code/datums/abilities/misc/hunter_summongear.dm
> +			if (istype(HG, /obj/item/gun/energy/plasma_gun/hunter))
In this part of the code `M.mind && M.mind.key == ...` could be replaced with `M.mind?.key = ...`.

Also the continue statements don't seem to be necessary as they are always at the end of each branch.

2022-01-25 22:30 UTC, pali6 commented on code/datums/abilities/misc/hunter_summongear.dm
> +			boutput(M, __red("Your plasma gun is lost or destroyed!"))
I think the __red stuff is pretty deprecated but not sure. I'd just manually enter the span with the alert class.

2022-01-25 22:30 UTC, pali6 commented on code/obj/item/gun/energy.dm
> +	proc/send_to_target_mob(var/mob/living/M)
The copypasted proc is not very neat. Ideally I think this all would be a component. But if you don't feel like making it a component probably make the proc a global one instead.

2022-02-06 17:02 UTC, TTerc approved these changes

2022-02-06 17:02 UTC, merged