Fix players dying in the blob tutorial
goonstation/goonstation pull request #7276
Opened 2022-01-23 23:06 UTC by MetricDuck

[BUG]

## About the PR 
During the learning to move by right-clicking phase of the blob tutorial, players are currently able to:
- Kill themselves by clicking the cordon or the wall (then walking into the cordon);
or
- Jump to adjacent blob tutorial areas.

Dying in the tutorial bypasses the grace period 2nd respawn and immediately ends your antagonist round. This is unfortunate for players rolling a reasonably rare antagonist for the first time.

## Why's this needed? 
Fixes #6511.

2022-01-23 23:06 UTC, MetricDuck commented
This is a resubmission of [this one](https://github.com/goonstation/goonstation/pull/7275) because I messed it up.

2022-01-25 22:19 UTC, pali6 requested changes
Instead of making the list change it so it checks area and turf type (not name) of the click when the click happens. Unless there's something preventing that solution.

2022-01-25 23:28 UTC, MetricDuck commented
> Instead of making the list change it so it checks area and turf type (not name) of the click when the click happens. Unless there's something preventing that solution.

Switched logic from checking from a list of turfs of pre-checked turfs to checking its in the correct area and the correct type.

2022-01-27 01:15 UTC, ZeWaka approved these changes

2022-02-01 05:42 UTC, merged