Make fabricators deconstructable without head of staff access
goonstation/goonstation pull request #7294
Opened 2022-01-25 01:19 UTC by stonepillars

## About the PR 

Makes fabricators deconstructable, specifically by giving them the `DECON_BUILT` decon flag

## Why's this needed? 

Fixes #7250 

![image](https://user-images.githubusercontent.com/65367576/150892527-5937079e-03ad-4aa0-9ac3-715de67b49e0.png)

## Changelog

```changelog
(u)Stonepillar
(+)Fabricators can once again be deconstructed without a head access.
```

2022-01-25 05:18 UTC, Azrun requested changes
Don't think changelog is needed as this is a bug.

2022-01-25 05:18 UTC, Azrun commented on code/obj/machinery/manufacturer.dm
> +	deconstruct_flags = DECON_SCREWDRIVER | DECON_WRENCH | DECON_WELDER | DECON_WIRECUTTERS | DECON_MULTITOOL | DECON_BUILT
Add a comment about why flag is added.

2022-01-25 16:11 UTC, Azrun approved these changes

2022-01-25 16:12 UTC, merged

2022-01-25 16:52 UTC, zjdtmkhzt commented
Does this make sense though? The fabricators aren't player built by default, so why would they get this flag. Shouldn't we fix the access check so it works properly for fabricators instead?

2022-01-26 21:19 UTC, Azrun commented
With hindsight I agree zjdtmkhzt.  At the time we incorrectly assumed this would result in the desired behavior (which it technically did) but had unforeseen consequences... like rkit/gene-booth locking PR. 😢