Adds new thrall abilities
goonstation/goonstation pull request #7368
Opened 2022-02-01 22:04 UTC by TerraGS

[BALANCE][REWORK]
## About the PR 

Adds new thrall-related abilities for thrall and vampire.
Alert Thralls: Gives vampires an ability that functions similar to the sec alert pda program.
Locate Master: Lets thralls toggle a pointer hud that guides them to their master.

Thralls will also be alerted when their master is in critical condition. This comes with a change to thralls that makes it so they die shortly after their master is killed.

## Why's this needed? 

These changes are intended to give more of a cooperative sense to the thrall role. Having an additional drawback should help disincentivize the "free antag" mentality.

## Changelog

```changelog
(u)TerraGS
(*)Vampires can now send an alert to their thralls for help via 'Alert Thralls' ability. Thralls can now pinpoint their master via 'Locate Master' ability. Thralls now die when their master is killed and will be warned when their master is in crit.
```

2022-02-01 22:24 UTC, ThatFiveGuys commented
I feel as if alert thral should automatically turn on the locate master ability.

2022-02-01 23:21 UTC, MeggalBozale commented
This is nice! Would be awesome to see more teamwork between thralls and their vampire, much better than the usual zombies running around doing benign things

2022-02-01 23:53 UTC, Vaskritaya commented
definitely feels like the thrall death would be too sudden. I've always felt like one of the duties of thralls is to revive their master should they die. The idea of thralls being tied to the master more is great, but I agree with fiveguys that it would make for more interesting gameplay if it was more gradual somehow.

2022-02-02 01:52 UTC, TerraGS commented
> definitely feels like the thrall death would be too sudden. I've always felt like one of the duties of thralls is to revive their master should they die. The idea of thralls being tied to the master more is great, but I agree with fiveguys that it would make for more interesting gameplay if it was more gradual somehow.

Good news is that I coded the kill_thrall function in such a way that I can add a delay to the actual dying part (currently between 1 and 5 seconds) so there is room to make it a longer span of time sufficient for a chance to revive the vampire.

2022-02-02 02:09 UTC, TobleroneSwordfish commented
> definitely feels like the thrall death would be too sudden. I've always felt like one of the duties of thralls is to revive their master should they die. The idea of thralls being tied to the master more is great, but I agree with fiveguys that it would make for more interesting gameplay if it was more gradual somehow.

Seeing my thralls leading a riot outside security after I was executed was one of my favourite vampire moments so I don't like the idea of it instantly killing them. Otherwise, great PR, more cooperative antags are the best.

2022-02-02 23:28 UTC, TerraGS commented
> I feel as if alert thrall should automatically turn on the locate master ability. Having thralls straight up just die when master dies seems boring, I think it would be more fun if the cap on blood loss was removed and the amount of blood drained was increased a lot (enough to where drinking more blood only delays your death and you cant really sustain it. If you manage to revive your dead master this uptick in blood loss + cap removal is reverted and its back to normal. Itd essientally put thralls on a timer to clone/revive there master or else they die. Overall good pr

It is done

2022-02-17 00:58 UTC, NightmareChamillian approved these changes
Aside from formalities for the if statements, everything seems peachy keen!

2022-02-17 00:58 UTC, NightmareChamillian commented on browserassets/html/traitorTips/vampireTips.html
> +				40 - <em>Enthrall / Thrall Speak / Alert Thralls</em>, revive a dead human as an enthralled servant.<br>
Wouldn't it be better if alert thralls had it's own mention, rather than being lumped in without mention?

2022-02-17 00:58 UTC, NightmareChamillian commented on code/datums/abilities/vampire.dm
> +		else if(isdead(owner) && !death_triggered)
it's tidiness to include spaces after if statements, I.E. ```else if (```

2022-02-17 00:58 UTC, NightmareChamillian commented on code/datums/abilities/vampire.dm
> +		if(owner.health < 0 && !crit_triggered)
likewise here, and the if check above it

2022-02-17 00:58 UTC, NightmareChamillian commented on code/datums/abilities/vampire/thrall_abilities.dm
> +		if(dist == 0)
again, just tidiness.

2022-03-10 17:46 UTC, Sovexe commented
https://hackmd.io/@goonstation/code#Spaces-after-control-statements

2022-03-10 22:40 UTC, TerraGS commented
> https://hackmd.io/@goonstation/code#Spaces-after-control-statements
> 
> Half of this pr is just polluting git history

This is becoming frustrating. Could you be exact about what I can do to remedy the situation?

2022-03-10 23:33 UTC, Sovexe commented
The changes if `if(` to `if (` is heavily frowned upon as mentioned in the linked code guidelines

2022-03-10 23:34 UTC, Sovexe commented on code/datums/abilities/vampire.dm
> +		else if (isdead(owner) && !death_triggered)
instead of checking if they are dead every life tick it would be probably be better to make use of `COMSIG_MOB_DEATH`

2022-03-10 23:41 UTC, Sovexe commented on code/datums/abilities/vampire.dm
> +		if (owner.health < 0 && !crit_triggered)
we sadly don't have a mob crit signal...at least not yet. 

Instead of checking health on life tick look into `/mob/proc/updatehealth()`

2022-03-10 23:43 UTC, Sovexe commented on code/datums/abilities/vampire/enthrall.dm
> +		for (var/mob/thrall in H.thralls)
since thralls is just a list of mobs there's no need for an implicit type check. Make us of `as anything` here

2022-03-10 23:45 UTC, Sovexe commented on code/datums/abilities/vampire/thrall_abilities.dm
> +		var/hudarrow_scale = 0.6 + 0.4 / (1 + 3 ** (3 - dist / 10))
These are both pretty magic numbery, could at least use a comment

2022-03-10 23:46 UTC, Sovexe requested changes
additional review

2022-04-04 00:55 UTC, closed without merging