Adds glue to the game
goonstation/goonstation pull request #7527
Opened 2022-02-17 22:10 UTC by colossusqw

[LABEL][sprites][feature][add to wiki]

## About the PR 
This PR adds space glue, glue will make you high if you injest it, will apply to tiles to prevent slipping and slow anyone who passes down. Made to be a funny sort of opposite space lube.

## Why's this needed? 
So the assistants can finally snort glue in maint and the clown has yet another weapon to instill horror in the station. :)

## Changelog

```changelog
(u)Hans
(*)Added space glue to the game.
```

2022-02-17 22:11 UTC, colossusqw commented
![image](https://user-images.githubusercontent.com/52242687/154579434-5a5bdf79-ecbf-4e9b-b691-acc7d9973df0.png)
the lube sprite on tiles

2022-02-17 23:50 UTC, ZeWaka commented on code/modules/chemistry/Reagents-Misc.dm
> +		//glue
Delete

2022-02-17 23:50 UTC, ZeWaka commented on code/mob/living/carbon.dm
> +			if(src.getStatusDuration("slowed")< 30 SECONDS)
Be consistent with spacing

2022-02-17 23:51 UTC, ZeWaka commented on code/modules/chemistry/Reagents-Misc.dm
> +					T.UpdateOverlays(wet, "wet_overlay")
is it really the wet overlay

2022-02-17 23:51 UTC, ZeWaka commented on code/modules/chemistry/Reagents-Misc.dm
> +					T.wet = 0
why does glue instantly dry water

2022-02-18 00:14 UTC, colossusqw commented on code/modules/chemistry/Reagents-Misc.dm
> +					if(L.getStatusDuration("slowed")<100)
100 is 10 seconds, i should make it 10 * SECONDS

2022-02-18 15:50 UTC, TobleroneSwordfish commented
more glue PRs, yes.

2022-02-19 19:28 UTC, Tarmunora requested changes

2022-02-19 19:28 UTC, Tarmunora commented on code/modules/chemistry/Chemistry-Recipes.dm
> +			result = "glue"
does not match reagent

2022-02-19 19:28 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Misc.dm
> +			pierces_outerwear = 1
```suggestion
```

2022-02-19 19:28 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Misc.dm
> +					if(L.getStatusDuration("slowed")< 10 SECONDS)
```suggestion
					else
```

2022-02-19 19:28 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Misc.dm
> +						L.setStatus("staggered", max(M.getStatusDuration("staggered"), 3*volume_passed))
add time units

2022-02-19 19:28 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Misc.dm
> +							L.changeStatus("slowed", 4*volume_passed, optional = 4)
add time unit

2022-02-19 19:28 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Misc.dm
> +							L.changeStatus("slowed", 10 SECONDS, optional = 4)
why not just clamp?

2022-02-19 19:28 UTC, Tarmunora commented on code/mob/living/carbon.dm
> +				src.changeStatus("slowed", 2 SECONDS)
```suggestion
				src.changeStatus("slowed", 2 SECONDS, optional = 2)
```

2022-02-21 22:01 UTC, Tarmunora requested changes

2022-02-21 22:01 UTC, Tarmunora commented on code/modules/chemistry/Reagents-Misc.dm
> +					SPAWN(80 SECONDS)
scale with volume

2022-03-01 23:14 UTC, Conchuckter commented
sniffing it should give you brain damage

2022-03-05 23:06 UTC, Tarmunora approved these changes

2022-03-05 23:07 UTC, merged