Resprites the SMG magazine
goonstation/goonstation pull request #7631
Opened 2022-02-26 17:49 UTC by NightmareChamillian

## About the PR 
this, as the title says, adds a new sprite for the smg magazine. Also I moved the inert meowitzer to be below the non inert meowitzer, and made the descriptions closer to one another

![image](https://user-images.githubusercontent.com/96703882/155853698-ab4d1b15-2c66-423c-aa6e-e3d7316861c5.png)

## Why's this needed? 

It should have a differentiable sprite from the pistol magazine one.

## Changelog

```changelog
(u)NightmareChamillian
(+)Resprites the SMG magazine
```

2022-03-03 00:08 UTC, frawhst requested changes
I don't think you set the SMG mag to use the new icon?

2022-03-03 22:07 UTC, NightmareChamillian commented
@frawhst 
either I actually forgot to do that in the commit and added it later, or you were looking in the wrong area, since it does use the sprites

![image](https://user-images.githubusercontent.com/96703882/156660748-e78ac7ed-99c6-4eed-b406-bfce804e32fb.png)

2022-03-05 01:52 UTC, frawhst approved these changes

2022-03-05 23:03 UTC, Tarmunora commented on code/obj/item/implant.dm
> +		icon_state = "blowdart"
tbh this one... probably just shouldn't implant at all lol

2022-03-05 23:03 UTC, merged