Brullbar
goonstation/goonstation pull request #7696
Opened 2022-03-06 02:38 UTC by Eagletanker

## About the PR 

Renames Wendigo's to be Brullbars

## Why's this needed? 

Wendigos are part of First Nations mythology and they dont like people apporpiating it. This PR replaces that with the name Brullbar, which means Howler Bear. No changelog needed. Help is needed though with fixing the type paths for the generators because randomly just they dont work but all the other paths do

## Changelog

2022-03-06 02:46 UTC, Eagletanker commented
Trying to get help for the type paths. Dont know why they are broken just in those 10 instances

2022-03-06 08:28 UTC, Eagletanker commented
cool its still breaking *scream

2022-03-06 08:49 UTC, coolbugcoder commented
While I'm fine with changing the name, why Brullbar? I can't find any type of monster named that, and a pale white skinny being doesn't really give the image of a bear to me. I think another name that more reflects its design would be much better.

2022-03-06 09:05 UTC, coolbugcoder commented
well, on hindsight, I think the name is decent at keeping the mythical sounding nature of wendigo and also reflects the howling nature, even if I don't think the "bear" part fits super well. Along with that, I can't find a good alternative myself admittedly. I thought Ghoul would work but that's apparently originally part of Arabian folklore and originally was mainly hanging around cemeteries, so that would probs have the same issue as Wendigo. Brullbar is okay even if I think an also mythical or threatening sounding name without the bear part would be better.

2022-03-06 09:13 UTC, Eagletanker commented
> While I'm fine with changing the name, why Brullbar? I can't find any type of monster named that, and a pale white skinny being doesn't really give the image of a bear to me. I think another name that more reflects its design would be much better.

Chosen from a list of names. It's purposefully it's own thing as researchers on [REDACTED] found them and screaming bear thing is probably what was gleamed from the few survivors of such attacks. We also have the non bear like space bear

2022-03-06 09:32 UTC, coolbugcoder commented
> > While I'm fine with changing the name, why Brullbar? I can't find any type of monster named that, and a pale white skinny being doesn't really give the image of a bear to me. I think another name that more reflects its design would be much better.
> 
> Chosen from a list of names. It's purposefully it's own thing as researchers on [REDACTED] found them and screaming bear thing is probably what was gleamed from the few survivors of such attacks. We also have the non bear like space bear

yeah, it's cool then.

2022-03-06 14:06 UTC, TTerc reviewed
![0](https://user-images.githubusercontent.com/62990808/156926699-ccdd9502-b9a0-4216-93df-0cac3fa535fd.png)

I assume icon state names in DMIs need an update too

2022-03-06 16:10 UTC, NightmareChamillian commented
This is massively needed change, but I do think the word "brullbar" is a little hard to take seriously, especially with how pants shittingly terrifying they are. If you're going with early European words, I suggest the "werr" or "wiff" roots to better reflect the fact that it's a fucked up angry pale guy who yells and then disembowel you. 

Regardless, this is a much needed step up from using wendigo.

2022-03-06 17:41 UTC, Eagletanker commented
> ![0](https://user-images.githubusercontent.com/62990808/156926699-ccdd9502-b9a0-4216-93df-0cac3fa535fd.png)
> 
> I assume icon state names in DMIs need an update too

Will do

2022-03-07 04:14 UTC, coolstation commented
nice, adopting this.

2022-03-07 06:05 UTC, Eagletanker commented
> ![0](https://user-images.githubusercontent.com/62990808/156926699-ccdd9502-b9a0-4216-93df-0cac3fa535fd.png)
> 
> I assume icon state names in DMIs need an update too
Done

2022-03-07 21:51 UTC, Kyle2143 commented
Is this complete? The name choice is fine,

2022-03-09 01:23 UTC, Eagletanker commented
> Is this complete now? The name choice is fine, it's not particularly terrifying, but then most names aren't and I don't think that's important.
> 
> So I'm fine to merge it on that score, but based on the comments and commits here it looked like there were some issues and it hadn't been compiled and tested locally.

Yep, let me clear the merge conflict and then do a last test compile and it should be good to go 
(hopefully :shelterfrog:)

2022-03-09 21:52 UTC, pali6 requested changes

2022-03-09 21:52 UTC, pali6 commented on code/datums/mapgen/IceMoonGenerator.dm
> +	fauna_types = list(/obj/critter/sealpup=15, /obj/critter/brullbar, p=5, /obj/critter/yeti=1)
This seems incorrect!

2022-03-10 07:47 UTC, zjdtmkhzt commented
I can't say I find this very intimidating, considering 95% of search results for Brüllbär are for the children's book series with a cute small bear making friends at kindergarten or whatever, but I already didn't find Wendigos very intimidating.
I mean, they are obj critters, you just kinda hit them until they die.

2022-03-18 00:42 UTC, Eagletanker commented
*scream I'll fix the conflict when I get home

2022-03-19 23:10 UTC, ZeWaka commented
!merge_upstream

2022-03-20 21:17 UTC, merged