makes radio channels more visible on dark mode
goonstation/goonstation pull request #7743
Opened 2022-03-09 04:13 UTC by nefarious6th

## About the PR 
makes the radio station and medical channels have better visibility on dark mode

## Why's this needed? 
easier to see. honestly don't know why i didn't just make the med channel cyan in the first place.

2022-03-09 05:46 UTC, flrsh commented
Could you include a screenshot? Thanks!

2022-03-09 10:48 UTC, nefarious6th commented
> Could you include a screenshot? Thanks!

added to original PR body

2022-03-09 13:20 UTC, TobleroneSwordfish commented
![image](https://user-images.githubusercontent.com/20713227/157449516-d224f687-313b-4d33-8248-ca4b6bee987a.png)
Very similar to this public intercom colour on cog 1

2022-03-09 22:01 UTC, pgmzeta commented on browserassets/css/browserOutput.css
> +body.theme-dark .rmedical {color: ##51DBCB;}
double hash->single hash

2022-03-09 22:01 UTC, pgmzeta commented on browserassets/css/browserOutput.css
> +body.theme-dark .rother {color: ##E896E5;}
double hash -> single hash here

2022-03-09 22:04 UTC, pgmzeta commented
Any chance you can include a pass at the syndicate radio channel while you're taking a look at these?

2022-03-09 23:05 UTC, nefarious6th commented
> Any chance you can include a pass at the syndicate radio channel while you're taking a look at these?

ty ty for reviewing. i can give syndie radio a look and then update with that and a better medical color

2022-03-12 08:17 UTC, ZeWaka requested changes
^

2022-03-21 19:43 UTC, nefarious6th commented
i will get back to this, sorry for the delay

2022-04-05 01:30 UTC, ZeWaka commented
not necessary can be done later this is good now

2022-04-05 01:30 UTC, merged