Seamwindows
goonstation/goonstation pull request #7928
Opened 2022-03-23 18:43 UTC by Laboredih123

## About the PR 
Makes windows seamless.

## Why's this needed? 
It looks cool. People liked it.

## Changelog

```changelog
(u)Laboredih123
(*)Nanotrasen has now made windows fully connected, removing seams.
```

2022-03-23 19:01 UTC, ZeWaka commented
This incorrectly affects standalone windows.

2022-03-23 19:02 UTC, ZeWaka commented
Also definitely not a major changelog.

2022-03-23 20:03 UTC, Laboredih123 commented
After some testing, It doesn't seem to affect standalones for me.
![image](https://user-images.githubusercontent.com/62359847/159786037-2c138c32-4367-4e05-8e00-4ae7c74d4a77.png)

2022-03-23 20:05 UTC, Laboredih123 commented
If you mean the single windows between walls, that is how the windows work.
![image](https://user-images.githubusercontent.com/62359847/159786324-0ed71a22-2f0a-4329-b022-7c3904301aed.png)

2022-03-23 20:25 UTC, Eagletanker commented
> If you mean the single windows between walls, that is how the windows work.
> ![image](https://user-images.githubusercontent.com/62359847/159786324-0ed71a22-2f0a-4329-b022-7c3904301aed.png)

The right window looks wronh

2022-03-23 20:32 UTC, Laboredih123 commented
I can assure you they are the same.

2022-03-23 20:32 UTC, Laboredih123 commented
![image](https://user-images.githubusercontent.com/62359847/159790394-993c7ab2-ba55-458f-9b66-b5d749060579.png)

2022-03-23 20:33 UTC, Laboredih123 commented
Although I notice a little seam.

2022-03-25 05:27 UTC, Laboredih123 commented
Should it be made that walls smooth with windows?

2022-03-25 19:23 UTC, ZeWaka commented
> Should it be made that walls smooth with windows?

it either needs to smooth with the windows or the windows need to not smooth with the walls

2022-03-25 20:00 UTC, Laboredih123 commented
I find it nicer to smooth with the windows

2022-03-25 20:00 UTC, Laboredih123 commented
I'll ask.

2022-03-25 20:30 UTC, Laboredih123 commented
So it turns out windows are unable to connect to walls without smoothing.

2022-03-25 20:33 UTC, Laboredih123 commented
![image](https://user-images.githubusercontent.com/62359847/160196938-21e7d1a8-43be-4b47-b7ef-b64a218b1fac.png)
This looks quite nice, other than the fact it looks like the walls have a depression on top.

2022-03-25 20:40 UTC, pali6 commented
I prefer having the connector overlay on walls.

2022-03-25 21:23 UTC, Laboredih123 commented
People prefer the overlay over the without.

2022-03-27 00:23 UTC, ZeWaka commented
Q: Why aren't we just applying the icon smoothing we use for walls, with the 40 states or whatever? Then we don't get window holes in 2x2 window cubes.

2022-03-27 02:32 UTC, pgmzeta commented
> Q: Why aren't we just applying the icon smoothing we use for walls, with the 40 states or whatever? Then we don't get window holes in 2x2 window cubes.

Do we have a tool to generate the sprites for this? right now it's using icon_states in a dmi for each cardinal x ordinal combination:
![image](https://user-images.githubusercontent.com/91498627/160264126-6bd50c83-443c-4e50-be52-57ba2f6d0d7a.png)

If we have sprites for those, it's a *very* small lift to make sure we can use them with the refactoring changes in flight.

2022-03-27 03:49 UTC, Laboredih123 commented
I believe this would be a good addition to the pr. What do ya'll think? https://github.com/Laboredih123/goonstation/pull/1

2022-03-27 18:34 UTC, ZeWaka commented
> > Q: Why aren't we just applying the icon smoothing we use for walls, with the 40 states or whatever? Then we don't get window holes in 2x2 window cubes.
> 
> Do we have a tool to generate the sprites for this?

Yes. https://github.com/tgstation/icon-cutter

2022-03-31 00:26 UTC, ZeWaka requested changes

2022-03-31 00:26 UTC, ZeWaka commented on code/obj/table.dm
> +		if(16 & connections) // NE
no, use the direction names.

2022-03-31 23:07 UTC, merged