Allows frogs to croak
goonstation/goonstation pull request #8022
Opened 2022-03-29 22:41 UTC by Bartimeus973

## About the PR 
Allows froak to croak with a tiny (1/1000) chance for a shelterfrog croak instead.

## Why's this needed? 
Cats meow, dogs bark, roaches chitter, birds caw but frogs cant croak. This fixes that and comes along with a small chance for a shelterfrog screech for fun!

2022-03-30 03:22 UTC, ZeWaka requested changes

2022-03-30 03:22 UTC, ZeWaka commented on code/mob/living/critter/small_animal.dm
> +					if(rand(1,1000) == 1000)
You want prob()

2022-03-30 16:55 UTC, AmazingDragon353 commented
Petition to rename gasp and deathgasp to croak and deathcroak for frogs

2022-04-21 19:04 UTC, TTerc approved these changes

2022-04-21 19:05 UTC, merged