Adds Chicken Tenders
goonstation/goonstation pull request #8194
Opened 2022-04-14 04:32 UTC by Windos-7

## About the PR 
You can now cut chicken nuggets into 3 strips, which you can then process into chicken tenders. Tendies have randomized names. You can even dip chicken tendies in bowls like tortillas!
Demonstration video
https://files.catbox.moe/9hnhrv.mp4

## Why's this needed? 
tendies

## Changelog

```changelog
(u)Fwll
(*)Added dippable chicken tenders
```

2022-04-14 04:36 UTC, Eagletanker commented
Uhhh
Nuggets are smaller than tenders, so it should be chicken tenders to nuggets 
Small nitpick

2022-04-14 10:10 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/ingredients.dm
> +				makeslices -= 1
```suggestion
			for (var/i in 1 to 3)
				new /obj/item/reagent_containers/food/snacks/ingredient/meat/chickenstrip(T)
```

2022-04-14 16:37 UTC, NightmareChamillian commented
can't wait to spend the entire round doing packet wizardry in tech storage whilst munching on tendies

2022-04-16 23:56 UTC, Kyle2143 commented
Remove the references to the tendie meme.

2022-04-17 00:36 UTC, Kyle2143 requested changes
above

2022-05-20 01:05 UTC, closed without merging