Adds A Unique Objective For Arcfiends
goonstation/goonstation pull request #8550
Opened 2022-05-11 04:10 UTC by Wisemonster

[FEATURE]

## About the PR 
This pr adds an objective for arcfiends to go for, involving draining a total of a certain amount of power.

## Why's this needed? 
Currently, arcfiends do not have any unique objectives. This fixes that by giving them objectives that fit them.

## Changelog

```changelog
(u)Wisemonster
(*)Add a new objective for Arcfiends!
```

2022-05-11 04:12 UTC, Wisemonster commented
Wasn't sure how high I should set the arcfiend objective goals. Let me know if it's too high/low.

2022-05-13 01:09 UTC, Tarmunora commented
@Sovexe

2022-05-13 01:47 UTC, Sovexe requested changes

2022-05-13 01:47 UTC, Sovexe commented on code/modules/antagonists/arcfiend/arcfiend.dm
> +
should be two procs, but at that point it also has no point vs just checking vars
```suggestion
```

2022-05-13 01:47 UTC, Sovexe commented on code/modules/antagonists/arcfiend/arcfiend.dm
> +		return 0
don't want to add more procs to mob
```suggestion
```

2022-05-13 01:47 UTC, Sovexe commented on code/datums/objective.dm
> +			return 0
```suggestion
	check_completion()
		var/datum/abilityHolder/arcfiend/AH = owner.current?.get_ability_holder(/datum/abilityHolder/arcfiend)
		return (AH?.lifetime_energy >= powercount)
```

2022-05-13 01:47 UTC, Sovexe commented on code/datums/objective.dm
> +	var/powercount
should probably called like power goal or something, since its a target not your count

2022-05-13 17:22 UTC, Sovexe commented
Power goals need to be higher, while 2500 is the cap it's not all that hard to reach 

Also could use additional goal variety if you're up for it. One idea would be to have a certain station area drained of power

2022-05-13 17:32 UTC, Wisemonster commented
I'll look into adding in an area power denial objective, although I'm not sure how to make it atm so that it requires more effort than simply removing an areas cell from the apc.

2022-05-13 20:10 UTC, Wisemonster commented
I might try to add the apc goal in a separate pr, cause I'm having trouble getting it to work.

2022-05-14 19:33 UTC, merged