Prevent force equipping items on missing limbs
goonstation/goonstation pull request #8602
Opened 2022-05-15 11:12 UTC by flappybatpal

[BUG]

## About the PR 
Updates can_equip to fail if the appropriate limbs are missing.

## Why's this needed? 
Resulted in lost objects.
It made no sense you could put shoes and gloves on someone with no arms or legs.
Possibly fixes some weirdness with item arms.

Tested:
Spawning in as a fully equipped role (Nuclear Commander)
Round start as regular job (Captain).
Fully equipping all slots on a naked tdummy.
Attempting to equip tdummy with no limbs/head.
Self equipping/removing all slots.
Cluwning via admin and wizard spell.
Admin macho man, flock goblin, slasher conversion.
Call wizards verb.
Admin giving item arm, regular arm.

This will does in some items failing to spawn if the target does not have the limbs and the method of conversion does not fully heal them first. For example, Call Wizards will not create the sandals with no legs or a staff with no arms.

2022-05-15 11:31 UTC, amylizzle commented
Is this for #7896 ?

2022-05-15 12:51 UTC, flappybatpal commented
No, I made this in response to messing around putting items on humans and noticing it bugged with no limbs.

2022-05-15 17:55 UTC, flappybatpal commented
Now it does. Also took me like three hours to work out...

2022-05-17 18:09 UTC, amylizzle requested changes

2022-05-17 18:09 UTC, amylizzle commented on code/mob/living/carbon/human.dm
> +					return 0
Github won't let me add suggestions, but is good to replace `return 0/1` with `return FALSE/TRUE` where appropriate. Update old code and all that.

2022-05-19 10:05 UTC, flappybatpal commented on code/mob/living/carbon/human.dm
> +				if (!istype(src.limbs.l_arm, /obj/item/parts/human_parts/arm) && !istype(src.limbs.l_arm, /obj/item/parts/robot_parts/arm))
I feel that this is out of scope.

2022-05-20 23:07 UTC, Tarmunora approved these changes

2022-05-21 02:12 UTC, ZeWaka commented on code/mob/living/carbon/human.dm
> +				if (!istype(src.limbs.l_arm, /obj/item/parts/human_parts/arm) && !istype(src.limbs.l_arm, /obj/item/parts/robot_parts/arm))
yeah, one day....

2022-05-21 02:13 UTC, ZeWaka approved these changes

2022-05-21 07:10 UTC, merged