Adding a PDA module for medics to get the attention of nearby people
goonstation/goonstation pull request #8612
Opened 2022-05-16 20:15 UTC by Kaan-NN

[QOL]

## About the PR 
I added a new pda module for the MD and everyone with the medical PDA.
This inherits from flashlight and therefore retains the default flashlight settings.
It works in similar fashion as the segway, but should be both auditory and visually distinct from it.
It plays the [https://github.com/goonstation/goonstation/blob/master/sound/effects/manta_alarm.ogg](url), as it currently is not used for commonly encountered stuff, and creates a slightly larger light then the segway.
It adds an ability button to the hud that triggers the effect with a 90 second cooldown (this can and should be changed if players decide to spam it to be annoying)

https://user-images.githubusercontent.com/68946148/168671158-16ae78ae-e0c7-4b5c-a040-42266a25a834.mp4

https://user-images.githubusercontent.com/68946148/168671165-84ce905e-4101-4110-94bb-8cddfcf21893.mp4

<img width="223" alt="UI_preview" src="https://user-images.githubusercontent.com/68946148/168671192-26c55b38-b44d-42e6-9fdd-4fb3e891eaf0.png">
<img width="164" alt="icon_preview" src="https://user-images.githubusercontent.com/68946148/168671193-adff6650-fa42-40e3-940c-90f051b5e0b1.png">

## Why's this needed? 
People that are heavily injured are only focused on getting to medbay no matter what, frequently ignoring any medical personnel that tries to help them, making it an overall annoying experience for both people involved. Since it works similar to the segway it could also make for a paramedic gimmick of running in clearing halls to make room for someone being dragged to medbay or doctors running through a crowded area towards the patient and could therefore be useful for RP.

## Changelog

```changelog
(u)Kaan
(+)Medical personnel now starts with a PDA module that sounds a siren to announce their presence.
```

2022-05-16 21:09 UTC, Kaan-NN commented
> 

![image](https://user-images.githubusercontent.com/68946148/168682883-5e61e42b-e40e-41c1-9927-52a793293aaf.png)
updated the icon to be a bit smaller

2022-05-16 23:32 UTC, ZeWaka commented
Definitely too loud

2022-05-16 23:33 UTC, Sbmhawk commented
And too bright imo

2022-05-17 11:13 UTC, Kaan-NN commented
I adjusted sound and brightness I hope the audio is fine this time I used the doors and owls as a reference since OBS does some weird audio stuff I havent figured out yet

https://user-images.githubusercontent.com/68946148/168797892-2bc63e79-9318-4d7d-9c0e-2546082a178d.mp4

2022-05-17 12:37 UTC, TobleroneSwordfish requested changes
Overall I like the idea, one of the most frustrating things about playing medic

2022-05-17 12:37 UTC, TobleroneSwordfish commented on _std/__build.dm
> -//#define IM_REALLY_IN_A_FUCKING_HURRY_HERE 1  // Skip setup for atmos, Z5, don't show changelogs, skip pregame lobby
Don't commit __build.dm

2022-05-17 12:37 UTC, TobleroneSwordfish commented on _std/compatibility.dme
> +#define FILE_DIR .
don't think this is meant to be committed either

2022-05-17 12:37 UTC, TobleroneSwordfish commented on code/obj/item/device/pda2/modules.dm
> +	var/datum/light/MedicLight
Consider changing this to a simple light, as robust lights look very laggy when attached to a moving object (and the player is always going to be moving if they're pressing this)

2022-05-18 18:28 UTC, Kaan-NN commented
Now using simple light with colors that should be decently visible
https://user-images.githubusercontent.com/68946148/169117460-940c86e0-f8ad-4a42-aaf3-6007d97ac1da.mp4

2022-05-19 02:06 UTC, Tarmunora commented on code/obj/item/device/pda2/modules.dm
> +		ColorChangeCycles = 6
Why is this initialized here and not when defined

2022-05-19 02:08 UTC, Tarmunora commented on code/obj/item/device/pda2/modules.dm
> +				Messages = list("Boss, thats a serious injury. It won´t heal on its own. You´ll need to treat it with first aid.", "Ready to heal! Dummkopfs", "Stop running you half dead moron [usr] will heal yo
give this another pass for punctuation and spelling

2022-05-19 02:43 UTC, Conchuckter commented
One thing that would make this better is if this sent a PDA notification to the medical department like the security alert module.

2022-05-19 17:33 UTC, flrsh commented
I agree with the motivation behind this PR, but I'm not sure this effect would actually compel people to, like, stop running away when you're trying to heal them or whatever. If anything, if I were a new player, I might want to run away from "person with bright flashing light and sound effect" even more.

2022-05-20 08:09 UTC, Kaan-NN commented
> I agree with the motivation behind this PR, but I'm not sure this effect would actually compel people to, like, stop running away when you're trying to heal them or whatever. If anything, if I were a new player, I might want to run away from "person with bright flashing light and sound effect" even more.

As someone on the forum stated people should get used to it over time. Especially during the honeymoon phase where doctors will likely spam it without end people will primarily see it used by medical staff and since it is imo distinct enough from other types of sirens currently used in game people should come to associate them them doctors quite quickly.

There was also someone that suggested to make an AI hologram styled cross appear over the medic but I tend overlook these so I disregarded that for now. If that is actually preferred Id be up to change that.

2022-05-22 21:30 UTC, mordent-goonstation commented
Not personally a fan, this seems comically obnoxious. If someone is able to evade you to the point of you needing to turn this on to get their attention rather than being able to hear you say "I'm a doctor!" then they aren't hurt badly enough for it to matter. If they aren't able to evade you, you can say the thing and if they don't want to be treated then they'll still crawl away.

I don't think this will actually solve the problem it is trying to solve.

2022-05-23 00:56 UTC, Tarmunora commented
All things considered I don't see this going in. Unless another dev has strong feelings one way or another, closing.

2022-05-23 00:56 UTC, closed without merging

2022-05-23 11:24 UTC, Kaan-NN commented
> All things considered I don't see this going in. Unless another dev has strong feelings one way or another, closing.

Since this was my first PR could you provide me with some information on why you dislike the idea, so that I can eventually rework the entire idea or at least know what to improve on for future PRs?

2022-05-24 01:08 UTC, Tarmunora commented
🤷 didn't vibe.

Also see mordent's response, because he sums it up pretty well