Makes the Revhead antag popup more descriptive.
goonstation/goonstation pull request #8705
Opened 2022-05-23 13:07 UTC by Josephin23

[QOL]
## About the PR 
Updates the Revhead antag popup, adding in a third point explaining that you can't leave the Z-Level. Also changes the part regarding the revolutionary flash.
![obraz](https://user-images.githubusercontent.com/93096874/169871936-f02ca74d-47ea-4f44-a491-af4bee2f995c.png)

## Why's this needed? 
It's pretty dumb that a really important condition that literally can severely handicap the rev team is completely unsaid in-game. This obviously causes a ton of confusion in first time Revheads. sometimes leading to round that end in 10 or less minutes because all of them leave the station.

2022-05-23 13:11 UTC, Josephin23 commented on browserassets/html/traitorTips/revTips.html
> +	</body>
![obraz](https://user-images.githubusercontent.com/93096874/169826968-33cce5df-0a08-4f1c-9a07-5fa2045f47e8.png)
what.

2022-05-23 16:03 UTC, frawhst requested changes
While we're here could you change "your revolutionary flash" to "any flash" (or similar phrasing)? sucks that the fact that you can use regular flashes to convert is weird arcane knowledge sometimes

otherwise lgtm

2022-05-24 04:57 UTC, Wisemonster commented
Maybe clarify that if no revheads are on station z-level, they'll lose. This seems to imply you'll be killed the moment you leave the z-level.

2022-05-25 00:45 UTC, frawhst approved these changes

2022-05-26 00:34 UTC, merged

2022-05-26 14:14 UTC, Josephin23 commented
well i wasn't done with that one yet
oh well, if i see it becoming too confusing i'll just add it