makes skeleton heads get the typing indicator instead of their body
goonstation/goonstation pull request #8964
Opened 2022-06-05 01:03 UTC by Skeletonman0

## About the PR 
This PR aims to make it so decapitated heads from skeletons get the typing indicator instead of their body.

## Why's this needed? 
the head talks, not the body. why does the body get the typing indicator?

talking skeleton head go brrrrrrr

![image](https://user-images.githubusercontent.com/64938519/172030516-0297fc98-fbf8-44b2-a1f5-d0b85964faab.png)

2022-06-05 04:15 UTC, Kapu1178 commented
The method of doing this is _really snowflakey_. You should use a signal to control this, by sending a signal and looking for a specific response, and if that response is gotten, you assume it was already handled.

2022-07-20 19:08 UTC, Tarmunora requested changes

2022-07-20 19:08 UTC, Tarmunora commented on code/obj/item/organs/head.dm
> +			src.UnregisterSignal(src.linked_human, "speech_bubble", .proc/speech_bubble)
```suggestion
			src.UnregisterSignal(src.linked_human, COMSIG_CREATE_TYPING)
			src.UnregisterSignal(src.linked_human, COMSIG_REMOVE_TYPING)
			src.UnregisterSignal(src.linked_human, COMSIG_SPEECH_BUBBLE)
```

2022-07-20 19:08 UTC, Tarmunora commented on code/obj/item/organs/head.dm
> +			src.RegisterSignal(src.linked_human, "speech_bubble", .proc/speech_bubble)
```suggestion
		if (src.linked_human)
			src.RegisterSignal(src.linked_human, COMSIG_CREATE_TYPING, .proc/create_typing_indicator)
			src.RegisterSignal(src.linked_human, COMSIG_REMOVE_TYPING, .proc/remove_typing_indicator)
			src.RegisterSignal(src.linked_human, COMSIG_SPEECH_BUBBLE, .proc/speech_bubble)
```

2022-07-20 21:01 UTC, flrsh commented on code/datums/mutantraces.dm
> +			src.head_tracker.UnregisterSignal(src.head_tracker.linked_human, "speech_bubble", /obj/item/organ/head.proc/speech_bubble)
Oh right, thanks!

2022-08-03 05:25 UTC, ZeWaka approved these changes

2022-08-04 01:20 UTC, merged