resprites incubators, microscopes
goonstation/goonstation pull request #9290
Opened 2022-06-22 11:41 UTC by nefarious6th

## About the PR 
resprites incubators and microscopes found in patho

## Why's this needed?
at the very least, incubators reused the reagent heater sprite, so hopefully no one walks into patho, sees the incubator, and thinks they can heat or cool reagents in it.
things matching art direction.

2022-06-22 11:42 UTC, nefarious6th commented
in advance, i can get the code to compile but am having trouble running the build of the .dmb, so if anyone can review what i did with the update_icon() for the on/off state, would be appreciated

2022-06-23 05:40 UTC, ZeWaka requested changes

2022-06-23 05:40 UTC, ZeWaka commented on code/modules/medical/pathology/pathogen_machines.dm
> +		icon_state = "incubator_on"
won't work

2022-07-08 22:46 UTC, XyzzyThePretender commented
If you still want to work on this PR, I'd recommend against modernizing the incubator sprite. I don't see a future for the pathogen nutrition system it was made for.

2022-07-08 22:50 UTC, ThatFiveGuys commented
Nothing prevents these sprites from being reused for something else

2022-07-18 05:31 UTC, flrsh commented on code/modules/medical/pathology/pathogen_machines.dm
> +		icon_state = "incubator_on"
```suggestion
		if (src.target)
				icon_state = "incubator_on"
		else 
				icon_state = "incubator"
```
Should be this.

2022-07-18 05:35 UTC, flrsh commented on code/modules/medical/pathology/pathogen_machines.dm
> +		icon_state = "incubator_on"
Oh lol I accidentally messed up the indents.

2022-07-18 05:35 UTC, flrsh commented on code/modules/medical/pathology/pathogen_machines.dm
> +				icon_state = "incubator"
```suggestion
			icon_state = "incubator_on"
		else 
			icon_state = "incubator"
```

2022-07-18 05:45 UTC, merged