Adds a tea plant and matcha!
goonstation/goonstation pull request #9356
Opened 2022-06-26 13:11 UTC by avimour

## About the PR 
Adds in a new botany plant, tea! You can grow tea and use it's leaves to create matcha, either by processing it in a processor or distilling it with a still. Matcha can then be used to create matcha tea, which is known to reduce cholesterol in someone's body.
The plant itself contains tea for some interesting botany splices!

![image](https://user-images.githubusercontent.com/92401911/175768805-36719cdb-9ad2-4c41-8325-fb82e0813565.png)
![image](https://user-images.githubusercontent.com/92401911/175769297-9db75f8f-b6fa-408c-95e1-31923d77f33f.png)

I do have a plan for more things for both matcha and the tea plant itself, however I'll add that in another PR since I don't want this one to get too big.

## Why's this needed? 
More variety is nice! Matcha tea can be used to purge cholesterol from someone which can be nice for a bartender to make for when the chef starts making unhealthy foods. Plus gives the chef an option for tasty green icing! With the tea plant containing tea you can also get some interesting splices in botany now, such as a half and half berry!

## Changelog

```changelog
(u)avimour
(*)Added a new botany plant: Tea. Which can be used to create matcha!
(+)Combine matcha and tea to get...matcha tea!
```

2022-06-26 13:21 UTC, TobleroneSwordfish requested changes
I'm amazed we don't already have a tea plant, this looks great

2022-06-26 13:21 UTC, TobleroneSwordfish commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +				return
```suggestion
```

2022-06-26 13:21 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/condiments.dm
> +	desc = "A powder created from dried tea leaves that could help with."
Could help with?

2022-06-26 13:21 UTC, TobleroneSwordfish commented on code/modules/hydroponics/plants_herb.dm
> +	isgrass = 1
```suggestion
	isgrass = TRUE
```

2022-06-26 13:21 UTC, TobleroneSwordfish commented on code/obj/item/plants.dm
> +	crop_suffix	= " leaves"
```suggestion
	crop_suffix = " leaves"
```

2022-06-26 13:21 UTC, TobleroneSwordfish commented on code/obj/item/plants.dm
> +	brewable = 1
```suggestion
	brewable = TRUE
```

2022-06-26 13:30 UTC, avimour commented on code/modules/food_and_drink/condiments.dm
> +	desc = "A powder created from dried tea leaves that could help with."
AAA i forgot to finish the sentence oTL

2022-06-29 11:10 UTC, WALPVRGIS approved these changes
Very cute, glad to see these made! Lovely artwork. :)

2022-06-30 14:10 UTC, Tarmunora commented
Does nobody else think it's a little weird that you brew/process the tea leaves into matcha, which then has to be mixed with tea *extracted* from tea leaves in order to make matcha tea? Because I find that process a little weird

2022-06-30 14:25 UTC, WALPVRGIS commented
I don't think it's too weird as a concept for the game, though as an analogue to irl matcha recipes is a bit odd upon some thought sdgjhf. Maybe just matcha and water would make more sense? My approval is based on sprites btw, leaving the chem stuff to you tarm aha. 👍

2022-07-02 12:05 UTC, avimour commented
!merge_upstream

2022-07-04 17:02 UTC, Tarmunora commented
🤷 I still think the way it's arranged is a *little* weird, but not a dealbreaker or anything

2022-07-04 17:02 UTC, merged