Adds a New Food: Ratatouille
goonstation/goonstation pull request #9375
Opened 2022-06-28 17:23 UTC by t-toasted

## About the PR 
As said in the title: adds in ratatouille to the game. This recipe can be made with cucumber, eggplant, tomato, and garlic put into an oven. Provides warm and energized benefits. Hopefully balanced appropriately against other recipes. Make some real ratatouille today. 

## Why's this needed? 
I love eating and making ratatouille in real life, so I decided to try adding it to the game. Also gives some culinary usages to eggplant/cucumber, which have very few recipes. 

## Changelog

```changelog
(u)Roddy
(*)Adds ratatouille to the game
```
![SharedScreenshot (1)](https://user-images.githubusercontent.com/105123457/176244253-c1a8d422-0fb1-4284-9add-1ff95045a168.jpg)

2022-06-28 18:29 UTC, ZeWaka commented
sprites are very 'eh'

2022-06-28 18:29 UTC, TobleroneSwordfish requested changes
Not sure the sprite is really recognisable as ratatouille, but then I'm not a spriter and have no idea how you'd draw it

2022-06-28 18:29 UTC, TobleroneSwordfish commented on code/modules/food_and_drink/snacks.dm
> +	needspoon = 1
```suggestion
	needspoon = TRUE
```

2022-06-28 18:52 UTC, t-toasted commented
> 

One of the problems I was having with spriting the dish is that it’s a stew that turns a mushy brown when properly cooked, so the alternative I can come up with is doing it in the exact style of the movie ratatouille, if that might fix it

2022-06-29 11:59 UTC, WALPVRGIS commented
Hmm, I'm not sold on the latest sprite, it's visually chaotic and a bit hard to decipher. Ratatouille is a tough dish to stylise, theres a lot going on so its gonna be a bit difficult. Definitely possible though, it'll need to exaggerate a lot colour-wise I think rather than going with Brown Stew (or the full dish like the current version you've made). 

Scaling down a photo of the dish suggests a neat direction for the sprite;
![image](https://user-images.githubusercontent.com/78533030/176430933-dfd85596-2998-4da3-88c8-1ed3243f83c0.png)
Something like the first attempt, but pushing those bright colours and slightly more defined Chunks could work hmmm 🤔 Feel free to ping me in spritercord, I'm happy to help figure it out! 😺

2022-06-30 03:50 UTC, t-toasted commented
> Hmm, I'm not sold on the latest sprite, it's visually chaotic and a bit hard to decipher. Ratatouille is a tough dish to stylise, theres a lot going on so its gonna be a bit difficult. Definitely possible though, it'll need to exaggerate a lot colour-wise I think rather than going with Brown Stew (or the full dish like the current version you've made).
> 
> Scaling down a photo of the dish suggests a neat direction for the sprite; ![image](https://user-images.githubusercontent.com/78533030/176430933-dfd85596-2998-4da3-88c8-1ed3243f83c0.png) Something like the first attempt, but pushing those bright colours and slightly more defined Chunks could work hmmm 🤔 Feel free to ping me in imspriter, I'm happy to help figure it out! 😺

I see the idea! I might ping you on it in a few days. Right now I'll put this on hold for a bit just so I can fiddle with some other projects, but since this just needs one sprite, I can let it simmer a bit.

2022-07-01 13:28 UTC, t-toasted commented
El RATOO has been respritted

2022-07-15 01:41 UTC, WALPVRGIS commented
!merge_upstream

2022-07-15 02:25 UTC, WALPVRGIS commented
Hmm, did a little tweak to give the current sprite outlines, thoughts @t-toasted ?
![image](https://user-images.githubusercontent.com/78533030/179134215-a3a34679-448f-4688-9632-9a3c744c9201.png)
It's still a little weird-looking when not on a plate though, I'm still debating whether this is one of those dishes that will need it's own built-in plate or not 😅

2022-07-15 05:18 UTC, t-toasted commented
> Hmm, did a little tweak to give the current sprite outlines, thoughts @t-toasted ?
> ![image](https://user-images.githubusercontent.com/78533030/179134215-a3a34679-448f-4688-9632-9a3c744c9201.png)
> It's still a little weird-looking when not on a plate though, I'm still debating whether this is one of those dishes that will need it's own built-in plate or not 😅

Oh wow it looks so much nicer with the outline. Kinda funny, I was literally just thinking “I should look into outlining the rat dish…”
But hMMM yeah if you think it should have a plate then go for it. Also :eyes: pls commit that much nicer outlined version too DHJCKVG

2022-08-24 20:46 UTC, ZeWaka commented
@WALPVRGIS closing soon unless update is pushed

2022-08-29 22:28 UTC, closed without merging