Separate armor penetration from D_PIERCING
goonstation/goonstation pull request #9412
Opened 2022-06-30 17:04 UTC by TDHooligan

## About the PR 
Adds a new variable to projectiles that allows coders to manually adjust how much ranged protection to ignore.

## Why's this needed? 
Currently the only method to reduce effective armor is with piercing damage, which currently makes security vests 100% useless.

For example, you want a gun that can crit an armored security guard in 2 hits. Right now your only options are:

**A:** Set the damage to the appropriate value to crit them in 2 hits 
Since secvests have 1 ranged prot, this is 100 damage, an instant crit to unarmored personnel.

**B:** Set piercing on, and make it do 50 damage, where there is no benefit security, naked or not.

Having this merged will mean certain weapons could do slightly more balanced spreads of damage, or completely ignore light armor.

2022-07-04 16:59 UTC, Tarmunora commented
Hm. I don't think I'm a huge fan of this existing both a.) separately from the armor-piercing part of D_PIERCING and b.) in such a different way (subtractive vs multiplicative reduction in rangedprot)

2022-07-05 21:26 UTC, TDHooligan commented
> Hm. I don't think I'm a huge fan of this existing both a.) 100% separately from the armor-piercing part of D_PIERCING and b.) in such a different way (subtractive vs multiplicative reduction in rangedprot)

it could be changed to multiplicative, but additive scaling was a bit easier to meet damage thresholds with, plus it could be used to determine whether or not a bullet gets implanted (IE: if pen > armor, implant)

Perhaps it's worth moving the penetration out from D_PIERCING and instead giving the old D_PIERCING weapons a bunch of new-style penetration? There are a lot of weapons that could suit the piercing damage type that don't deserve full armor pen.

2022-07-09 17:06 UTC, ZeWaka commented
Label your PRs

2022-07-11 02:21 UTC, Tarmunora commented
> Perhaps it's worth moving the penetration out from D_PIERCING and instead giving the old D_PIERCING weapons a bunch of new-style penetration? There are a lot of weapons that could suit the piercing damage type that don't deserve full armor pen.

That would probably be good, yeah.

2022-07-18 05:47 UTC, flrsh commented
@TDHooligan still planning on working on this?

2022-07-18 18:57 UTC, TDHooligan commented
> @TDHooligan still planning on working on this?

just getting back on this now!

2022-07-21 01:58 UTC, flrsh commented on code/modules/projectiles/projectile_parent.dm
> +	var/armor_ignored = 0		 // Percentage of armor to ignore
Could you add an example in the comment?

2022-07-21 02:23 UTC, Tarmunora requested changes
code looks good, but the `armor_msg` stuff could/should probably be pulled out of the damage_type switch and handled just with rangedprot/armor_ignored values now, yeah?

2022-07-21 12:57 UTC, TDHooligan commented
good shout. moved that out and also adjusted the slash damage proc to apply to armor penetration.

2022-07-21 13:40 UTC, Tarmunora commented on code/mob/living.dm
> +			armor_msg = ", but [P] pierces through your armor!"
should only print the message if you actually *had* armor to be pierced - i.e.: `if (rangedprot_base > 1)`

2022-07-22 00:57 UTC, merged