makes certain vamp powers work in containers
goonstation/goonstation pull request #9447
Opened 2022-07-03 11:07 UTC by ZWRh3

[BALANCE][BUG]
## About the PR 
makes some vamp powers such as cancel stuns and thrallspeak work in containers

## Why's this needed? 
fixes #9441, allows for vampires to use certain powers which shouldnt be restricted for being in a container such as cancel stuns

(not i am not aware of the balance implications of this and the port a brig)
## Changelog

```changelog
(u)ZWRh3
(*) Certain vampire powers now work when inside of a container
```

2022-07-03 19:12 UTC, nefarious6th commented
for balance in the pbrig perspective, most of these seem okay for both inside lockers and the pbrig; i think thrallspeak makes a lot of sense for either scenario, im not particularly drawn to radio jam needing to be outside-containers only, and the cancel stun for the sake of the pbrig doesn't really matter. enthralling from within containers seems weird for within the pbrig but it could probably lead to some funny moments and i see a lot of value in being able to enthrall from inside lockers/coffins.

coffin escape being usable in the pbrig is a huge detriment though because it guarantees there is no reliable way to catch a vampire for brigging, since they can bat out of normal brigs and that leaves the pbrig as an only resort for secure jailing. in a general sense, that would make me more likely to just outright hunt and kill vamps instead of trying to catch them and give appropriate sentences they could serve in the pbrig. likewise with screech inside of a pbrig; arcfiend's AOE disorient stun leaves me the same way when they're inside the pbrig; i'd much rather have executed a problematic arcfiend before shuttle arrival versus trying to take them along in the pbrig when they're just going to chain shock everyone. i see screech going similarly.

2022-07-03 20:02 UTC, ZWRh3 commented
should i add a 2 option of the var which is all containers but the port a brig?

2022-07-03 22:07 UTC, nefarious6th commented
if you can make it work, then by all means; the variable could probably see some use on other antags' abilities later on down the line too. vampire coffin escaping from inside a locker or whatever seems neat to me

2022-07-03 22:21 UTC, ZWRh3 commented
> if you can make it work, then by all means; the variable could probably see some use on other antags' abilities later on down the line too. vampire coffin escaping from inside a locker or whatever seems neat to me

funnily enough i mainly did it out of remembering that one time i got validhunted using the fucking port a medbay because it preventing using cancel stuns

2022-07-04 17:34 UTC, Tarmunora requested changes
imo ditch the portabrig stuff. No need to treat it any differently than say, a welded locker. (iread: block coffin escape in all objects)

2022-07-04 20:47 UTC, ZWRh3 commented
> 

would screaming while in the port a brig be ok?

2022-07-05 17:56 UTC, Tarmunora approved these changes

2022-07-05 23:09 UTC, ZeWaka requested changes

2022-07-05 23:09 UTC, ZeWaka commented on code/datums/abilities/vampire/coffin.dm
> +	not_when_in_an_object = 0
FALSE

2022-07-05 23:09 UTC, ZeWaka commented on code/datums/abilities/vampire.dm
> +	var/not_when_in_an_object = 1
TRUE

2022-07-05 23:09 UTC, ZeWaka commented on code/datums/abilities/vampiric_thrall.dm
> +	var/not_when_in_an_object = 1
ditto everywhere else

2022-07-11 23:56 UTC, flrsh commented on code/datums/abilities/vampire/coffin.dm
> +	not_when_in_an_object = FALSE
```suggestion

```

2022-07-11 23:57 UTC, merged