Transfer pathology's leprosy into the standard diseases code
goonstation/goonstation pull request #9503
Opened 2022-07-06 22:51 UTC by XyzzyThePretender

## About the PR 
Makes the leprosy symptom a discrete disease and refactors the armadillo code to account for this.

## Why's this needed? 
Armadillo-borne leprosy is a loose end that needs to be closed for both of pathology's endcases.
I don't think this necessitates a changelog entry, correct me if I am wrong.

## Changelog

```changelog
```

2022-07-09 17:05 UTC, ZeWaka commented
Label your PRS

2022-07-11 02:19 UTC, Tarmunora requested changes

2022-07-11 02:19 UTC, Tarmunora commented on code/modules/medical/diseases/leprosy.dm
> +/datum/ailment/disease/leprosy/stage_act(var/mob/living/affected_mob, var/datum/ailment_data/D, mult)
add `mult` handling.

2022-07-11 19:59 UTC, ZeWaka requested changes

2022-07-11 19:59 UTC, ZeWaka commented on code/modules/medical/diseases/leprosy.dm
> +						SPAWN(rand(150,200))
150 to 200 what

2022-07-14 01:39 UTC, merged