Chemical requests console feature
goonstation/goonstation pull request #9607
Opened 2022-07-12 21:36 UTC by TobleroneSwordfish

[FEATURE]
## About the PR 
Remake of #9361 with all map changes removed for being cursed. I will make a separate PR to add it to maps once this is merged.
No changelog for this PR, since it doesn't actually add the machines to maps

Adds a chemical request console for placing orders with chemistry. One is found outside science and one in medbay on every map. (I had to move/remove a couple of things to make them fit, actual mappers feel free to tell me if it looks wrong)
Might be good to give botany one as well, lmk what you think.

Request interface:
![image](https://user-images.githubusercontent.com/20713227/178566628-6334f02f-1e7f-4035-9eae-3da243693744.png) ![image](https://user-images.githubusercontent.com/20713227/178566774-067eacff-3b55-410d-9af4-13b43f2b719a.png)

There is a corresponding console in chemistry itself for fulfilling or denying requests, and a PDA alert is sent to all science PDAs when a request is placed.
![image](https://user-images.githubusercontent.com/20713227/178374604-fcd8a95c-0350-4fe7-8b7e-d6bd85d9e678.png)
![image](https://user-images.githubusercontent.com/20713227/178374640-65cff887-5660-486c-ba58-e8b464b84836.png)

Both consoles currently use the same sprite ala QM consoles and because I am not creative: 
![image](https://user-images.githubusercontent.com/20713227/175938148-9b9b18c5-9d69-46d2-a093-bb82ba0d1eca.png)

## Why's this needed? 
Chemistry in theory is able to quickly make and distribute chemicals for the crew via the mail chutes, however this rarely happens as radio and PDA messages tend to be missed and chemistry is often isolated from the rest of the station. (kudos to donut 3, kondaru and clarion for having chemistry front desks)
Adding a formal request system should make it a lot easier for people to request what they want, and hopefully encourage chemistry to fulfil those requests at some point.
The chemistry terminal keeps a history of all requests made and whether or not they were denied, allowing for some investigation into who is to blame for the clown getting access to thermite.

2022-07-12 22:01 UTC, Momoberry commented
JOB DUTY FOR SCIENCE, WOOOOOOOO

2022-07-17 16:28 UTC, TobleroneSwordfish commented
!merge_upstream

2022-07-17 16:29 UTC, TobleroneSwordfish commented
merge driver be kind 🙏

2022-07-21 22:13 UTC, TobleroneSwordfish commented
!merge_upstream

2022-07-31 21:50 UTC, TobleroneSwordfish commented
!merge_upstream

2022-08-26 02:15 UTC, ZeWaka requested changes

2022-08-26 02:15 UTC, ZeWaka commented on tgui/packages/tgui/interfaces/ChemRequester.js
> +const IDCard = (props, context) => {
I'd like this in Common, actually

2022-08-26 02:15 UTC, ZeWaka commented on code/obj/machinery/computer/chem_requester.dm
> +				chem_requests["[src.request.id]"] = src.request
might be cooler to store this on the mainframe or something, packets so nerds can sniff and see?
(not required, idea)

2022-08-28 03:14 UTC, ZeWaka approved these changes

2022-08-28 03:14 UTC, ZeWaka commented on code/obj/machinery/computer/chem_requester.dm
> +var/list/datum/chem_request/chem_requests = list()
i'd like the file moved to the chemistry module folder, other than that all looks good

2022-08-28 07:52 UTC, TobleroneSwordfish commented
Okay I've done the review changes, I want to do packets for this at some point but that is likely going to have to be after I refactor `machinery/networked` for the sake of my sanity so should probably be in a separate PR.

2022-08-29 07:08 UTC, merged