Rework Flock compute updates
goonstation/goonstation pull request #9617
Opened 2022-07-13 04:47 UTC by FlameArrow57

[REWORK][QOL][PERFORMANCE]

## About the PR 
This PR reworks how Flock used and total compute is updated for Flockmind and Flocktraces.

Compute will now only be updated when the thing that is added or removed from a Flock that changes current compute actually modifies compute.

Compute will also now only be updated corresponding to the change added by the thing being added or removed from the Flock instead of compute being recalculated iterating over every Flock thing.

Compute for Flocktraces will now also update along with the Flockmind's compute updates.

## Why's this needed? 
Current compute updates update compute looking at everything in the Flock instead of just what is being added or removed.

Flocktrace compute updating was done in the life loop, which would mean updates weren't as often.

2022-07-13 10:01 UTC, amylizzle requested changes
One major but fixable problem with this: Some structures (ie, Sentinels) vary the amount of compute they use depending on behaviour. You'd need to get them to send an update when compute usage changed. It probably wouldn't be a terrible idea to make `changeCompute()` a proc on flock_structure parent, and handle the update there.

2022-07-14 01:01 UTC, FlameArrow57 commented on code/datums/flock/flock.dm
>  /datum/flock/proc/total_compute()
There's several places where it is though, so was uncertain

2022-07-14 13:19 UTC, TobleroneSwordfish commented
Does this fix #9641 or is that different spaget?

2022-07-16 00:17 UTC, FlameArrow57 commented on code/datums/flock/flock.dm
> +/datum/flock/proc/update_computes()
Idk, they are on different types, on datum versus ability holder

2022-07-16 00:17 UTC, FlameArrow57 commented
It does not, wasn't able to fix that

2022-07-27 05:45 UTC, ZeWaka commented
x

2022-07-27 08:23 UTC, FlameArrow57 commented
Currently a small bug with this, will try to fix in the next 24 hours

2022-07-28 05:59 UTC, FlameArrow57 commented
Ok should be ready

2022-07-28 06:31 UTC, merged