Fixes chugging while clumsy teleporting the glass
goonstation/goonstation pull request #9658
Opened 2022-07-14 17:46 UTC by MetricDuck

[BUG]
## About the PR 
Click dragging to chug a drinks container whilst having the clumsy trait has a 50% chance to teleport the glass to you and chuck it behind you - regardless of your distance from said glass.

This is because the mouse_drop range checks are all in the parents and get overridden; the parents are called via `..()` but they just `return` back to our child function (which then proceeds as normal).

This PR adds a range check to the relevant `mouse_drop()` function that actually does the chugging action.

## Why's this needed? 
Fixes #8647

2022-07-22 22:27 UTC, ZeWaka commented on code/modules/chemistry/tools/food_and_drink.dm
> +		if(BOUNDS_DIST(C, src) > 0)
shouldn't this be in interact range

2022-07-25 19:55 UTC, ZeWaka requested changes
x

2022-07-26 08:22 UTC, MetricDuck commented on code/modules/chemistry/tools/food_and_drink.dm
> +		if(BOUNDS_DIST(C, src) > 0)
Didn't know that was a proc - amended

2022-07-26 20:31 UTC, ZeWaka commented on code/modules/chemistry/tools/food_and_drink.dm
> +		if(BOUNDS_DIST(C, src) > 0)
It's in the readme code guide 😭

2022-07-26 20:32 UTC, ZeWaka approved these changes

2022-07-27 05:51 UTC, merged