Make flockdrones hibernate if they have nothing to do
goonstation/goonstation pull request #9720
Opened 2022-07-17 13:44 UTC by amylizzle

## About the PR 
If a drone has spent the last few cycles of it's AI wandering, it will instead go into hibernation. This causes it to a) stop eating tons of CPU doing JPS wandering, and b) provide 5 bonus compute to the flock.

Drones will wake from hibernation on being given specific orders, or on detecting an enemy nearby (this is done on the `Life()` loop, so every few seconds or so).

## Why's this needed? 
Flock basically stops moving towards the end of the round because of all the drones doing pathing. This should substantially reduce that.

## Changelog

```changelog
(u)Amylizzle
(+)Flockdrones with nothing to do will now hibernate, providing 5 extra compute. They will wake from hibernation when given orders or an enemy is detected.
```

2022-07-17 13:59 UTC, TobleroneSwordfish requested changes

2022-07-17 13:59 UTC, TobleroneSwordfish commented on code/mob/living/critter/ai/flock/flocktasks.dm
> +	if(istype(D))
This PR contains three different ways of casting `holder.owner` to `/mob/living/critter/flock/drone`, please gods pick one

2022-07-17 13:59 UTC, TobleroneSwordfish commented on code/mob/living/critter/flock/flockdrone.dm
> +	flock_speak(src, "No tasks in queue. Allocating higher functions to resource generation.", src.flock)
```suggestion
	flock_speak(src, "No tasks in queue. Allocating higher functions to compute generation.", src.flock)
```

2022-07-18 11:33 UTC, amylizzle commented
!merge_upstream

2022-07-18 23:43 UTC, FlameArrow57 commented
Are there any more AI optimizations that can be done? I just kind of hate that we have to resort to making drones hibernate if that's how intensive the AI is going to be

2022-07-19 10:54 UTC, amylizzle commented
There's probably a few tweaks to be made, but I already did a pretty thorough pass. The problem is just that pathfinding is expensive, and doing it a lot slows things down. Short of caching the pathfinding results (won't work, things changing too much), there's not a lot that can be done.

Plus, you do always end up with like 50 drones just wandering at the end of the round because they've eaten everything and converted everything. No point wasting all those cycles.

2022-07-22 15:32 UTC, amylizzle commented
!merge_upstream

2022-07-22 18:12 UTC, amylizzle commented
!merge_upstream

2022-07-23 01:03 UTC, FlameArrow57 commented
Seems critters already have an is_hibernating variable, not sure if that could be reused if wanted

In Discord it was mentioned Life() ticks like every 12 seconds or something on main, feel like it could also be good to add it to TakeDamage() too, or maybe was_harmed, might be good to integrate with the COMSIG_MOB_GRABBED signal for waking too otherwise think a hibernating drone probably shouldn't shock a person

Also need to add waking to drone/Login()

Need to add to handle_flock_attack() proc so that hibernating drones don't report attacks

Need to add to check_health() proc to not update icon when hibernating

Also need to add to flock/Life() to not use extinguisher while ai is paused, could also maybe wake drone up if on fire

If drones can eat items while wandering, probably should either prevent hibernating while eating items, or stop items from being eaten while hibernating

Probably should make it so that drones that are dormantized don't report going dormant if hibernating

Also not sure if drones that are hibernating should report death upon dying

2022-07-23 12:02 UTC, amylizzle commented on _std/macros/flock.dm
> +#define FLOCK_DRONE_WANDER_PAUSE_COUNT 5
I put them as defines so they'd be easily configurable for future balance changes without needing to dig into the code. I've found it pretty useful when debugging and tuning this.

2022-07-23 12:04 UTC, amylizzle commented on code/mob/living/critter/flock/flockdrone.dm
> +	src.compute = FLOCK_DRONE_COMPUTE_HIBERNATE
That PR isn't merged yet?

2022-07-23 12:05 UTC, amylizzle commented on code/mob/living/critter/flock/flockdrone.dm
> +	src.damaged = -1 //force icon refresh
It does, setting damaged to -1 triggers the icon update back to the appropriate level for the drone's health
```
	switch(percent_damage)
		if(75 to 100)
			if(damaged == 0) return
			damaged = 0
			if(!dormant)
				src.icon_state = "drone"
```

2022-07-23 12:09 UTC, amylizzle commented on code/mob/living/critter/flock/flockdrone.dm
> +	if(src.client)
agreed

2022-07-23 12:10 UTC, amylizzle commented on code/mob/living/critter/flock/flockdrone.dm
> +		if(src.flock) //if we have a flock, use the enemies list, otherwise just use non-flock mobs in view
Flock could die, or the drone could have been spawned without a flock (azone or something)

2022-07-23 12:11 UTC, amylizzle commented on code/mob/living/critter/flock/flockdrone.dm
> +		src.pause_ai()
I mean, if you've wandered 5 times in a row already, it's not like there's a lot changing there. I think it's fine to check this sparingly.

2022-07-23 12:16 UTC, amylizzle commented
> Seems critters already have an is_hibernating variable, not sure if that could be reused if wanted

Yeah, I looked into it when I started this one. It does too much other stuff and is used for azone area stuff. Too different to be useful unfortunately.

 
> In Discord it was mentioned Life() ticks like every 12 seconds or something on main, feel like it could also be good to add it to TakeDamage() too, or maybe was_harmed, might be good to integrate with the COMSIG_MOB_GRABBED signal for waking too otherwise think a hibernating drone probably shouldn't shock a person

Life() ticks commented as above, I think it'll be fine. Adding it to TakeDamage() and the like is a good idea, will do.
 
> Also need to add waking to drone/Login()

ditto 

> Need to add to handle_flock_attack() proc so that hibernating drones don't report attacks

I think it makes sense for them to report attacks, since they are _aware_ of enemies - that's how they wake up. Reporting an attack could wake them up too.

> Need to add to check_health() proc to not update icon when hibernating

smort.
 
> Also need to add to flock/Life() to not use extinguisher while ai is paused, could also maybe wake drone up if on fire

Waking up because you're on fire seems reasonable.

> If drones can eat items while wandering, probably should either prevent hibernating while eating items, or stop items from being eaten while hibernating

I'm fine with passive absorbtion, but this should never happen because drones will have to have been wandering for 5 cycles first which means they haven't done any harvesting recently.

> Probably should make it so that drones that are dormantized don't report going dormant if hibernating

will do

> Also not sure if drones that are hibernating should report death upon dying

Yeah, they ought to. Hibernation is just a less active state, there's still some awareness there.

2022-07-26 21:52 UTC, flrsh commented
!merge_upstream

2022-07-26 23:07 UTC, flrsh approved these changes
Briefly reviewed and looks good to me!

2022-07-26 23:07 UTC, merged