5 New Drink Recipes for Bartender
goonstation/goonstation pull request #9727
Opened 2022-07-17 16:15 UTC by t-toasted

## About the PR 
Adds in 5 new recipes for the bartender: iced coconut milk espresso, iced pineapple matcha, thai iced coffee, peppermint hot chocolate, and mexican hot chocolate.  

## Why's this needed? 
Some bartenders like their mixtures to have actual names. Gives bartenders more ideas of things to serve up, for a barista feel, and encourages them to use more stuff from botany for their drinks.

## Changelog

```changelog
(u)Roddy
(+)Added in five new drink recipes for the bartender.
```
[Feature] [add to wiki]

2022-07-17 18:07 UTC, flrsh commented
Could you make all the iced drinks an iced subtype just for the sake of organization?

2022-07-17 18:15 UTC, t-toasted commented
> Could you make all the iced drinks an iced subtype just for the sake of organization?

Can do!

2022-07-17 23:10 UTC, t-toasted commented
!merge upstream

2022-07-18 04:46 UTC, flrsh requested changes

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Chemistry-Recipes.dm
> +		iced_coconutmilkespresso
```suggestion
		iced/coconutmilkespresso
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Chemistry-Recipes.dm
> +		iced_pineapplematcha
```suggestion
		iced/pineapplematcha
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Chemistry-Recipes.dm
> +		iced_thaiicedcoffee
```suggestion
		iced/thaiicedcoffee
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Chemistry-Recipes.dm
> +		iced_thaiicedcoffee/thaiicedcoffee2
```suggestion
		iced/thaiicedcoffee/thaiicedcoffee2
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +		fooddrink/icedcoconutmilkespresso
```suggestion
		fooddrink/iced/coconutmilkespresso
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +		fooddrink/icedpineapplematcha
```suggestion
		fooddrink/iced/pineapplematcha
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +		fooddrink/thaiicedcoffee
```suggestion
		fooddrink/iced/thaicoffee
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +			name = "thai iced coffee"
```suggestion
			name = "Thai iced coffee"
```

2022-07-18 04:46 UTC, flrsh commented on code/modules/chemistry/Reagents-FoodDrink.dm
> +			name = "mexican hot chocolate"
```suggestion
			name = "Mexican hot chocolate"
```

2022-07-18 17:51 UTC, wolfolotl commented
thing I realized looking at this: for the hot chocolate recipes you'll want to add in duplicate formulas that use the chocolate milk reagent instead of chocolate and milk separately, or that reaction might occur first and lock the bartender out of the drink. similar things have happened with recipes that require tea and sugar but don't have a recipe with the sweet tea reagent itself

2022-07-18 19:30 UTC, t-toasted commented
> thing I realized looking at this: for the hot chocolate recipes you'll want to add in duplicate formulas that use the chocolate milk reagent instead of chocolate and milk separately, or that reaction might occur first and lock the bartender out of the drink. similar things have happened with recipes that require tea and sugar but don't have a recipe with the sweet tea reagent itself

Oh! How didn’t I catch that. Yes yes, good idea, let me fix that

2022-07-21 03:07 UTC, flrsh approved these changes
Looks good to me. Could also make Mexican hot chocolate and peppermint hot chocolate subtypes of hot chocolate, but since there are only two kinds (right now) it's up to you.

2022-07-21 13:47 UTC, t-toasted commented
> Looks good to me. Could also make Mexican hot chocolate and peppermint hot chocolate subtypes of hot chocolate, but since there are only two kinds (right now) it's up to you.

If I add more in the future, I’ll change them to be a subtype (now that I know how to too), but for now I’ll leave them be

2022-07-28 20:34 UTC, merged