TGUI Safes
goonstation/goonstation pull request #9752
Opened 2022-07-19 01:35 UTC by blackrep

## About the PR 
TODO:
- [X] Replace 0 and 1, with FALSE and true
- [X] Support arbitrary code lengths
- [ ] Refactor key functions outside of Topic
- [ ] Make TGUI UI
- [ ] Hook up UI to object

## Why's this needed? 

## Changelog

```changelog
(u)CodeDude
(*)Added soft soft pizza to the game - a tasty drink found in soda machines!
(+)Made some small sprite changes to the base pizza sprite.
```

2022-07-20 06:07 UTC, ZeWaka commented on code/obj/item/storage/secure_safe.dm
> +				src.submit_guess()
pass `usr` into this proc as a `mob/user`

2022-07-20 06:09 UTC, Luxizzle requested changes

2022-07-20 06:09 UTC, Luxizzle commented on tgui/packages/tgui/interfaces/SecureSafe.js
> +    <ProgressBar
We shouldn't be abusing the progress bar component like this. It is fine to add a bit of custom CSS for your interface for whatever purpose this is doing.

2022-07-21 00:41 UTC, blackrep commented
Wow I really messed that up.

2022-07-21 00:41 UTC, closed without merging

2022-07-21 00:56 UTC, blackrep commented
Redoing this PR with #9776. I really messed up try to rebase this, and do not want to try to fix this.