Updates some food and cooking code to modern style standards
goonstation/goonstation pull request #9765
Opened 2022-07-20 03:00 UTC by XyzzyThePretender

[cleanliness]
## About the PR 
Regexed some booleans to TRUE/FALSE.
Changed for loops to 'for-in-to' and 'as anything' style as needed.
Cleaned unusual spacing.
Standardized item var to 'I' (from P or S).
Deleted unnecessary 'as mob' from procs.

## Why's this needed? 
Needed to look into the cooking code for a potential mycology/yeast implementation, so I cleaned a bit while I'm here.
Regex replacement went all over the place: the main cleanup was in cooking.dm, cookingrecipes.dm, and food_and_drink.dm.
Standardization good.

## Changelog

2022-07-20 06:17 UTC, ZeWaka requested changes

2022-07-20 06:17 UTC, ZeWaka commented on code/obj/submachine/cooking.dm
> +		for(var/obj/item/I as anything in src.contents)
no, not everything inside people is an item

2022-07-20 06:17 UTC, ZeWaka commented on code/obj/submachine/cooking.dm
> +			for (var/obj/I as anything in src.contents)
same here and elsewhere

2022-07-20 06:17 UTC, ZeWaka commented on code/obj/submachine/cooking.dm
> +				boutput("<span class='notice'>You wet [W].</span>")
```suggestion
				boutput(user, "<span class='notice'>You wet [W].</span>")
```

2022-07-20 06:17 UTC, ZeWaka commented on code/obj/submachine/cooking.dm
> +				boutput("<span class='notice'>You fill [W] with water.</span>")
```suggestion
				boutput(user, "<span class='notice'>You fill [W] with water.</span>")
```

2022-07-20 06:17 UTC, ZeWaka commented on code/obj/submachine/cooking.dm
> +			for(var/flavor as anything in flavors)
unnecessary 
```suggestion
			for(var/flavor in flavors)
```

2022-07-20 06:17 UTC, ZeWaka commented on code/obj/submachine/cooking.dm
> +			for (var/obj/item/I as anything in src.contents)
x

2022-07-20 06:17 UTC, ZeWaka commented on code/obj/submachine/cooking.dm
> +				for(var/obj/item/I as anything in src.contents)
x

2022-07-20 13:29 UTC, XyzzyThePretender commented on code/obj/submachine/cooking.dm
> +				for (var/obj/item/I as anything in to_remove)
type is set by line 1219

2022-07-22 03:00 UTC, closed without merging

2022-07-22 03:50 UTC, ZeWaka commented
?