Map fun
goonstation/goonstation pull request #9780
Opened 2022-07-21 06:45 UTC by MajesticBBQ

## About the PR 
Updated Clarion to no longer have hotwired APCs prebuilt into the map at the engineering gas storage and SW maint, as well as add missing utility vendors in the now larger maint
![image](https://user-images.githubusercontent.com/45326732/180146575-b6e4a7c0-b087-409f-b56c-078ebc868820.png)

Made new random rooms, one of each size
![image](https://user-images.githubusercontent.com/45326732/180147490-fa7756d9-3010-4cc3-a591-adba4b134568.png)
![image](https://user-images.githubusercontent.com/45326732/180147521-9df9017e-d68e-4215-bf53-f022ee53ffe5.png)
![image](https://user-images.githubusercontent.com/45326732/180147540-258814b3-e23a-479e-972c-0b14a8e9c4f0.png)

## Why's this needed? 
Because the hotwiring was very dangerous to engineers in either the SW maint or Engineering Gas storage and needed fixing.
Wanted to add some new fun Random Rooms.

## Changelog

2022-07-21 10:34 UTC, TobleroneSwordfish commented on assets/maps/random_rooms/3x5/library.dmm
> +//MAP CONVERTED BY dmm2tgm.py THIS HEADER COMMENT PREVENTS RECONVERSION, DO NOT REMOVE
this file probably shouldn't be here

2022-07-21 11:23 UTC, amylizzle commented
Probably best to split the random rooms from the clarion fix and pr them separately

2022-07-22 04:13 UTC, flrsh commented
Yeah what Amy said. You should use separate branches so that your changes from other PRs don't show up.

2022-07-27 05:48 UTC, ZeWaka requested changes
x

2022-07-27 06:08 UTC, flrsh commented
!merge_upstream

2022-07-27 15:52 UTC, merged