Gives random event flockminds a free trace as a treat
goonstation/goonstation pull request #9808
Opened 2022-07-23 00:31 UTC by TobleroneSwordfish

[BALANCE]
## About the PR 
Flockmind spawned from random events when the server has >40 alive players will immediately attempt to spawn a free (0 compute) trace.

## Why's this needed? 
Flock getting destroyed immediately after spawning is a problem, this tries to help with that by giving them more sentience to fight back against early attacks without directly increasing their growth speed or power level too much.

2022-07-23 01:39 UTC, FlameArrow57 commented
Kind of against, if Flock is dying upon spawning then I think they just picked a not great spot, plus can get a new trace with converting a computer and making a few drones. Also think traces should be something that need to be built to

Also a possibility the Flockmind isn't wanting any traces

2022-07-23 02:20 UTC, TobleroneSwordfish commented
I agree it breaks the rule of traces being directly linked to compute, but what I've seen happening is flock being discovered right around when they get their first trace, then one drone dies and the trace gets booted again, leading to them getting steamrolled shortly afterwards. As far as flockminds not wanting traces goes... Why?

2022-07-23 02:27 UTC, FlameArrow57 commented
Idk just playstyle, can probably just ignore

2022-07-23 02:49 UTC, FlameArrow57 commented
Is that issue with spawn choice though, or players happening to find Flock by chance? If it's with finding by choice, does it go back to just increasing Flockmind's early game defense like with sentinels? Dunno how much Flocktraces would help with that

2022-07-28 13:30 UTC, TobleroneSwordfish commented
drafting since I found bugs

2022-08-05 03:09 UTC, TobleroneSwordfish commented on code/mob/living/intangible/flock/flocktrace.dm
> +	aH?.updateCompute()
that's what I get for resolving conflicts on github

2022-08-14 06:42 UTC, ZeWaka requested changes
x

2022-08-14 06:42 UTC, ZeWaka commented on code/procs/antagonist_procs.dm
> +	for(var/client/C)
will return null instead of 0

2022-08-15 17:55 UTC, merged