Removes most trailing zeroes after decimal point
goonstation/goonstation pull request #9944
Opened 2022-07-29 10:05 UTC by ZWRh3

## About the PR 
removes (most) trailing zeroes, tries to make more stuff use defines

NOTE: its most not all as trying to basically manually replace them all is gonna make me go insane

## Why's this needed? 
cleanliness

2022-07-29 10:05 UTC, ZWRh3 commented
any tips on finding the rest?

2022-07-29 12:11 UTC, Luxizzle requested changes
Why would you do this to yourself?

Quick scan, but looks good! But damn, this is used way more than I expected.

2022-07-29 12:11 UTC, Luxizzle commented on code/procs/elecflash.dm
> +		src.TakeDamage("chest", 0, rand(0,1.0) * power * 0.2, damage_type=DAMAGE_BURN)
```suggestion
		src.TakeDamage("chest", 0, rand(0,1) * power * 0.2, damage_type=DAMAGE_BURN)
```

2022-07-29 13:13 UTC, Josephin23 commented
> Why would you do this to yourself?
> 
> Quick scan, but looks good! But damn, this is used way more than I expected.

most of this was done with regex, idk how you'd do all of this manually

2022-07-29 14:16 UTC, ZWRh3 commented
> > Why would you do this to yourself?
> > Quick scan, but looks good! But damn, this is used way more than I expected.
> 
> most of this was done with regex, idk how you'd do all of this manually

while i did search for several strings using regex to semi automate it i still manually double checked stuff, this took hours to do

2022-07-29 19:07 UTC, ZeWaka commented
ur fault if something breaks

2022-07-29 19:08 UTC, merged

2022-07-30 07:55 UTC, ZWRh3 commented
> ur fault if something breaks

this may either stop your concerns or make them worse but: i manually double checked it all