Tgui in-hand material sheet construction menu
goonstation/goonstation pull request #9963
Opened 2022-07-30 10:32 UTC by Garash2k

[Feature][QoL][tgui]

## About the PR 
Replaces the old html in-hand material sheet menu with a TGUI one.
Inspired by the human inventory menu and the seed fabricator.
![image](https://user-images.githubusercontent.com/6396368/181904859-529643f3-6d25-4693-acfb-3ec67f3d1814.png)
![image](https://user-images.githubusercontent.com/6396368/181904865-8736d380-0fb6-4a33-86c3-89e2ce91827f.png)
![image](https://user-images.githubusercontent.com/6396368/181904871-a9df07e5-593a-4fa9-a2d2-e8ebd53c2294.png)

## Why's this needed? 
ICONS!!!!
Having a button become disabled after a craft is good feedback.
Also TGUI looks better and is more responsive.

## Changelog

```changelog
(u)Garash
(+)New UI for the material sheet's in-hand construction menu.
```

2022-07-30 10:45 UTC, Garash2k commented
Wow, there's still weird lingering commits from exactly 4 days ago, I've completely reset my origin/master branch to upstream/master so I imagine it'll be fine next time.

2022-07-30 16:05 UTC, ZeWaka commented
It's because you keep rebasing

2022-07-30 17:02 UTC, Garash2k commented
Yeah I figured it's related to that one bad merge, but I didn't expect it to be a problem in the long term, should be fine with a new master from now on

2022-07-30 18:41 UTC, Luxizzle requested changes
TGUI code looks good 👍 just a small change in the layout and I'm happy

2022-07-30 18:41 UTC, Luxizzle commented on tgui/packages/tgui/interfaces/SheetCrafting.js
> +        <Section title={"Recipes"}>
Can you divide these 2 sections with a `Stack` so you can make the first one scrollable and the second one is always visible? 
![image](https://user-images.githubusercontent.com/14966486/181937163-a4ac82ff-b990-4539-bb02-c1ff31888a7b.png)

2022-07-31 10:22 UTC, Luxizzle commented
TGUI looks good! Recipes could *probably* be moved into ui_static_data, but it isn't a big deal I think.

2022-07-31 23:09 UTC, Garash2k commented
I doubt the "computer3.dm,656: Cannot modify null.plane." error is caused by this PR, any ways to re run the checks? Or is taking no action ok?

2022-08-01 01:24 UTC, Garash2k commented
> TGUI looks good! Recipes could _probably_ be moved into ui_static_data, but it isn't a big deal I think.

Thanks for telling me about ui_static_data, but I've actually thought of a reason not to use it!

Say you whack the metal sheet into an artifact Matter Transmutation bomb, it then becomes glass, so it's good that the recipes are eventually gonna update!

2022-08-02 20:50 UTC, Tarmunora commented
!merge_upstream

2022-08-09 17:43 UTC, Garash2k commented
!merge_upstream

2022-08-14 10:10 UTC, BatElite commented
Unless you code in TGUI support for ghostdrones this would effectively break them.

2022-08-15 02:07 UTC, Garash2k commented
I think, making use of the `isghostdrone()` function and `NO_GHOSTCRITTER` flag, I've got a reasonable solution.
![image](https://user-images.githubusercontent.com/6396368/184565700-784802a4-2b83-4dc9-952f-0e36efd35daf.png)

2022-09-12 14:23 UTC, Garash2k commented
@ZeWaka can the Stale timer be reset on this pull request? The last outstanding point was addressed and I've tested it post feature freeze.

2022-10-11 04:29 UTC, merged